### ISSUE TITLE
dotnetcoresdk issue on ubuntu 17.10

### ISSUE THREAD

**Issue by KostadinAlmishev** [OmniSharp/omnisharp-roslyn#1006]
Hi,

I am trying to build omnisharp-roslyn with ./build.sh, but the following error occurred:

Executing task: InstallDotNetCoreSdk                                   
dotnet_install: Error: OS name could not be detected: ubuntu.17.10     
An error occurred when executing task 'InstallDotNetCoreSdk'.          
Error: Failed to Install .NET Core SDK 1.0.4

**Comment by DustinCampbell** [comment]
@KostadinAlmishev : It sounds like you need to sync master. The build currently downloads .NET Core SDK 2.0.0.

**Comment by KostadinAlmishev** [comment]
Thank you!
