### ISSUE TITLE
Go to Definition fails in Cake alias 'Argument'

### ISSUE THREAD

**Issue by SIkebe** [OmniSharp/omnisharp-roslyn#1010]
## Environment data
```
dotnet --info
.NET コマンド ライン ツール (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
VS Code version:1.17.2
C# Extension version:1.13.0

## Steps to reproduce
1. Make a `build.cake` file.
2. Put the following code.
```csharp
var target = Argument("target", "Default");
```
3. Focus `Argument`.
4. Enter F12.

## Expected  behavior
Go to the definition of `Argument` alias

## Actual behavior
`No definition found for 'Argument'` appeared.  

Almost all other alias works well. Even though a method in the same namespace as `Argument` like `HasArgument("name")` works.
And when you hover `Argument`, VSCode shows proper definition.

Omnisharp logs are as follows.
```
        ************ Request ************
{"Type":"request","Seq":318,"Command":"/gotoDefinition","Arguments":{"FileName":"c:\\Develop\\GitHub\\example\\build.cake","Line":7,"Column":25,"WantMetadata":true}}
[dbug]: OmniSharp.Stdio.Program
        ************  Response ************ 
{"Request_seq":318,"Command":"/gotoDefinition","Running":true,"Success":true,"Message":null,"Body":{"FileName":null,"Line":1,"Column":1,"MetadataSource":null},"Seq":152,"Type":"response"}
```

**Comment by SIkebe** [comment]
Sorry if this is a wrong place.
(perhaps `omnisharp-vscode` or `Cake.Bakery`?)

**Comment by DustinCampbell** [comment]
I'm OK with having this here since it's about Cake support in C# for VS Code. cc @mholo65

**Comment by DustinCampbell** [comment]
I'm OK with having this here since it's about Cake support in OmniSharp. cc @mholo65

**Comment by DustinCampbell** [comment]
I'm OK with having this here since it's about Cake support in OmniSharp. cc @mholo65

**Comment by mholo65** [comment]
Yes, we just suggest `Cake.Bakery` as a starting point since it might be difficult to know where the actual issue is. In this case tough, the issue seems to be that Cake’s `GotoDefinitionHandler` don’t handle generic methods correctly. So this is actually the correct repo.

@DustinCampbell would it be possible to assign this issue to me, or tag it with a Cake tag, so that Cake issues are not forgotten by the Cake Team.

**Comment by mholo65** [comment]
Ah, saw that you already added the Cake tag! Thanks! @devlead could we start monitoring issues in this repo tagged with Cake?

**Comment by SIkebe** [comment]
I cannot repro this issue anymore. 

VS Code version:1.23.1
C# Extension version:1.15.2

Maybe fixed by later version.
