### ISSUE TITLE
Support .rsp files for Scripting Project System bootstrapping

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#1024]
Spun off from https://github.com/OmniSharp/omnisharp-vscode/issues/1856

It would be useful for people not using CSI or dotnet-script - especially those using custom CSX hosts - to be able to predefine using statements and assembly references via `.rsp` files. Those are standard files already used by the compiler itself and look like this: https://github.com/dotnet/roslyn/blob/version-2.4.0/src/Interactive/csi/csi.rsp

In our case, we'd pick up the references used there and use them as globally imported namespaces / references when constructing CSX project system. Configuration proposal - inside `omnisharp.json`, under `script` node, as `rspPath` property. For example:

Since `omnisharp.json` can be global, you could even - in one sweep - configure your entire DEV box if you wanted.

**Comment by KarloX2** [comment]
This is a great idea!

Ideally, referencing assemblies with /r would optionally allow the usage of environment variables, maybe like so:

    /r:C:\Some\Specific\Folder\MyLib.dll
    /r:%MY_ENV_VAR%\Folder\MyOtherLib.dll

**Comment by KarloX2** [comment]
cc me: @KarloX2

**Comment by filipw** [comment]
OK I've made some good progress on this - will PR this soon.

**Comment by KarloX2** [comment]
Very good! I'm really curious to see it. Can you please post here once the update is available? Thanks!
