### ISSUE TITLE
Editing .csx: XML Docs of own libraries are not displayed in Intellisense popups

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#1026]
_From @KarloX2 on November 13, 2017 5:44_

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.18.0
C# Extension version: 1.13.0

## Steps to reproduce

Create a **.csx** files in VS Code and put the line

    #r "C:\Some\Folder\MyLibrary.dll"

in the first line. Make sure that, in the same folder, a .xml documentation file (crated by Visual Studio along with the .dll) exists. Assume there's a class MyClass defined in the dll and documented in the .xml. Try to declare a variable of that class type and observe that the documentation is _not_ being displayed in the IntelliSense popup.

    MyClass myVariable; //<<<--- IntelliSense will show signatures but not the docs.

## Expected  behavior

Member documentation shall be included in IntelliSense popups.

## Actual behavior

No member documentation is displayed.

_Copied from original issue: OmniSharp/omnisharp-vscode#1858_

**Comment by filipw** [comment]
I had a look at this, and it is caused by the fact that we moved to use Roslyn's `RuntimeMetadataReferenceResolver` for resolving `#r` which skips XML docs [here](https://github.com/dotnet/roslyn/blob/version-2.4.0/src/Scripting/Core/Hosting/Resolvers/RuntimeMetadataReferenceResolver.cs#L69).

**Comment by KarloX2** [comment]
@filipw: Is this fix already available in a current release? It seems not to work in 1.13.1.
Thanks

**Comment by filipw** [comment]
not yet, it's part of OmniSharp Roslyn 1.28.0 (https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.28.0) but C# for VS Code 1.13.1 is based on OmniSharp Roslyn 1.26.3. 

Actually the timing was a bit unfortunate, this fix was merged on 14 Nov, but 1.13.1 came out on 13 Nov.
