### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by baurzhan** [OmniSharp/omnisharp-roslyn#1041]
build.sh ends with error: unable to find version '2.3.0-beta4-build3722' of package 'xunit.runner.console'

**Comment by DustinCampbell** [comment]
The latest master branch doesn't reference that version, just `2.3.0-rc1-build3809`. Have pull the latest sources?

**Comment by baurzhan** [comment]
I pulled latest source of omnisharp-vim which includes omnisharp-roslyn as submodule. I'll try pull latest source of omnisharp-roslyn.

**Comment by nickspoons** [comment]
`omnisharp-vim` has its roslyn submodule at to an earlier version and won't work out of the box with the latest build of `omnisharp-roslyn` - from memory, you'll need to modify `autoload/OmniSharp/util.vim` to point to `OmniSharp.Http.exe` instead of just `OmniSharp.exe`

**Comment by Danielhp95** [comment]
I hav the  same issue as @baurzhan. Is there any update on this? I can modify `autoload/OmniSharp/util.vim`, but I would not know how to proceed after that.

**Comment by monefeldt** [comment]
I also would like to bump this issue, I have the exact same issue as above. Tried changing `util.vim` and re-run the build.sh script, but to no avail - same error!

**Comment by monefeldt** [comment]
You have to manually open each .csproj file and change the version of each xunit package by hand! Go to nuget.org and lookup the correct version!

**Comment by monefeldt** [comment]
Or better yet, delete the entire omnisharp-roslyn folder and clone the master branch directly from here:

https://github.com/OmniSharp/omnisharp-roslyn

**Comment by filipw** [comment]
we have moved off the package mentioned in the original issue. I will close this as obsolete, feel free to open a new issue if you still have troubles.
