### ISSUE TITLE
Build Error - Ubuntu 17.10 - Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:37:08 UTC 2017)

### ISSUE THREAD

**Issue by jkvargas** [OmniSharp/omnisharp-roslyn#1048]
Hello dear friends,
I am trying to build but I am getting a SIGSEGV while executing it.
I am not going to paste the entire error log here, instead I am attaching the log message.
Let me know if there is something else that I can do to give you more info if needed.

[omnisharp-roslyn.log](https://github.com/OmniSharp/omnisharp-roslyn/files/1541169/omnisharp-roslyn.log)

Thanks, Jhonny.

**Comment by DustinCampbell** [comment]
This looks like a Mono issue rather than an OmniSharp build issue.

**Comment by jkvargas** [comment]
should I use another version?
