### ISSUE TITLE
dotnet restore in the background

### ISSUE THREAD

**Issue by forki** [OmniSharp/omnisharp-roslyn#1058]
If my sln contains dotnet core C# projects then OmniSharp shows me that it wants to "dotnet restore" and I have to confirm. Why not directly restore it like Ionide does with fsproj?

/cc @Krzysztof-Cieslak

**Comment by Krzysztof-Cieslak** [comment]
I think in medium-long term plan we will add parsing of `csproj`s anyway (to get Ionide's solution explorer working with C# projects) so probably we will include automatic restore too... /shrug

**Comment by DustinCampbell** [comment]
@forki: C# for VS Code does not support auto restore because there were simply too many problems it auto-restoring when the user didn't want it to. For example, auto-restoring when performing git or build operations at the command-line.

**Comment by david-driscoll** [comment]
OmniSharp supports autorestore, but as dustin notes, it's disabled in vscode today.

We could perhaps improve things so that we take a snapshot of dependencies and only restore if we see them change.  This however isn't super easy because it's possible to have variables for version numbers and such will then come from really random locations.

**Comment by forki** [comment]
it works really nice in Ionide!?

**Comment by forki** [comment]
also VisualStudio 2015 does it as well!?

**Comment by DustinCampbell** [comment]
@forki : Is this a request for this feature in C# for VS Code? It sounds like @Krzysztof-Cieslak was planning to do something in Ionide. This repo is for OmniSharp, which already supports package auto-restore. For C# for VS Code, we already have an issue tracking a request for auto restore: https://github.com/OmniSharp/omnisharp-vscode/issues/1731.

**Comment by forki** [comment]
closing in favor of OmniSharp/omnisharp-vscode#1731
