### ISSUE TITLE
Support for whitesmiths brace style

### ISSUE THREAD

**Issue by itslittlejohn** [OmniSharp/omnisharp-roslyn#1065]
In Visual Studio, basic support existed for the whitesmiths indent style:
![image](https://user-images.githubusercontent.com/2136925/34048632-6dfb29e8-e182-11e7-8545-17be9553c24b.png)

It also appears that it was once in option in the omnisharp server:
https://github.com/OmniSharp/omnisharp-server/blob/e1902915c6790bcec00b8d551199c8a3537d33c9/OmniSharp/Configuration/OmniSharpConfiguration.cs#L51-L53

Do you know if/when this support will be coming (back?) to omnisharp?

Thanks!

**Comment by filipw** [comment]
The same feature is already supported in OmniSharp. Create an `omnisharp.json` in the root of your project and use the following setting:

```
{
  "FormattingOptions": {
    "IndentBraces": true
  }
}
```

You can also define this globally on your machine, by creating the `omnisharp.json` at `%USERPROFILE%/.omnisharp/omnisharp.json`. More info [here](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#global-omnisharpjson).

Hope this helps.

**Comment by itslittlejohn** [comment]
Excellent, thanks for pointing that out. 

Although it looks like the config.json link on that wiki page is currently broken. I couldn't find it anywhere else in the repository. Could you update the wiki with the correct link?
