### ISSUE TITLE
Add "IndentNamespace" formatting option.

### ISSUE THREAD

**Issue by Chaser324** [OmniSharp/omnisharp-roslyn#1079]
Some people, myself included, prefer to not indent namespace contents. Currently, I don't think there's any easy way to configure omnisharp to do this.

**Comment by filipw** [comment]
This is really an issue for Roslyn - OmniSharp just [uses the formatting options exposed by Roslyn](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.cs,129) - this applies to all indentation settings.

I'd suggest opening an issue in https://github.com/dotnet/roslyn - any formatting capabilities added there will automatically get picked up by OmniSharp.

**Comment by Chaser324** [comment]
Sorry for that. I wasn't sure how far down the chain I needed to go.

**Comment by Yanpas** [comment]
See https://github.com/dotnet/roslyn/issues/24129
