### ISSUE TITLE
A multi-platform distribution

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-roslyn#1081]
I'd like to embed Omnisharp-roslyn in a multi-platform IDE.
I have the impression it'd be achievable to simply merge the multiple tars/zips and hope it works.
However, I believe it'd be more interesting to have such a multiplatform delivery directly shipped by OmniSharp rather than hand made.

I'll try a few things locally and will report whether I manage to have a multi-platform distribution working. If I succeed, I'll try to contribute that to OmniSharp, but any help would be welcome in the meantime.

**Comment by willl** [comment]
omnisharp-emacs already does this. You can see their implementation [here](https://github.com/OmniSharp/omnisharp-emacs/blob/master/omnisharp-server-installation.el). 

Also the related [issue](https://github.com/OmniSharp/omnisharp-emacs/issues/275) by @razzmataz.

**Comment by david-driscoll** [comment]
Yeah this is something we need to look at, it may certainly be doable, however may not be super straight forward.

The biggest problem comes with crossing windows / linux when you look at how things work and build on the desktop framework vs mono, file permissions, etc.  So we would have to have a way to merge those together.

`run` could be modified to use the correct mono runtime version for the environment (linux-x86, linux-x64 or osx).

**Comment by david-driscoll** [comment]
Did some looking manually, we could create a `posix` package that packs in all the bits for `*nix` like systems.  I have not updated `run` or done any real testing (I need a mac, but I also need money to buy one 😢) but the package size only grew by 2.5 MB with all three mono versions inside.

Mixing the windows and posix packages however would be harder as the `OmniSharp.exe` does different between windows and *nix, one won't run under the other (at least it won't for me at the moment).  That's what CoreCLR offers, with the dotnet executable, we won't be on .net core for the foreseeable future for various reasons.  

We could potentially embed the windows version of mono, however that seems fairly pointless as there is a perfectly good version of the .net framework installed on windows already.

**Comment by mickaelistria** [comment]
Thanks for checking. In that case, I don't think it's worth the effort in our use-case: Eclipse already has smart mechanism to provision platform-specific components, so we can just use them instead of adding trickiness and workload in Omnisharp-Roslyn.
From my POV, you can close the ticket as David's answers helped to highlight that this is a non-trivial effort and better solutions should be considered on client side.

**Comment by david-driscoll** [comment]
It used to be more complex when we had to deal with all the different possible distributions (back with .net core) but now we have a fairly constrained set, it shouldn't be a huge deal.
