### ISSUE TITLE
[LSP] Hover sometimes illegaly returns `contents: [null, null]`

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-roslyn#1087]
In some circumstances not yet identified, the LSP support returns `{"protocolVersion":"2.0","id":"2","result":{"contents":[null,null]}}`. This value doesn't seem conform to the protocol which doesn't make any of the value nullable or optional here. As a consequence the parser in LSP4J api fails at parsing the stream and closes it to handle the error, cascading to a restart of the LS and so on.
While LSP4J has a part of responsibility, it's somehow fair to assume that the messages sent conform to specification. In the case of `contents:[null,null]`, it would be better to simply return `contents:[]`.

**Comment by mickaelistria** [comment]
This is really happening quite often even with latest version of OmniSharp and it results in error in some clients. Is there a way this could be fixed soon?
According to https://microsoft.github.io/language-server-protocol/specification , in this case, 
```
{"protocolVersion":"2.0","id":"2","result":null}
```
would be a better error message.

**Comment by mickaelistria** [comment]
I cannot reproduce it with latest snapshot (includes more recent OmniSharp version)

**Comment by rcjsuen** [comment]
I'm still seeing this with`omnisharp-mono.tar.gz` on v1.34.0. It was originally reported by two other users from TypeFox/monaco-languageclient#146.

**Comment by tomv564** [comment]
Still seeing this as well from the Sublime Text LSP package on version v1.34.2.

**Comment by lxbarbosa** [comment]
Issue still happening in **1.34.9**: https://github.com/joaotavora/eglot/issues/371#issuecomment-568254412


log: http://ix.io/253F/text  - lines:  3177 and 3555

full reporting: https://github.com/joaotavora/eglot/issues/371#issuecomment-568205461
