### ISSUE TITLE
Not able to use preexisting environment variables in an OmniSharp project

### ISSUE THREAD

**Issue by Ruin0x11** [OmniSharp/omnisharp-roslyn#1091]
I have a script that sets the environment to select the correct version of `MsBuildFrameworkToolsPath`, `MsBuildToolsPath` and other paths needed by MSBuild for series of projects. However, running the OmniSharp server does not respect these variables, and I get errors that are the same as if I hadn't run the initial script when opening a solution in Visual Studio 2015. The path to the MSBuild executable would be something like:

```
D:\path\to\MSBuild\v14.0\Bin\MSBuild.exe
```

So, I created a global `omnisharp.json` like:

```
{
    "MsBuild": {
        "MSBuildSdksPath": "D:\\path\\to\\MSBuild\\",
        "TargetFrameworkRootPath": "D:\\path\to\\MSBuild\\",
        "MSBuildExtensionsPath": "D:\\path\\to\\MSBuild\\Extensions"
    }
}
```

But launching the OmniSharp server does not respect these settings for some reason. It still reports this in the log:

```
[14:55:10] INFORMATION: OmniSharp.MSBuild.Discovery.MSBuildLocator, Registered MSBuild instance: StandAlone 15.0 - "c:\users\ian\.emacs.d\.cache\omnisharp\server\v1.26.3\msbuild\15.0\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\users\ian\.emacs.d\.cache\omnisharp\server\v1.26.3\msbuild\15.0\Bin\Roslyn
            MSBuildExtensionsPath = c:\users\ian\.emacs.d\.cache\omnisharp\server\v1.26.3\msbuild
            MSBuildToolsPath = c:\users\ian\.emacs.d\.cache\omnisharp\server\v1.26.3\msbuild\15.0\Bin
```

The `omnisharp-emacs` project I'm using downloads a copy of the OmniSharp server into a cache to use it later.

The following is the kind of error preventing the projects from being opened. However, having the environment properly set beforehand fixes them.

```
[14:55:10] INFORMATION: Loading project D:\some\project.csproj
[14:55:10] WARNING: Failed to load project file 'D:\some\project.csproj'
Microsoft.Build.Exceptions.InvalidProjectFileException: The value "" of the "Project" attribute in element <Import> is invalid.
```

**Comment by Ruin0x11** [comment]
Seems to be fixed by changing the way I started cmd.exe. Closing.

**Comment by victorfonsec4** [comment]
What changes did you do to the way you start cmd?
