### ISSUE TITLE
Support for fixing code issues?

### ISSUE THREAD

**Issue by mispencer** [OmniSharp/omnisharp-roslyn#1098]
I am porting a client from the legacy Omnisharp to roslyn Omnisharp, and support for /fixcodeissue is the last feature I'm trying to port. Does this feature exist in roslyn Omnisharp?

To clear, code issues are these:
![capture](https://user-images.githubusercontent.com/1434266/35424358-5a60cc90-0210-11e8-9d72-4ab7659b9469.PNG)

This is distinct from code actions, which is supported by roslyn Omnisharp.

**Comment by filipw** [comment]
This was implemented as part of #1076
