### ISSUE TITLE
partial class

### ISSUE THREAD

**Issue by martingronlund** [OmniSharp/omnisharp-roslyn#1116]
My code with a partial class split into three files compiles and runs just fine, but intellisense can't find the symbols.

It says things like
- `The name 'FooProperty' does not exist in the current context`
- `'FooClass.BarMethod': no suitable method found to override`.
- `'FooClass' does not contain a definition for 'barProperty' and no extension method 'barProperty' accepting a first argument of type 'FooClass' could be found (are you missing a using directive or an assembly reference?)`

Would love to have this working!

**Comment by DustinCampbell** [comment]
Any chance you could provide a project that reproduces the issue?

**Comment by filipw** [comment]
Closing due to lack of response. Feel free to re-open or open a new issue if you could provide repro steps and OmniSharp log. Thanks.
