### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by Redmancometh** [OmniSharp/omnisharp-roslyn#1120]
The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\Redmancometh\Downloads\omnisharp-roslyn\.dotnet\dotnet-install.ps1:491 char:24
+ $free = Get-CimInstance <<<<  -Class win32_logicaldisk | where Deviceid -eq "${installDrive}:"
    + CategoryInfo          : ObjectNotFound: (Get-CimInstance:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bsh-git** [comment]
I had the same problem on Windows 7.  Installing Windows Management Framework 3.0  to the PC fixed the problem.

**Comment by DustinCampbell** [comment]
cc @livarcocc for the dotnet install script.

**Comment by livarcocc** [comment]
@johnbeisner

**Comment by filipw** [comment]
Closing this as obsolete. Please open a new issue if this still happens with the latest build.
