### ISSUE TITLE
The "SkipNonexistentTargets" parameter is not supported by the "MSBuild" task.

### ISSUE THREAD

**Issue by awyl** [OmniSharp/omnisharp-roslyn#1121]
When loading a project with this attribute `SkipNonexistentTargets` in vscode on Mac OSX.

https://github.com/OrchardCMS/OrchardCore/blob/04694c0e56d0d55963f44c90f3ba1f257045a185/src/OrchardCore/OrchardCore.Application.Targets/OrchardCore.Application.Targets.targets#L14

**Comment by cocoke** [comment]
Hi, I think this can help
https://github.com/OrchardCMS/OrchardCore/issues/1523

**Comment by awyl** [comment]
Thanks.
