### ISSUE TITLE
Omnisharp doesnt search reference paths

### ISSUE THREAD

**Issue by TobiasLorek** [OmniSharp/omnisharp-roslyn#1122]
In out csproj file we import an other project path.csproj which has the reference path for all the dlls we are using. However, omnisharp doesn't seem to follow the reference and are instead complaining that it can't find the referenced dlls in the project root directory. 
I.e. we get errros of the following form
```
warn: OmniSharp.MSBuild.ProjectManager[0]
Unable to resolve assembly Sln\P1\Sln.dll
warn: OmniSharp.MSBuild.ProjectManager[0]
Unable to resolve assembly Sln\P1\P2.dll
```
When the dlls are located in \Build\Debug

**Comment by DustinCampbell** [comment]
Hi! Could you provide an example project that demonstrates the problem?

**Comment by filipw** [comment]
closing due to lack of inactivity. if you are able to reproduce this with the latest OmniSharp, please open the issue again and provide the omnisharp log and a repro project - thank you!
