### ISSUE TITLE
Possibility to exclude paths when searching for project files and script files

### ISSUE THREAD

**Issue by mholo65** [OmniSharp/omnisharp-roslyn#1126]
Possibility to exclude paths when searching for project files and script files. Exclude patterns could be added via OmniSharp [Configuration Options](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options).

**Comment by filipw** [comment]
This looks almost like a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/896?

**Comment by mholo65** [comment]
@filipw, yeah it’s a duplicate. Closing this then..
