### ISSUE TITLE
Nuget dependencies not complete (eg.: Newtonsoft.Json)

### ISSUE THREAD

**Issue by DavidUser** [OmniSharp/omnisharp-roslyn#1139]
[![asciicast](https://asciinema.org/a/W6KVf76G8IRIkyVUCjIV2eVyF.png)](https://asciinema.org/a/W6KVf76G8IRIkyVUCjIV2eVyF)

**Comment by nickspoons** [comment]
Instead of just `touch coreApp.sln`, create the `sln` file with `dotnet` and add the project to the solution:

    dotnet new sln
    dotnet sln add coreApp.csproj

Now you can get completion etc.

**Comment by DavidUser** [comment]
Same problem, no completion.
[![asciicast](https://asciinema.org/a/f8MmJcRKxGiHnsXs0jIuCofcd.png)](https://asciinema.org/a/f8MmJcRKxGiHnsXs0jIuCofcd)

**Comment by nickspoons** [comment]
You didn't add the NuGet reference to your .csproj file in that example

**Comment by nickspoons** [comment]
dotnet new sln -o coreApp
    cd coreApp
    dotnet new console
    dotnet sln add coreApp.csproj
    dotnet add coreApp.csproj package "Newtonsoft.Json"
    dotnet restore
    vim Program.cs

Line 5 adds the `Newtonsoft.Json` reference, just as you manually added it to `coreApp.csproj` in your first example

**Comment by DavidUser** [comment]
[![asciicast](https://asciinema.org/a/kFcvv2gYqZZBaNLfExOzSJ9v7.png)](https://asciinema.org/a/kFcvv2gYqZZBaNLfExOzSJ9v7)

**Comment by nickspoons** [comment]
Well then I'm stuck. I've tested those commands a couple of times now and it works fine for me with dotnet --version 2.1.101.

Could you try to create a valid program using Newtonsoft and see if it can build? Something like this:

    using System;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    
    namespace coreApp
    {
        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine(JObject.Parse("{'Hello':'world'}").ToString(Formatting.Indented));
            }
        }
    }

Then do `dotnet run` and see if it works?

**Comment by DavidUser** [comment]
Runs correctly, Netonsoft related completion still doesn't work.
[![asciicast](https://asciinema.org/a/XrenG9wJCJyEwxy37Xrx3AfLl.png)](https://asciinema.org/a/XrenG9wJCJyEwxy37Xrx3AfLl)

**Comment by DavidUser** [comment]
My dotnet version is 2.1.101 too.

**Comment by DavidUser** [comment]
OK! Looking to YCM third_party directory, I see that it's using OmniSharpServer and not this omnisharp-roslyn.

I'll need ask to YCM to support omnisharp-roslyn.

**Comment by DavidUser** [comment]
https://github.com/Valloric/YouCompleteMe/issues/2959

**Comment by nickspoons** [comment]
Since it's not a roslyn problem, do you want to close the issue @DavidUser?
