### ISSUE TITLE
Unable to get autocompletion for dynamically created files in omnisharp-roslyn

### ISSUE THREAD

**Issue by RudraNilBasu** [OmniSharp/omnisharp-roslyn#1140]
The following autocomplete request is sent to a server running on http://localhost:2000 by omnisharp-roslyn (passing the path to the project's .sln file via `./OmniSharp.exe -s ~/path/to/sln/file`), which produces the correct response.

```
curl -H "Content-Type: application/json" -X POST -d '{"Line":9,"Column":18, "FileName":"/path/to/file.cs","WantDocumentationForEveryCompletionResult":"true","WordToComplete":"Consol"}' http://localhost:2000/autocomplete
```

Result:

```
{
"CompletionText":"Console",
"Description":"Represents the standard input, output, and error streams for console applications. This class cannot be inherited.",
"DisplayText":"Console","RequiredNamespaceImport":null,"MethodHeader":null,"ReturnType":null,
"Snippet":null,
"Kind":null,
"IsSuggestionMode":false
},
...
```

However, on creating a new file and making an autocomplete request for the newly created file (without restarting the server)

```
curl -H "Content-Type: application/json" -X POST -d '{"Line":9,"Column":18, "FileName":"/path/to/new/file.cs","WantDocumentationForEveryCompletionResult":"true","WordToComplete":"Consol"}' http://localhost:2000/autocomplete
```

results in an empty array `[]`

On restarting the server and following the same procedure, the result comes as expected.

Is there a way to get autocomplete responses for a newly created file without having to restart the server? Am I missing something here?

**Comment by nickspoons** [comment]
Your request should contain the current contents of the buffer:

    ..., "FileName": "/path/to/file.cs", "Buffer": "using System;\r\nusing ...", ...

**Comment by RudraNilBasu** [comment]
That works, thanks
