### ISSUE TITLE
ProjectAdded event is not fired for a script project

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-roslyn#1141]
Steps to Reproduce:
Add a .csx file in a folder and open it through vscode (C# extension)

Expected: 
The `projectAdded` event is fired.

Actual Behavior:
The `projectAdded` event is not fired

cc @rchande @TheRealPiotrP @colombod

**Comment by DustinCampbell** [comment]
cc @filipw

**Comment by rchande** [comment]
@akshita31 Is this fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/1142#event-1558785784 or do we have more work to do?

**Comment by akshita31** [comment]
Yes #1142 fixes it.
