### ISSUE TITLE
a little question about '/currentfilemembersastree'

### ISSUE THREAD

**Issue by SteamUpdate** [OmniSharp/omnisharp-roslyn#1162]
This endpoint not returning a `FileName` in `Location` property. I can easily fix it.
A question is: bug it or not?

**Comment by DustinCampbell** [comment]
It probably should. Although, I expect the value to be the same as the `FileName` that's passed in with the request.

**Comment by DustinCampbell** [comment]
Sorry! I forget to update you here. This end point is effectively deprecated at this point. You should use the `/v2/codestructure` end point, which replaces this.
