### ISSUE TITLE
Code formatting feature

### ISSUE THREAD

**Issue by NichitaCiuprin** [OmniSharp/omnisharp-roslyn#1167]
I want to create a c# formatter that is independent from editor. Thou cant find any related formating logic in a source. Can you please tell me there i can find it?

**Comment by DustinCampbell** [comment]
OmniSharp doesn't really contain C# formatting code. Instead, it uses Roslyn to perform formatting here: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs#L86-L99.

**Comment by NichitaCiuprin** [comment]
Thanks for help
