### ISSUE TITLE
[Linux Http server] Unable to create directory "/Debug/". Access to the path "/Debug/" is denied.

### ISSUE THREAD

**Issue by as3mbus** [OmniSharp/omnisharp-roslyn#1168]
I am trying to run omnisharp http server for omnisharp vim but failed with these warning and error : 
```
warn: OmniSharp.MSBuild.ProjectLoader[0]
      Unable to create directory "/Debug/". Access to the path "/Debug/" is denied.
warn: OmniSharp.MSBuild.ProjectLoader[0]
      Could not write state file "/Debug/Assembly-CSharp.csprojResolveAssemblyReference.cache". Could not find a part of the path "/Debug/Assembly-CSharp.csprojResolveAssemblyReference.cache".
fail: OmniSharp.MSBuild.ProjectLoader[0]
      Could not write lines to file "/Debug/Assembly-CSharp.csproj.CoreCompileInputs.cache". Could not find a part of the path "/Debug/Assembly-CSharp.csproj.CoreCompileInputs.cache".
warn: OmniSharp.MSBuild.ProjectManager[0]
      Failed to load project file '/media/Produce/Projects/Final Assignment/Open_Fuzzy_Scenario/Assembly-CSharp.csproj'.                                               

```
the command i use to run the omnisharp is
```
TERM=xterm mono /home/as3mbus/.vim/omnisharp.http-linux-x64/omnisharp/OmniSharp.exe                                                              
```
i'm sorry that i couldn't give anymore detail since i don't have much understanding about how stuff work.

**Comment by nickspoons** [comment]
Appears to be related to #1676, although that was on a Mac and apparently solved, whereas this is arch Linux. A few more details given at OmniSharp/omnisharp-vim#356

**Comment by as3mbus** [comment]
thank you @nickspoons for the follow up. 

according to every issue and error i found in the internet including one that provided above. it seems like it would need msbuild, or maybe other (i don't really know much). unfortunately mono doesn't provide installation step for arch linux, and there are no package like mono-mdk either like on Mac 

Here several thing i've tried : 
1. install msbuild-bin from AUR, 
2. trying to run `msbuild <csproj file> results in 0 error
3. install mono-tools, and mono-addins from Official repository
4. reinstalling mono

the error still persist after everything i did. 
I'm stuck

**Comment by nickspoons** [comment]
Perhaps @DustinCampbell might have some ideas? (pinging you since you solved the linked issue)

**Comment by DustinCampbell** [comment]
What version of Mono is installed? Have you tried the OmniSharp run script packaged with omnisharp.http-linux-x64?

**Comment by DustinCampbell** [comment]
Thanks. In that case, it definitely doesn't address the problem. Have you tried installing the msbuild package for ArchLinux (https://aur.archlinux.org/packages/msbuild-stable/)?

**Comment by as3mbus** [comment]
It worked, without error nor warning. 
what i've tried is msbuild-bin it upstreamed to dotnet instead of mono. maybe that's why
way too long package name make me FUD to install the msbuild-stable package
anyway thanks.

**Comment by DustinCampbell** [comment]
Glad to hear it worked!

**Comment by uniqueinx** [comment]
it worked for me on manjaro linux based on arch
