### ISSUE TITLE
Omnisharp-1.29.2-beta.163 error

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-roslyn#1172]
Steps to Reproduce:
In vscode C# extension set `omnisharp.path: "latest"` [ On linux or Mac ] and try to run the Integration Tests

Expected behavior
The tests run

Actual behavior
The tests do not run as there is a problem with omnisharp and some error occurs while omnisharp is trying to warm up to run for that project.

An example travis build that is failing for the extension:
https://travis-ci.org/OmniSharp/omnisharp-vscode/builds/369325063?utm_source=github_status&utm_medium=notification

Note that if we set the path to some previous version number then the tests run properly.

Once this issue is resolved, please create a PR to omnisharp vscode that sets the "omnisharp.path" back to "latest" for the integration test folders. Specifically the two files here :  https://github.com/OmniSharp/omnisharp-vscode/blob/master/test/integrationTests/testAssets/singleCsproj/.vscode/settings.json

https://github.com/OmniSharp/omnisharp-vscode/blob/master/test/integrationTests/testAssets/slnWithCsproj/.vscode/settings.json

cc @rchande @TheRealPiotrP

**Comment by rchande** [comment]
Thanks @akshita31 , I'll take a look.

**Comment by akshita31** [comment]
@rchande I believe this is fixed now.
