### ISSUE TITLE
Return class name in the features when /currentfilemembersastree request is sent

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-roslyn#1198]
We added a "Run All Tests" and "Debug All Tests" utility in vscode. We should display the class name in the logs : `Running tests in class : abc`

**Comment by akshita31** [comment]
We can add a node is ClassDeclarationSyntax if statement here, but how to model the syntax feature here, what should be the name and data fields ?
cc @DustinCampbell

**Comment by DustinCampbell** [comment]
I'm not sure I understand. Shouldn't the node that the `Run All Tests` and `Debug All Tests` code lenses are attached to already have a name that we can display?

**Comment by akshita31** [comment]
![codelens_class](https://user-images.githubusercontent.com/12554141/40443290-b5f6e604-5e7a-11e8-90ac-fbdbd31d6b72.PNG)

@DustinCampbell This is all the information we have. I do see a "Text" property in "Location" but that is just the name of the class. Should we just print `Running Tests in Class UnitTest1` or should we have the metadata name as we have for the test methods ?

**Comment by DustinCampbell** [comment]
I think we can provide better information here. Let me take a look.

**Comment by rchande** [comment]
@DustinCampbell @akshita31 If we move the unit tests codelens to call Dustin's new "codestructure" API, do we get this info?

**Comment by DustinCampbell** [comment]
Yes. I'm working on a PR to move all of CodeLens over to the `/codestructure` endpoint.

**Comment by DustinCampbell** [comment]
The PR will also move `DocumentSymbolProvider` over to `/codestructure` as well.

**Comment by akshita31** [comment]
This has been resolved by using the new CodeStructure APi
