### ISSUE TITLE
Multiple omnisharp.json settings for one project

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#1208]
_From @ypapouin on May 31, 2018 11:20_

Currently, you can override FormattingOptions by placing an omnisharp.json file at the project root folder. 

In my projects, I'm using a lot of sub-modules (git) developed by third parties with different C# settings, but all changes made (for merge request to upstream) in these sub-modules must be formatted by hand to avoid losing original formatting.

I would be happy to be able to customize FormattingOptions for each of these sub-modules.

For each folder containing an omnisharp.json, all sub-folder would recursively apply these settings until a new omnisharp.json is found.

## Environment data
`dotnet --info` output:
Outils en ligne de commande .NET (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

VS Code version: 1.23.1
C# Extension version: 1.15.2

_Copied from original issue: OmniSharp/omnisharp-vscode#2357_

**Comment by filipw** [comment]
@ypapouin thanks for a feature request.

could you provide a bit more background on what you are trying to do? you have a single solution, where you load multiple projects, but would like to effectively have per-project settings based on the paths, am I understanding you correctly? 

Because you can already have multiple omnisharp.json files on different levels, what matters is the startup folder though - OmniSharp will select the one in the current startup directory.

**Comment by ypapouin** [comment]
Thanks for moving issue to the right project.

Actually I have a single solution with a single project, but my project is versioned using git and some third-party libraries (as source code) that are set in their own sub-folder. 

All these libraries sub-folders are git sub-modules since they are maintained for multiple project. But their maintainer have different formatting options:

```
MyProject:
├───.git
├───lib
│   ├───display
│   │   ├───.git
│   │   └───code.cs
│   ├───input
│   │   ├───.git
│   │   └───code.cs
│   └───network
│       ├───.git
│       └───code.cs
├───src
│    └───main.cs
├───omnisharp.json
├───project.csproj
└───project_solution.sln
```

```
LibMaintainerProject:
├───.git
├───lib
│   ├───display
│   │   ├───.git
│   │   └───code.cs
│   ├───input
│   │   ├───.git
│   │   └───code.cs
│   └───network
│       ├───.git
│       └───code.cs
├───omnisharp.json
├───src
│    └───test_display.cs
│    └───test_input.cs
│    └───test_network.cs
├───omnisharp.json
├───project_lib.csproj
└───project_lib_solution.sln
```

Would be nice to be able to have:
```
MyProject:
├───.git
├───lib
│   ├───display
│   │   ├───.git
│   │   ├───code.cs
│   │   └───omnisharp.json
│   ├───input
│   │   ├───.git
│   │   ├───code.cs
│   │   └───omnisharp.json
│   └───network
│       ├───.git
│   │   ├───code.cs
│   │   └───omnisharp.json
├───src
│    └───main.cs
├───omnisharp.json
├───project.csproj
└───project_solution.sln
```
or:
```
MyProject:
├───.git
├───lib
│   ├───display
│   │   ├───.git
│   │   └───code.cs
│   ├───input
│   │   ├───.git
│   │   └───code.cs
│   └───network
│   │   ├───.git
│   │   └───code.cs
│   └───omnisharp.json
├───src
│    └───main.cs
├───omnisharp.json
├───project.csproj
└───project_solution.sln
```

**Comment by DustinCampbell** [comment]
Wouldn't this be better solved by supporting `.editorconfig` files?

**Comment by Siccity** [comment]
+1

**Comment by filipw** [comment]
We have decided to not implement this in favor of `.editorconfig` which can already be used to achieve everything described here
