### ISSUE TITLE
Support for code actions/refactorings that show UI in Visual Studio

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-roslyn#1220]
There are a number of useful code actions in Visual Studio that, when invoked, show some UI that let the user specify the behavior of the code action. This includes, (but might not be limited to) "Extract Interface", "Generate Type", "Generate Equals/Hashcode", "Reorder Parameters", etc. Apart from "Reorder Parameters", it's likely that not showing a UI and simply generating all possible members could be useful.

**Comment by filipw** [comment]
@rchande this was implemented in https://github.com/OmniSharp/omnisharp-roslyn/pull/1406 can we close it?
