### ISSUE TITLE
OmniSharp server not listening on any port

### ISSUE THREAD

**Issue by m0v0nage** [OmniSharp/omnisharp-roslyn#1247]
`mono /path/to/omnisharp/OmniSharp.exe -p 2000 -s /path/to/project.sln`

OS: `Debian 9`
solution target framework: `dotnet core 2.1`
libuv: `1.9.1`
mono version: `5.12.0.226`
omnisharp-roslyn version: `1.32.1`

The server seems to start without error but a `netstat -ln` shows nothing listening on the port I specify. It's also evident by the fact that omnisharp-vim doesn't seem to be doing anything when I run commands.

Any ideas to what is causing this?

**Comment by nickspoons** [comment]
Are you using the HTTP version of the omnisharp-roslyn binaries? i.e. `omnisharp.http-linux-x64.tar.gz` from https://github.com/OmniSharp/omnisharp-roslyn/releases ?

**Comment by m0v0nage** [comment]
That was the root issue! I read that HTTP was required on Linux, and assumed that it was included in version I was using. In addition, for anyone who might see this later, I had to install the Debian libuv1-dev package.

**Comment by m0v0nage** [comment]
Maybe there is a way to make it more explicit. When I went to the release page, I just assumed that the 64 bit version for Linux included Http support. Or perhaps the exe should spit out a warning if it sees flags it doesn't support. Thanks for the time you spend on this project, @nickspoons.

**Comment by filipw** [comment]
At some point in the past the two servers were actually shipped together, but a while ago they were split into separate executables. We should add a more explicit note into the docs.

**Comment by nickspoons** [comment]
I think vim is the main user of the HTTP version now. The vim README needs
a bit of an overhaul (it still includes functionality that is only
available in the legacy server) so I can try to make it more explicit.

A note on the OmniSharp-roslyn releases page would be helpful though -
especially as the editors which use the stdio version include automatic
download, of the server, so I imagine vim users are the main readers of the
releases page.
