### ISSUE TITLE
The type 'X' exists in both 'Y' and 'Z' when using omnisharp-roslyn for unity projects

### ISSUE THREAD

**Issue by saevarb** [OmniSharp/omnisharp-roslyn#1248]
I've been spending quite some time trying to get omnisharp-roslyn to work properly for Unity3D projects lately, so that I can develop on Linux using emacs.

The issue: Using certain modules from Unity seems to lead to omnisharp finding references to the same type in multiple different assemblies.

` GameMana…    11  12 error           The type 'GameObject' exists in both 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' (csharp-omnisharp-codecheck)`

It seems like this may be related to #1225, but as I wasn't sure I decided to create an issue.
I was unfortunately not able to test whether the recently merged changes for that issue fixed it, as trying to build omnisharp-roslyn on my machine leads to strange segfaults during building, which I have been completely unable fix. 

Things I've tried:

1. Updating omnisharp from v1.31.1 to the latest release (No change)
2. Removing references to CoreModule in the .csproj file manually (More errors)

**Comment by dmgonch** [comment]
You could try the fix by adding **"omnisharp.path": "latest"** in VS Code User Settings (https://github.com/OmniSharp/omnisharp-vscode/releases, scroll to Options)

**Comment by saevarb** [comment]
I use emacs, not VS code, unfortunately. And I've already tried the latest release.

**Comment by saevarb** [comment]
It seems this was a problem with my environment. I figured it out after recreating the project.
