### ISSUE TITLE
"Remote end closed connection without response" on any command

### ISSUE THREAD

**Issue by Eranikid** [OmniSharp/omnisharp-roslyn#1263]
Hello.

I am trying to get OmnisharpVim working. I am completely new to it, and to vim in general, but I am trying my best. I have chosen to install Omnisharp server automatically, and it succesfully installed and started, as `lsof -i` shows me that process `mono` listens on port 36625. My `.vimrc`is the following:

    call plug#begin('~/.vim/plugged')

    Plug 'OmniSharp/omnisharp-vim'

    call plug#end()

    filetype plugin on

    let g:OmniSharp_timeout = 5

    set completeopt=longest,menuone,preview

    set previewheight=5

    augroup omnisharp_commands
        autocmd!

        autocmd CursorHold *.cs call OmniSharp#TypeLookupWithoutDocumentation()

        autocmd FileType cs nnoremap <buffer> gd :OmniSharpGotoDefinition<CR>
        autocmd FileType cs nnoremap <buffer> <Leader>fi :OmniSharpFindImplementations<CR>
        autocmd FileType cs nnoremap <buffer> <Leader>fs :OmniSharpFindSymbol<CR>
        autocmd FileType cs nnoremap <buffer> <Leader>fu :OmniSharpFindUsages<CR>

        autocmd FileType cs nnoremap <buffer> <Leader>fm :OmniSharpFindMembers<CR>

        autocmd FileType cs nnoremap <buffer> <Leader>fx :OmniSharpFixUsings<CR>
        autocmd FileType cs nnoremap <buffer> <Leader>tt :OmniSharpTypeLookup<CR>
        autocmd FileType cs nnoremap <buffer> <Leader>dc :OmniSharpDocumentation<CR>
        autocmd FileType cs nnoremap <buffer> <C-\> :OmniSharpSignatureHelp<CR>
        autocmd FileType cs inoremap <buffer> <C-\> <C-o>:OmniSharpSignatureHelp<CR>

        autocmd FileType cs nnoremap <buffer> <C-k> :OmniSharpNavigateUp<CR>
        autocmd FileType cs nnoremap <buffer> <C-j> :OmniSharpNavigateDown<CR>
    augroup END

    nnoremap <Leader><Space> :OmniSharpGetCodeActions<CR>
    xnoremap <Leader><Space> :call OmniSharp#GetCodeActions('visual')<CR>

    nnoremap <Leader>nm :OmniSharpRename<CR>
    nnoremap <F2> :OmniSharpRename<CR>
    command! -nargs=1 Rename :call OmniSharp#RenameTo("<args>")

    nnoremap <Leader>cf :OmniSharpCodeFormat<CR>

    nnoremap <Leader>ss :OmniSharpStartServer<CR>
    nnoremap <Leader>sp :OmniSharpStopServer<CR>

    nnoremap <Leader>th :OmniSharpHighlightTypes<CR>

, which is essentially the config from `OmnisharpVim` main page, without `SyntasticCheck` with the config necessary to install `OmnisharpVim` plugin.

All the commands are autocompleted, so the plugin itself seems to have connected, however when trying to execute any command, the bottom status bar says `CONNECTION: Remote end closed connection without response`. Is there any chance that vim targets the wrong port or something?

`:echo has('python3') || has('python')` returns 1.
Vim version 8.0
Ubuntu 18.04.1 LTS

Please request any additional information if you need it.
Thanks in advance for any help!

**Comment by nickspoons** [comment]
This is an OmniSharp-vim issue and should be opened [here](https://github.com/OmniSharp/omnisharp-vim/issues)

Vim won't be listening on the wrong port, vim has assigned the port and started the server running on it. There are various things you can check but the first thing is to check you have the right server (the HTTP version) since this is what tends to be the problem when people get started with a manually installed server.

Could you please open a new issue in the OmniSharp-vim repo, and include why you chose to manually install the server? Did you try letting vim install it?

Please include the output of launching your server from the command line like this:

    $ /full/path/to/omnisharp/run -v -s /full/path/to/your.sln

**Comment by Eranikid** [comment]
Oh dear lord, I have confused browser tabs, this is the wrong repo!

Sorry for disturbance, thank you @nickspoons for your participation, I will close this issue and go bug folks at OmniSharp-vim.
