### ISSUE TITLE
Failing test on Windows

### ISSUE THREAD

**Issue by mat-mcloughlin** [OmniSharp/omnisharp-roslyn#128]
We've got a test that fails on Windows but not nix

`FormattingFacts.TextChangesAreSortedLastFirst`

For some reason its returning 8 spaces as the text change in windows and only a single space on nix.

Had a quick peek around but not familiar with the code so may be one for @jrieken :)

**Comment by jrieken** [comment]
Funky - it seems to pick up a setting from somewhere ;-) I will investigate but I am afraid I won't find time before tomorrow.

**Comment by mat-mcloughlin** [comment]
Ah, good. At least it wasn't something obvious I was missing :)

**Comment by nosami** [comment]
Please.... this is tweaking my OCD :)

**Comment by mat-mcloughlin** [comment]
Is it worth just skipping the test for now?

**Comment by nosami** [comment]
Haven't got my head around TextChanges yet, but it looks like a genuine fail - whether that's coming from omnisharp or roslyn, not so sure. But I think we should leave it until we have an answer.

**Comment by jrieken** [comment]
back from :ski: and this is high on my list - it is strange tho and doesn't repo on my windows box...

**Comment by mat-mcloughlin** [comment]
Any output I can get you that will help?

**Comment by jrieken** [comment]
@mat-mcloughlin anything is appreciated ;-) this is becoming very weird... can you repro this locally?

**Comment by jrieken** [comment]
getting there with PR #148 - it is the way git preserves or replaces newline character when fetching stuff...
