### ISSUE TITLE
Duplicate "find symbols" results

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-roslyn#1281]
This looks like a regression in the 1.32 release...

![image](https://user-images.githubusercontent.com/3751401/44924633-c74b3480-ad00-11e8-9dd0-4f1e86516123.png)

**Comment by mholo65** [comment]
Same problem we had with `/codecheck` a while ago? What happened to `/findsymbols`? Does it check whole solution instead of file nowadays?

**Comment by rchande** [comment]
@mholo65 I don't believe there was a behavior change to findSymbols. I'm guessing this got regressed when we added the cake handler.

**Comment by rchande** [comment]
@mholo65 I would guess so--I could be wrong about it being new in 1.32. The find symbols implementation hasn't changed since April 2017.
