### ISSUE TITLE
Auto-import assembly / namespace

### ISSUE THREAD

**Issue by CoreyKaylor** [OmniSharp/omnisharp-roslyn#129]
Similar to the way that R# can automatically import namespaces and add references based on code written into the editor. It would be nice if omnisharp could do the same type of thing.

Golang has a similar behavior with the vim-go plugin. In the event of a conflict or multiple matches it defaults to the first match last time I checked. That might be a good starting point. I actually like the behavior of this vim plugin more than R# because it happens when the document is saved instead of while you're typing.

**Comment by nosami** [comment]
:+1: Would be cool if it could automatically download nuget packages too. I heard the aspnet team were working on this and would share the code with us.

**Comment by JulioJu** [comment]
3 years after, there is a plan to add auto-import ? It seams that it's added for Visual-Studio-Code (see https://github.com/OmniSharp/omnisharp-vscode/issues/1117) but not for Vim Users. Actually, with omnisharp-vim, we could not auto import "using".
Thanks in advance for your answer ;-).

**Comment by filipw** [comment]
Implemented in https://github.com/OmniSharp/omnisharp-roslyn/pull/1896
