### ISSUE TITLE
[LSP] language server mode not conforming to base protocol?

### ISSUE THREAD

**Issue by ilohmar** [OmniSharp/omnisharp-roslyn#1300]
I am trying to use the language-server mode from the generic Emacs implementation https://github.com/joaotavora/eglot (that works with several other language servers).  This is on a linux machine, in case it matters.  From my debugging of the communication it looks like omnisharp does not implement the base protocol https://microsoft.github.io/language-server-protocol/specification (the relevant part is the same in the 2.x version):

1) A valid request MUST have at least one header field (HTTP-like), and the header must be terminated by an extra `\r\n`.  But `Omnisharp.Stdio.Host.HandleRequest` chokes on everything preceding the JSON object itself (in particular a protocol-conforming `Content-Length: 1234\r\n\r\n`).

I haven't looked into the code too much, it seems that there is no actual handling of the HTTP headers?  Maybe because in the HTTP implementation they are already parsed and stripped and JSON is passed in the body?  Just guessing here...

2) If I deliberately pass the non-compliant pure JSON object in the `initialize` call, I see that Omnisharp does not complain any more.  But it still does not seem to send any reply, as demanded by the protocol (null result for a successful call).

Thanks for your efforts!  I am full of hope to get rid of most of my VS use :)

**Comment by omajid** [comment]
Possibly related to https://github.com/OmniSharp/omnisharp-roslyn/issues/1269

**Comment by LoneBoco** [comment]
Yes, because of #1269, Omnisharp wasn't going into LSP mode.  It was trying to parse LSP packets using the old Omnisharp protocol.

**Comment by Daniel-V1** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/issues/1382#issuecomment-456531969

**Comment by ilohmar** [comment]
The not-even-getting-into-the-right-mode case has been fixed as of release 1.32.9.  Unfortunately, still no server response with any content complies with the protocol, see #1312.
