### ISSUE TITLE
Support project wide code check

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#131]
When changing code I often break other files that depend on the file I am currently editing, like tests. IMO it would be beneficial if OmniSharp gives me a change to check the whole project at once. I am thinking of ```/codecheck``` without a filename.

**Comment by nosami** [comment]
Sounds good to me.

**Comment by jrieken** [comment]
on a second though we can also use the event emitter to send back diagnostics whenever buffers update. that way Omnisharp has a chance to be smart and delay validation when documents constantly change. but maybe that's a different story

**Comment by nosami** [comment]
fixed by #133
