### ISSUE TITLE
[LSP] language server emits protocolVersion instead of jsonrpc

### ISSUE THREAD

**Issue by razzmatazz** [OmniSharp/omnisharp-roslyn#1312]
I see this was fixed in https://github.com/OmniSharp/csharp-language-server-protocol/issues/98 – would it be possible update src/Omnisharp.LanguageServerProtocol to use the updated version?

At the moment the issue is that lsp-mode from emacs fails to read response from the current implementation due to the missing `jsonrpc` property.

Related to https://github.com/emacs-lsp/lsp-mode/issues/415

**Comment by Aayush04** [comment]
I am getting the same issue. Any idea when it will be getting fixed in this repository Or how to get latest  OmniSharp.LanguageServerProtocol.dll in the omnisharp-roslyn ?

**Comment by Daniel-V1** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/issues/1382#issuecomment-456531969

**Comment by ilohmar** [comment]
Ping.. same issue here..

**Comment by ilohmar** [comment]
It seems this can be closed with release 1.32.11..

**Comment by razzmatazz** [comment]
@ilohmar right, this works now as i have checked with emacs-lsp
