### ISSUE TITLE
OmniSharp version manager.

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#132]
We've spoken briefly about this on JabbR, but I thought that I'd bring it up on here for us to discuss.

So, right now we have the problem that clients can't easily switch between omnisharp-server and omnisharp-roslyn, and also, users can't easily get updates to omnisharp-roslyn as we release them (they need to wait for binaries to be packaged with the plugin).

To address this, we discussed having a version manager script. This would be analogous to `kvm` but would work for OmniSharp binaries. The script would be responsible for downloading a prebuilt version of omnisharp and also querying for updates and released versions etc.

We would need 2 scripts, one for Windows (powershell or cmd) and another for Linux and OSX. The idea behind this is that we wouldn't need to handle the feed parsing / downloading for each editor client. It should be possible to invoke the script transparently by the editor.

We will also require some kind of feed. It was suggested that we might be able to abuse nuget for this purpose.

Thoughts or suggestions? What commands would we need to support?

**Comment by Yantrio** [comment]
https://github.com/OmniSharp/omnisharp-brackets/blob/master/update-omnisharp.cmd

That is probably the crudest way to do it :) I like the idea of having it come in over something like nuget.

**Comment by nosami** [comment]
@ctolkien suggested using npm for this

**Comment by davidfowl** [comment]
NPM? We can just setup a NuGet server on MyGet and push zips to it. Then copy the logic from kvm/dnvm.

**Comment by mat-mcloughlin** [comment]
@Yantrio very crude :)

**Comment by Mpdreamz** [comment]
I kind of like NPM as a standard tooling distribution, the aspnet generator project already relies on it. 

I would personally also love if the kvm/dnvm were installed through npm 

```bash
npm install -g dnvm
dnvm upgrade #could be done as post install script for previous command
npm install -g omnisharp #ovm?
npm install -g generator-aspnet
```

Easy to remember and same on every platform :smile: 

Trolling aside (do forgive me) it does feel right to distribute the `ovm` tooling on NPM and have it download and install server versions from a myget feed. 

Speaking for myself a single javascript file is easier to maintain then having our versions of [kvm.sh](https://github.com/aspnet/Home/blob/master/kvm.sh) and [kvm.ps1](https://github.com/aspnet/Home/blob/master/kvm.ps1)

One big thing kvm does that ovm will not have to is to manage platform builds. The [build for omnisharp-server-roslyn-binaries](https://github.com/OmniSharp/omnisharp-server-roslyn-binaries/blob/master/build.sh) already patches the osx build to also work on windows. And in the future I presume we will build against CoreFX (w00t)?

**Comment by nosami** [comment]
NPM  is certainly the best solution for Atom :) You think we should take a dependency on NPM for emacs users? Not saying we couldn't but it's something to consider.

I'd prefer to take no extra dependencies.

**Comment by Mpdreamz** [comment]
As a standard means of redistributing `ovm` command line tooling, yes it makes sense, otherwise we have to maintain a shell script and powershell script in the same vain as `dnvm` does. Which currently patches your profile directly to add aliases (not sure how well that flies with the hardcore emacs crowd). 

Not against it but not something I'd like to take ownership of tbh.

Or we can publish to all the different package managers directly (rpm, yum, apt, brew, chocolatey).

**Comment by nosami** [comment]
I just stumbled across svm - a version manager for scriptcs https://github.com/scriptcs-contrib/svm

**Comment by Mpdreamz** [comment]
w00t copy paste svm seems very viable +1:

**Comment by nosami** [comment]
@filipw You know how svm works? Think it's a good fit for us? Should we steal it?

**Comment by filipw** [comment]
ping @paulbouwer

**Comment by paulbouwer** [comment]
I'm happy to have a conversation about what has worked and what hasn't for `svm`. I'm also in the process of moving away from PS (win) and bash (OSX, Linux) - considering node.js or C#/.NET/mono (scriptcs already has those requirements).

It is much easier to maintain a single codebase across platforms for consistency and sanity.

I really like the idea from @Mpdreamz about installing the version manager via npm - that may sway me towards node.js as an option :smile:

**Comment by nosami** [comment]
@paulbouwer Interesting. I have mixed feelings about this.

On the one hand I don't think having a dependency on NPM is a good idea, but on the other I don't want to write Yet Another Package Manager.

I think that @Mpdreamz's point about yeoman already requiring NPM is a good one. 

If scriptcs worked natively without requiring any install step on any platform, it would be a natural fit for OmniSharp - especially considering that it will hopefully be integrated at some point.

**Comment by nosami** [comment]
I know - let's use MELPA :) http://melpa.org/#/

**Comment by filipw** [comment]
I will close this as obsolete - for the time being, the releases are published to https://github.com/OmniSharp/omnisharp-roslyn/releases and to the blob storage, as documented in the readme.
