### ISSUE TITLE
Proposal: introduce `latest-stable` switch for `omnisharp.path` configuration

### ISSUE THREAD

**Issue by d-dizhevsky** [OmniSharp/omnisharp-roslyn#1325]
Here is the note from user-config section:

 > // Specifies the path to OmniSharp. This can be the absolute path to an OmniSharp executable, a specific version number, or "latest". If a version number or "latest" is specified, the appropriate version of OmniSharp will be downloaded on your behalf.
>
>  "omnisharp.path": null

It would be handy if I could also tell it to keep my local version up-to-date with the latest stable up to minor version (i.e. download 1.32.7, but ignore 1.32.7-beta.*).

With `latest`:
 - **1.32.7-beta.23 <-- this is the version it will download**
 - 1.32.7-beta.22
 - 1.32.7-alpha.1

With `latest-stable`:
 - 1.32.7-beta.23
 - 1.32.7-beta.22
 - 1.32.7-alpha.1
 - **1.32.6 <-- this is the version it will download**
 - 1.32.6.beta-123
 - 1.32.5

**Comment by DustinCampbell** [comment]
I think this is meant for the omnisharp-vscode repo, corect?

**Comment by filipw** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2644

**Comment by filipw** [comment]
indeed it looks like that - I moved the issue
