### ISSUE TITLE
VSCode cannot build .NET Framework Unit Tests

### ISSUE THREAD

**Issue by dmgonch** [OmniSharp/omnisharp-roslyn#1331]
Problem: .NET Framework Unit Test projects created in VS2017 can be successfully built and run in the IDE. But when the same project is opened in VSCode, attempt to run the tests fails while building. At the same time msbuild can successfully build the project.

Repro steps (on Windows):
1. Prepare a machine with both VS2017 and VSCode with C# OmniSharp extension.
2. Unzip [UT_NET461_VS2017.zip](https://github.com/OmniSharp/omnisharp-roslyn/files/2570307/UT_NET461_VS2017.zip) to c:\tests\UT_NET461_VS2017
3. Open " Developer Command Prompt for VS 2017"
4. cd /d c:\tests\UT_NET461_VS2017
5. msbuild /t:restore
6. msbuild /t:rebuild /p:DebugType=portable
7. code . (launches VSCODE which opens the UT project)
8. Click on UnitTest1.cs to open it in the text editor
9. Click on "Run Test" above TestMethod1
10. Observe errors as in picture below:

----- Running test method "UT_NET461_VS2017.UnitTest1.TestMethod1" -----

Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

UnitTest1.cs(2,17): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(6,6): error CS0246: The type or namespace name 'TestClassAttribute' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(6,6): error CS0246: The type or namespace name 'TestClass' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(9,10): error CS0246: The type or namespace name 'TestMethodAttribute' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(9,10): error CS0246: The type or namespace name 'TestMethod' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]

Build FAILED.

UnitTest1.cs(2,17): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(6,6): error CS0246: The type or namespace name 'TestClassAttribute' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(6,6): error CS0246: The type or namespace name 'TestClass' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(9,10): error CS0246: The type or namespace name 'TestMethodAttribute' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
UnitTest1.cs(9,10): error CS0246: The type or namespace name 'TestMethod' could not be found (are you missing a using directive or an assembly reference?) [c:\tests\UT_NET461_VS2017\UT_NET461_VS2017.csproj]
    0 Warning(s)
    5 Error(s)

Time Elapsed 00:00:01.37

----- Test Execution Summary -----

Total tests: 0. Passed: 0. Failed: 0. Skipped: 0

![image](https://user-images.githubusercontent.com/30739723/48323565-a39a4980-e5e1-11e8-9249-1da0dd05057c.png)

**Comment by DustinCampbell** [comment]
It might be better to open this in omnisharp-vscode.

**Comment by DustinCampbell** [comment]
cc @rchande

**Comment by rchande** [comment]
@dmgonch OmniSharp uses dotnet build/dotnet vstest to run unit tests. I get the same set of errors you mentioned if I simply `dotnet build UT_NET461_VS2017.csproj`. I suspect that if you convert this project to an SDK-style project that can build/test using `dotnet` that it will also work in OmniSharp.

**Comment by dmgonch** [comment]
@rchande : doesn't this strike you though as a rather inconsistent user experience: on one hand OmniSharp.exe can successfully load the project using MSBuild it located and provide just fine any code navigation requests. On the other hand when building/running tests in the project the extension always assumes that it deals with an SDK-style project?
