### ISSUE TITLE
VSCode cannot natively debug .NET Framework Unit Tests - fails with "Only 64-bit processes can be debugged."

### ISSUE THREAD

**Issue by dmgonch** [OmniSharp/omnisharp-roslyn#1332]
Problem: .NET Framework Unit Test projects created in VS2017 can be successfully debugged in the IDE. But an attempt to debug the same project is opened in VSCode, attempt to run the tests fails.

Repro steps (on Windows):
1. Prepare a machine with both VS2017 and VSCode with C# OmniSharp extension.
2. Unzip [UT_NET461_VS2017_1.zip](https://github.com/OmniSharp/omnisharp-roslyn/files/2570478/UT_NET461_VS2017_1.zip) to c:\tests\UT_NET461_VS2017_1 (to work around https://github.com/OmniSharp/omnisharp-roslyn/issues/1331 two explicit references to Microsoft.VisualStudio.TestPlatform.TestFramework assemblies were added manually)
3. Open "Developer Command Prompt for VS 2017"
4. cd /d c:\tests\UT_NET461_VS2017_1
5. msbuild /t:restore
6. msbuild /t:rebuild /p:DebugType=portable
7. code . (launches VSCODE which opens the UT project)
8. Click on UnitTest1.cs to open it in the text editor
9. Click on "Debug Test" above TestMethod1
10. Observe the popup windows with "Only 64-bit processes can be debugged":
 ![image](https://user-images.githubusercontent.com/30739723/48325608-4f946280-e5eb-11e8-8afa-c7462d095936.png)

**Comment by DustinCampbell** [comment]
It might be better to open this in omnisharp-vscode.

**Comment by DustinCampbell** [comment]
cc @rchande

**Comment by rchande** [comment]
Closing this copy.
