### ISSUE TITLE
Omnisharp Fails To Download In VS Code

### ISSUE THREAD

**Issue by firezdog** [OmniSharp/omnisharp-roslyn#1336]
Everything was working fine yesterday -- then today I opened the editor and got this.  Following the link indicates that the package is not found.  Omnisharp seemed to be working when I reset the path to "1.32.7" instead of "latest."

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.8-beta.4' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.8-beta.4/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2681
