### ISSUE TITLE
[question] [help wanted] omnisharp-http-win-x64 and omnisharp-http-win-x86

### ISSUE THREAD

**Issue by hellboy81** [OmniSharp/omnisharp-roslyn#1338]
Difference between `omnisharp-http-win-x64` / `omnisharp-http-win-x86` (**with** `http`) and `omnisharp-win-x64` / `omnisharp-win-x86` (**without** `http`) ?

**Comment by nickspoons** [comment]
The "http" version expects http connections (default port 2000), i.e using `curl`. This is the version that OmniSharp-vim still uses.

The "non-http" version uses `stdio`

**Comment by hellboy81** [comment]
for normal usage "non-http" version should be used?

**Comment by filipw** [comment]
> for normal usage "non-http" version should be used?

both are relevant for normal usage - you can simply choose which transport protocol makes sense to you. It's generally speaking easier to integrate into an HTTP server, but it's faster and more reliable on stdio.

I hope this answers your question - I will close this for now.
