### ISSUE TITLE
[Question] Code Analysis (FxCop) and StyleCop

### ISSUE THREAD

**Issue by JulioJu** [OmniSharp/omnisharp-roslyn#1341]
Hi,

Have you an idea how to integrate Linter Code Analysis (FxCop) ans StyleCop to OmniSharp?

@nickspoons, the author of https://github.com/OmniSharp/omnisharp-vim tell me to add my question here (see https://github.com/OmniSharp/omnisharp-vim/issues/426). 

Thanks in advance ;-).

**Comment by savpek** [comment]
Once #1076 is ready FxCop (https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/) and stylecop (https://github.com/DotNetAnalyzers/StyleCopAnalyzers) can be used

**Comment by JulioJu** [comment]
@savpek thanks a lot ;-). I wait :-).
