### ISSUE TITLE
Intellisense seem not working good in my dotnet core project.

### ISSUE THREAD

**Issue by Aaaaash** [OmniSharp/omnisharp-roslyn#1343]
I am working for [Cloud Studio](https://studio.dev.tencent.com), This is online WebIDE based on Monaco and LSP.

When I use omnisharp to provide language services for it,I reference to the implementation of [omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode), i implemented most of the LSP functions and worked fine.most csharp projects perform very well,even including omnisharp-resolyn, but in some dotnetcore projects, intelliSense doesn't seem to work very well. 
For example omnisharp-roslyn
![图片](https://dn-coding-net-production-pp.codehub.cn/2efbe371-63be-4938-8d2b-1e38251d25c3.gif)
It's work very well.

For example dotnet new mvc project
![图片](https://dn-coding-net-production-pp.codehub.cn/a3c77d27-4c54-4b09-a307-55377b9b9844.png)
It's can find some renferences, response some hover request, but most intellisence not work. including `Console.Write`. can't even find the definition of string.

There are no obvious error messages in the log.

I don't know the difference between the two projects, or some configuration is missing from the dotnetcore project. i am not very familiar with csharp. how can I make it work?

**Comment by filipw** [comment]
What is the output of OmniSharp log in both cases? you can start OmniSharp with logging set to debug level and perhaps you could shared the output here. There should be some error messages printed there.

**Comment by Aaaaash** [comment]
It’s my fault, this issue can be closed.
