### ISSUE TITLE
IndentSwitchCaseSection handled improperly if case only contains a block

### ISSUE THREAD

**Issue by Meitinger** [OmniSharp/omnisharp-roslyn#1351]
### How to reproduce:
Add/set the following in `omnisharp.json`:

    {
        "FormattingOptions": {
            "IndentSwitchCaseSection": false
        }
    }

Format the following C# code:

    class Test
    {
        public int Foo(int bar)
        {
            switch (bar)
            {
                case 1:
                    return 1;
                case 2:
                    {
                        return 2;
                    }
                case 3:
                    ;
                    {
                        return 3;
                    }
            }
        }
    }

### Expected result:

    class Test
    {
        public int Foo(int bar)
        {
            switch (bar)
            {
                case 1:
                return 1;
                case 2:
                {
                    return 2;
                }
                case 3:
                ;
                {
                    return 3;
                }
            }
        }
    }

### Actual result:

    class Test
    {
        public int Foo(int bar)
        {
            switch (bar)
            {
                case 1:
                return 1;
                case 2:
                    {
                        return 2;
                    }
                case 3:
                ;
                {
                    return 3;
                }
            }
        }
    }

**Comment by DustinCampbell** [comment]
The issue here is that there are *two* `IndentSwitchCaseSection` settings support by the C# formatter in Roslyn, but OmniSharp only exposes one of them. The other option is `IndentSwitchCaseSectionWhenBlock`, which OmniSharp needs to support.
