### ISSUE TITLE
"Ambiguity between '<Type> and '<Type>’" errors if a file is edited before projects are loaded

### ISSUE THREAD

**Issue by dmgonch** [OmniSharp/omnisharp-roslyn#1356]
PROBLEM: Editing a source file before the project referencing a file is fully loaded causes  "Ambiguity between '<Type> and '<Type>’ " errors.

REPRO STEPS:
1.	Launch VSCode with OmniSharp installed
2.	Clone https://github.com/OmniSharp/omnisharp-roslyn repo locally and open in VSCode
3.	Close all document if any are opened and open src\OmniSharp.Roslyn\OmniSharpWorkspace.cs
4.	Click menu View -> Output and select OmniSharp.log
5.	Close VSCode
6.	Launch VSCode again – it will automatically open omnisharp-roslyn folder and OmniSharpWorkspace.cs file
7.	Wait until you see any text showing up in OmniSharp.log of Output windows
8.	In OmniSharpWorkspace constructor quickly typing in the following: test <Enter> test <Enter> test <Enter>. Then save the file.
9.	Wait until OmniSharp finishes loading all projects.
10.	Hover over red squiggles in the constructor and observe the following errors
Ambiguity between 'OmniSharpWorkspace.BufferManager' and 'OmniSharpWorkspace.BufferManager'
Ambiguity between 'OmniSharpWorkspace._logger' and 'OmniSharpWorkspace._logger'
11.	Undo changes to OmniSharpWorkspace.cs made in step 8 and save the file. Note that ‘Ambiguity’ were not cleared.
12.	Close and reopen OmniSharpWorkspace.cs. Note that ‘Ambiguity’ errors are still there.

EXPECTED: No ‘Ambiguity’ error should be shown in steps 10-12.

ATTACHED:
- Full trace log [AmbiguityErrorsLog.zip](https://github.com/OmniSharp/omnisharp-roslyn/files/2664197/AmbiguityErrorsLog.zip)
- Screenshot for the error ![ambiguityerrors](https://user-images.githubusercontent.com/30739723/49749889-5223bf80-fc5e-11e8-8786-fd64c87eddd8.png)

**Comment by SirIntruder** [comment]
Thanks for the report, I've seen this multiple times. I've submitted a PR that should fix this: #1357

I've tested this in a couple of repos and it's very easy to repro - 1) restart omnisharp 2) edit and save something while it's still loading 3) wait for the errors to appear.

**Comment by dmgonch** [comment]
Thanks for the fix - tested and it is working great!
