### ISSUE TITLE
Does omnisharp-roslyn could work on cshtml files ?

### ISSUE THREAD

**Issue by JulioJu** [OmniSharp/omnisharp-roslyn#1358]
Hi,

I would like to know if omnisharp-roslyn could work on cshtml files ? I've tested with Omnisharp-Vim, but it seems doesn't work. 

If the server can't, is it plan ?

Thanks in advance :-)

**Comment by filipw** [comment]
You can find Razor tooling, which is layered on top of OmniSharp, here https://github.com/aspnet/Razor.VSCode

**Comment by JulioJu** [comment]
Ok thanks for the Link. Therefore it will not be available for others editors, like Vim or Emacs? 

What do you think about that @nickspoons (for omnisharp-vim)? 

I see @razzmatazz you are the main developer of omnisahrp-emacs. Same for Emacs, no plan to integrate it?
