### ISSUE TITLE
/findSymbols: Support for 'interface', 'enum', delegate' in 'kind'

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-roslyn#136]
/findSymbols returns elements with a kind, giving information about the type of the element.
Right now 'NamedType' is returned for classes, interfaces, enums and delegates.

I'd be great if we can distinguish these and have 'Class', 'Interfaces', 'Enum' and 'Delegate' instead.

'Kind' got added just recently, so refining will not be breaking.

**Comment by nosami** [comment]
I think if we are going to do this, we should probably do it for intellisense also. I don't use this at all in emacs, so it doesn't make any difference to me.

@mat-mcloughlin, @ctolkien - Would this cause a problem if this was done for intellisense too?

**Comment by ctolkien** [comment]
:+1 - No issues here, we'll get a benefit of additional icon types in intellisense "lighting up" in the UI (anything coming back currently with 'NamedType' is skipped).

Struct should probably also be in the list?

**Comment by mat-mcloughlin** [comment]
nope, all good
