### ISSUE TITLE
Hosting a shared omnisharp-roslyn server in docker - is it possible? (questions)

### ISSUE THREAD

**Issue by TheTechArch** [OmniSharp/omnisharp-roslyn#1375]
Hi.
We are working on a platform where developers can develop and host end user services. 
As part of the development process the user will code against local repos stored in the cloud.
The editor that is used is [Monaco](https://microsoft.github.io/monaco-editor/index.html), and we want a language server that can give code completion for the developers. 

We are planning to use [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to connect to a C# language server from Monaco editor.-

It seems like omnisharp-roslyn is one of the few language servers for C# that implement LSP. 
Since the documentation is not clear we have the following questions.

1.	Can omnisharp-roslyn run in a docker image?
2.	Does omnisharp-roslyn support that same language server process can work on several C# projects/solutions at the same time. (there will be multiple developers working on different projects at the same time). (Does the protocol support that each request must have info about which file/project the request is related for)
3.	Does code completion consider other files in the project or only the open file? 
4.	Does omnisharp-roslyn support .Net core projects. (the documentation only talks about 4.6)

Thanks for any reply.
Rune

**Comment by filipw** [comment]
> * Can omnisharp-roslyn run in a docker image?

yes

> * Does omnisharp-roslyn support that same language server process can work on several C# projects/solutions at the same time. (there will be multiple developers working on different projects at the same time). (Does the protocol support that each request must have info about which file/project the request is related for)

no, it supports single "workspace" only (solution with multiple projects or folder with multiple projects)

> * Does code completion consider other files in the project or only the open file?

it considers the entire solution or collection of csproj files

> * Does omnisharp-roslyn support .Net core projects. (the documentation only talks about 4.6)

it supports .NET Core, it only needs full framework (.NET 4.7.2 at the moment, or mono 5.18+) for itself to run.

**Comment by TheTechArch** [comment]
@filipw  thanks for you reply. 

Do you think it is possible for us to modify omnisharp-roslyn so it in fact supports multiple workspaces in the same running process or would that require enormous amount of changes.. (years of development work)

**Comment by patilarpith** [comment]
@TheTechArch I tried something similar without much success
https://github.com/OmniSharp/omnisharp-roslyn/issues/1524#issuecomment-511365464

Please let me know if you've gotten ominsharp roslyn to initialize a project in LSP mode

**Comment by filipw** [comment]
I will close this as answered.
There are no plans to make a single instance of OmniSharp server work with many independent project/solutions concurrently.
