### ISSUE TITLE
Tuple formatting ignore SpaceAfterComma

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-roslyn#1377]
Always set to false, still add a space

![image](https://user-images.githubusercontent.com/1042507/50747656-a3c46780-1267-11e9-8d58-e671e4a59a15.png)

**Comment by filipw** [comment]
thanks, I saw that you opened the bug in Roslyn too (https://github.com/dotnet/roslyn/issues/32207), and that is actually the correct place to handle this issue - so I will close this one.
