### ISSUE TITLE
When is next release?

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-roslyn#1382]
The Language Server Protocol was broken for a while and recently got fixed.
When is next release available so we can upgrade Omnisharp in code consuming it over LSP?

**Comment by mickaelistria** [comment]
cc @filipw @david-driscoll @DustinCampbell

**Comment by filipw** [comment]
Recently we aligned released with a new version being needed for the VS Code extension, I am all for publishing a new release as soon as possible, especially as it comes with new Roslyn version. cc @rchande 

when you talk ab out the fix, which PR you refer to? Also there is a pending PR to update LSP #1387 which will be very useful

**Comment by filipw** [comment]
Release 1.32.9 has been published today - thanks for opening this issue 
https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.32.9

**Comment by mickaelistria** [comment]
Thank you!
