### ISSUE TITLE
CTRL+F12 not working when use dependency injection in ASP.NET Core controllers

### ISSUE THREAD

**Issue by neumartin** [OmniSharp/omnisharp-roslyn#1386]
Using ASP.NET Core 2.2, when I try to go to implementation for manager class I get the message "No implementation fount for ....".
I have an interface and the implementation.

The DI configuration is in startup.cs like this:
services.AddSingleton<IBoardingPassManager, BoardingPassManager>();

Some times works, some times not.

**Comment by filipw** [comment]
Please open a new issue and provide the repro project and the output of the OmniSharp log if you are still having troubles. I will close this one as outdated - thanks.
