### ISSUE TITLE
No debug or trace logging

### ISSUE THREAD

**Issue by dmgonch** [OmniSharp/omnisharp-roslyn#1392]
After building the latest at the moment commit (https://github.com/OmniSharp/omnisharp-roslyn/commit/06e3f4577c054f0db4751142e5141f0fc83698cf) and running the exe with "--loglevel trace" no debug or trace messages appear in the output.

Repro on WIndows:
- Open basic non-admin command prompt
- Clone https://github.com/OmniSharp/omnisharp-roslyn.git
- build -target quick
- artifacts\publish\OmniSharp.Stdio.Driver\win7-x64\OmniSharp.exe --stdio DotNet:enablePackageRestore=false --loglevel trace -s OmniSharp.sln
- Observe that the output includes only INFORMATION messages like below but no DEBUG or TRACE ones

{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Stdio.Host","Message":"Starting OmniSharp on Windows 6.2.9200.0 (x64)"},"Seq":1,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Services.DotNetCliService","Message":"DotNetPath set to dotnet"},"Seq":2,"Type":"event"}

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\.dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\.dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\.dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by filipw** [comment]
There is no `--stdio` argument when running OmniSharp.Stdio. 

This should work in your case: `OmniSharp.exe DotNet:enablePackageRestore=false --loglevel trace -s c:/path/to/my.sln`

Please reopen the issue if you still have issues - thanks.

**Comment by dmgonch** [comment]
@filipw Yes that worked. VSCode C# extension still passed the argument though. Found the related changes and left a comment: https://github.com/OmniSharp/omnisharp-roslyn/commit/6e327216868f13bf3058e4e7ebfd07d27b1b2bc9#r32082280

Thanks!.
