### ISSUE TITLE
Should mention .NET Framework Developer Pack prerequisite for Win builds

### ISSUE THREAD

**Issue by IoriBranford** [OmniSharp/omnisharp-roslyn#1393]
On Windows 7 Home x64, after manually installing roslyn for omnisharp-vim, I was getting Connection Refused and Could Not Connect errors. I found out by testing in command line that I had to install .NET Framework Targeting Pack 4.7.1.

https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers

(I also had to downgrade roslyn to 1.32.1 and edit omnisharp.exe.config)
```xml
  <runtime>
    <loadFromRemoteSources enabled="true"/>
  ...
  </runtime>
```

**Comment by filipw** [comment]
This was resolved by https://github.com/OmniSharp/omnisharp-roslyn/pull/1469 as OmniSharp will now display a popup to install the missing .NET 4.7.2 framework

**Comment by Thaina** [comment]
@filipw Why current omnisharp still require 4.7.1 ?
