### ISSUE TITLE
Add hashed reference assemblies and file extensions of .NET projects to telemetry.

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-roslyn#1402]
Hashing can be done using this service: https://github.com/aspnet/Tooling-Internal/blob/master/telemetry-scripts/andrehal/ScopeQueries/src/Queries.CSharp/DataGridQueries.CSharp/HashingService.cs

**Comment by rchande** [comment]
Ported from https://github.com/aspnet/Razor.VSCode/issues/284

**Comment by akshita31** [comment]
@rchande That link doesn't work for me

**Comment by filipw** [comment]
this was resolved
