### ISSUE TITLE
/fixusings

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#141]
omnisharp-server had a /fixusings endpoint. https://github.com/OmniSharp/omnisharp-server/blob/master/OmniSharp.Tests/FixUsings/FixUsingsTests.cs

It would sort, remove and add any missing using statements. In the event of ambiguous using statements when adding, it would return the symbols that couldn't be resolved.

It's essentially a code action, but it isn't context aware, i.e. it can be invoked from anywhere in the document.

We should add the same thing.

**Comment by sriramgd** [comment]
Can I take a shot at this one?

**Comment by nosami** [comment]
Sure you can.. I started to look into this already. Roslyn has some code for [removing unused usings](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/RemoveUnnecessaryImports/CSharpRemoveUnnecessaryImportsService.cs,22) and [sort usings]http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/OrganizeImports/CSharpOrganizeImportsService.cs,16) 

Think you're going to be on your own for adding using statements. You'll need to scan for all unresolved nodes and apply the AddImportDiagnostic fix to each one.

Good luck... this will be tricky!

**Comment by nosami** [comment]
Might be easier to wait until the Features assembly has been packaged https://github.com/dotnet/roslyn/issues/572

Otherwise, you're going to end up copying and pasting a lot of code I think :)

**Comment by sriramgd** [comment]
@nosami , I figured out how to get all unresolved symbols and get the using namespace (or list in case of ambiguous).
I am actually stuck at how to call the remove and sort methods you pointed to - they are declared in an internal namespace, how do I get a handle on the containing classes and call these methods. Any pointer is appreciated.

**Comment by nosami** [comment]
That's why I mentioned dotnet/roslyn#572. The code that you need is in an assembly that doesn't have a nuget yet.

I think I'd be happy to merge this even if it just has 'Add usings'. We could do the rest later.

**Comment by CoreyKaylor** [comment]
Even partial functionality would be nice for this I agree.

**Comment by sriramgd** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/pull/150
