### ISSUE TITLE
Upgrade Roslyn to 16.0p4

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-roslyn#1413]
We should upgrade to the version specified in https://github.com/dotnet/versions/blob/master/build-info/dotnet/roslyn/dev16.0p4/Latest_Packages.txt

**Comment by rchande** [comment]
@filipw Interested in picking this one up?

**Comment by filipw** [comment]
yes, sure I can have a look. I'd suggest we start by merging https://github.com/OmniSharp/omnisharp-roslyn/pull/1404 first though, as that will bridge a feature gap on nullable references
