### ISSUE TITLE
How Do I force Omnisharp/Roslyn to target Linux

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [OmniSharp/omnisharp-roslyn#1419]
I am working on a windows host with VSCode, .net core 2.2.

I am running Docker for Desktop and my images are alpine. So my running containers are using
`dotnet watch -r alpine-x64` my local filesystem is mounted into the container so that any file changes will be picked up.

When I attach to the container process that allows me to debug my application. Intellisense in VSCode shows everything as red, when infact everything is fine. I believe its because Omnisharp/roslyn (I'm not sure who would be responsible) is working with the bin/obj folder that is compiled for alpine-x64. But there is a disconnect because my host system would obviously be win10.

**Comment by CodeSwimBikeRunner** [comment]
are more details needed?

**Comment by filipw** [comment]
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3621
