### ISSUE TITLE
No intellisense on linux Ubuntu

### ISSUE THREAD

**Issue by cloudrex** [OmniSharp/omnisharp-roslyn#1455]
I get 0 intellisense from my NuGet package (LLVMSharp) after installing it or anything at all. Everything compiles, but no intellisense.

![image](https://user-images.githubusercontent.com/41349879/56003416-76d38680-5c94-11e9-807b-410aad8d6846.png)

Any ideas? I have dotnetcore updated to latest, and using Ubuntu 18.01.

I'm also getting this when starting VSCode:

![image](https://user-images.githubusercontent.com/41349879/56003480-966aaf00-5c94-11e9-8648-8574e5dccd9a.png)

My .csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RootNamespace>llvm_sharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LLVMSharp" Version="5.0.0" />
  </ItemGroup>

</Project>
```

**Comment by akshita31** [comment]
This might be related to https://github.com/OmniSharp/omnisharp-vscode/issues/2965. Could you try the workaround that is mentioned(downgrading the sdk)?
We are working on it and a fix will be out soon.

**Comment by cloudrex** [comment]
> This might be related to [OmniSharp/omnisharp-vscode#2965](https://github.com/OmniSharp/omnisharp-vscode/issues/2965). Could you try the workaround that is mentioned(downgrading the sdk)?
> We are working on it and a fix will be out soon.

Thanks for the quick fix! Very fast response, saved my day!
