### ISSUE TITLE
Omnisharp locking analyzer DLLs

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-roslyn#1465]
I can't share the project, but when I dotnet build a .net core/xunit project that I've opened in VS Code, I sometimes get:

```
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\NuGet.targets(119,5): error : Access to the path 'xunit.analyzers.dll' is denied. [C:\MLS-Monitoring\Monitoring.sln]
```

Killing omnisharp seems to make the build succeed.
cc @savpek

**Comment by filipw** [comment]
That would be correct, our implementation of Roslyn's `IAnalyzerAssemblyLoader` is  our own [AssemblyLoader](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Host/Services/AssemblyLoader.cs) used for other things, and it doesn't shadow copy or read bytes unless explicitly asked to. Roslyn does this https://github.com/dotnet/roslyn/blob/master/src/Compilers/Shared/ShadowCopyAnalyzerAssemblyLoader.cs

**Comment by mholo65** [comment]
We have the `dontLockAssemblyOnDisk` option here. https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Host/Services/AssemblyLoader.cs#L69 We use that when loading Cake.Core for HostObject https://github.com/OmniSharp/omnisharp-roslyn/blob/426ba087907c16d464c95b3841a11172d3123e7e/src/OmniSharp.Cake/CakeProjectSystem.cs#L274

**Comment by savpek** [comment]
Tested omnisharp assembly loader with file bit true. However it causes errors:
`Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.":"Microsoft.CodeAnalysis.Analyzers, Version=2.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"} | System.Exception {System.IO.FileNotFoundException}`

Does `Assembly.Load(byte[] ...)` support binding redirects? There may be difference between `Assembly.LoadFrom `and `Assembly.Load` that is hit here.

I think i will write analyzer assembly loader based on roslyn shadow copy loader. Another solution is to invoke existing via reflection, dunno how robust solution that is 🙂

**Comment by filipw** [comment]
the shadow copy seems like a safe way to go indeed

**Comment by savpek** [comment]
@rchande can you try version compiled from #1474 if issue will be fixed by it.
