### ISSUE TITLE
XML Docs for direct DLL references don't work 

### ISSUE THREAD

**Issue by CreatorVilius** [OmniSharp/omnisharp-roslyn#1476]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.505
 Commit:    b220231234

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.505\

Host (useful for support):
  Version: 2.1.9
  Commit:  dcedc87d22

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
VS Code version: 1.33.1
C# Extension version: 1.19.0

## Steps to reproduce

1. Make C# console project
2. Open as workspace in Visual Studio Code
3. Include `Microsoft.Scripting.dll` and `Microsoft.Scripting.Core.dll` into `csproj`
4. Put this into `csproj` file:
```xml
<ItemGroup>
    <Reference Include="Microsoft.Scripting">
      <HintPath>./lib/Microsoft.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Scripting.Core">
      <HintPath>./lib/Microsoft.Scripting.Core.dll</HintPath>
    </Reference>
    <Reference Include="ErrorHandling">
      <HintPath>./lib/ErrorHandling.dll</HintPath>
    </Reference>
  </ItemGroup>
```
5. Try using any constructor (for example `Microsoft.Scripting.Hosting.CompiledCode`).

## Expected  behavior

As you put in paranthese(`(` and `)`) after constructor, it should put docs above caret. Just like typing `new string()` shows docs above caret.

## Actual behavior

Nothing comes up after you put in paranthese. No documentation.

Hints should show up, as `Microsoft.Scripting.DLL` and `Microsoft.Scripting.Core.DLL` are managed code DLLs.

**Comment by CreatorVilius** [comment]
Thing is, I haven't found any xml information for Microsoft.Scripting and Microsoft.Scripting.Core. Yet, I had to use open-source stuff to get those DLLs.

**Comment by filipw** [comment]
I would imagine they should be part of the official IronPython distribution.

That said this is not a tooling issue for OmniSharp - here everything is working as designed, so I will close this issue. Thanks.
