### ISSUE TITLE
On Linux (debian 9) Intellisense not working for .cs file on ubuntu using latest-> v1.32.18 release's omnisharp-linux-x64.zip

### ISSUE THREAD

**Issue by amarnath-mishra** [OmniSharp/omnisharp-roslyn#1477]
I was trying to build the latest master first to get the omnisharp.exe, but was getting https://github.com/GitTools/GitVersion/issues/1097 error while building it, tried this solution -> https://github.com/OmniSharp/omnisharp-roslyn/issues/1202#issuecomment-421543905 also, but still getting same error.

So, I decided to use the exe which i can get from last release through v1.32.18 (omnisharp-linux-x64.zip), but now even if my Lsp server is running, it is not giving any results if I am providing it .cs file with .csproj file in rootUri, while it is working with .csx.

I am running it with command:
 **mono /pathTo/OmniSharp.exe  -lsp -s /pathTo/rootUri**
and in rootUri folder, I have a file.cs/csx file and file.csproj file.
Content of file.csproj file-

`<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ExternalConsole>true</ExternalConsole>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="*" />
  </ItemGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
</Project>`

**Comment by filipw** [comment]
I will close this as obsolete. Please open a new issue if this still happens with the latest OmniSharp build.
