### ISSUE TITLE
Import completion for types

### ISSUE THREAD

**Issue by duki994** [OmniSharp/omnisharp-roslyn#1482]
Is there any possibility of supporting this in future?
https://github.com/dotnet/roslyn/pull/34808

It's still in preview and based on idea of IntelliSense Extender VS extension.
It will be out of preview in a few versions.

Roslyn itself is capable of providing unimported type information via TypeImportCompletionProvider implemented in above pull request. CompletionService should suffice and support this new CompletionProvider without any major changes. Maybe even without changes.

**Comment by filipw** [comment]
Yes it's in the plans.

**Comment by filipw** [comment]
I have built a prototype for this now and we'll have a look at integrating it soon. It will require some changes to the VS Code side of the extension too.

**Comment by nickspoons** [comment]
Once the prototype is built, a brief description of that request->response->extra process would be very much appreciated, so we can implement it in other clients (OmniSharp-vim)

**Comment by Gameghostify** [comment]
Any movement on this? Features like this is what makes roslyn/omnisharp so great and would be **amazing** to have 👀

**Comment by filipw** [comment]
still work in progress 😄

**Comment by fabiopicchi** [comment]
@filipw Can I help somehow? Is there a WIP branch?

**Comment by JoshuaLight** [comment]
Any progress so far? Must have feature!

**Comment by Gameghostify** [comment]
+1 this would be amazing to have

**Comment by bazuka5801** [comment]
> Yes it's in the plans.

Any status?

**Comment by bazuka5801** [comment]
![image](https://user-images.githubusercontent.com/11452353/84871464-3ede8500-b089-11ea-9d14-aafc22312271.png)
![image](https://user-images.githubusercontent.com/11452353/84871495-47cf5680-b089-11ea-989b-97446eae9705.png)

No suggestions? how to fix that?

**Comment by phil-harmoniq** [comment]
@filipw Is this still in the works? This is a much needed feature imho.
