### ISSUE TITLE
Enabling Omnisharp causing editor errors (compile and run is fine) with dotnetcore3 preview 5

### ISSUE THREAD

**Issue by natrajgs** [OmniSharp/omnisharp-roslyn#1483]
Enabling Omnisharp causing editor errors (compile and run is fine) with dotnetcore preview 5
![omnisharpbug](https://user-images.githubusercontent.com/48722935/57496864-c0ff5600-729a-11e9-83a3-da87105165db.png)

**Comment by filipw** [comment]
Omnisharp now fully supports .NET Core 2.1, 3.1 and 5.0 RC2.
