### ISSUE TITLE
Unused using codecheck incorrect

### ISSUE THREAD

**Issue by CoreyKaylor** [OmniSharp/omnisharp-roslyn#151]
Using aspnet vnext on mono / mac with emacs. When importing the Shouldy assertion library it seems to report that the using statement is unused, and lower in my tests using the .ShouldBe extension methods it is indicating a missing using statement. Here is what my project.json looks like and the error messages in the Messages buffer. Compiling and running the tests works fine however.

'string' does not contain a definition for 'ShouldBe' and no extension method 'ShouldBe' accepting a first argument of type 'string' could be found 

The type or namespace name 'Shouldly' could not be found (are you missing a using directive or an assembly reference?)

``` json
{
  "version": "1.0.0-*",
  "dependencies": {
    "xunit": "2.1.0-beta1-*",
    "xunit.runner.aspnet": "2.1.0-beta1-*",
    "Shouldly": "2.4.0",
    "kmon": "0.3.0",
    "Rx-Main": "2.2.5"
  },
  "commands": {
    "test": "xunit.runner.aspnet",
    "autotest": "kmon --ext cs --server test"
  },
  "frameworks": {
    "aspnet50": {
      "dependencies": {
        "System.Collections": ""
      }
    },
    "aspnetcore50": {
      "dependencies": {
        "System.Collections": "",
        "System.Runtime": "4.0.20-*"
      }
    }
  }
}
```

**Comment by filipw** [comment]
The unused usings has been revamped completely over time - this issue has been resolved.
