### ISSUE TITLE
Roslyn analyzer fails to load using Security.Cryptography namespace.

### ISSUE THREAD

**Issue by bchavez** [OmniSharp/omnisharp-roslyn#1512]
Hello,

My analyzer works fine on **Windows** and **MacOS** inside **VS Code**.

However, when my analyzer references objects in the `System.Security.Cryptography` namespace on **Linux**, **OminiSharp** fails to load my analyzer in **VS Code** with the following message (debug level log):
```
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Found '/home/bchavez/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/omnisharp/.msbuild/Current/Bin/System.Security.Cryptography.Algorithms.dll' but name, 'System.Security.Cryptography.Algorithms, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a', did not match.
```

Invoking the core Roslyn compiler `dotnet build` from the command-line (on all operating systems) works fine. The analyzer seems to be picked up fine without issues. For example, on **Linux**:
```
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 45.2 ms for /home/bchavez/Desktop/ToolsTest/ToolsTest.csproj.
Program.cs(6,10): warning AnalyzerTest: Type name 'Program' contains lowercase letters [/home/bchavez/Desktop/ToolsTest/ToolsTest.csproj]
Program.cs(15,17): warning AnalyzerTest: Type name 'Foo' contains lowercase letters  [/home/bchavez/Desktop/ToolsTest/ToolsTest.csproj]
```

The reason I'm using `System.Security.Cryptography` inside a Roslyn analyzer is to verify an RSA signature on a license file.

Here's what the test analyzer looks like running **VS Code on Windows** and everything works fine.

![Code_3319](https://user-images.githubusercontent.com/478118/58759017-89ba4880-84d8-11e9-87c7-b8e672236c2b.png)

When running on **Windows** with **OmniSharp** log level set to debug, there are no log entries indicating any failures to load `System.Security.Cryptography.Algorithms.dll`.

The loading problem only appears to be on **VS Code on Linux** as shown below.

![vmware_3317](https://user-images.githubusercontent.com/478118/58758459-37752980-84d0-11e9-8e86-1494afe3efce.png)

## Reproduction Steps

I made a minimal repro available here: https://github.com/bchavez/AnalyzerTest

* `git checkout` the project above ***on Linux***.
* `cd` to **ToolsTestProgram** folder.
* `dotnet restore --source .` to restore the locally built `AnalyzerTest.1.0.3.nupkg` package.
* Set Logging Level to trace:
   ![vmware_3318](https://user-images.githubusercontent.com/478118/58758558-c2a2ef00-84d1-11e9-8d68-659e6ea03d34.png)
* Open the **ToolsTestProgram** folder in **VS Code** and you should get **OminiSharp** debug log messages about failing to load `System.Security.Cryptography.Algorithms.dll` and the analyzer will not work.

If you remove these lines here:
https://github.com/bchavez/AnalyzerTest/blob/571d362812118fe0a152c6a67ae1366be3cd0f63/AnalyzerTest/AnalyzerTest/AnalyzerTestAnalyzer.cs#L38-L39
* Increment the [package build number](https://github.com/bchavez/AnalyzerTest/blob/4f49dd1d680e44f85302ea01cd4570aa0697fb9e/AnalyzerTest/AnalyzerTest/AnalyzerTest.csproj#L11-L12)
* Recompile **AnalyzerTest** project with `dotnet build`
* Copy the `.nuget` package to **ToolsTestProgram** folder,
* `dotnet clean`
* `dotnet add package AnalyzerTest --version NEW_VERSION --source .`
* `dotnet restore`
* `dotnet build`
* Open the **ToolsTestProgram** folder in **VS Code** analyzer will work on **Linux**.

## Other notes

This was somewhat difficult to diagnose because of the obscure nature of the failure. It would have helped if **OminiSharp** was more explicit like:

* `[msg]: YO, ERROR: YOUR AnalyzerTest.dll FAILED TO LOAD BECAUSE THERE ISN'T ENOUGH ELECTRICITY IN ELECTRON`.

It was more like:

* `FAILURE: 'System.Security.Cryptography.Algorithms.dll'  ¯\_(ツ)_/¯`

Also, ya'll need to hit the star :star2:  button my **Bogus** :8ball: project because it's dope. https://github.com/bchavez/Bogus

**Bogus** :8ball: the best fake data generator for .NET which is the reason for all this. I was trying to get my Premium License analyzer working in VS code. https://github.com/bchavez/Bogus#bogus-premium-extensions

:smile_cat:

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**

### OminiSharp Extension Info:
```
Name: C#
Id: ms-vscode.csharp
Description: C# for Visual Studio Code (powered by OmniSharp).
Version: 1.19.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
```

### OS info
```
root@test3:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

### VS code help > info:

![zzz_3314](https://user-images.githubusercontent.com/478118/58757904-edd51080-84c8-11e9-957c-e110ffae30e4.png)

### .NET runtime:
```
root@test3:~# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.105 [/usr/share/dotnet/sdk]
  2.2.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by bchavez** [comment]
Hm. Tried building `omnisharp-roslyn` from source on **Linux**. No dice.

```
bchavez@test3:~/Desktop/omnisharp-roslyn$ ./build.sh 
Feeds used:
  /home/bchavez/.nuget/packages/
  https://api.nuget.org/v3/index.json
  https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
  https://dotnet.myget.org/F/dotnet-cli/api/v3/index.json
  https://www.myget.org/F/omnisharp/api/v3/index.json
  https://dotnet.myget.org/F/roslyn/api/v3/index.json
  https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json

All packages listed in /home/bchavez/Desktop/omnisharp-roslyn/tools/packages.config are already installed.
/proc/self/maps:
40b63000-40b73000 rwxp 00000000 00:00 0 
41290000-412e0000 rwxp 00000000 00:00 0 
560cac127000-560cac578000 r-xp 00000000 08:01 3804429                    /usr/bin/mono-sgen
560cac778000-560cac77f000 r--p 00451000 08:01 3804429                    /usr/bin/mono-sgen
560cac77f000-560cac784000 rw-p 00458000 08:01 3804429                    /usr/bin/mono-sgen
560cac784000-560cac79b000 rw-p 00000000 00:00 0 
560caceb2000-560cad1c1000 rw-p 00000000 00:00 0                          [heap]
7fbebc000000-7fbebc021000 rw-p 00000000 00:00 0 
7fbebc021000-7fbec0000000 ---p 00000000 00:00 0 
7fbec4000000-7fbec4021000 rw-p 00000000 00:00 0 
7fbec4021000-7fbec8000000 ---p 00000000 00:00 0 
7fbec8000000-7fbec8021000 rw-p 00000000 00:00 0 
7fbec8021000-7fbecc000000 ---p 00000000 00:00 0 
7fbecc000000-7fbecc021000 rw-p 00000000 00:00 0 
7fbecc021000-7fbed0000000 ---p 00000000 00:00 0 
7fbed0000000-7fbed0058000 rw-p 00000000 00:00 0 
7fbed0058000-7fbed4000000 ---p 00000000 00:00 0 
7fbed4000000-7fbed4021000 rw-p 00000000 00:00 0 
7fbed4021000-7fbed8000000 ---p 00000000 00:00 0 
7fbed9f8b000-7fbeda1d8000 r-xp 00000000 08:01 3808047                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7fbeda1d8000-7fbeda3d8000 ---p 0024d000 08:01 3808047                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7fbeda3d8000-7fbeda400000 rw-p 0024d000 08:01 3808047                    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7fbeda400000-7fbeda403000 rw-p 00000000 00:00 0 
7fbeda403000-7fbeda463000 r-xp 00000000 08:01 3808049                    /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7fbeda463000-7fbeda663000 ---p 00060000 08:01 3808049                    /usr/lib/x86_64-linux-gnu/libssl.so.1.1
Error: One or more errors occurred. (Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''.)
	Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''.
```

**Comment by filipw** [comment]
I don't think the problem is Linux vs Mac here.

If you posted the full OmniSharp log it would help, but it looks to me as if on Linux you are running on OmniSharp's embedded Mono, while on Mac you are running on global Mono installation. OmniSharp's embedded Mono is a custom build which in this case fails (and it will fail on both Mac and Linux).

If you have global Mono installed (5.18.1+), then OmniSharp will automatically prefer that one.

**Comment by bchavez** [comment]
Hi @filipw,

Thanks for the reply. Sure enough, I installed a full version of **Mono on Linux** and my analyzers work as expected.

Thanks for the information. I'll be sure to tell my users they'll need to install full **Mono** on **Linux** to get the analyzer to work.

Thanks again for the help!
Brian

**Comment by nickenchev** [comment]
I'm trying to install the server on Arch.
Linux office-arch 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux

Mono JIT compiler version 5.20.1 (makepkg/886c4901747 Wed Apr 17 15:49:14 UTC 2019)

Getting this:
```Error: One or more errors occurred. (Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''.) Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''.```
