### ISSUE TITLE
Allow to add a global ignore for code diagonistics messages

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-roslyn#1518]
Currently there is no way (or at least I could not find any) to add some diagnostic messages to a global ignore setting.

One such example:
![image](https://user-images.githubusercontent.com/2249071/58877675-a5d50a00-86d1-11e9-8e66-b933159a5274.png)

This message pops up everywhere in our big solution at work and I would love to disable it globally on my local machine. I realize that there are ruleset files that can ignore this message, however, this would be an incredible time-consuming task to write ruleset files for all the projects in this solution.

**Comment by filipw** [comment]
You could create a ruleset and add it to the `Directory.Build.props` at the root of your solution:

```
<Project>
  <PropertyGroup>
    <CodeAnalysisRuleset>$(MSBuildThisFileDirectory)MyRules.ruleset</CodeAnalysisRuleset>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="my.analyzers" Version="0.0.1" />
  </ItemGroup>
</Project>
```

Then it applies to all csproj files starting from the root.

**Comment by RononDex** [comment]
@filipw thanks, although that way of "solving" it was already known to me.

The issue with that way is, that I have to edit our top most .props file and will always have it listed as a change in the git repository. Since we are a lot of people (~160) working on the same code base this is forbidden and the only way, in this case, to solve the issue in vscode "reliably" is by having a global ignore, or a file that I can add to .gitignore and is not in the git repository already (like omsnisharp.json for example).

**Comment by filipw** [comment]
You will be able to control it with `.editorconfig` (see #1526)

**Comment by RononDex** [comment]
Aweomse, thanks!

**Comment by filipw** [comment]
editorconfig support for analyzer severities has been implemented
