### ISSUE TITLE
Make it possible to "auto-fix" documents

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-roslyn#1519]
Currently, omnisharp is not supporting "auto-fix" functionality to VSCode.

Implementing this functionality would lead to a very efficient way to produce clean code.

One possibility would be to add an action "omnisharp: fix document", have a setting in the vscode user json file like
```
"omnisharp.autofixactions": [
    "RemoveUnusedUsings",
    "SimplifyNames",
   ...
]
```

**Comment by filipw** [comment]
This will be possible once #1526 is merged. We'll then be able to add a fix endpoint that fixes everything according to `.editorconfig` settings.

**Comment by RononDex** [comment]
Perfect, thanks!

**Comment by savpek** [comment]
Currently working on this, may be few weeks before i push PR though.

**Comment by filipw** [comment]
fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/1581
