### ISSUE TITLE
"Missing XML comments" issues used to be warnings, are now errors

### ISSUE THREAD

**Issue by ob-stripe** [OmniSharp/omnisharp-roslyn#1528]
## Issue Description ##
After a recent Omnisharp update, "Missing XML comment" problems that used to be reported as warnings are now reported as errors in the "Problems" tab.

## Steps to Reproduce ##
Open the `Stripe.net` project (https://github.com/stripe/stripe-dotnet) with VSCode and the C# extension.

## Expected Behavior ##
The "Problems" tab reports "Missing XML comment" issues as warnings, and the names of files with these issues are not printed in red in the "Explorer" tab.

(This was the case until a couple weeks ago.)

## Actual Behavior ##
The "Problems" tab reports "Missing XML comment" issues as errors, and the names of files with these issues are printed in red in the "Explorer" tab.

### OmniSharp log ###
<details>
Starting OmniSharp server at 6/21/2019, 11:37:20 AM
    Target: /Users/ob/workspace/dotnet/stripe-dotnet/src/Stripe.net.sln

OmniSharp server started with Mono 5.18.0.
    Path: /Users/ob/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/OmniSharp.exe
    PID: 35167

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.5 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/ob/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/ob/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/ob/workspace/dotnet/stripe-dotnet/src'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/ob/workspace/dotnet/stripe-dotnet/src/Stripe.net.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/ob/workspace/dotnet/stripe-dotnet/src/Stripe.net/Stripe.net.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/ob/workspace/dotnet/stripe-dotnet/src/StripeTests/StripeTests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/ob/workspace/dotnet/stripe-dotnet/src'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/ob/workspace/dotnet/stripe-dotnet/src/Stripe.net/Stripe.net.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/ob/workspace/dotnet/stripe-dotnet/src' on host 35136.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/ob/workspace/dotnet/stripe-dotnet/src/Stripe.net/Stripe.net.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/ob/workspace/dotnet/stripe-dotnet/src/Stripe.net/Stripe.net.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/ob/workspace/dotnet/stripe-dotnet/src/StripeTests/StripeTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/ob/workspace/dotnet/stripe-dotnet/src/StripeTests/StripeTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/ob/workspace/dotnet/stripe-dotnet/src/StripeTests/StripeTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Stripe.net
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: StripeTests
</details>

### C# log ###
<details>(empty)</details>

## Environment information ##

**VSCode version**: 1.35.1
**C# Extension**: 1.20.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.18.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  1.1.13 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|All-Autocomplete|Atishay-Jain|0.0.20|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|change-case|wmaurer|1.0.0|
|csharp|ms-vscode|1.20.0|
|EditorConfig|EditorConfig|0.13.0|
|gitlens|eamodio|9.8.2|
|path-autocomplete|ionutvmi|1.13.3|
|vscode-clangd|llvm-vs-code-extensions|0.0.15|
|vscode-fileutils|sleistner|2.14.5|
|vscode-markdownlint|DavidAnson|0.28.0|
|vscode-open-in-github|ziyasal|1.3.6|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|vscodeintellicode|VisualStudioExptTeam|1.1.7|;

</details>

**Comment by ob-stripe** [comment]
@filipw Ah, I see. Thanks for taking a look!

The project does have custom StyleCop rulesets though, so those missing XML comments should not appear as warnings or errors. Can Omnisharp read custom rulesets files?

**Comment by savpek** [comment]
Yes custom .ruleset files are supported, they should work similar way as in visual studio once added to project.

**Comment by filipw** [comment]
you can control severity via custom rulesets or (new) via editorconfig files

i will close this issue
