### ISSUE TITLE
Editorconfig support doesn't work when folder contains [] characters

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#1551]
My root folder `${workspaceFolder}` name `[Foo] bar` contains the characters `[]`. If I rename to `foobar`, everything will work.

1. create folder `[Foo] bar` & open
2. `dotnet new console -n Proj1`
3. put `.editorconfig`
4. open via VSCode `[Foo] bar` folder
5. no warning

_Originally posted by @ExceptionGit in https://github.com/OmniSharp/omnisharp-roslyn/pull/1526#issuecomment-510816624_

**Comment by filipw** [comment]
We actually use an external component - `Microsoft.VisualStudio.CodingConventions` to do editorconfig settings discovery, and it's really a bug there.
In fact, I just checked, it doesn't work in Visual Studio too.

**Comment by MrFoxPro** [comment]
> We actually use an external component - `Microsoft.VisualStudio.CodingConventions` to do editorconfig settings discovery, and it's really a bug there.
> In fact, I just checked, it doesn't work in Visual Studio too.

Could you please share how did your configure omnisharp to work with Microsoft.VisualStudio.CodingConventions?

**Comment by filipw** [comment]
this has been resolved by moving to Roslyn's native editorconfig support
