### ISSUE TITLE
Let editors know when no or not the matching DTH could be found

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#156]
Not everyone has DNX installed and currently that's buried in an error message somewhere. For a better getting started experience we should use the ```EventEmitter``` and send an explicit message to the editor so that it guide the user through the installation (get dnvm, get dnx, etc)

**Comment by jrieken** [comment]
tracked in #172

**Comment by nosami** [comment]
Fixed in #172
