### ISSUE TITLE
can't build in macos

### ISSUE THREAD

**Issue by fatfatson** [OmniSharp/omnisharp-roslyn#1564]
```
========================================
CreateMSBuildFolder
========================================
Copying Mono MSBuild runtime...
Copying MSBuild libraries...
Copying MSBuild SDK resolver...
An error occurred when executing task 'CreateMSBuildFolder'.

----------------------------------------
Teardown
----------------------------------------
Shutting down MSBuild server...
Shutting down VB/C# compiler server...
MSBuild server shut down successfully.
VB/C# compiler server shut down successfully.
Error: One or more errors occurred. (/Users/wellbye/repos/lib/omnisharp-roslyn/tools/Microsoft.DotNet.MSBuildSdkResolver/lib/netstandard2.0/Microsoft.DotNet.MSBuildSdkResolver.dll does not exist)
        /Users/wellbye/repos/lib/omnisharp-roslyn/tools/Microsoft.DotNet.MSBuildSdkResolver/lib/netstandard2.0/Microsoft.DotNet.MSBuildSdkResolver.dll does not exist

```

`Microsoft.DotNet.MSBuildSdkResolver` doesn't exist in `tools` on macos, but it does on windows.

**Comment by filipw** [comment]
can you please provide the full build log? also, how did you invoke the build script? please try `./build.sh --configuration Release --verbosity Verbose --target All --publish-all --archive` and please ensure you have Mono 5.18+ installed.

each PR and each release is built on macOS too so it definitely works.

**Comment by fatfatson** [comment]
I'm sorry it's my problem. 
maybe  a accidently wrong change to the `tools/packages.config`:
![image](https://user-images.githubusercontent.com/5842874/61600825-49b84c00-ac65-11e9-9499-0df39b7d2263.png)
I don't know which util modifies it(looks like a auto upgrade)
after resetting it , the build goes correctly.

**Comment by filipw** [comment]
thanks I will close it then 👍
