### ISSUE TITLE
Remove AppVeyor and Travis integrations

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#1569]
Since we now use Azure DevOps for everything, the checks on AppVeyor and Travis seem redundant and can be removed. Especially on Travis the builds are very unstable and it all adds maintenance overhead.

cc @david-driscoll

**Comment by david-driscoll** [comment]
I have disabled the integrations and removed them as required for pushing to master.

**Comment by filipw** [comment]
awesome, thanks!

**Comment by david-driscoll** [comment]
This is done... and hopefully we don't run into any problems.  Worst case we can turn them on as I didn't remove the config files yet.

**Comment by filipw** [comment]
this is resolved - thanks!
