### ISSUE TITLE
Also rename variables when renaming a symbol / class

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-roslyn#1585]
This is a feature request.

When I rename a class, and I have instances of that class, the variable names should be renamed too.

For example, if I have a class called `SomeClass1` and have it instanced with
```csharp
var someClass1 = new SomeClass1();
```

If I now rename `SomeClass1` to `SomeOtherClass1`, it should also rename the variable name to
```csharp
var someOtherClass1 = new SomeOtherClass1();
```

Same should also happen for renaming of interfaces, parameter names in methods, ...

EDIT: Formatting

**Comment by filipw** [comment]
Thanks - this should be implemented Roslyn - here is an issue tracking this https://github.com/dotnet/roslyn/issues/8933, you can upvote that one.

We expose all the Roslyn rename options (other than rename file) see - https://github.com/OmniSharp/omnisharp-roslyn/pull/1495
Once this feature is available in Roslyn we'll be able to expose it too.
