### ISSUE TITLE
/stopserver

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#16]
stops the server

**Comment by cubitouch** [comment]
I can take that, Application.Exit() is sufficient or you need something more elaborate ?

**Comment by nosami** [comment]
Think you need to do this
https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Program.cs#L118

**Comment by cubitouch** [comment]
Thanks, I'm on it :)

**Comment by nosami** [comment]
👍

**Comment by filipw** [comment]
i bet kestrel will throw exceptions here, mark my words :smile:

**Comment by cubitouch** [comment]
Should it return a response ?

**Comment by davidfowl** [comment]
Don't call application, exit. Use the IApplicationShutdown interface.

**Comment by cubitouch** [comment]
System.NullReferenceException:
![image](https://cloud.githubusercontent.com/assets/7486151/6218985/71264080-b624-11e4-953e-a252e1f9b4ce.png)

@davidfowl do you have an idea ? Throwing this when I run a "_applicationShutdown.RequestShutdown();"

**Comment by cubitouch** [comment]
I will move on something else in the next few days, if someone need to get what I did the other day, in case the kestrel exception is fixed -> https://gist.github.com/cubitouch/99e5d61573c74789b498

**Comment by sriramgd** [comment]
cubitouch's code stops the server okay when I tested by sending the /stopserver command from omnisharp-vim via python on ubuntu and windows. The only change I had to make was to use HttpPost since we use that now in omnisharp-vim.
Am I missing something?
cubitouch, would it be possible to submit the PR? If not I can submit it.

**Comment by cubitouch** [comment]
@sriramgd Please create the PR, glad my gist could help ;)

**Comment by nosami** [comment]
Oh! That's good news. The bug in Kestrel must be fixed now. 

@sriramgd All requests should be POSTs

**Comment by david-driscoll** [comment]
Stop server landed with #302
