### ISSUE TITLE
Omnisharp analyzer recommends C# 8 refactorings for a C# 7 project

### ISSUE THREAD

**Issue by giulianob** [OmniSharp/omnisharp-roslyn#1620]
I enabled `enableAnalyzersSupport` and the analyzer is giving me `Use 'switch' expression (IDE0066)` recommendation in a csproj that targets .net 4.7.2

My csproj file contains `<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>`. When I try to build the project I do receive errors from msbuild after applying the recommended refactoring:
```
 error CS8652: The feature 'recursive patterns' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. 
```

Is there anyway for omnisharp to only recommend refactorings that are actually supported in my current project version?

**Comment by filipw** [comment]
OmniSharp is built with a new version of Roslyn in which the default language version means actually C# 8 already. See this Roslyn PR https://github.com/dotnet/roslyn/pull/37074

You can set `<LangVersion>7.0</LangVersion>` in your project to override this.

**Comment by giulianob** [comment]
Great that works. Thank you.
