### ISSUE TITLE
Go to metadata doesn't work

### ISSUE THREAD

**Issue by worming004** [OmniSharp/omnisharp-roslyn#1624]
## Issue Description ##

When I press F12 on a type from an external library (imported from third party library or system like int), the message 'No definition found for {type}' instead of getting metadata informations in a new windows.

I don't have any issue pressing F12 on a class defined in current project.

## Steps to Reproduce ##

In any method

* Write `int value = 5;`
* Press F12 on `ìnt`

## Expected Behavior ##

Open a new tab with metada information

## Actual Behavior ##

a tooltip is shown with 'No definition found for int' message

### OmniSharp log ###
<details>
Starting OmniSharp server at 04/10/2019 à 07:32:00
    Target: c:\Git\Multi\MessagingServer

OmniSharp server started.
    Path: C:\Users\Wormi\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\OmniSharp.exe
    PID: 15928

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.3.29324.140 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.0 - "c:\Users\Wormi\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.3.29324.140 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Git\Multi\MessagingServer'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Git\Multi\MessagingServer'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Git\Multi\MessagingServer'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Git\Multi\MessagingServer\MessagingServer.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Git\Multi\MessagingServer' on host 9896.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MessagingServer
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Git\Multi\MessagingServer\MessagingServer.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MessagingServer
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Web\analyzers\cs\Microsoft.AspNetCore.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Web\analyzers\cs\Microsoft.AspNetCore.Mvc.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Web\analyzers\cs\Microsoft.AspNetCore.Components.Analyzers.dll
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Git\Multi\MessagingServer\MessagingServer.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MessagingServer
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Git\Multi\MessagingServer\MessagingServer.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Git\Multi\MessagingServer\MessagingServer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MessagingServer
</details>

### C# log ###

NO LOGS

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.4

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.0|
|bazel-code|DevonDCarew|0.1.9|
|beautify|HookyQR|1.5.0|
|Bookmarks|alefragnani|10.5.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.4|
|csharpextensions|jchannon|1.3.0|
|cypher-query-language|jakeboone02|1.0.2|
|docker-explorer|formulahendry|0.1.6|
|fantomas-fmt|paolodellepiane|0.0.22|
|ginfuru-vscode-jekyll-syntax|ginfuru|0.1.0|
|git-graph|mhutchie|1.16.0|
|git-project-manager|felipecaputo|1.7.1|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|10.0.1|
|Go|ms-vscode|0.11.7|
|go-outliner|766b|0.1.20|
|gotestexplorer|premparihar|0.1.10|
|gulptasks|nickdodd79|1.3.1|
|html-css-class-completion|Zignd|1.19.0|
|JavaScriptSnippets|xabikos|1.7.2|
|language-stylus|sysoev|1.11.0|
|material-icon-theme|PKief|3.9.0|
|node-module-intellisense|leizongmin|1.5.0|
|nodejs-extension-pack|waderyan|0.1.9|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|pdf|tomoki1207|0.5.1|
|powershell|ms-vscode|2019.9.0|
|rest-client|humao|0.22.2|
|search-node-modules|jasonnutter|1.3.0|
|tslint|eg2|1.0.44|
|typescript-hero|rbbit|3.0.0|
|vs-code-snippet-generator|dkultasev|1.0.1|
|vscode-arduino|vsciot-vscode|0.2.27|
|vscode-bazel|BazelBuild|0.3.0|
|vscode-css-peek|pranaygp|3.0.2|
|vscode-docker|ms-azuretools|0.8.1|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.4|
|vscode-markdownlint|DavidAnson|0.30.2|
|vscode-proto3|zxh404|0.3.0|
|vscode-pull-request-github|GitHub|0.11.2|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscode-yaml|redhat|0.5.3|
|vsliveshare|ms-vsliveshare|1.0.905|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by filipw** [comment]
thanks for reporting - the PR with a fix is open https://github.com/OmniSharp/omnisharp-roslyn/pull/1625

**Comment by amarkezic** [comment]
Had the same problem. If you have mono installed on linux a temporary solution is to move xbuild location `/usr/lib/mono/xbuild` -> `/usr/lib/mono/xbuild-backup` (but makes it so you cant use xbuild). 

Version [1.21.9](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.9) of Omnisharp fixed the problem for me.

**Comment by filipw** [comment]
yeah mono paths are no longer loaded for Mono < 6.4.0 in 1.21.9

**Comment by ImJaviPerez** [comment]
I have the same problem using last version.
Is it fixed?


Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T11:22:13.689Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic
