### ISSUE TITLE
Use Roslyn's native .editorconfig support

### ISSUE THREAD

**Issue by JoeRobich** [OmniSharp/omnisharp-roslyn#1657]
EditorConfigDocumentOptionsProvider pulls options from Workspace.AnalyzerDocuments. Need to register this OptionsProvider with the OptionService during Workspace initialization.

**Comment by coder2000** [comment]
Is this supported now?

**Comment by filipw** [comment]
not yet

**Comment by coder2000** [comment]
Any timeline for implementation? It gets kind of annoying having 800 warnings that are not supposed to be there.

**Comment by filipw** [comment]
> Any timeline for implementation?

no timeline, hopefully soon

**Comment by 333fred** [comment]
Also looking for this, I'm assuming my issues with analyzer settings not being respected are due to this.

**Comment by filipw** [comment]
yes correct, when we implemented editorconfig there was no native Roslyn support yet so we had to use the VS conventions package like dotnet format did at the time
