### ISSUE TITLE
Hover MarkedString returning :contents [nul nul]

### ISSUE THREAD

**Issue by elxbarbosa** [OmniSharp/omnisharp-roslyn#1671]
Hi,

OmniSharp-Roslyn server is returning `[null null]` as the `:contents` field of a response to `textDocument/hover`. 

```
server-reply (id:5) Sat Dec 21 16:14:38 2019:
 (:jsonrpc "2.0" :id 5 :result
 	  (:contents  [nil nil]))
```
and
```
server-reply (id:5) Sat Dec 21 16:14:38 2019:
 (:jsonrpc "2.0" :id 5 :result
 	  (:contents  [nil nil]))
```

while it should return: `type MarkedString = string | { language: string; value: string };` . 

What might be not conformant with LSP specs: https://microsoft.github.io//language-server-protocol/specifications/specification-3-14/#textDocument_hover

https://github.com/OmniSharp/omnisharp-roslyn/blob/dacc49a3176c30767d0c1604cce6073afb0a7f6e/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpHoverHandler.cs#L50

----
related: https://github.com/OmniSharp/omnisharp-roslyn/issues/1087 , https://github.com/emacs-lsp/lsp-ui/issues/350
initial reporting: https://github.com/joaotavora/eglot/issues/371#issuecomment-568205461
more: https://github.com/joaotavora/eglot/issues/371#issuecomment-568254412
full log:  http://ix.io/253F/text    lines: 3177 and 3555
Version: 1.34.9
OS: Ubuntu 18.10

**Comment by 333fred** [comment]
I think this may have been fixed by my hover changes a bit ago, as we now return a MarkupContent instead of a MarkedString:
https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpHoverHandler.cs#L48

@elxbarbosa does this still repo?

**Comment by elxbarbosa** [comment]
@333fred @filipw 

It is working correctly now.

log: https://pastebin.pl/view/1679ae38

**Comment by filipw** [comment]
thanks
