### ISSUE TITLE
Is it possible to have omnisharp-roslyn target .NET Core?

### ISSUE THREAD

**Issue by Legogris** [OmniSharp/omnisharp-roslyn#1703]
Is it possible to use the C# vscode extension without mono at all? On nixos the mono package in repos rarely gets updated and it's a pain to have the extension broken with every other update. I'd wager most users of this extension have 0 use for mono.

**Comment by filipw** [comment]
We can keep this open but it's not possible to achieve unless we drop support for Unity/desktop .NET which I don't think will happen anytime soon 😃
You can find more information here #988 and here #666 and here #915

**Comment by xsoheilalizadeh** [comment]
Seems it'll be possible when .NET 5 released, am I right?

**Comment by rickardp** [comment]
Also consider Alpine linux which is very common these days and not glibc-based. Would not not be possible to use multi targeting and support a reduced feature set (.NET core projects only) with only .net core installed. The only cases of needing anything beyond that I know of is Unity and Xamarin (IIRC, desktop is not supported on .net core), and there is a ton of projects out there not needing those.

I understand that supporting multiple targets adds complexity, but I think the case of using Alpine-based containers in VS Code devcontainer.json is (or will be) quite common.

**Comment by filipw** [comment]
> Seems it'll be possible when .NET 5 released, am I right?

no there are still issues in terms of executing msbuild tasks that are desktop .NET
additionally, there is currently a dependency on Visual Studio Test Protocol to run and debug tests which is also desktop .NET

**Comment by rickardp** [comment]
@filipw IMHO the project would benefit greatly from a clear strategy for developing .NET core web/backend services using OmniSharp. Depending on Mono severely restricts the set of containers that can be used.
It is so close to being possible to use VS Code with dev containers for all C# development now and finally ditch Visual Studio. With GitHub code spaces etc coming up, finally getting rid of the Windows VM just to have Visual Studio would be a huge win for the C# developer community. For example, I now do all my Python development exclusively in containers, using either VS code or Theia in a browser. And with C# we are almost there, I just think issues like this needs a bit more focus.

**Comment by filipw** [comment]
> I just think issues like this needs a bit more focus.

like I said, it's not impossible, it just means we would need to have a dual model:

 - "full" version that supports Unity and desktop based MSBuild tasks
 - "light" version that only works with .NET Core / .NET 5 development

The major problem, however, is that with how things stand at the moment debugger and test execution are also coupled to "full" version due to VS dependencies. Under the hood OmniSharp is not really fully independent of VS.

**Comment by Spongman** [comment]
"~full~ legacy" version that supports Unity and desktop based MSBuild tasks
"~light~ modern" version that only works with .NET Core / .NET 5 development

**Comment by rickardp** [comment]
Any updates on this subject. Dragging along the full mono-devel dependency for this is becoming increasingly heavy for a very small gain in functionality, especially now with .net 5 and .net 6 on the way. Maybe maintaining the current version for Unity and focusing on .net-framework-less .net 5/6 for future development would make sense?

**Comment by rickardp** [comment]
@filipw As other people pointed out earlier, the embedded version isn't portable. For example IIRC there's still not an aarch64 version (maybe fixed now?) and it's not compatible with Alpine Linux.

For a .net 5 dev container, removing the Mono dependency makes a lot of sense.

Sounds promising that there is work on .net 5/6 support though!

**Comment by Mithras** [comment]
hey @filipw,
I'm trying to build `demo/net50` to try it out and it seems to build just fine but it fails to publish:
![image](https://user-images.githubusercontent.com/2098029/117519480-864b5980-af58-11eb-9b53-3d9ade10c370.png)
I'm running these to build:
```
docker run -v "/c/s/omnisharp-roslyn/:/src" -it --rm mono:latest
cd /src
./build.sh --target Quick --configuration Release
```
Am I doing something wrong?

**Comment by filipw** [comment]
The generic publish task doesn't work on that branch, try running `./build.sh --target PublishNet5Builds --configuration Release`

**Comment by Mithras** [comment]
That worked, thank you!
![image](https://user-images.githubusercontent.com/2098029/117547873-c9540e00-afe6-11eb-9840-1ba4360bd98c.png)

Now I'm having another issue. There are dozens of this exceptions in the log and no intellisense at all:
```
File name: 'NuGet.Frameworks, Version=5.9.1.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /workspace/EcoManager/Public.ApplicationServices.Core/Public.ApplicationServices.Core.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "ProcessFrameworkReferences" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.9.1.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```
I don't have "NuGet.Frameworks" anywhere in my code. Should I add it somewhere?

**Comment by Mithras** [comment]
I do have 3 of them though
![image](https://user-images.githubusercontent.com/2098029/117549144-877a9600-afed-11eb-8e45-e99f5d5ef5f5.png)

**Comment by Mithras** [comment]
Any ideas why `demo/net50` doesn't work for me? Main releases crash every couple hours and eat all my CPU in between crashes. I really want to try pure .NET 5 build.

**Comment by filipw** [comment]
yes https://github.com/OmniSharp/omnisharp-roslyn/tree/feature/omnisharp-vnext

**Comment by Mithras** [comment]
> yes https://github.com/OmniSharp/omnisharp-roslyn/tree/feature/omnisharp-vnext

Cool. Do I need to specify some special target or just `./build.sh --target Quick --configuration Release` should work?
I tried:
```
docker run -v "/c/s/omnisharp-roslyn/:/src" -it --rm mono:latest
cd /src
./build.sh --target Quick --configuration Release
```
and it worked
![image](https://user-images.githubusercontent.com/2098029/133489488-c7e77feb-372e-4505-8839-03b5ce95b89c.png)
THere were a couple errors though:
![image](https://user-images.githubusercontent.com/2098029/133488183-899c4534-96ee-4cdc-b2a7-8d04b6f17e63.png)
but it doesn't work when I try to use it:
![image](https://user-images.githubusercontent.com/2098029/133492169-6eeaec21-8abf-4076-ba98-fd733ac7789a.png)
it is the correct path:
![image](https://user-images.githubusercontent.com/2098029/133492262-09cc56b4-2aac-4da4-bfd2-bb1f22ba5dbc.png)
Am I missing something?

**Comment by filipw** [comment]
you should set `omnisharp.path` to `"omnisharp.path": "{your cloned directory}/artifacts/publish/OmniSharp.Stdio.Driver/osx-x64/net5.0/OmniSharp"`

**Comment by Mithras** [comment]
I think it was permissions issue and now after doing `chmod -R a+x /opt/omnisharp` I'm getting a different error:
![image](https://user-images.githubusercontent.com/2098029/133494197-8d92557b-a606-4176-918e-3a3fb037730a.png)

**Comment by filipw** [comment]
Yes, as I said, you should find the published x-plat under artfiacts in the platform specific folder. In this case I have no idea what you have under `opt`, because we never publish anything there and why is it lowercase - all OmniSharp files are pascal cased. The entry point on Linux/Mac is called `OmniSharp`.

The steps are:

1) run `./build.sh --target Quick --configuration Release` or even better `./build.sh --target PublishNet5Builds --configuration Release` (the latter, despite the name, will be quicker)
2) set `omnisharp.path` to `"omnisharp.path": "{your cloned directory}/artifacts/publish/OmniSharp.Stdio.Driver/osx-x64/net5.0/OmniSharp"` where `osx-x64` should be replaced by the relevant platform folder that was created for you

If it doesn't work, then it is because this branch is not supported 😀

**Comment by Mithras** [comment]
We are using Linux dev containers to do all development so if it doesn't work on Linux it's not something I can test or use.

>I have no idea what you have under opt

I just mapped artifacts there:
![image](https://user-images.githubusercontent.com/2098029/133495462-79e85aea-cfa0-4956-a81e-4a0c334b6e1b.png)
so it's whatever I got after building in `/omnisharp-roslyn/artifacts/publish/OmniSharp.Stdio.Driver/linux-x64/net5.0`

> or even better ./build.sh --target PublishNet5Builds --configuration Release

I'll try this one

**Comment by Mithras** [comment]
`./build.sh --target PublishNet5Builds --configuration Release` is definitely much faster:
![image](https://user-images.githubusercontent.com/2098029/133496807-34373583-f13d-49ac-8de9-f7c498b9397a.png)
but still the same
![image](https://user-images.githubusercontent.com/2098029/133497273-77f6a14e-7c01-4bc1-8b37-bec77f147345.png)

**Comment by filipw** [comment]
as I wrote before this is not really an OmniSharp error, it means your configuration is incorrect and you are pointing to a non-existing path.

**Comment by Mithras** [comment]
![image](https://user-images.githubusercontent.com/2098029/133510487-3aedd983-b780-4681-880a-b32ba73759cb.png)
I'm just doing what's written in the readme. Not sure what path are you talking about.

**Comment by filipw** [comment]
your screenshot showed you set `"omnisharp.path":"/opt/omnisharp"`. Assuming your artifact folder is `/opt/omnisharp` ,you should set it to `"omnisharp.path":"/opt/omnisharp/OmniSharp"` because the executable is named `OmniSharp`

**Comment by Mithras** [comment]
Ok, that was my problem. It starts now:
![image](https://user-images.githubusercontent.com/2098029/133511592-0d8a7eb1-c304-4532-a19a-776ed180d35a.png)
And then I get 50 of these:
```
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "ProcessFrameworkReferences" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.11.0.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'NuGet.Frameworks, Version=5.11.0.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/workspace/EcoManager/Infrastructure/Infrastructure.csproj'.
/workspace/EcoManager/Infrastructure/Infrastructure.csproj
/usr/share/dotnet/sdk/5.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(89,5): Error: The "ProcessFrameworkReferences" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.11.0.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'NuGet.Frameworks, Version=5.11.0.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```
and nothing works

**Comment by filipw** [comment]
This is because you have SDK `5.0.400` installed, and at the moment this branch is pinned to `5.0.302` and won't support anything newer.

**Comment by Mithras** [comment]
ok, I'll try it with older SDK later. Is there a reason it's pinned to a specific version?

**Comment by Mithras** [comment]
> I'll try it with older SDK later

or not. I don't feel like randomly trying all of [these](https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/vscode/devcontainers/dotnet?P1=1631755248&P2=1&P3=1&P4=duNmBLt3cfQ2GOBQvGTDf6UKFNx72eUHCuBAwa4XYWs%3D&se=2021-09-16T01%3A20%3A48Z&sig=hkm5rDfDm0I9o72VYA0CyAaGWh594ZEeqmMwCsV5ra0%3D&sp=r&sr=b&sv=2015-02-21) to find which one has `5.0.302`
Please update the issue when the branch supports newer SDKs.

**Comment by vchirikov** [comment]
If you don't need to use csx/cake, you can use [my fork of omnisharp](https://github.com/vchirikov/omnisharp-roslyn).
I cut them off and migrated the code to the net6.0 (+ some minor updates like ilspy/msbuild etc).
`dotnet publish -c Release -o artifacts/omnilight` + 

```json
"omnisharp.path": "<RepoRootPath>\\artifacts\\omnilight\\OmniSharp.exe",
```

**Comment by Mithras** [comment]
Also, is it expected that Omnisharp breaks even when patch version of SDK changes? E.g. 5.0.401 works but 5.0.402 does not. I've tried to find/replace all 5.0.401 with 5.0.402 but it still doesn't work. Is there a guide what exactly do I need to change to make it work with a specific SDK version?

**Comment by filipw** [comment]
resolved by https://github.com/OmniSharp/omnisharp-roslyn/pull/2291
