### ISSUE TITLE
failed to build on arch linux

### ISSUE THREAD

**Issue by LarryLeb** [OmniSharp/omnisharp-roslyn#1705]
1. git clone https://github.com/OmniSharp/omnisharp-roslyn.git
2. cd omnisharp-roslyn
3. ./build.sh
I get error /home/user/Downloads/omnisharp-roslyn/build.cake(47,20): warning CS0618: 'ITFBuildProvider.IsRunningOnTFS' is obsolete: 'Please use ITFBuildProvider.IsRunningOnAzurePipelines instead.'

**Comment by filipw** [comment]
this is not an error, just a warning that is currently always displayed with the latest version of Cake, it doesn't impact the build.
Do you have any *real* error?

**Comment by LarryLeb** [comment]
Hello thank you for response, here is last 4 lines in terminal when ./build.sh
-Adding package 'xunit.runner.console.2.4.0' to folder '/home/zuwei/Downloads/omnisharp-roslyn/tools'
-Added package 'xunit.runner.console.2.4.0' to folder '/home/zuwei/Downloads/omnisharp-roslyn/tools'
-/home/user/Downloads/omnisharp-roslyn/build.cake(47,20): warning CS0618: 'ITFBuildProvider.IsRunningOnTFS' is obsolete: 'Please use ITFBuildProvider.IsRunningOnAzurePipelines instead.'
-Error: One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)
	GitVersion: Process returned an error (exit code 1).

**Comment by LarryLeb** [comment]
i can paste whole log if you would like but its mostly just adding and restoring nuget
