### ISSUE TITLE
Unable to use/consume Nuget Package 'OmniSharp.Roslyn.CSharp'

### ISSUE THREAD

**Issue by warrenbuckley** [OmniSharp/omnisharp-roslyn#1709]
Hello 👋 
I am trying to play around and experiment with getting OmniSharp HTTP Server to run in the same application to use in conjunction with the Monaco Editor.

When trying to install the Nuget package - `OmniSharp.Roslyn.CSharp` I get the following error

>NU1101: Unable to find package **Microsoft.VisualStudio.CodingConventions**. No packages exist with this id in source(s): dotnet.myget.org roslyn, Microsoft Visual Studio Offline Packages, nuget.org

Additionally, some short examples in a Wiki or Readme about how to consume/use the public listed Nuget packages would be helpful too, please :)

https://www.nuget.org/packages?q=omnisharp

**Comment by filipw** [comment]
That package is on the `<add key="vs-editor" value="https://www.myget.org/F/vs-editor/api/v3/index.json" />` feed.
In fact you may need all/most of them to successfully restore https://github.com/OmniSharp/omnisharp-roslyn/blob/master/NuGet.Config due to other dependencies i.e. beta Roslyn.

**Comment by warrenbuckley** [comment]
Added the feed thanks @filipw 
But is there a version of OmniSharp.Roslyn.CSharp Nuget package that does not depend on a beta version of Roslyn?


>NU1107 Version conflict detected for **Microsoft.CodeAnalysis.Common**. Install/reference Microsoft.CodeAnalysis.Common 3.5.0-beta3-20058-03 directly to project Umbraco.Web.UI to resolve this issue. 
>
 >Umbraco.Web.UI -> OmniSharp.Roslyn.CSharp 1.34.11 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.5.0-beta3-20058-03 -> Microsoft.CodeAnalysis.Common (= 3.5.0-beta3-20058-03) 
 Umbraco.Web.UI -> Microsoft.CodeAnalysis.CSharp 2.10.0 -> Microsoft.CodeAnalysis.Common (= 2.10.0).	Umbraco.Web.UI	C:\Code\Umbraco-CMS-MONACO\src\Umbraco.Web.UI\Umbraco.Web.UI.csproj

**Comment by filipw** [comment]
not for a longtime (maybe not at all since we started publishing nugets), we always use betas to support the latest language and compiler features

**Comment by filipw** [comment]
I will close this as this should answer the question https://github.com/OmniSharp/omnisharp-roslyn/issues/1709#issuecomment-585228310
