### ISSUE TITLE
Formatting Option for brace newlines in switch expressions

### ISSUE THREAD

**Issue by fmoo** [OmniSharp/omnisharp-roslyn#1718]
The current collection of [Configuration Options](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options) do not seem to include an option to disable newlines before the opening brace of a [Switch Expression](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions).

This creates visual inconsistencies with switch statements for projects that have e.g., NewLinesForBracesInControlBlocks set to false.

Could we get a new property for switch expressions (or have an existing property mapped) to allow for consistency in formatting?

**Comment by filipw** [comment]
thanks a lot for the issue - however, OmniSharp doesn't have its own formatting engine - we merely expose to the users the features what Roslyn gives us (and, well, not just us but also, for example, Visual Studio). The issue you mentioned is already logged in the Roslyn repo https://github.com/dotnet/roslyn/issues/36913

once that's available in Roslyn, we will have it in OmniSharp
