### ISSUE TITLE
Couldnt able to install in my ubuntu docker container

### ISSUE THREAD

**Issue by dhananjayharel** [OmniSharp/omnisharp-roslyn#1723]
When I do ./build.sh
At the end of installation I am getting the following error:
`
  App -> /home/project/omnisharp-roslyn/test-assets/test-projects/ProjectWithMultiTFMLib/App/bin/Debug/netcoreapp2.1/App.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.11
Restoring and building: ExternAlias...
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 32.15 ms for /home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.App/ExternAlias.App.csproj.
  Restore completed in 32.16 ms for /home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.App2/ExternAlias.App2.csproj.
  Restore completed in 0.61 ms for /home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.Lib/ExternAlias.Lib.csproj.
/home/project/omnisharp-roslyn/.dotnet/sdk/3.0.100/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ExternAlias.Lib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.App/ExternAlias.App.csproj]
  ExternAlias.Lib -> /home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.Lib/bin/Debug/netstandard2.0/ExternAlias.Lib.dll
  ExternAlias.App2 -> /home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.App2/bin/Debug/netcoreapp2.1/ExternAlias.App2.dll
Program.cs(1,14): error CS0430: The extern alias 'abc' was not specified in a /reference option [/home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.App/ExternAlias.App.csproj]

Build FAILED.

/home/project/omnisharp-roslyn/.dotnet/sdk/3.0.100/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ExternAlias.Lib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.App/ExternAlias.App.csproj]
Program.cs(1,14): error CS0430: The extern alias 'abc' was not specified in a /reference option [/home/project/omnisharp-roslyn/test-assets/test-projects/ExternAlias/ExternAlias.App/ExternAlias.App.csproj]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.68
An error occurred when executing task 'PrepareTestAssets:CommonTestAssets'.

----------------------------------------
Teardown
----------------------------------------
Shutting down MSBuild server...
Shutting down VB/C# compiler server...
Shutting down Razor build server (process 912)...
VB/C# compiler server shut down successfully.
Razor build server (process 912) failed to shut down: The shutdown command failed: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.2' was not found.
  - The following frameworks were found:
      3.0.0 at [/home/project/omnisharp-roslyn/.dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download

MSBuild server shut down successfully.
Error: One or more errors occurred. (.NET Core CLI: Process returned an error (exit code 1).)
        .NET Core CLI: Process returned an error (exit code 1).`

**Docker Ubuntu Version: 18.04
.Net core SDK version 3.1.102
.Net core runtime version 3.1.2**

**Comment by filipw** [comment]
this test is flaky. Does it fail all the time, or did it just fail once?

**Comment by tamasvajk** [comment]
Thanks @filipw. 
Now I'm running into the GitVersion problem mentioned in https://github.com/OmniSharp/omnisharp-roslyn/issues/1891

**Comment by filipw** [comment]
Fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/2030
