### ISSUE TITLE
Workspace symbols on LSP client

### ISSUE THREAD

**Issue by matheuslessarodrigues** [OmniSharp/omnisharp-roslyn#1743]
So, if you try to use omnisharp on Neovim through Coc.vim, it's not possible to list workspace symbols.
Relevant `coc-omnisharp` issue: https://github.com/coc-extensions/coc-omnisharp/issues/14

It's strange because the feature exists on vscode (throught `ctrl-t`) but not on a regular lsp client it seems?

Anyone have any idea? Thanks in advance!

**Comment by razzmatazz** [comment]
@matheuslessarodrigues vscode does not use (iirc) LSP Interface to omnisharp Server but uses a custom protocol instead

**Comment by matheuslessarodrigues** [comment]
oh, is that feature harder to implement with lsp? is there a workaround? or even how one could contribute with an implementation?

**Comment by razzmatazz** [comment]
> oh, is that feature harder to implement with lsp? is there a workaround? or even how one could contribute with an implementation?

Semantics are slightly different, and omnisharp roslyn uses older version of https://github.com/OmniSharp/csharp-language-server-protocol/ library. I guess the job is to try and upgrade it (in omnisharp-roslny) and see what other things need to be done to make it work with the latest changes and if all this helps.

**Comment by CyanBlob** [comment]
Is anyone working on supporting more of the LSP? The `coc-omnisharp` extension for Coc.vim doesn't seem to be able to jump to definition/implementation due to this project not fully supporting LSP: https://github.com/coc-extensions/coc-omnisharp/issues/15

**Comment by razzmatazz** [comment]
@CyanBlob the library that omnisharp uses to support LSP has quite a lot of improvements done lately, but not a lot of that has yet been integrated into omnisharp, probably because it is very much still in flux:
 - https://github.com/OmniSharp/csharp-language-server-protocol

**Comment by razzmatazz** [comment]
I have submited a PR #1799 that implements `workspace/symbol` LSP request, in particular.

**Comment by matheuslessarodrigues** [comment]
Oh, This is super cool! Thank you!
