### ISSUE TITLE
Would it be possible to Authenticode sign the Omnisharp dlls and exe

### ISSUE THREAD

**Issue by bencyoung** [OmniSharp/omnisharp-roslyn#1760]
Our work has a fairly locked down policy for running code in that anything that's not signed by a trusted signer can't be run. I can request for OmniSharp to be whitelisted, but to do that it needs a publisher signature. Otherwsie we need to allow it individually on each machine!

I know it's a hassle but would you consider signing the exe and dlls?  All the MS stuff is already signed so VS Code itself runs ok.

**Comment by filipw** [comment]
@david-driscoll what do you think? I am personally not a big fan of doing that..

**Comment by filipw** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/2143
