### ISSUE TITLE
Settings from .editorconfig not respected by OmniSharp formatting

### ISSUE THREAD

**Issue by Iron-E** [OmniSharp/omnisharp-roslyn#1765]
# Problem

In several editors, I have had issues with OmniSharp-Roslyn ignore the settings of my ".editorconfig". I have tried using it in Neovim (with OmniSharp-Vim, and in VSCode with OmniSharp-VSCode. In both editors, the settings of that file are completely ignored.

# Steps to Reproduce

1. Take a sample ".editorconfig" file, such as this:
	```dosini
	[*.cs]
	csharp_indent_braces = false
	```
2. Take some code, such as this:
	```cs
	int foo = 0;
	switch (foo)
	{
		case 0:
		{
			// some code here
		}
	}
	```
3. Format the code using the editor of your choice, and you will see this:
	```cs
	int foo = 0;
	switch (foo)
	{
		case 0:
			{
				// some code here
			}
	}
	```

Note that this happens __despite__ the `csharp_indent_braces = false` rule in the ".editorconfig" file.

**Comment by filipw** [comment]
did you enable editorconfig support? it's off by default in OmniSharp

**Comment by Iron-E** [comment]
There's no mention anywhere of there being a configuration option for turning editorconfig support on or off in any of the documentation. 

See the [README](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/README.md), [Configuration Options](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options), and, [Using OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/doc/Using-Omnisharp.md) pages.

I had to search [the issues](https://github.com/OmniSharp/omnisharp-roslyn/issues/1558) to find that there is an option `"EnableEditorConfigSupport"`. Upon enabling it, things work as expected. I feel like it should be mentioned in at least one of the documents I listed previously, though. How did the person in the issue discover it? Was it in the documentation before, but it was accidentally removed?

**Comment by filipw** [comment]
It's in the release notes https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#1330---2019-07-01 and I blogged about it here https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/ (it comes up on 
top in google when searching for "omnisharp editorconfig").

But you are right, it should be included in the Wiki too.

I will close this issue since it works now - thanks.
