### ISSUE TITLE
Gray out unnecessary diagnostics in the editor

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-roslyn#178]
This awesome bag in roslyn has an "unnecessary" string.

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs#L194
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Diagnostic/DiagnosticDescriptor.cs#L60

**Comment by nosami** [comment]
This is also possible using the Classifier / highlighting api

**Comment by david-driscoll** [comment]
`/highlight` give us this information now, and can be enabled for editors that support it.
