### ISSUE TITLE
Nullable and IAsyncEnumerable break syntax highlighting

### ISSUE THREAD

**Issue by jaredpar** [OmniSharp/omnisharp-roslyn#1786]
This will reproduce on pretty much every C# project I've tested, even `dotnet new console`. 

Type in the following code to the editor 

```cs
            string s1 = "hello"; // string is colored
            await foreach (var x in e) { }
            string s2 = "world"; // string is not colored
```

Notice that the presence of `await foreach` causes the second usage of `string` to not get properly syntax highlighted. It will be white instead of blue. The moment you delete `await` then everything will snap back to normal.

This problem appears to impact a number of C# 8 features. For instance the same effect occurs when using a nullable array. 

```cs
            string s1 = "hello"; // string is colored
            int[]? example;
            string s2 = "world"; // string is not colored
```

**Comment by jaredpar** [comment]
One way to work around this is to add an empty statement after the `await foreach`

```cs
                ; // empty statement to fix vs code syntax bug around await foreach
```

**Comment by filipw** [comment]
This is really an issue of C# extension for VS Code not of OmniSharp.
It uses https://github.com/dotnet/csharp-tmLanguage for highlighting, which is very limited and hasn't been updated in quite a while.

OmniSharp exposes semantic highlighting endpoint based on Roslyn's semantic highlighting (I added your two cases as tests here to make sure they are covered (https://github.com/OmniSharp/omnisharp-roslyn/pull/1789)) but at the moment the C# extension still doesn't use that endpoint - it's a work in progress to incorporate it github.com/OmniSharp/omnisharp-vscode/pull/3667

**Comment by filipw** [comment]
this is resolved via semantic hihglighting
