### ISSUE TITLE
MSBuild Load Error (Tools version 14.0 not supported)

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#179]
Reported by @luisrudge
![](https://jabbrlive.blob.core.windows.net/jabbr-uploads/clipboard_851d.png)

**Comment by davidfowl** [comment]
Is msbuild 14 installed?

**Comment by luisrudge** [comment]
No. It's a solution created in vs 2015 and I'm running vs 2013

Enviado pelo meu Windows Phone
________________________________
De: David Fowler<mailto:notifications@github.com>
Enviada em: ‎24/‎04/‎2015 05:34
Para: OmniSharp/omnisharp-roslyn<mailto:omnisharp-roslyn@noreply.github.com>
Cc: Luís Rudge<mailto:luis@luisrudge.net>
Assunto: Re: [omnisharp-roslyn] MSBuild Load Error (Tools version 14.0 not supported) (#179)

Is msbuild 14 installed?

---

**Comment by nosami** [comment]
Ah. So this isn't technically an omnisharp issue then.

**Comment by luisrudge** [comment]
Well, VS2013 has no problem in building this. Omnisharp shouldn't have too.

**Comment by nosami** [comment]
You don't have msbuild 14 installed though? Didn't you need to change the tools version to 12.0 to get it to work?

**Comment by luisrudge** [comment]
I don't have msbuild14. Still, visual studio runs just fine, while omnisharp complains about the msbuild version.

**Comment by davidfowl** [comment]
This is going to be tricky and I assume hard to get right. We need to figure out which toolset we should use based on the available toolsets. There's likely some heuristic for this though I have on idea what it is. Maybe we need to look at all available toolsets and pick the "best one".

**Comment by luisrudge** [comment]
:+1: For that

Enviado pelo meu Windows Phone
________________________________
De: David Fowler<mailto:notifications@github.com>
Enviada em: ‎28/‎04/‎2015 05:59
Para: OmniSharp/omnisharp-roslyn<mailto:omnisharp-roslyn@noreply.github.com>
Cc: Luís Rudge<mailto:luis@luisrudge.net>
Assunto: Re: [omnisharp-roslyn] MSBuild Load Error (Tools version 14.0 not supported) (#179)

This is going to be tricky and I assume hard to get right. We need to figure out which toolset we should use based on the available toolsets. There's likely some heuristic for this though I have on idea what it is. Maybe we need to look at all available toolsets and pick the "best one".

---

**Comment by nosami** [comment]
Fixed by #198
