### ISSUE TITLE
Generate typescript definitions for Api/Models and Stdio/Protocol classes

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-roslyn#180]
I made a simple grunt task to regenerate a typescript interface from the classes provided by the server.  Ideally this could be part of the build pipeline for the binaries, so that any editor written in Typescript can strongly type their requests and responses.

https://github.com/OmniSharp/omnisharp-atom/blob/master/tasks/build-models.js

**Comment by nosami** [comment]
What about using something like this? http://type.litesolutions.net

**Comment by jrieken** [comment]
will go into the binaries repo
