### ISSUE TITLE
Consume Quick Info APIs

### ISSUE THREAD

**Issue by RikkiGibson** [OmniSharp/omnisharp-roslyn#1808]
It appears the reading experience when using OmniSharp is somewhat limited because OmniSharp is not using the Quick Info APIs provided by Roslyn.

![VS quick info example](https://user-images.githubusercontent.com/5833655/82690467-20fc3c80-9c11-11ea-9e80-bdd34bda7f74.png)

![OmniSharp quick info-like example](https://user-images.githubusercontent.com/5833655/82690526-3ec9a180-9c11-11ea-99bc-3b2cd8a366ab.png)

**Comment by filipw** [comment]
yeah this is definitely on the TODO. when we started it didn't exist yet 😀

**Comment by 333fred** [comment]
@filipw this can be closed now :)

**Comment by filipw** [comment]
indeed!

**Comment by RikkiGibson** [comment]
Is there recent work implementing this?

**Comment by RikkiGibson** [comment]
@333fred wasn't sure where to follow up with this part-- seems like the nullable flow state bit and the doc comment bit don't always format quite right with the new quick info feature.

![image](https://user-images.githubusercontent.com/5833655/90572523-14807500-e169-11ea-8563-f4f3dce67359.png)

I think we expect more space between the doc comment and the nullable flow state text. Here's how a similar Quick Info looks in VS:

![image](https://user-images.githubusercontent.com/5833655/90572606-56a9b680-e169-11ea-9c32-21bf00538300.png)

**Comment by 333fred** [comment]
@RikkiGibson open a new bug :)
