### ISSUE TITLE
How to make override autocomplete fill snippet on enter

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-roslyn#1809]
It was a habit of me to just type override select autocomplete like this

![image](https://user-images.githubusercontent.com/1042507/82750872-7d13bc00-9ddd-11ea-8511-b8b4eb0912c9.png)

I expect that if I press enter it would completely emit type and modifier from the base class like this

![image](https://user-images.githubusercontent.com/1042507/82750884-9f0d3e80-9ddd-11ea-96ce-3eb06c616206.png)

But currently now it only emit just this line

![image](https://user-images.githubusercontent.com/1042507/82750879-89981480-9ddd-11ea-8ba4-487f391fe891.png)

I am not sure I have making some mistake in omnisharp config, or it just not support in omnisharp vscode? If so may I request this feature?

**Comment by filipw** [comment]
this is currently not supported - it will be supported once we move to the CompletionService fully, including the ability to resolve completion item by the client

**Comment by Thaina** [comment]
@filipw Thank you for your information

**Comment by filipw** [comment]
it is currently an Omnisharp server limitation
