### ISSUE TITLE
Add support for empty_block_style formatting option

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-roslyn#1826]
Resharper has following setting, which can be set through editorconfig:
```
resharper_empty_block_style=together
```
What this does is format empty code blocks to have the brackets on the same line, like so:
```csharp
public SomeConstructor() : base()
{ }
```

Whereas omnisharp tries to format it like this:
```csharp
public SomeConstrcutor() : base()
{
}
```

Would it be possible to add a new formatting option (in omnisharp.json and / or through editorconfig) that would enable us to configure omnisharp to have the same behaviour?

**Comment by filipw** [comment]
OmniSharp uses Roslyn formatting features. You should open a feature request issue in https://github.com/dotnet/roslyn/issues 

Once it's available in Roslyn we will automatically offer it too.
