### ISSUE TITLE
csx support does not correctly support #load'ing files outside the "workspace"

### ISSUE THREAD

**Issue by JakeSays** [OmniSharp/omnisharp-roslyn#1830]
Omniscript fails to recognize scripts loaded like this: `#load "../../foo.csx"`. One would expect any referenced script file to be available for intellisense.

**Comment by JakeSays** [comment]
This also seems to be working fine. No clue what I was looking at. Sorry for the trouble.

**Comment by filipw** [comment]
thanks 😀
