### ISSUE TITLE
[Urgent] Orphan child process  or zombie process

### ISSUE THREAD

**Issue by GNSubrahmanyam** [OmniSharp/omnisharp-roslyn#1838]
@filipw 
Reference: https://github.com/OmniSharp/omnisharp-roslyn/issues/1834

![image](https://user-images.githubusercontent.com/18217008/84812956-d3ff6080-b02c-11ea-8423-a1d94e46bace.png)

**Comment by GNSubrahmanyam** [comment]
@filipw Any update why omnisharp process is not getting killed in docker after client disconnects

**Comment by filipw** [comment]
This is a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1834
