### ISSUE TITLE
IntelliSense completion in DateTime and TimeSpan string literals

### ISSUE THREAD

**Issue by loligans** [OmniSharp/omnisharp-roslyn#1874]
As a user, when I place my caret inside the DateTime or TimeSpan string literal and press (Ctrl + Space). It should complete with  options and optionally an explanation as to what each character means. 

![image](https://user-images.githubusercontent.com/3218210/89458131-5fd36600-d71b-11ea-8046-74211ca31ad8.png)

**Comment by filipw** [comment]
this is already implemented and will be released in the next version https://github.com/OmniSharp/omnisharp-roslyn/pull/1871
