### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by GoldenHuaji** [OmniSharp/omnisharp-roslyn#1891]
This is the code

<pre><font color="#CC0000"><b>$ </b></font><font color="#4E9A06">./build.sh</font>
Feeds used:
  /home/goldenhuaji/.nuget/packages/
  https://api.nuget.org/v3/index.json
  https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json
  https://www.myget.org/F/omnisharp/api/v3/index.json

/home/goldenhuaji/.cache/vimfiles/repos/github.com/OmniSharp/omnisharp-vim/omnisharp-roslyn-server/tools/packages.config 中列出的所有程序包均已安装。
<span style="background-color:#2E3436"><font color="#FCE94F">/home/goldenhuaji/.cache/vimfiles/repos/github.com/OmniSharp/omnisharp-vim/omnisharp-roslyn-server/build.cake(48,20): warning CS0618: &apos;ITFBuildProvider.IsRunningOnTFS&apos; is obsolete: &apos;Please use ITFBuildProvider.IsRunningOnAzurePipelines instead.&apos;</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">Error: </font></span><span style="background-color:#EF2929"><font color="#EEEEEC">One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)</font></span>
	<span style="background-color:#EF2929"><font color="#EEEEEC">GitVersion: Process returned an error (exit code 1).</font></span>
</pre>

**Comment by GoldenHuaji** [comment]
On  Ubuntu 20.04

**Comment by filipw** [comment]
cc GitVersion experts @mholo65 @david-driscoll

**Comment by david-driscoll** [comment]
I've not seen this issue myself on WSL (not saying it's not an issue).

I can look at updating our version, I'm not sure if we're fully up to date or not.

**Comment by R0flcopt3r** [comment]
Also on Fedora 32

**Comment by R0flcopt3r** [comment]
Also on Fedora 32.

```
> ./build.sh
[...]
Adding package 'System.Text.Encodings.Web.4.7.1' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Added package 'System.Text.Encodings.Web.4.7.1' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Restoring NuGet package System.Text.Json.4.7.1.
Adding package 'System.Text.Json.4.7.1' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Added package 'System.Text.Json.4.7.1' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Restoring NuGet package System.Threading.Tasks.Dataflow.4.11.1.
Adding package 'System.Threading.Tasks.Dataflow.4.11.1' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Added package 'System.Threading.Tasks.Dataflow.4.11.1' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Restoring NuGet package System.Threading.Tasks.Extensions.4.5.4.
Adding package 'System.Threading.Tasks.Extensions.4.5.4' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Added package 'System.Threading.Tasks.Extensions.4.5.4' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Restoring NuGet package xunit.runner.console.2.4.0.
Adding package 'xunit.runner.console.2.4.0' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
Added package 'xunit.runner.console.2.4.0' to folder '/home/eirik/Git/omnisharp-roslyn/tools'
/home/eirik/Git/omnisharp-roslyn/build.cake(48,20): warning CS0618: 'ITFBuildProvider.IsRunningOnTFS' is obsolete: 'Please use ITFBuildProvider.IsRunningOnAzurePipelines instead.'
Error: One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)
	GitVersion: Process returned an error (exit code 1).
```

**Comment by sverbist** [comment]
Same here
```
stephen@svacer> uname -r
5.8.14-arch1-1
```
```
stephen@svacer> ./build.sh
Feeds used:
  /home/stephen/.nuget/packages/
  https://api.nuget.org/v3/index.json
  https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json
  https://www.myget.org/F/omnisharp/api/v3/index.json

All packages listed in /home/stephen/Repositories/omnisharp-roslyn/tools/packages.config are already installed.
/home/stephen/Repositories/omnisharp-roslyn/build.cake(48,20): warning CS0618: 'ITFBuildProvider.IsRunningOnTFS' is obsolete: 'Please use ITFBuildProvider.IsRunningOnAzurePipelines instead.'
Error: One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)
	GitVersion: Process returned an error (exit code 1).
./build.sh  7.02s user 0.27s system 104% cpu 6.995 total
```

**Comment by sverbist** [comment]
Managed getting it working by following https://github.com/OmniSharp/omnisharp-roslyn/issues/1202#issuecomment-421543905 without the change on build.cake#L51 because that's not there (anymore?)
I should've just read it to begin with, but hopefully this will help others that missed it also

**Comment by eruizc-dev** [comment]
Just failed to me in Manjaro with same output

**Comment by filipw** [comment]
you can disable the git version task as a workaround
