### ISSUE TITLE
Any way to use .net 3.5 framework

### ISSUE THREAD

**Issue by jsyx1994** [OmniSharp/omnisharp-roslyn#1931]
my project need an old version of .net framework (3.5). I am using VS code for my IDE, is there any way to use omniSharp with .net 3.5 frame work?

the omnisharp log says:
"Error: The primary reference "NSubstitute" could not be resolved because it has an indirect dependency on the framework assembly "System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v3.5,Profile=Unity Subset v3.5". To resolve this problem, either remove the reference "NSubstitute" or retarget your application to a framework version which contains "System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
"

**Comment by filipw** [comment]
Yes - please install global Mono https://www.mono-project.com/download/stable/ and set `"omnisharp.useGlobalMono": "always"` in VS Code settings.
