### ISSUE TITLE
Add support for Inline Parameter Name Hints

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#1932]
This is a new feature in VS 2019 16.8 Preview

![](https://pbs.twimg.com/media/EgTHpxHVoAAtWoQ?format=png&name=small)

It is backed by a (fully internal at the moment) [CSharpInlineParameterNameHintsService](http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/InlineParameterNameHints/CSharpInlineParameterNameHintsService.cs,a407564ee0a64378).

**Comment by filipw** [comment]
while it would be easy to add it to the server side, I am not convinced how useful this will be for the editors. For example VS Code does not currently have any official API to consume this https://github.com/Microsoft/vscode/issues/16221

**Comment by Kingwl** [comment]
Hey folks.

https://github.com/microsoft/vscode/pull/113285 has been merged and seems we could provide the inlineHints now!

**Comment by somedeveloperhappy** [comment]
any updates yet?

**Comment by filipw** [comment]
We have been blocked by this https://github.com/dotnet/roslyn/pull/59941

**Comment by 333fred** [comment]
Now that vscode's API has been finalized (wasn't done until the 1.65 release a week or two ago) and the LSP spec has been finalized (around the same time), we can add support for the feature. Server support is https://github.com/OmniSharp/omnisharp-roslyn/pull/2357, and vscode support is https://github.com/OmniSharp/omnisharp-vscode/pull/5107. See the vscode PR for a couple of screenshots of what this will look like.
