### ISSUE TITLE
extra backslash on markdown hyperlink intellisense

### ISSUE THREAD

**Issue by devel0** [OmniSharp/omnisharp-roslyn#1938]
repro:

```cs
/// <summary>
/// enumerate given items returning a tuple (item,next,isLast) with next=null for last element or next=first if repeatFirstAtEnd=true on latest el
/// </summary>                
/// <param name="repeatFirstAtEnd">last enumerated result will (last,first,true)</param>        
/// <remarks>
/// [unit test](https://github.com/devel0/netcore-util/tree/master/test/Enumerable/EnumerableTest_0001.cs)
/// </remarks>
public static IEnumerable<(T item, T next, bool isLast)> WithNext<T>(this IEnumerable<T> en, bool repeatFirstAtEnd = false) where T : class
{
}
```

with intellisense I got follow

![image](https://user-images.githubusercontent.com/13405008/92995338-0244ed00-f503-11ea-9666-6189aff695c3.png)

but this is the markdown I used

```
[unit test](https://github.com/devel0/netcore-util/tree/master/test/Enumerable/EnumerableTest_0001.cs)
```

Note: the produced link <a href="https://github.com/devel0/netcore-util/tree/master/test/Enumerable/EnumerableTest_0001.cs/">unit test</a> works but the ending slash I think is an addiction that with some web server could generate a directory not found.

**Comment by 333fred** [comment]
C# documentation comments are not markdown. We escape any markdown sigils in said comments. This is expected behavior.

**Comment by devel0** [comment]
Thanks for the explanation, but I'm unsure about it, you said that any sigils in the markdown are escaped but from what I see:

```
[DESC](URL)
```

produces in the vscode intellisense ballon

```
[DESC](URL\)
```

so only ending ) are escaped while the other ```(``` still unescaped; observed that I tought that slash may coming from a unexpected directory char separator ( windows style ) appended to the url and I reported for further investigation.
Btw, with actual implementation it works due to the fact that destination web server ( github ) automatically manage that extra slash detecting its a file, not a directory.

Initially in the comment documentation, I tried to use ```<a href="xxx">linktext</a>``` that works for the DocFx generated documentation but not for the vscode intellisense ballon text.

**Comment by 333fred** [comment]
All of them are actually getting escaped, it's just that vscode's rendering is interpreting the trailing \ as part of the url, not as an escape character. https://github.com/OmniSharp/omnisharp-roslyn/blob/96aec1d27209a4db238a6831f29745f1bc349c78/src/OmniSharp.Roslyn.CSharp/Helpers/MarkdownHelpers.cs#L14 is the escape code. I'm somewhat surprised that vscode's rendering doesn't display the a tag correctly though, I would have expected that to work.

**Comment by devel0** [comment]
thanks for the precise clarification referring also in the code, for me it's enough: generated hyperlink from vscode balloon even misrendered still works for the purpose.
I prevent to open an issue for this feedback on vscode because of low impact and stll there 5k+ opened issues atm.
