### ISSUE TITLE
Embedded regex language provider support does not seem to escape regex constructs correctly

### ISSUE THREAD

**Issue by webczat** [OmniSharp/omnisharp-roslyn#1949]
Hi, currently using c# extension version 1.23.2 and testing embedded language providers, mainly regex.
If I type that somewhere in code `Regex.Match("test", "");` and try to trigger suggestions in the empty quotes of second argument, I see that the regex provider is triggered. Then, if I try to select some backslash suggestion like `\s`, what I get after pressing enter is just `"\s". However, because the string is non verbatim, it should be escaped as `"\\s"`.

In addition, if I do the same but trigger completion after first typing two backslashes and then select something like `\A`, I get `"\\\A"` instead of just `"\A"`.

I believe it does work in vs proper, so reporting it here.

CC: @333fred

**Comment by JoeRobich** [comment]
> can you move this to omnisharp-roslyn?

@333fred TIL that I can =)
