### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Balroth** [OmniSharp/omnisharp-roslyn#1959]
Hello!

I am a newbie on this kind of stuff, but I will do my best to detail everything on the issue

I have Windows 7, and installed Vim 8, Vim works without issues
I want to use this https://github.com/OmniSharp/omnisharp-vim
I downloaded it, placed it onto 

> C:\Program Files (x86)\Vim\vim82\pack\vendor\start

Whenever I boot Vim and open a .cs file, it gives the "Needs Roslyn Server" so it seems to have worked.
It asks to download&install Roslyn Server
![RoslynInstallation](https://user-images.githubusercontent.com/25630803/94370442-ad0afd00-00f8-11eb-9e6f-1415eeb12987.PNG)
I press Yes
![RoslynError](https://user-images.githubusercontent.com/25630803/94370462-cca22580-00f8-11eb-8838-eaf2fe074406.PNG)

No idea what that means, or how to edit that id variable. Anyway, since omnisharp-roslyn is a dependency of omnisharp-vim (which seems to work fine), I download it, place it on a folder, open the vimrc settings
`let g:OmniSharp_server_path = 'C:\Program Files (x86)\Vim\vim82\pack\vendor\start\omnisharp.win-x64\OmniSharp.exe'`
(Being on start doesn't matter, even when it was on `C:\Program Files (x86)\OmniSharp\omnisharp.win-x64\OmniSharp.exe` along with the files ofc, it had the same result)
And I get this when I open a .cs file with it
![RoslynDetected](https://user-images.githubusercontent.com/25630803/94370507-1e4ab000-00f9-11eb-9636-2c8c634324ab.PNG)

Since the release version has failed me, I go clone the omnisharp-roslyn, and try to build it.
Downloaded the .NET dependency it asked for Windows.
I ran build.sh, and...
It downloaded NuGet packages but then the below picture happens when I click it again
There is a folder of .omnisharp on home directory but it is empty (no hidden files)
![Build Failure](https://user-images.githubusercontent.com/25630803/94370565-7da8c000-00f9-11eb-8d3a-995f30b3b197.PNG)

=====

I sadly do not know if this is a bug or I am missing something, I report this nonetheless since I am truly looking forward to using omnisharp-vim

**Comment by nickspoons** [comment]
This is an OmniSharp-vim issue, please open it [there](https://github.com/OmniSharp/omnisharp-vim/issues) and I'll try to help you out.

**Comment by Balroth** [comment]
I did not know if I should post it here or there, I did copy-paste it there as you said, thanks for notifying me I posted it on the wrong place :+1:

**Comment by filipw** [comment]
thanks. please note that Windows 7 is not supported anymore too
