### ISSUE TITLE
intellisense performance poor in Omnisharp 1.37.2

### ISSUE THREAD

**Issue by devhawk** [OmniSharp/omnisharp-roslyn#1982]
VSCode on my machine updated to Omnisharp 1.37.2 this afternoon. Intellisense performance has fallen off a cliff. Operations that were instant before are now taking upwards of 10 seconds, making intellisense shortcuts basically unusable. 

is there some type of log I can capture to assist in debugging?

**Comment by filipw** [comment]
did you upgrade from 1.37.1 to 1.37.2 or from some other version? there were no major changes to completion in 1.37.2.

you can set `omnisharp.loglevel: "debug"` in settings and capture the log from omnisharp log panel but it doesn't contain any timings. it would be best if you could share the affected project - is this on every project type that you experience this or just on a specific one?

**Comment by devhawk** [comment]
I didn't manually upgrade, I just noticed that the vscode extension was updating omnisharp, so I'm not sure what version it was upgrading from. 

I'm only working on one project right now, I can check other projects tomorrow. This is the project / branch that I noticed the issue: https://github.com/neo-project/neo-express/tree/devhawk/nxp

**Comment by filipw** [comment]
thanks, you are right, I can repro this using the project you link on a Mac (on Windows it performs very good).

@JoeRobich @333fred any ideas?
for example on this line https://github.com/neo-project/neo-express/blob/master/src/neo-express/BlockchainOperations.cs#L38 typing `wallets.` and then pressing `cmd+space`, it takes forever for the completion list to be populated. this happens with import completions switched off too

**Comment by filipw** [comment]
actually you are right. 

looks like it was regressed by https://github.com/OmniSharp/omnisharp-roslyn/pull/1962

Switching to `"omnisharp.path": "1.37.2-beta.105"` still has good performance, and there is only https://github.com/OmniSharp/omnisharp-roslyn/pull/1970 (which is LSP specific so not related) and https://github.com/OmniSharp/omnisharp-roslyn/pull/1962 between `1.37.2-beta.105` and `1.37.2`.

**Comment by filipw** [comment]
1.37.2-beta.105
![completion-good](https://user-images.githubusercontent.com/1710369/95875999-e8e9c780-0d72-11eb-877a-e09d5ad5a63d.gif)


1.37.2
![completion-bad](https://user-images.githubusercontent.com/1710369/95876020-ed15e500-0d72-11eb-8937-efd63cad75c0.gif)

**Comment by 333fred** [comment]
Are you sure you mean #1962? Did we already do a release with that in it?

**Comment by jannickj** [comment]
I am seeing the same :(

**Comment by filipw** [comment]
it looks like the regression is on codecheck which then impacts the completion
I believe this issue, https://github.com/OmniSharp/omnisharp-vscode/issues/4111 and https://github.com/OmniSharp/omnisharp-roslyn/issues/1983 all have the same root cause

**Comment by 333fred** [comment]
@filipw I can do a targeted revert tonight: I'll bring the old caching behavior back, and make the fixall service not depend on the analyzer diagnostic worker for diagnostics in a different way. However, this implies that completion itself may have bugs where it's not using up-to-date semantic info. I'm not sure how that would manifest exactly, but there's likely something.

**Comment by filipw** [comment]
thank you! we need to invest in performance testing 😩
