### ISSUE TITLE
Provide an easily viewable downloadable list of versions

### ISSUE THREAD

**Issue by VizorKit** [OmniSharp/omnisharp-roslyn#1996]
The documentation lists the below url
`https://roslynomnisharp.blob.core.windows.net/releases/{version}/{packagename}-{os/arch}.{ext}`

I have no idea what the latest version is, what the package name is. The ext and os/arch are listed, so that is relatively easy to surmise.

Is it possible to provide the list of packages in easily digestible format?
I attempted a few combinations of these url's to see if there was some sort of file browser, but there is not.

`https://roslynomnisharp.blob.core.windows.net`
`https://roslynomnisharp.blob.core.windows.net/releases`

**Comment by VizorKit** [comment]
Okay. right after I posted, i found this.
https://github.com/OmniSharp/omnisharp-roslyn/releases

Could you update your documentation to include this as the source of download?

**Comment by filipw** [comment]
I updated the docs today
