### ISSUE TITLE
Unable to use C# 9 in a script project

### ISSUE THREAD

**Issue by germanftorres** [OmniSharp/omnisharp-roslyn#2003]
Hi!,

I'm trying to use the 'records' feature and others latest additions of C# 9 in a script project, but OmniSharp seems to be configured with `LanguageVersion.CSharp8` hardcoded in `ScriptProjectProvider` and complaints about the feature not being available in C# 8.

https://github.com/OmniSharp/omnisharp-roslyn/blob/93d280728820892c2b83caef19c94b14b98297f7/src/OmniSharp.Script/ScriptProjectProvider.cs#L46

Not sure if this value can be updated to `CSharp9` or `Latest` without breaking existing projects. Any chance this may be configured throught `omnisharp.json` in it's script section?

Thanks!!

Germán

**Comment by filipw** [comment]
I already changed it earlier today https://github.com/OmniSharp/omnisharp-roslyn/pull/2001

**Comment by germanftorres** [comment]
Great! 👍
