### ISSUE TITLE
Read `Directory.Packages.props` file's config

### ISSUE THREAD

**Issue by VahidN** [OmniSharp/omnisharp-roslyn#2033]
If I add a `Directory.Packages.props` file to the root folder of the project, with for instance `Nullable` set to `enabled`:
```xml
<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```
The C# compiler (`dotnet built` command) uses it and produces the related errors and warnings for all of the sub-projects of the current solution. But the `omnisharp-roslyn` and its VSCode extension won't. It doesn't show anything in the VSCode.

**Comment by filipw** [comment]
The file should be called `Directory.Build.props` (e.g. https://github.com/OmniSharp/omnisharp-roslyn/blob/master/Directory.Build.props). `Directory.Packages.props` is for package management only.
