### ISSUE TITLE
[Question] Config file in .vscode

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-roslyn#2059]
I'm a little unclear about the name (omnisharp.json and config.json) and location of the config file. Also there are two projects, there's this one and the c# extension for vscode.

In vscode there's a canonical directory in which all config is stored: `project/.vscode`. I hoped the omnisharp config file could go in there to keep things neat, as is the convention.

But that doesn't work. Is there some trick I need to do to make this work? Or is the filename the issue?

**Comment by filipw** [comment]
Omnisharp is a language server that is independent of VS Code and built without any notion of VS Code. It serves a magnitude of client extensions for various editors, and VS Code happens to be one of its users.

As such configuration of Omnisharp is not coupled to any editor specifics and each editor has its own way of integrating into Omnisharp config.

At the high level, Omnisharp has hierarchical configuration options which are [documented here](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options). These consist of startup arguments, environment variable, local omnisharp.json file and a global omnisharp.json file. As an editor extension user you can then use some of these to feed config into Omnisharp bypassing the editor or you could rely on the editor's mapping of some of its own config settings to Omnisharp settings (those are typically passed in by the extensions as startup args). e.g. VS Code C# extension has a setting [to enable analyzers](https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L802) which just maps to Omnisharp configuration setting.

If you have any special C# extension for VS Code wishes please open an issue in [its repo](https://github.com/OmniSharp/omnisharp-vscode) inatead. Hope this helps.

**Comment by lonix1** [comment]
@filipw Thanks for the detailed explanation!

I'm glad my use case is possible... so I'll follow up in the other repo as you recommended.
