### ISSUE TITLE
Razor analyzer doesn't seem to work in the latest release (1.37.5)

### ISSUE THREAD

**Issue by arthrp** [OmniSharp/omnisharp-roslyn#2062]
I keep getting the following error:
```Unhandled exception. OmniSharp.Extensions.JsonRpc.Server.MethodNotSupportedException: Method not found: 'razor/serverReady'```

Then it keeps trying to restart several times and after that you get:
```Connection to server got closed. Server will not be restarted.```

**Comment by filipw** [comment]
cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg is taking a look to see if we can repro on our end

**Comment by ryanbrandenburg** [comment]
@arthrp this did not reproduce for me. Looking at the message though I wonder if this isn't an older version of the extension which has acquired the latest O# version. If you're not on the latest C# extension (1.23.8) could you update and see if it still happens?

**Comment by arthrp** [comment]
Thanks, I updated C# extension from MS to 1.23.8 and disabled C# extension from _muhammad-sammy_ - then the error disappeared.
