### ISSUE TITLE
bin/mono: No such file or directory on server start

### ISSUE THREAD

**Issue by oakular** [OmniSharp/omnisharp-roslyn#2063]
OS: Nix OS 20.09
Release: v1.37.5

When starting the Linux x64 server, the call to `bin/mono` in the Omnisharp directory fails with this message:
`./run: line 27: /home/cal/Omnisharp/bin/mono: No such file or directory`

This occurs if I start the server manually, or through lsp-mode in Emacs.

**Comment by oakular** [comment]
I am closing this as I found the fix for it [here](https://github.com/NixOS/nixpkgs/pull/57205).

**Comment by ibraheemdev** [comment]
@oakular How did you solve the issue? I am facing the same error,
