### ISSUE TITLE
Trigger characters for signatureHelp are wrong

### ISSUE THREAD

**Issue by genericptr** [OmniSharp/omnisharp-roslyn#2071]
I'm trying to use omnisharp from Sublime Text and we have discovered that the trigger characters which are registered are simply wrong. At the very least they must contain `(`. omnisharp works in VSCode but that appears to be because their client manually triggers signatureHelp with the correct characters for C#, namely `(` .

https://github.com/OmniSharp/omnisharp-roslyn/blob/db948600c7fef3ff462782fdee3a1f8ffde52a41/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpSignatureHelpHandler.cs#L23

**Comment by rwols** [comment]
Gentle ping @david-driscoll, you seem to have last modified this line in 9539e299d6665b4cd0eb3c8ee1d0df1691df1bf4.

Is there any special logic in the vscode client that causes omnisharp to show signature help when an opening parenthesis is typed?

**Comment by rwols** [comment]
It looks like signature help isn't implemented at all. Because changing those triggers to `(` and `,` will show raw XML docs, which should be translated to Markdown.

**Comment by insidewhy** [comment]
@rwols signature help is implemented, it works fine in neovim, but I had to override the `signature_help_trigger_characters` to `"(", ",", "<"` via my plugin.

**Comment by rwols** [comment]
@insidewhy omnisharp will still render the signature help docs as raw unformatted XML.

**Comment by insidewhy** [comment]
@rwols I don't know what to say, but it's working perfectly in neovim after this fix. I'm not seeing any raw unformatted XML, everything is looking great.

**Comment by insidewhy** [comment]
> At the very least they must contain `(`. 

@genericptr It must also contain `,` or you won't get signature help for anything but the first argument. Typescript language server will also give signature help for generics, so there `<` should also be provided, but I'm not sure if omnisharp can support that yet (but it doesn't hurt to include it).

**Comment by rwols** [comment]
@filipw this was resolved by https://github.com/OmniSharp/omnisharp-roslyn/pull/2193

**Comment by filipw** [comment]
correct thanks
