### ISSUE TITLE
When starting omnisharp with -lsp flag, everything works fine, except goto definition

### ISSUE THREAD

**Issue by cas1no** [OmniSharp/omnisharp-roslyn#2080]
Is it a bug or defined behavior?

**Comment by filipw** [comment]
Please provide some log information, repro steps, sample project reproducing the problem etc. Thanks.

**Comment by cas1no** [comment]
I found why there is a problem, so my question is, can I somehow get the metadata from omnisharp in lsp mode?

**Comment by razzmatazz** [comment]
@cas1no I have a PR that enables handling go-to-definition in LSP that is pending review/merge:
- https://github.com/OmniSharp/omnisharp-roslyn/pull/2079

The PR allows for omnisharp to return special URIs to code that is present in metadata. This special URI needs to be handled by LSP handler so it can retrieve the code by invoking `o#/metadata` (`emacs-lsp` implementation is here: https://github.com/emacs-lsp/lsp-mode/pull/2573/).

In addition https://github.com/OmniSharp/csharp-language-server-protocol/ needs to be updated to the latest (non-released) version `0.19.0-beta.5` as at the moment the current omnisharp releases crashes when invoking `o#/metadata` (see https://github.com/OmniSharp/csharp-language-server-protocol/pull/488).

**Comment by filipw** [comment]
it is as described by @razzmatazz Additionally this handles decompilation as discussed in the PR
closing this issue
