### ISSUE TITLE
Scripts not working on MacOS

### ISSUE THREAD

**Issue by georgefst** [OmniSharp/omnisharp-roslyn#2081]
MacOS Big Sur. I have a file `Hello.csx`:

```csx
Console.WriteLine("hello");
```

No useful feedback in the editor beyond syntax highlighting (e.g. even if I introduce trivial syntax errors). No warnings to tell me that setup failed for any reason. Nothing interesting in the log, AFAICT.

EDIT: This is in VScode. I meant to open this in the VScode-specific repo. Although I haven't quite sussed how all these projects relate - I'm very new to the C# ecosystem.

**Comment by filipw** [comment]
Please post the Omnisharp log, thanks.

**Comment by georgefst** [comment]
So, the log was full of messages about my other C# project. So I thought, right, I'll remove that folder from the workspace. But once I did so, everything started working with the script file.

Does Omnisharp aim to support working on multiple projects simultaneously?

**Comment by filipw** [comment]
Scripting project system runs parallel to MSBuild project system, so it should work. Perhaps the other project crashed OmniSharp though?

If you have a repro of the issue, it would be helpful - thanks.

**Comment by georgefst** [comment]
Thanks. It's a Unity game in a private repo - I'll try to create something more minimal.

**Comment by filipw** [comment]
I will close this due to lack of activity.
