### ISSUE TITLE
Release builds for ARM32 + arm64 linux distributions

### ISSUE THREAD

**Issue by shaunawins** [OmniSharp/omnisharp-roslyn#2084]
Would it be possible to get builds for Linux on ARM32 and ARM64? I've recently discovered that Omnisharp VIM functions on Termux in mono mode on Android devices, but I want to be developing using dotnet core, not mono.... and as there are no dotnet core builds for Termux, I've moved on to running a proot Debian install inside Termux, but I now require a Linux ARM64 build of Omnisharp in order to get Omnisharp VIM working. 

It would also be cool to get it working on 32 bit phones and Android TVs.

**Comment by nickspoons** [comment]
@shaunawins relevant PR (on hold): https://github.com/OmniSharp/omnisharp-roslyn/pull/1706

**Comment by shaunawins** [comment]
Thank you! I'm sad that it's on hold... kinda tempted to try building it on my own, but I have basically 0 faith in my ability to successfully do so.

**Comment by Zaneris** [comment]
Definitely needs more priority with the Pi400 being a thing now, it'd be nice to be able to work with .NET on them.

**Comment by shaunawins** [comment]
> Definitely needs more priority with the Pi400 being a thing now, it'd be nice to be able to work with .NET on them.

Could you maybe update issue #1706 with this same comment so they know there's some demand for such a build?

**Comment by razzmatazz** [comment]
It is probably not the definite solution in place of an arm build but in most cases you can run this server on arm/raspberry PIs by side-loading mono from distro packages.

[This comment](https://github.com/OmniSharp/omnisharp-roslyn/issues/2124#issuecomment-811889623) by @lafleurh says that it works for him

**Comment by lafleurh** [comment]
It works but you have to create your own "run" shell script. See my [comment on 2124](https://github.com/OmniSharp/omnisharp-roslyn/issues/2124#issuecomment-811889623)

**Comment by shaunawins** [comment]
> It works but you have to create your own "run" shell script. See my [comment on 2124](https://github.com/OmniSharp/omnisharp-roslyn/issues/2124#issuecomment-811889623)

Maybe I'm missing something as I haven't had my normal coffee dose, but your comment appears to apply to mono, not dotnet core... did you manage to get it working for dotnet core on android?

**Comment by lafleurh** [comment]
Yes, mono. I haven't tried it since .Net 6. .Net core 3.1 did not run on Android (or at least I couldn't figure out how, even tried compiling)

**Comment by filipw** [comment]
We now have arm64 Mono builds and arm64 .NET 6 builds.
