### ISSUE TITLE
nvim-lsp + .editorconfig

### ISSUE THREAD

**Issue by alxcnt** [OmniSharp/omnisharp-roslyn#2087]
Would you mind explaining how to tell Omnisharp to respect the .editorconfig using nvim-lsp client?

I currently register the server as follows in my _init.vim_:

:lua << EOF
        local pid = vim.fn.getpid()
        local omnisharp_bin = [path_here]
        require'lspconfig'.omnisharp.setup{
        on_attach=require'completion'.on_attach;
        cmd = { omnisharp_bin, "--languageserver" , "--hostPID", tostring(pid) };
        }
EOF

Is there a way to globally enable it for all clients? Thanks!

**Comment by nickspoons** [comment]
Create a ~/.omnisharp/omnisharp.json file containing the following:

```json
{
   "FormattingOptions": {
      "EnableEditorConfigSupport": true
   }
}
```

See https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#formatting-options

**Comment by alxcnt** [comment]
Awesome, thank you so much!
