### ISSUE TITLE
omnisharp-osx.zip package should use a more recent version of mono

### ISSUE THREAD

**Issue by svermeulen** [OmniSharp/omnisharp-roslyn#2093]
At least for me, on macOS Catalina 10.15.7, the current distributed release zip `omnisharp-osx.zip` fails to work for many solution types (eg. Unity-generated ones) due to the following error:

```
OmniSharp.MSBuild.ProjectLoader: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```

Upon googling this problem I found the fix was to use a more recent version of mono.  I then tried changing the `run` script distributed inside `omnisharp-osx.zip` to use my system mono (which is version `6.12.0.107`) and this resolved the problem for me. So I think it would help others to update the pre-packaged mono version

**Comment by filipw** [comment]
This is not a problem of having an outdated version. OmniSharp's embedded Mono is also 6.12, however it doesn't ship with reference assemblies for Desktop .NET because we omit them intentionally. 

The solution is to have a global Mono installed on your machine and configure the editor to launch OmniSharp with global Mono e.g. by using `"omnisharp.useGlobalMono": "always"` setting when you use VS Code.

I wonder why you use see such error, because in the latest release it was changed to be more helpful:

```
This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. 'omnisharp.useGlobalMono':'always' in C# Extension for VS Code).
```

https://github.com/OmniSharp/omnisharp-roslyn/pull/2069

**Comment by filipw** [comment]
> wonder why you use see such error, because in the latest release it was changed to be more helpful:

ah I see now, we didn't ship this yet, it will be included in the next release

**Comment by svermeulen** [comment]
Ok great.  How do I set this value when not using vs code?  I tried the following inside `~/.omnisharp/omnisharp.json` but did not work:

```
{
  "omnisharp.useGlobalMono": "always"
}
```

**Comment by filipw** [comment]
you have to set 

```
{
  "omnisharp.useGlobalMono": "always"
}
```

and then the omnisharp executable has to be started using mono from your PATH e.g. `mono Omnisharp.exe`. The run script only runs the embedded Mono.

**Comment by svermeulen** [comment]
Gotcha.  I will continue to just hand-edit the omnisharp run script in that case.

**Comment by Zammy** [comment]
Windows 10. After installing .NET sdk and laterst Mono I still get the same error.
