### ISSUE TITLE
Support goto definition for things that don't exist in source

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-roslyn#21]
Similar to how visual studio shows definitions from metadata instead of source

**Comment by david-driscoll** [comment]
This is in, a little hacky at times, so it will require improvement in the future, but closing for now.

**Comment by anfomin** [comment]
Any plans to implement "Go to definition" to display metadata?

**Comment by david-driscoll** [comment]
We have support for it in atom.  Sometimes it works other times it doesn't, we reflect into Roslyn and make some calls to private and internal classes to make it work.

Vscode doesn't yet have support for it though.

**Comment by anfomin** [comment]
@davidfowl is there any plans/dates to implement this feature in VS Code?
