### ISSUE TITLE
Trouble to connect with unity

### ISSUE THREAD

**Issue by VidsSkids** [OmniSharp/omnisharp-roslyn#2109]
I download and setup unity properly. After i want to use vs code to code in c# for unity and begin ton link them. All work properly exept the font prediction and i saw in my OUTPUT terminal this issue : 
Starting OmniSharp server at 06/03/2021 à 21:03:42
    Target: d:\Unity code\Projet\Test\Test.sln

[ERROR] Error: spawn cmd ENOENT
I try every solution i found on the net (as known as add C/Window/System32 in your path value but did not change) so i need help

**Comment by filipw** [comment]
This is OmniSharp server repo, of you have a problem with C# extension please open an issue here https://github.com/OmniSharp/omnisharp-vscode and provide the necessary details (OmniSharp log, repro steps and so on). Thanks.
