### ISSUE TITLE
String interpolation broken 

### ISSUE THREAD

**Issue by afcruzs** [OmniSharp/omnisharp-roslyn#2110]
I'm on v1.23.9 of the C# extension for vscode. And string interpolation shows everything as as string, I'm expecting the stuff part of `"{stuff}"` to be showed a different color.

![image](https://user-images.githubusercontent.com/4340932/110232758-a1580980-7ed4-11eb-8a51-61c439e41214.png)

**Comment by filipw** [comment]
This is OmniSharp server repo, of you have a problem with C# extension please open an issue here https://github.com/OmniSharp/omnisharp-vscode and provide the necessary details (OmniSharp log, repro steps and so on). Thanks.
