### ISSUE TITLE
On mono, omnisharp-roslyn should kill the DTH process on exit

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#212]
Because of [this](https://github.com/aspnet/dnx/commit/c2cee49b6ee98c811d3343b45d57b71886283e92), the DTH process isn't being terminated.

![dth process](https://cloud.githubusercontent.com/assets/667194/7531124/d896c534-f54c-11e4-9359-1c15b513b3d9.gif)

We should kill DTH on application exit.

**Comment by jrieken** [comment]
hm, shouldn't it die by its parent being dead?

**Comment by nosami** [comment]
Ideally, yes.... but it doesn't on mono right now. See the link I referenced.

**Comment by davidfowl** [comment]
Hmmmm. We do some crazy stuff to try and make this work https://github.com/OmniSharp/omnisharp-roslyn/blob/db74baa796e2dd65c1fd2751c601a02f91617a87/src/OmniSharp/Utilities/ProcessExtensions.cs#L40

**Comment by nosami** [comment]
I just tried this with VSCode. Same result.

**Comment by jrieken** [comment]
:scream:

**Comment by troydai** [comment]
We've moved to dotnet-cli base. DTH is retired.
