### ISSUE TITLE
CSX projects aren't send out with project events

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#215]
There is something missing here: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Roslyn/ProjectEventForwarder.cs#L76

**Comment by jrieken** [comment]
@filipw - Do also want this one?

**Comment by filipw** [comment]
yes you can assign all such things to me :)

**Comment by jrieken** [comment]
:dancers:

**Comment by filipw** [comment]
This was fixed a while ago - see https://github.com/OmniSharp/omnisharp-roslyn/blob/c786717208d4167fc584d12bce4a6b3099cb09ae/src/OmniSharp.Script/ScriptProjectSystem.cs#L233
