### ISSUE TITLE
Disable warning for methods based on attribute

### ISSUE THREAD

**Issue by marcospgp** [OmniSharp/omnisharp-roslyn#2156]
I'd like to disable warning IDE0051 for all methods with the `[PunRPC]` attribute, like so:

![image](https://user-images.githubusercontent.com/3464445/118867552-1edbc500-b8db-11eb-9940-9ca47f992db6.png)

Is there a way to do this in the omnisharp settings?

Thank you!

**Comment by 333fred** [comment]
There is not, no. You can make a `DiagnosticSuppressor` (similar to making analyzer) that could do such a thing. But this isn't something OmniSharp can control.

**Comment by marcospgp** [comment]
@333fred do you have any references on how I could go about writing such a thing? Thanks!

**Comment by 333fred** [comment]
@mavasani do we have documentation on DiagnosticSuppressors anywhere?

**Comment by filipw** [comment]
The support for suppressors in OmniSharp was merged here https://github.com/OmniSharp/omnisharp-roslyn/pull/2182
The PR contains a super basic suppressor example too.

I will close this PR because there is nothing left for OmniSharp to do here - thanks
