### ISSUE TITLE
Error Install DotNetCoreSdk

### ISSUE THREAD

**Issue by Johan-Palacios** [OmniSharp/omnisharp-roslyn#2199]
OS: WSL1 Ubuntu

The Error when I execute `./build.sh`
![image](https://user-images.githubusercontent.com/77251405/127238031-234d5491-4fdf-41a0-a385-e180e9a24db4.png)

And I have Dotnet Installed in my PC

![image](https://user-images.githubusercontent.com/77251405/127238370-73b0ccc1-00d9-4222-88e5-242e50710990.png)

Can you give me a solution for this?

**Comment by filipw** [comment]
The build script installs a local SDK on its own regardless of your global installation.
Judging by the error, either the network on your machine was unreachable at the time, or there was some downtime or other issue on the official SDK feed.

**Comment by filipw** [comment]
see https://github.com/dotnet/announcements/issues/192#event-5076853675
