### ISSUE TITLE
Expose k commands

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#22]
We need a new endpoint that can list the available k commands that can be ran from an editor.

**Comment by jrieken** [comment]
@davidfowl - Already an idea how to approach this? Monaco is showing some interest here as well ;-)

**Comment by davidfowl** [comment]
Yes, I do :smile: . We need a new end point the project information. The question is, should we make it general so that it can support both project types, or should we have a project.json one and an msbuild one?

**Comment by davidfowl** [comment]
I've added a /projects endpoint that should surface project information (for both project types).

**Comment by davidfowl** [comment]
Fixed in https://github.com/OmniSharp/omnisharp-roslyn/commit/fb5d2f177a48abca375ba86133953ed09246d271

**Comment by jrieken** [comment]
Thanks!
