### ISSUE TITLE
How to run omnisharp-like analysis via command line for CI purposes ?

### ISSUE THREAD

**Issue by sakshamsaxena** [OmniSharp/omnisharp-roslyn#2200]
Hello,

Needed some suggestions as to how to use omnisharp like analysis on a .NET 5 project but triggered via command line (mac/linux) that would show Errors, Warnings, and Suggestions just like it shows in VSCode etc. This would actually help immensely in my CI system to detect such issues for PRs and commits.

Thanks

**Comment by filipw** [comment]
OmniSharp is a language server. If you would like to perform code analysis, you should use the libraries provided by the Roslyn compiler directly. You can find more help and documentation at https://github.com/dotnet/roslyn
