### ISSUE TITLE
Omisharp server not running

### ISSUE THREAD

**Issue by Pulsefirejr** [OmniSharp/omnisharp-roslyn#2229]
![image](https://user-images.githubusercontent.com/73306068/132116367-a6d2eb5d-5d6d-4977-98c6-a757b8c37afa.png)

**Comment by Pulsefirejr** [comment]
![](https://user-images.githubusercontent.com/73306068/132116367-a6d2eb5d-5d6d-4977-98c6-a757b8c37afa.png)

**Comment by filipw** [comment]
please open an issue in https://github.com/OmniSharp/omnisharp-vscode and post the extension logs too

This is the server repository, the assets are generated by the extension.
