### ISSUE TITLE
Analyzing projects is extremely slow compared to MSBuild or Visual Studio

### ISSUE THREAD

**Issue by DavidZidar** [OmniSharp/omnisharp-roslyn#2241]
I am working on a .NET Framework-project where a full build using all .NET 5 SDK analyzers takes about 40 seconds, Visual Studio can analyze the project in a similar amount of time.

OmniSharp on the other hand can analyze for hours on end and use many gigabytes of RAM. In fact, it never gets done because as I work things change so one CPU core is running hot all day long. I just had to kill the OmniSharp process because it was using 21 GB of RAM.

I have noticed this performance difference in other projects too, even in pure .NET Core projects. This has been the status quo for years.

So there seems to be a fundamental difference in how analysis is done in OmniSharp vs regular Roslyn since there is at least an order of magnitude or more difference in speed.

Would it be possible to involve Microsoft to get this properly fixed once and for all?

**Comment by DavidZidar** [comment]
A year or two ago I tried to do some performance tracing with dotTrace but I didn't really know what to look for. I remember could see that it was the analyzers back then too. It must be possible to run them more efficiently somehow. Maybe Microsoft developers from the Roslyn project can help? They should be interested in making C# development experience great even in VS Code.

**Comment by kieranbenton** [comment]
Just to illustrate the problem - this is a screengrab from btop. I've just restarted VSCode about 10 minutes ago - and after a period of multicore usage (which would be fine) the usage settles down into mono alone continuously pegging at least one core to 100%.

![image](https://user-images.githubusercontent.com/39090/136248997-e713757c-dc52-477f-b5fa-69c3660645ae.png)

Its this behaviour that then basically never goes away.

Running ```strace -p <monopid>``` results in obviously a huge amount of output - but from my untrained eye, it looks like the same sequence is just being repeated over and over with little variation:

```
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn({mask=[]})                 = 202
futex(0x564fd31dd608, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigprocmask(SIG_BLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigsuspend(~[RTMIN RT_1 RT_4], 8)    = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGRT_4 {si_signo=SIGRT_4, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigreturn({mask=~[KILL STOP RTMIN RT_1]}) = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_UNBLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn({mask=[]})                 = 202
futex(0x564fd31dd608, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigprocmask(SIG_BLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigsuspend(~[RTMIN RT_1 RT_4], 8)    = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGRT_4 {si_signo=SIGRT_4, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigreturn({mask=~[KILL STOP RTMIN RT_1]}) = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_UNBLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn({mask=[]})                 = 202
futex(0x564fd31dd608, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigprocmask(SIG_BLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigsuspend(~[RTMIN RT_1 RT_4], 8)    = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGRT_4 {si_signo=SIGRT_4, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigreturn({mask=~[KILL STOP RTMIN RT_1]}) = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_UNBLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn({mask=[]})                 = 202
futex(0x564fd31dd608, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigprocmask(SIG_BLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigsuspend(~[RTMIN RT_1 RT_4], 8)    = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGRT_4 {si_signo=SIGRT_4, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigreturn({mask=~[KILL STOP RTMIN RT_1]}) = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_UNBLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn({mask=[]})                 = 202
futex(0x564fd31dd608, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigprocmask(SIG_BLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigsuspend(~[RTMIN RT_1 RT_4], 8)    = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGRT_4 {si_signo=SIGRT_4, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigreturn({mask=~[KILL STOP RTMIN RT_1]}) = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_UNBLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn({mask=[]})                 = 202
futex(0x564fd31dd608, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TKILL, si_pid=11417, si_uid=1000} ---
rt_sigprocmask(SIG_BLOCK, [RT_4], NULL, 8) = 0
futex(0x564fd1b9aa00, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigsuspend(~[RTMIN RT_1 RT_4], 8^Cstrace: Process 11417 detached
```

**Comment by DavidZidar** [comment]
@kieranbenton `feature/omnisharp-vnext` contains several versions of OmniSharp that can be built, I built a `net5.0` one using `.\build.ps1 PublishNet5Builds` which did work on my home project which is .NET 5 but it could not load my ASP.NET project at work so I tried `.\build.ps1 PublishWindowsBuilds` in that same branch which produces a build based on `net472` but that one does not seem to show any improvements either.

**Comment by seesharper** [comment]
@DavidZidar I don't work on this repo, but my guess is that the `vnext` branch is simply an effort to make it work on `net5.0` and that there is still some leftovers from the original branch. That being said, I have also tried this a couple of weeks back and could not really see a big difference in performance.

**Comment by alexrp** [comment]
> Personally I prefer the whole solution to be analyzed, it's all to easy to miss warnings in files that aren't currently open when refactoring code.

Strong agree fwiw. I've always found it very impractical that when I do manual refactoring in VS Code, I have to either force a full reanalysis or do a build to find out what broke. Would love to have a toggle for full solution analysis.

**Comment by TomasEkeli** [comment]
i've made an implementation that seems to work nicely for my machine
https://github.com/TomasEkeli/omnisharp-roslyn/commit/37b2fb0d528e8d52674c562b5d3bb67dcce8bf41

it defaults to using half of the available cores, but allows configuration with a new key in `omnisharp.json`: `RoslynExtensionsOptions.threadsToUseForAnalyzers`

in my testing on a pretty large c# solution (32 projects) it is a lot quicker than it used to be and spins up the number of cores i configure it to.

**Comment by TomasEkeli** [comment]
> Great work @DavidZidar! Definitely the new `Parallel.ForEachAsync` would be a perfect fit for that.
> 
> Out of interest, are you actually interested in analyzers running for the whole solution? I would much prefer if they would just run 'on demand' for the currently opened files. Otherwise even with making those code paths parallel, for a decently sized solution thats going to absolutely clobber multiple cores -> 100% until the whole solution is complete. In some ways only clobbering a single core is actually preferable to me at least... (can't believe I'm saying that).

isn't this analyze-only-open-files what the foreground worker does? https://github.com/OmniSharp/omnisharp-roslyn/pull/1507

if that is correct - then what you are asking for could essentially be an option to turn off the background worker, and just do the foreground analysis?

**Comment by kieranbenton** [comment]
@TomasEkeli yes, that sounds bang on - am I correct in assuming there is no way to turn off the background worker right now? 

My workflow is effectively run a full project analyze once after I add a new analyzer - do any wide ranging cleanup for results I deem important enough to tackle up front, then crank the rest down to informational and fix as I work on individual files as part of other work.

Avoiding the 5 mins of 100% CPU on VSCode startup (even now after the vnext branch has landed - which seems much more stable) would be great.

**Comment by TomasEkeli** [comment]
> @TomasEkeli yes, that sounds bang on - am I correct in assuming there is no way to turn off the background worker right now?
> 
> My workflow is effectively run a full project analyze once after I add a new analyzer - do any wide ranging cleanup for results I deem important enough to tackle up front, then crank the rest down to informational and fix as I work on individual files as part of other work.
> 
> Avoiding the 5 mins of 100% CPU on VSCode startup (even now after the vnext branch has landed - which seems much more stable) would be great.

can i suggest registering a new issue for that? i like the suggestion

**Comment by DaRosenberg** [comment]
I took a stab at this also in #2312, building upon the excellent work by @TomasEkeli in #2285 but with some further improvements.

**Comment by DavidZidar** [comment]
Thanks everyone that worked on this, it will help a lot! But seeing how this issue was closed entirely I have to say it doesn't really solve the underlying problem, OmniSharp is still using several times more processing power to do the same thing that MSBuild and Visual Studio do with much less. Using more cores is a good step on the way though!

**Comment by DavidZidar** [comment]
I'm not sure there is a solution currently, it's just a constant pain.

If only Microsoft could take VS Code seriously and rewrite OmniSharp and use the Roslyn API efficiently in the same way that Visual Studio does, that would be something.

**Comment by TomasEkeli** [comment]
that would be nice, but i doubt they will - the recent hot-reload kerfuffle showed that microsoft are still aiming to make visual-studio the better experience.
