### ISSUE TITLE
Neovim: Omnisharp Go To Definition produces weird path to file

### ISSUE THREAD

**Issue by HiMyNameIsGarch** [OmniSharp/omnisharp-roslyn#2245]
The server is running fine, I get code errors when I type, but when I try to go to definition to one of the build-in methods (ex: ` Console.WritleLine();` ) it redirects me to a blank page. that has the path:
`/$metadata$/Project/Tic-Tac-Toe/Assembly/System/Console/Symbol/System/Console.cs`

**Comment by filipw** [comment]
closing as duplicate
