### ISSUE TITLE
[Bug] User snippets are broken after #2253

### ISSUE THREAD

**Issue by vchirikov** [OmniSharp/omnisharp-roslyn#2254]
- https://github.com/OmniSharp/omnisharp-roslyn/pull/2253 Breaks the user snippet experience.

I have the user snippet:

```json
{
	"ConfigureAwait": {
		"scope": "csharp",
		"prefix": "ca",
		"body": [
			".ConfigureAwait(false);",
		],
		"description": "Adds '.ConfigureAwait(false);'"
	},
}
```

Behavior before `1.37.17-beta.14` (`1.37.17-beta.11`):

![before](https://user-images.githubusercontent.com/40987940/138069657-e789c78b-64f4-446e-b839-e936b05fccd0.gif)

Behavior after `1.37.17-beta.14`:
![after](https://user-images.githubusercontent.com/40987940/138068970-d71c8e01-4f8f-4002-93e8-51277e65d9f3.gif)

cc: @JoeRobich

**Comment by JoeRobich** [comment]
@vchirikov I can't reproduce this behavior. One thing I noticed from your very helpful gifs was that you brought up completion with 'ctrl+space' and in the first working example you dismissed it by pressing 'escape' before typing 'ca'. In the second failing example you didn't dismiss the completion popup. Can you try again on latest with the completion popup dismissed?

The completion that I changed it wholly separate from VS Code and its snippet support. OmniSharp-Roslyn has no impact on when custom VS Code snippets are offered or how they are committed.

**Comment by vchirikov** [comment]
>  in the first working example you dismissed it by pressing 'escape' before typing 'ca'

I'm sorry, yep, looks like my fault, you're right
Sorry for bother you. 🙏
