### ISSUE TITLE
no code actions available using VSCODE

### ISSUE THREAD

**Issue by KitCarson03** [OmniSharp/omnisharp-roslyn#2255]
I'm using vscode with new .net 6 rc1 version but the same issue is present also with .net 5 officiale release.
VSCode doesn't display any available fixes also for simple errors like a missing semicolon at the end of a single line of code like removing it from the default console template project.

here it is the Omnisharp Log:
https://pastebin.com/Bk90SKpG

**Comment by filipw** [comment]
Looking at your logs, it seems that you are affected by the same issue with loading assemblies from remote sources as described here 

https://github.com/OmniSharp/omnisharp-roslyn/issues/1847#issuecomment-653763335

The solution discussed here should help you - there is not much Omnisharp can do here.
