### ISSUE TITLE
Compilation fails for CSharp project with Visual Basic project dependency

### ISSUE THREAD

**Issue by sudsy** [OmniSharp/omnisharp-roslyn#2260]
We have a legacy visual basic project that a number of our CSharp projects depend upon. When using the vscode-omnisharp extension with embedded mono, the compilation fails with the error:

```
OmniSharp server started.
    Path: /root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.16/.omnisharp/1.37.16/run
    PID: 6000

[fail]: OmniSharp.MSBuild.ProjectLoader
        The imported project "/root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.16/.omnisharp/1.37.16/omnisharp/.msbuild/Current/Bin/Roslyn/Microsoft.VisualBasic.Core.targets" was not found.
```
Because or this error, intellisense is broken for the CSharp projects.

If I take the file from https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets

and place it at the path /root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.16/.omnisharp/1.37.16/omnisharp/.msbuild/Current/Bin/Roslyn/Microsoft.VisualBasic.Core.targets

the project compiles and intellisense works in the CSharp project.

Is this something the team would consider fixing or accepting a PR for?

**Comment by filipw** [comment]
That is interesting! Sure.

**Comment by sudsy** [comment]
This issue has been resolved by the new useModernNet option. Fixes a few other issues I was having too. Great Work!
