### ISSUE TITLE
CSX project system should listen file added events

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#227]
I would be cool if the ScriptCS project system listens to additions and deletions of CSX files so that OmniSharp doesn't need to be restarted.

**Comment by nosami** [comment]
Yes!

**Comment by filipw** [comment]
does the client currently notify omnisharp at all about new document creation/deletion?

**Comment by jrieken** [comment]
they should! there is a route ```/filesChanged```

**Comment by jrieken** [comment]
also on windows we could use the native file watcher, see #193

**Comment by nosami** [comment]
We add new cs files to a project without a watcher.

**Comment by jrieken** [comment]
yeah, but only when their path matches the path of another directory. So, as a first step we could add the logic here: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Roslyn/BufferManager.cs. That would make sure new files sort even without file events
