### ISSUE TITLE
cannot customize csharp formatting

### ISSUE THREAD

**Issue by rafaelsanchezsouza** [OmniSharp/omnisharp-roslyn#2277]
Hi!

I have been using alt+shift+f for a while now, for auto formatting my code.
However, the only thing it does is to fix the identation of the document

I did some research and found out that I could customize this formatting by following the instructions in: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options

I created the omnisharp.json both in my project root folder and my .omnisharp folder, however, none of them seems to change the behaviour of the auto formatting

Am I missing something?

Any help would be greatly appreciated
Thanks!

**Comment by 333fred** [comment]
That page seems pretty out of date. You should use an editorconfig to control formatting options, which will apply to both omnisharp and VS: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules. Make sure the editorconfig support is turned on for omnisharp.

![image](https://user-images.githubusercontent.com/2371880/144182643-e3fc6cf1-7e09-45bb-a32d-5163731085cd.png)

**Comment by baoxiehao** [comment]
> That page seems pretty out of date. You should use an editorconfig to control formatting options, which will apply to both omnisharp and VS: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules. Make sure the editorconfig support is turned on for omnisharp.
> 
> ![image](https://user-images.githubusercontent.com/2371880/144182643-e3fc6cf1-7e09-45bb-a32d-5163731085cd.png)

but after enabling the Config Support still not working as what I config in the ~/.omnisharp/omnisharp.json

**Comment by 333fred** [comment]
Don't use omnisharp.json for this. Use an editorconfig file, as shown in the link I sent earlier.

**Comment by baoxiehao** [comment]
> Don't use omnisharp.json for this. Use an editorconfig file, as shown in the link I sent earlier.

but where should I put the .editorconfig? VSCode's settings.json?

**Comment by 333fred** [comment]
> but where should I put the .editorconfig? VSCode's settings.json?

In a `.editorconfig` file.

**Comment by 333fred** [comment]
See also https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022.
