### ISSUE TITLE
AspNet5ProjectSystem should filter 'Sources' message by file extension

### ISSUE THREAD

**Issue by borgdylan** [OmniSharp/omnisharp-roslyn#230]
Could omnisharp ignore requests pertaining to files that do not have a c# extension?

**Comment by jrieken** [comment]
Can you reopen with more detail please? In all cases I know of OmniSharp first looks up the file path from the request in the workspace. If the file doesn't belong to any project a default/empty response is generated, e.g. when requesting formatting of an unknown file: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Api/Formatting/OmnisharpController.Format.cs#L18.

**Comment by borgdylan** [comment]
When in VSCode, if I use a language other than c# in a project.json based project, onnisharp butts in insisting the files are c# even when the extensions say otherwise. This means I get errors/warnings from roslyn when the project should be compiled by the compiler referenced by project.json instead. I have already configured a way to automatically compile using teh other compiler but the errors/warnings from omnisharp are still appearing in the list of issues.

**Comment by borgdylan** [comment]
As far as I know roslyn does not check if a file is in its remit or not.

**Comment by borgdylan** [comment]
If omnisharp ignored requests for files that do not end in .cs or .csx, this problem would not be there.

**Comment by borgdylan** [comment]
@jrieken the issue cannot be reopened

**Comment by jrieken** [comment]
Ok, the problem is OmniSharp taking whatever DTH returns as source as C# files - ignoring DTH being language agnostic. Thanks for clarifying!

**Comment by borgdylan** [comment]
Thanks for understanding. I do hope one day "Omni" will be mean any .NET langauge not just any editor.

**Comment by borgdylan** [comment]
@jrieken will the fix make it in a future release of omnisharp that is bundled in VSCode?

**Comment by jrieken** [comment]
it might not make it into the June release of VSCode, but please stay tuned. wrt DNX vs KRE we are still blocked by a bug in DNX...

**Comment by jrieken** [comment]
PR submitted

**Comment by borgdylan** [comment]
:+1:
