### ISSUE TITLE
javascript code extension, beginscripts doesn't recognize in partials view

### ISSUE THREAD

**Issue by jonatanfelipesiqueira** [OmniSharp/omnisharp-roslyn#2321]
![image](https://user-images.githubusercontent.com/43968142/148578873-f27a3539-d12e-4f81-a45c-a2ff1883fda1.png)

when using code extension to send the javascript from a partial view to the index, the code is not recognized, would this correction be possible? same works in visual studio 2019

in vs 2019

![image](https://user-images.githubusercontent.com/43968142/148579177-ac2fc14d-f688-465c-951f-f397f517f00c.png)

**Comment by filipw** [comment]
Duplicate of https://github.com/dotnet/razor-tooling/issues/5962
