### ISSUE TITLE
VS Code: Using quick actions does not show using directivity.

### ISSUE THREAD

**Issue by v-polly** [OmniSharp/omnisharp-roslyn#2322]
REPRO CONFIGURATION: Win10 x64 ENU 21H1 + Dev17.1 Preview 2
**Latest SDK Version:**6.0.200-preview .21617.4
**Latest Runtime Version:**6.0.1

**INSTALL STEPS:**

1.Clean machine: Win10 x64 ENU 21H1
2.Install VS Community  Dev17.1 P2 [d17.1-32020.100] from PR 370165
3.Install VS Code from: https://code.visualstudio.com/Download
4.Install C# Extensions version: v1.24.0-beta1/csharp-1.24.0-win32-x64.vsix from: https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.24.0-beta1/csharp-1.24.0-win32-x64.vsix

**Testcases Affected**
[SimpleWebAppRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppRazorEditingWithVSCode.md)

**Platform**

- [X]  Windows
- [X]  macOS
- [ ]  Linux

**Repro Steps**

1.Open a normal Terminal Emulator
2.Create mvc project and open it using VS code

```
md mvc
cd mvc
dotnet new mvc
code .
```

3.Go to https://github.com/OmniSharp/omnisharp-vscode/releases > Download the csharp-1.24.0-win32-x64.vsix.
4.In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
5.In VS Code, using CTRL + ~ to open up TERMINAL window, type the following code.

```
'namespace MVC3x // Or Razor3x
{
    public class CustomTagHelper
    {
    }
}' | Out-File CustomTagHelper.cs
```

6.In CustomTagHelper.cs, type ": TagHelper" following the class. And then use Quick Actions (ctrl +.) "No code actions available" is displayed after that.

**Note:**

This issue not repro on the SDK 6.0.200-preview.21573.3/6.0.100
This issue has nothing to do with the version of C# Extensions.

**Actual Result**
Windows:
![image](https://user-images.githubusercontent.com/88425944/149058493-281a4adb-a539-42d5-9c49-9485424c9c36.png)

macOS:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/88425944/151485269-487b9a3c-3328-43d9-8da8-83dd07d7a779.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/88425944/149058541-56d03056-c464-4b4d-a603-bbf1056d9dc3.png)

**Comment by v-sherryfan** [comment]
Closed it as not repro.

**Comment by v-polly** [comment]
closed it as not repro.
