### ISSUE TITLE
Clean up branches on omnisharp-roslyn

### ISSUE THREAD

**Issue by ghost** [OmniSharp/omnisharp-roslyn#233]
It looks like there are a number of stale branches on this repository: 
https://github.com/OmniSharp/omnisharp-roslyn/branches/stale

It wouldn't hurt to remove these branches. Additionally, there's a number of merged pr's whose branches could also be deleted. (https://github.com/OmniSharp/omnisharp-roslyn/branches/active)

**Comment by filipw** [comment]
I will close this issue for now. We have cleaned up 20+ stale branches. The remaining ones are kept for reference purposes for now as we might revisit them
