### ISSUE TITLE
/home/user/emacs.d/.../lsp/server/omnisharp-roslyn/latest/omnisharp-roslyn/bin/mono: no such file or directory

### ISSUE THREAD

**Issue by talvdav** [OmniSharp/omnisharp-roslyn#2331]
i use lsp-mode in emacs (27.2)
lsp-install-server succeeds in installing the server, however, the run script can't find the mono binary.
I checked the path for mono_cmd, permissions etc. i also tried to change it to ~/bin/mono and copied the binary into that folder, i always get the same error message.

Even when in the directory where to mono binary is, the file can't be run. you can use cat, head, type but you can't run it, it always tells you: no such file or directory, i don't know why.

**Comment by talvdav** [comment]
this is a nixos specific error

**Comment by jeslie0** [comment]
Did you find a fix for this?

**Comment by talvdav** [comment]
Hi,

yes, install steam-run and edit the script that runs omnisharp. Just put steam-run infront of it

**Comment by jeslie0** [comment]
Another fix is to set run `(setq lsp-csharp-server-path (executable-find "omnisharp"))`. 

With help from (calc-eval "sqrt(-1)") on the System Crafters discord:
https://discord.com/channels/767406463265538068/767406463265538071/961338653450334208
