### ISSUE TITLE
OmniSharp 1.38.0 doesn't work on CentOS 7 or RHEL 7

### ISSUE THREAD

**Issue by omajid** [OmniSharp/omnisharp-roslyn#2335]
OmniSharp 1.38.0 no longer works on CentOS 7 or  RHEL 7 like previous releases of OmniSharp. It produces an error because the embedded `mono` binary has a dependency on a too-recent version of glibc.

The error looks generally like this:

```
  omnisharp/bin/mono: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by omnisharp/bin/mono)
  omnisharp/bin/mono: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by omnisharp/bin/mono)
```

The last release, 1.37.17 doesn't have this issue.

An `lld` is sufficient to show the problem:

```
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
$ ldd omnisharp-v1.37.17/bin/mono 
        linux-vdso.so.1 =>  (0x00007fffc1361000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f7932ae0000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f79328d8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f79326d4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f79324b8000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f79321b0000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f7931eae000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7931c98000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f79318ca000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7932cf6000)
$ ldd omnisharp-v1.38.0/bin/mono 
omnisharp-v1.38.0/bin/mono: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by omnisharp-v1.38.0/bin/mono)
omnisharp-v1.38.0/bin/mono: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by omnisharp-v1.38.0/bin/mono)
        linux-vdso.so.1 =>  (0x00007ffe77bc5000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f6a4838e000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f6a48186000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f6a47f82000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6a47d66000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f6a47a5e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f6a4775c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6a47546000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f6a47178000)
```

**Comment by filipw** [comment]
The embedded Mono is deprecated and will be removed https://github.com/OmniSharp/omnisharp-roslyn/issues/2339
The recommendation is to move to .NET 6 builds of OmniSharp or to use global Mono.

**Comment by SonGokussj4** [comment]
Can you specify what should I do to make it work?
I'm not sure what to think of "move to .NET 6 build of OmniSharp" - is that a library for Linux or vscode?
Can I downgrade OmniSharp to working version?

**Comment by filipw** [comment]
You need to use the distributions of Omnisharp that are suffixed with net6.0 here https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.38.1 and launch them with `dotnet OmniSharp.dll` using .NET 6 SDK.

How you acquire it differs from editor to editor and is editor extension specific, or you can download it manually of course.

**Comment by z9tree** [comment]
I had this problem with using the C# extension in vscode with the ssh remote extension on rhel7, and I have a hacky fix. So here is a fix that might work for you  - first grab the suggested version of omnisharp with the suffix net6.0 from the above post, then replace the files in 

~/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1/omnisharp/

With the files from the zip, then chmod+x ~/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1/omnisharp/OmniSharp 

then you edit the run script at

~/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1/run

to have the following:

```
#!/usr/bin/env bash

base_dir="$(cd "$(dirname "$0")" && pwd -P)"
bin_dir=${base_dir}/bin
etc_dir=${base_dir}/etc
omnisharp_dir=${base_dir}/omnisharp

#mono_cmd=${bin_dir}/mono
dotnet_cmd=`which dotnet`
mono_cmd="${dotnet_cmd} ${omnisharp_dir}/OmniSharp.dll"
omnisharp_cmd=${omnisharp_dir}/OmniSharp
config_file=${etc_dir}/config

chmod 755 "${mono_cmd}"

no_omnisharp=false

if [ "$1" = "--no-omnisharp" ]; then
    shift
    no_omnisharp=true
fi

export MONO_CFG_DIR=${etc_dir}
export MONO_ENV_OPTIONS="--assembly-loader=strict --config \"${config_file}\""

if [ "$no_omnisharp" = true ]; then
    "${mono_cmd}" "$@"
else
    "${omnisharp_cmd}" "$@"
fi
```

This might not work in all cases but it got intellisense working for my setup of vscode, I would recommend backing up the 1.38.1 directory with these customizations in case vscode automatically upgrades the C# plugin.

**Comment by filipw** [comment]
You should not need to manually edit anything. Setting `"omnisharp.useModerNet": true` should download the correct .NET 6.0 distro of OmniSharp and use dotnet from the path to launch it.

**Comment by filipw** [comment]
I will close this now because there is no more embedded Mono on the main branch.
