### ISSUE TITLE
Error trying to update to 1.38 Nuget package

### ISSUE THREAD

**Issue by OrionRiftStudios** [OmniSharp/omnisharp-roslyn#2341]
Hello!
I am trying to update to the latest version 1.38 but there is an issue with the nuget packages

Error	NU1101	Unable to find package Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp. No packages exist with this id in source(s): nuget.org	

After checking on nuget.org
![image](https://user-images.githubusercontent.com/90126030/152751631-3d4b8d4e-ad5c-4053-b893-d0744241114d.png)

but if you click the nuget package you  will see a not found error page

https://www.nuget.org/packages/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp/

do you know how to fix this issue? 

Thank you

**Comment by filipw** [comment]
This is "by design". OmniSharp requires the Roslyn NuGet feed to be added to your solution

```
<add key="vs-impl" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json" />
```

This time it is this package that fails, but in other situations it could be others as well, because the Roslyn feed usually has newer dependencies than public feed.

**Comment by OrionRiftStudios** [comment]
Thank you for your response 
I added the new feed but I am getting the same error maybe the feed url is wrong?
![image](https://user-images.githubusercontent.com/90126030/152757902-0d82bb43-ba00-4c8a-a1b5-2d4cb8fba3bf.png)

**Comment by filipw** [comment]
Try all the feeds from here https://github.com/OmniSharp/omnisharp-roslyn/blob/master/NuGet.Config 😅

**Comment by OrionRiftStudios** [comment]
this one is working 
 <add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />
thank you
