### ISSUE TITLE
VS Code: Error after creating blazor project: "The name 'routeData' does not exist in the current context." 

### ISSUE THREAD

**Issue by v-sherryfan** [OmniSharp/omnisharp-roslyn#2352]
**REPRO CONFIGURATION:** Win10 x64 ENU 20H2 + SDK 7.0.100-preview.2.22152.5
**Latest SDK Version:** 7.0.100-preview.2.22152.5
**Latest Runtime Version:** 7.0.0-preview.2.22128.3

**INSTALL STEPS​:**
1. Clean machine: Win 10 x64 ENU 20h2
2. Install the sdk 7.0.100-preview.2.22152.5 from: [https://aka.ms/dotnet/7.0.1xx-preview2/daily/dotnet-sdk-win-x64.exe](url)
4. Install VS Code from: [https://code.visualstudio.com/Download](url)
5. Install C# Extensions version: v1.24.1.vsix from: [https://github.com/OmniSharp/omnisharp-vscode/releases](url)

**Testcases Affected**
[SimpleBlazorRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleBlazorRazorEditingWithVSCode.md)

**Platform**
- [x] Windows
- [x] macOS
- [x] Linux

**Repro Steps**
1. Open a normal Terminal Emulator
2. Create blazor project and open it using VS code
```
  md Blazor
  cd Blazor
  dotnet new blazorserver
  code .
```
3. Go to [https://github.com/OmniSharp/omnisharp-vscode/releases](url) > Download the csharp-1.24.1.vsix.
4. In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
5. Navigation to the problems window will encounter a error: "The name 'routeData' does not exist in the current context."

**Note:**
**1. Error will disappear if you open the App.razor file
2. This issue works fine on C# Extensions is v1.24.0.**

**Actual Result**
![image](https://user-images.githubusercontent.com/71361488/156538720-a6c1e54a-6aa6-4a3a-88ad-9f8e5d230b12.png)

**Expected Result**
The problems window does not have error.

**Comment by Cpt-Falcon** [comment]
This is still happening and occurs in visual studio 2022 as well 
![image](https://user-images.githubusercontent.com/10540204/219114080-1d3bc0d4-d1a0-4b79-b792-9307460767b1.png)

**Comment by KSahu997** [comment]
@using Microsoft.AspNetCore.Components.Routing
try including above solved mine

**Comment by wgrs** [comment]
Still happening - is this error being ignored?

**Comment by JoeRobich** [comment]
Balzor/Razor support is implemented in the https://github.com/dotnet/razor repository. Closing this issue as work will be tracked in https://github.com/dotnet/razor/issues/9020
