### ISSUE TITLE
imports don't seem to be sorted

### ISSUE THREAD

**Issue by metta-al** [OmniSharp/omnisharp-roslyn#2356]
current code:
https://github.com/OmniSharp/omnisharp-roslyn/blob/47bebf9eb1d2fd45710ff58640e9aaf96d66f29d/src/OmniSharp.Roslyn.CSharp/Workers/Refactoring/FixUsingsWorker.cs#L56-L58

code when fixusing is first implemented:
https://github.com/OmniSharp/omnisharp-roslyn/blob/eeb76b426c47252f96f2c66b1a88fa0fd3f8b43c/src/OmniSharp/Workers/Refactoring/FixUsings.cs#L31-L34
 
was trying to figure out how to turn on the sorting of imports. couldnt find a flag to turn it on, i found that sort function was left out of the current `fixusing` function, is it implemented elsewhere, and if so, how do we trigger it?

**Comment by filipw** [comment]
It was moved to formatting https://github.com/OmniSharp/omnisharp-roslyn/blob/696cf2159f89a6c9e7bbc296e6eb95e76ac916ac/src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs#L109-L115

when enabled, imports are organized as part of regular code formatting.

**Comment by metta-al** [comment]
thank u very much, i managed to find the corresponding flag :+1:
