### ISSUE TITLE
Signature Help Documentation is the xml and not human-readable

### ISSUE THREAD

**Issue by AnonymusRaccoon** [OmniSharp/omnisharp-roslyn#2372]
The [signature help](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs#L171) uses the xml data and not the summary tag for the documentation of the signature. The specification wants plain text or markdown instead. 

Plain text is already used for parameters documentation, it should be the same everywhere. This issue was already raised during the implementation of Structured [here](https://github.com/OmniSharp/omnisharp-roslyn/pull/1085/files#r161122095), but it was not modified (I don't know why).

I confirmed that [VS Code](https://github.com/OmniSharp/omnisharp-vscode/blob/d1785942e51f3afee1d8e62b406ee46b35168c63/src/features/signatureHelpProvider.ts#L32) is not using the documentation field so changing it would not break their implementation, but I don't know about other editors, so should I PR or not?

For now on editors that don't do a custom thing for Roslyn, this is shown instead:
![image](https://user-images.githubusercontent.com/32224410/160647842-bfade2c7-51a9-4cc6-99fe-d2fea452287c.png)

**Comment by nickspoons** [comment]
We don't use the 'Documentation' property in OmniSharp-vim, we use the `StructuredDocumentation`.

**Comment by JoeRobich** [comment]
@AnonymusRaccoon Which OmniSharp host is being used in this scenario? The LSP or STDIO/HTTP? If it is the LSP, then the fix would go in the Handler for the signatureinfo requests. https://github.com/OmniSharp/omnisharp-roslyn/blob/0208ea2280fc1f721ac98c6901a680ae63a2b5a5/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpSignatureHelpHandler.cs#L52

**Comment by AnonymusRaccoon** [comment]
I use the lsp mode, but I think it would be better to return a human readable documentation on this field on every mode, since others fields are made for humans to read.

**Comment by AnonymusRaccoon** [comment]
Okay, I will update the PR accordingly.

**Comment by AnonymusRaccoon** [comment]
Replaced by #2392
