### ISSUE TITLE
Can add a Unity3d debuger?

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-roslyn#239]
Can integrate a debugger like this? @lukaszunity
https://github.com/Unity-Technologies/MonoDevelop.Debugger.Soft.Unity

**Comment by DustinCampbell** [comment]
Closing this issue as it is very stale. Note that there is a debugger for VS Code here: https://marketplace.visualstudio.com/items?itemName=Unity.unity-debug.
