### ISSUE TITLE
(neovim lsp): method textDocument/prepareRename is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by quantum-booty** [OmniSharp/omnisharp-roslyn#2393]
neovim version: NVIM v0.8.0-dev+100-g371dfb174  
omnisharp version: 1.38.2
os: archlinux

Trying to do `:lua vim.lsp.buf.rename()` gives the following error:
`[WARN][2022-05-02 19:50:09] .../lua/vim/lsp.lua:89	"method textDocument/prepareRename is not supported by any of the servers registered for the current buffer"`
Other api like `textDocument/definition` and `textDocument/codeAction` works fine, just rename is not working.

**Comment by jlissner** [comment]
I am running into the same error, what was the resolution?

**Comment by quantum-booty** [comment]
> I am running into the same error, what was the resolution?

This is a bug upstream in neovim master I think
