### ISSUE TITLE
`SuppressMessage` hover info seems to have regressed

### ISSUE THREAD

**Issue by alexrp** [OmniSharp/omnisharp-roslyn#2397]
Unless my memory is completely failing me, I'm fairly certain I used to be able to hover over the `"CA5401"` in e.g. the following snippet

```csharp
    [SuppressMessage("", "CA5401")]
    public async Task WriteAsync(Stream stream, DataCenter center, CancellationToken cancellationToken)
    {
    }
```

and get a hover telling me what exact diagnostic (name, description) is being suppressed here. But in recent versions of OmniSharp (i.e. `latest` for the past 2~ months), this is no longer the case; I just see the generic hover telling me that it's a `System.String`.

I have no idea if this is a Roslyn or OmniSharp thing though.

**Comment by 333fred** [comment]
Looks like this was broken by https://github.com/dotnet/roslyn/pull/60266. @JoeRobich, can we move that provider back down to the Features layer?
