### ISSUE TITLE
For when ms-dotnettools.csharp-1.25.0-darwin-ARM ?

### ISSUE THREAD

**Issue by justPaulo** [OmniSharp/omnisharp-roslyn#2408]
Still:
Starting OmniSharp server at 6/5/2022, 12:22:55 PM
    Target: /Users/user/Desktop/app

OmniSharp server started with .NET 7.0.100-preview.2.22153.17
.
    Path: /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-x64/.omnisharp/1.39.0-net6.0/OmniSharp.dll
    PID: 82917

Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by filipw** [comment]
This is a C# extension problem, not an OmniSharp. It means you have x64 dotnet installed on an ARM machine. Make sure that you have correctly configured ARM dotnet installation.

**Comment by justPaulo** [comment]
This is what I have:
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   7.0.100-preview.2.22153.17
 Commit:    9c52c56c13

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-preview.2.22153.17/

Looks like, per RID, it's indeed ARM64.
