### ISSUE TITLE
OmniSharp.SdkInstanceProvider fails to parse 'omnisharp.sdkVersion' and 'omnisharp.sdkPath'

### ISSUE THREAD

**Issue by BBergquist** [OmniSharp/omnisharp-roslyn#2412]
Repro (using the latest version of OmniSharp w/ `omnisharp.useModernNet` enabled):
1. Override `omnisharp.sdkVersion` or `omnisharp.sdkPath` with any value (including the recommended values: "6.0.300" or "/home/username/dotnet/sdks/6.0.300").
2. Restart OmniSharp.

Expected behavior: OmniSharp successfully restarts, finding the specified SDK version from the user settings.

Actual behavior: `[fail]: OmniSharp.MSBuild.Discovery.Providers.SdkInstanceProvider            The Sdk version specified in the OmniSharp settings was not a valid semantic version. Configured version is ''6.0.300''. Please update your settings and restart OmniSharp.`

I [checked the regex](http://regexstorm.net/tester?p=%5e%28%3f%3cmajor%3e%280%7c%5b1-9%5d%5cd*%29%29%5c.%28%3f%3cminor%3e%280%7c%5b1-9%5d%5cd*%29%29%5c.%28%3f%3cpatch%3e%280%7c%5b1-9%5d%5cd*%29%29%24&i=%273.1.420%27) found in the code. 6.0.300 (no quotes) is a valid semantic version, but '6.0.300' is not. That paired with the logging message showing double ticks suggests that OmniSharp is receiving the setting value with extra quotes and needs to strip them out.

**Comment by BBergquist** [comment]
The impact is that this bug prevents users from building .NET Core 3.1 SDK-style projects.

**Comment by estellise-yukihime** [comment]
I'm still receiving this same error when I tried setting the sdkPath and the sdkVersion on v1.25.1-beta.

**Comment by JoeRobich** [comment]
@estellise-yukihime What values are you using?

**Comment by mcm-ham** [comment]
This is my value:
```json
"omnisharp.sdkVersion": "6.0.201"
```

This is the omnisharp log:
```json
[fail]: OmniSharp.MSBuild.Discovery.Providers.SdkInstanceProvider
        The Sdk version specified in the OmniSharp settings was not a valid semantic version. Configured version is ''6.0.201''. Please update your settings and restart OmniSharp.
```

**Comment by mcm-ham** [comment]
That fixed it for me, if I edit `/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/dist/extension.js` to remove those quotes it now works.

**Comment by tvardero** [comment]
Please reopen the issue, it is not solved.
```
[fail]: OmniSharp.MSBuild.Discovery.Providers.SdkInstanceProvider
        The Sdk version specified in the OmniSharp settings was not a valid semantic version. Configured version is ''6.0.403''. Please update your settings and restart OmniSharp.
[fail]: OmniSharp.MSBuild.Discovery.Providers.SdkOverrideInstanceProvider
        The Sdk path specified in the OmniSharp settings does not exist. Configured path is ''C:/Program Files/dotnet/sdk/6.0.403''. Please update your settings and restart OmniSharp.
```

```json
"omnisharp.sdkPath": "C:/Program Files/dotnet/sdk/6.0.403",
"omnisharp.sdkVersion": "6.0.403",
```

Omnisharp version v1.25.2
