### ISSUE TITLE
Hosting in WASM (without backend)

### ISSUE THREAD

**Issue by ShadowDancer** [OmniSharp/omnisharp-roslyn#2433]
I'm investigating possibility to run the language server entirely in the browser. Monaco editor can be used as a frontend.

My use case is:
Code editor with IntelliSense running entirely in WASM (without backend).

I'm not really familiar with the OmniSharp internals - can someone tell me if this can be done in reasonable timeframe?
[Case of Bicep](https://github.com/OmniSharp/csharp-language-server-protocol/issues/456) shows that it's possible to wire up language server with Monaco.

OmniSharp-Roslyn needs MsBuild, and I imagine MsBuild won't play nicely in browser (as it depend a lot on filesystem). I wonder if it'd be possible to grab some guts of Omnisharp, feed it reference assemblies and make it work? Some thoughts?

**Comment by filipw** [comment]
Because of the concurrency in use (various `Task.Run` and such), I am pretty sure you will not be able to get it up and running on Blazor.  Additionally, OmniSharp relies on full file system to be available and I can imagine you will run into problems there too.

**Comment by ShadowDancer** [comment]
Thanks !
