### ISSUE TITLE
OmniSharp cannot start

### ISSUE THREAD

**Issue by chenyulue** [OmniSharp/omnisharp-roslyn#2438]
My OS is win7 sp1, 32 bit, and dotnet version is 6.0.400.

`dotnet` can build a project and run it correctly. However, in vscode with C# plugin, omnisharp cannot start a server, which gives a fatal error 0xC0000005:

```shell
Fatal error. 0xC0000005
    at OmniSharp.Stdio.Driver.Program.Main(System.String[])
```

If I run `OmniSharp.exe --versoin`, it also gives the `Fatal error. 0xC0000005`. 

If I delete the C# plugin, and reinstall it, OmniSharp can start the server correctly, but if I close vscode then, and reopen it, the same fatal error happerns.

I have no idea why this weird issue happerns.

**Comment by filipw** [comment]
The 'normal' support for Windows 7 came to an end on January 14, 2020, which is almost 3 years ago. Does this happen on a modern Windows system too?

**Comment by chenyulue** [comment]
@filipw This issue doesn't happen on my Win 10.  

I understand that Win 7 is an old system, and many softswares drop support for it. But every time I uninstall and then re-install the C# plugin in vscode, Omnisharp can work correctly. Once I close vscode and reopen it, Omnisharp can't start the server. This is wierd.

**Comment by filipw** [comment]
Thanks for confirming! But I am really sorry then, but because of the lack of support for the OS, it will not be fixed or looked at 😇
