### ISSUE TITLE
Doesn't start on macOS

### ISSUE THREAD

**Issue by NxSoftware** [OmniSharp/omnisharp-roslyn#2440]
**Steps to Reproduce**
1. Download the latest (1.39.1) release for Apple Silicon (https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.1/omnisharp-osx-arm64-net6.0.zip)
2. Extract the .zip file, e.g. into `~/Downloads/omnisharp-osx-arm64-net6.0`
3. `chmod +x ~/Downloads/omnisharp-osx-arm64-net6.0/OmniSharp`
4. Attempt to run the app `./Downloads/omnisharp-osx-arm64-net6.0/OmniSharp`

**Expected Behaviour**
The app starts.

**Actual Behaviour**
The app fails to start with the following message:
> "OmniSharp" can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.

<img width="372" alt="Screenshot 2022-08-20 at 16 36 13" src="https://user-images.githubusercontent.com/1206172/185754876-0974b7cd-c404-481a-bbb3-178b3e94ea66.png">

The HTTP build (https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.1/omnisharp.http-osx-arm64-net6.0.zip) suffers the same problem.

To be brutally honest I'm not even sure if these steps are the correct / expected way of running the app as there is zero documentation that I can find on either running the app standalone, or using the C# library in an existing app.

**Comment by filipw** [comment]
OmniSharp is not a built as an self contained executable for Unix. You need to install [dotnet SDK](https://dotnet.microsoft.com/en-us/download) (for ARM in your case) and then run `dotnet OmniSharp.dll`
