### ISSUE TITLE
Is the .NET 6 version of OmniSharp meant to work on my .NET Framework projects?

### ISSUE THREAD

**Issue by KiLLeRRaT** [OmniSharp/omnisharp-roslyn#2445]
Hi,

I have an interesting problem, maybe it's a known thing.

I run Neovim, and using OmniSharp for me LSP when using C#.  If I use the .NET 6 version, and I use it on my .NET Core+ projects, it works fine.  When I open one of my .NET Framework projects, things like goto definition, and find all references doesn't work.  I get the following in the lsp log in Neovim:

```
[WARN][2022-09-01 09:13:04] ...lsp/handlers.lua:457	"OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService: No document found. File: c:\\[REDACTED]\\Constants.cs. | "
```

If I swap to use the .NET Framework version of OmniSharp  (Same version, just the different build). Then it works, and I can use Go to definition, and find all references etc.

Is this a know thing? Or am I missing something somewhere?

This is how OmniSharp is called:
```
Config: omnisharp
 	filetypes:         cs, vb
 	root directory:    C:\[REDACTED]\src\[REDACTED]
 	cmd:               C:\GBox\Applications\Tools\Applications\Neovim\lua\AppData\Local\nvim-data\mason\bin\omnisharp.CMD -z -s C:/[REDACTED]/src --hostPID 282612 DotNet:enablePackageRestore=false --encoding utf-8 --languageserver FormattingOptions:EnableEditorConfigSupport=true Sdk:IncludePrereleases=true
```

Here is that `omnisharp.cmd`
```
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%dp0%\..\packages\omnisharp\omnisharp.cmd" %*
```

And here is the next `omnisharp.cmd`
```
@ECHO off

dotnet "C:\\GBox\\Applications\\Tools\\Applications\\Neovim\\lua\\AppData\\Local\\nvim-data\\mason\\packages\\omnisharp\\OmniSharp.dll" %*
```

Any ideas or tips appreciated!

**Comment by filipw** [comment]
Non-SDK-style .NET Framework projects are not supported by the .NET 6.0 build of OmniSharp (.NET Framework projects using SDK-style projects should work on Windows). 
For opening legacy .NET Framework projects, the global Mono O# variant is still needed (*nix) or the .NET Framework O# variant (Windows), as in the past.
