### ISSUE TITLE
Omnisharp-roslyn can't identify 3rd party library on Windows 8.1 but working on Windows 10.

### ISSUE THREAD

**Issue by gkjgh** [OmniSharp/omnisharp-roslyn#2451]
Environment: 
Windows 10 PC at office.
Windows 8.1 PC at home.
neovim 0.7.2 + .net 6.0 + omnisharp-roslyn
3rd party library: ctrader

lspconfig:
local status_ok, lspCfg = pcall(require, "lspconfig")
if not status_ok then
  return
end

local lspCfg = require("lspconfig")

lspCfg.omnisharp.setup({
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  on_attach = function(client, bufnr)
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
  end,
  cmd = { "dotnet", "D:/omnisharp/OmniSharp.dll" },
})

Everything working on Windows 10.
I copied "C:\User\user\AppData\Local\nvim" and "C:\Users\user\AppData\Local\nvim-data" directories form Windows 10 to Windows 8.1. and code analysis on Windows 8.1 prompt: "Unnecessary using directive." on "using cAlgo.API;" line which is used. While "using System;" line has no prompt which means identifed.

Is this a bug or what should I do to fix this?

**Comment by filipw** [comment]
It is difficult to say, because we do not really test on Windows 8.1 - so I wouldn't say it's a bug but it's just not being supported.

[.NET 6.0 will also stop supporting Windows 8.1 soon - in January 2023](https://learn.microsoft.com/en-us/lifecycle/products/windows-81).
