### ISSUE TITLE
start with lsp option, OmniSharp won't respect the root paths sended by editor.

### ISSUE THREAD

**Issue by jidibinlin** [OmniSharp/omnisharp-roslyn#2452]
<img width="1081" alt="Screen Shot 2022-09-25 at 13 20 00" src="https://user-images.githubusercontent.com/38578679/192129556-881d36be-e26e-4c71-83f6-9cbb34b70ded.png">

<img width="1255" alt="Screen Shot 2022-09-25 at 13 22 37" src="https://user-images.githubusercontent.com/38578679/192129590-71d07216-5b07-49fe-8205-c2e5c21a81b6.png">

**Comment by filipw** [comment]
If you pass `-s` or `--source` option at startup it is given precedence over `rootUri`. `rootUri` is only respected when no explicit startup source was provided.

**Comment by jidibinlin** [comment]
I used the wrong method to start omnisharp. 
when I use mono start omnisharp it's works fine
