### ISSUE TITLE
I can't find Roslyn with the version (4.3.0-2.22267.5)  in https://github.com/dotnet/roslyn

### ISSUE THREAD

**Issue by lxz12523** [OmniSharp/omnisharp-roslyn#2453]
I can't find Roslyn with the version (4.3.0-2.22267.5)  in https://github.com/dotnet/roslyn

[[4.3.0-2.22267.5](https://github.com/OmniSharp/omnisharp-roslyn/pull/2401)](https://github.com/OmniSharp/omnisharp-roslyn/pull/2401)

**Comment by filipw** [comment]
OmniSharp uses private NuGet feeds, if you want to build OmniSharp and its dependencies you need to make sure to include them https://github.com/OmniSharp/omnisharp-roslyn/blob/master/NuGet.Config
