### ISSUE TITLE
Omnisharp Unity Analyzer In Visual Studio Path Wrong on MacOS

### ISSUE THREAD

**Issue by Space1230** [OmniSharp/omnisharp-roslyn#2454]
According to the error log, the path used to find the Unity Analyzer is:

"/Applications/Visual Studio.app/Contents/MonoBundle/Addins/MonoDevelop.Unity/Analyzers/Microsoft.Unity.Analyzers.dll"

when in reality it is

"/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.Unity/Analyzers/Microsoft.Unity.Analyzers.dll"

I confirmed this was the issue by creating a symbolic link between both of the addIn folders and everything works fine albeit a little slow.

The original error message was as follows
>OmniSharp.MSBuild.ProjectManager: Failure while loading the analyzer reference 'Microsoft.Unity.Analyzers': Could not find a part of the path "/Applications/Visual Studio.app/Contents/MonoBundle/Addins/MonoDevelop.Unity/Analyzers/Microsoft.Unity.Analyzers.dll". |

**Comment by filipw** [comment]
Thanks for the report, however, this is provided by the Mono and Unity installation - and it is not related to OmniSharp, it only uses what is surfaced to it (OmniSharp has no explicit knowledge of Unity).
