### ISSUE TITLE
VS Code: After installing c# extension on arm64 machine, the document color and color presentation are not displayed.

### ISSUE THREAD

**Issue by lemon0213** [OmniSharp/omnisharp-roslyn#2472]
**Environment data**
MacOS Machine: MacOS Monterey(12.5) on M1 machine
VS Code version:1.73.0
C# Extension version:[[1.25.1]](https://microsoft-my.sharepoint.com/:u:/r/personal/allichou_microsoft_com/Documents/csharp-1.25.1/[csharp-1.25.1-darwin-arm64.vsix](https://microsoft-my.sharepoint.com/:u:/r/personal/allichou_microsoft_com/Documents/csharp-1.25.1/csharp-1.25.1-darwin-arm64.vsix?csf=1&web=1&e=wf7AwI)?csf=1&web=1&e=wf7AwI)
SDK: 7.0.100

**Platform**
- [ ] Windows
- [x] macOS
- [x] Linux

**REPRO STEPS**

1. Open a normal Terminal Emulator, create MVC project and open it using VS code

```
mkdir MVC3x
cd MVC3x
dotnet new mvc
code .
```

2. In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded. Wait for install successfully.
3. Type below code to Views/Shared/_Layout.cshtml file.
`<h1 style="background-color:blue;">Hello World</h1>`

NOTE:This issue only repro on M1 machine.

**ACTUAL**
![image](https://user-images.githubusercontent.com/66412274/199691151-731b4081-2a9f-4f64-97dd-78f48095bcd4.png)

**EXPECTED**
![image](https://user-images.githubusercontent.com/66412274/199691216-0352ccf2-3e4a-4d31-b7c8-047628fca4a9.png)

**Comment by v-sherryfan** [comment]
This issue also repro on Linux arm64 machine(Ubuntu 20.04). But you will also encounter an existing bug [#6925](https://github.com/dotnet/razor-tooling/issues/6925), I am not sure if it is causing the linux arm64 machine to not display color boxes as well.

**Comment by lemon0213** [comment]
Change this issue path to dotnet/razor repo, so I will close it and track it throug bug [#7913](https://github.com/dotnet/razor/issues/7913).
