### ISSUE TITLE
"Add explicit cast" code fix inserts the wrong cast

### ISSUE THREAD

**Issue by filip-hejsek** [OmniSharp/omnisharp-roslyn#2475]
The following code contains an error because there is no implicit conversion from `int` to `short`.
```csharp
short s = 0;
int i = 0;
s += i;
```
OmniSharp offers a fix for this error: "Add explicit cast". However, applying the fix results in this code:
```csharp
short s = 0;
int i = 0;
(void)(s += i);
```
This not only doesn't fix the error, but also introduces another error because it's illegal to cast to `void`. OmniSharp then offers the same fix again, which just leads to more `void` casts.

The correct fix should be this:
```csharp
short s = 0;
int i = 0;
s += (short)i;
```

OmniSharp version: `1.39.0`

**Comment by filipw** [comment]
Thanks for the report - this is a bug in Roslyn not in OmniSharp (same happens in Visual Studio) - I opened an issue there https://github.com/dotnet/roslyn/issues/66369
