### ISSUE TITLE
Question: Is the `-s` parameter still required when invoking omnisharp-net6.0?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [OmniSharp/omnisharp-roslyn#2478]
Just curious; working on additions to an emacs package. I notice no mention of the parameter on the wiki, only in the docs.

**Comment by filipw** [comment]
If it's not passed it will default to current directory (which often is buried somewhere in the extension/plugin filesystem tree), so normally it should be passed, pointing to either a folder with a solution/project or a solution file itself.

**Comment by JordanAnthonyKing** [comment]
Thanks for clarifying
