### ISSUE TITLE
Configuring OmniSharp for Kate Editor

### ISSUE THREAD

**Issue by TechScribe-Deaf** [OmniSharp/omnisharp-roslyn#2481]
This is merely instructions for fellow Kate users who wish to integrate C# into their preferred editor by searching through issues board here.

1. Download release zip or tar archive file related to your platform: https://github.com/OmniSharp/omnisharp-roslyn/releases
2. Create a directory: `mkdir ~/.langserv`
3. Extract the zip/tar into `~/.langserv`
4. Update `~/.bashrc` by adding `export PATH=/home/{yourusername}/.langserv/omnisharp-linux-x64-net6.0:$PATH` at the end of the script, you can also run this to do the same:
```sh
echo "export PATH=/home/$USER/.langserv/omnisharp-linux-x64-net6.0/:\$PATH" >> ~/.bashrc
```
5. Open Kate Editor and add the followings into your LSP Client menu, User Server Settings tab, configuration between "cpp" and "d" stubs:
```json
        "c-sharp": {
            "command": ["OmniSharp", "-lsp", "-s=%{Document:Path}"],
            "url": "https://github.com/OmniSharp/omnisharp-roslyn",
            "highlightingModeRegex": "^C#$"
        },
```

Close and then reopen Kate and it should now work when you open folder in Kate editor in any C# project.

Enjoy.

**Comment by Lumpupu** [comment]
If omnisharp is looking for a project in the wrong place - try removing = next to -s
As a result, it will be like this: "-s %{Document:Path}". 

so everything worked for me, thank you!

**Comment by AndreasGkizis** [comment]
I am struggling to understand what is going on here, 
I have installed it on windows 10 and 11 and I have a feeling that this is reffering to linux since you mention bash.

Could anyone help me understand and set it up somehow?
Thank you

**Comment by Lumpupu** [comment]
@AndreasGkizis try using the absolute path to OmniSharp
Maybe this will help...
