### ISSUE TITLE
Homebrew formula/repository

### ISSUE THREAD

**Issue by sjrmanning** [OmniSharp/omnisharp-roslyn#249]
It would be great to eventually have omnisharp available for install via homebrew, and I was considering pull-requesting this formula into the main homebrew repository but I think they'll require it has some tests post-install — the likelihood of getting it pulled in without that seems low.

In the mean-time, one option is to have a repository for an omnisharp homebrew formula which we can tap with `brew tap omnisharp/omnisharp`, similar to the dnvm formula hosted at [https://github.com/aspnet/homebrew-dnx](https://github.com/aspnet/homebrew-dnx), installable with `brew tap aspnet/dnx && brew install dnvm).

Here's an example omnisharp.rb brew formula using the 1.0.3 release build that's working fine for me:
```ruby
class Omnisharp < Formula
  desc "Cross platform .NET development in the editor of your choice"
  homepage "http://www.omnisharp.net/"
  url "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.0.3/omnisharp.tar.gz"
  version "1.0.3"
  sha256 "dd6d130bf83082045763caa6dfeaa7520956e06f835dd60e3143fdeda1916461"

  depends_on "mono" => :recommended
end
```

The benefit (personally!) is that `omnisharp` ends up in my PATH with all other brew-installed packages, and upgrading to newer releases becomes very painless.

[Some detailed info on brew taps is available here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md)

**Comment by davidfowl** [comment]
Why would you want omnisharp on the path?

**Comment by nosami** [comment]
I think it's because he uses emacs and starts the server manually. 

I'm not opposed to this idea in principle, but I just don't want any more future work going forward.

It's not difficult to git clone and set an alias to point to the server.

**Comment by sjrmanning** [comment]
Obviously someone would need to maintain the formula so a `brew update` sees when a new version is released, but aside from the path thing being able to catch updates and only have to run `brew upgrade omnisharp` would be hugely beneficial for OS X users (in my biased opinion). I guess #132 is tangentially related to this.

**Comment by davidfowl** [comment]
I wouldn't say OS X users, each editor usually bundles omnisharp. I understand emacs doesn't but it still feels ofd

**Comment by nosami** [comment]
@sjrmanning - How about I create a repo under https://github.com/OmniSharp and give you write access? It will be your responsibility to keep it updated.

**Comment by sjrmanning** [comment]
@nosami sure I'd be more than happy to do that. It just needs to be prefixed with `homebrew`, e.g. `homebrew-omnisharp`.

**Comment by nosami** [comment]
@sjrmanning Here you go https://github.com/OmniSharp/homebrew-omnisharp-roslyn :)

**Comment by sjrmanning** [comment]
@nosami excellent! Thanks very much, will push the current formula along with a little README explaining the use asap :)

**Comment by nosami** [comment]
thank you!

**Comment by nosami** [comment]
@sjrmanning I just though.. maybe this should depend on the dnvm homebrew package too?

**Comment by sjrmanning** [comment]
Yes I think you're right — I'm testing now on a fresh install without dnvm or having run the build.sh to make sure the formula works correctly. I suspect it will complain about missing dnx and the like. `depends_on "aspnet/dnx/dnvm"` should be sufficient. Will do some testing and see.
