### ISSUE TITLE
[Enhancement] Generate code between functions is tabbed up to tab level

### ISSUE THREAD

**Issue by tilkinsc** [OmniSharp/omnisharp-roslyn#2493]
![image](https://user-images.githubusercontent.com/7494772/212449134-51806eb0-2da8-46fa-8fff-cf745ce95b15.png)

I like the autogenerated code emitted by omnisharp for vscode.

I do not like how when they get generated empty lines don't match the current tab level, as seen in the image.

People seem to really like their code prettyfiers but I don't use any, mostly for the fact it eliminates the tabs. My tabs are sacred to me and its purpose for being there is so that I don't have to tab to make a function or deal with the existence of empty lines since the editor when pressing enter will give you one. You also will get tabs emitted when you select a function's closing brace and press enter to create said function (the only way to do it besides clicking into the 'pit' to tab it up then to create a function).

**Comment by 333fred** [comment]
As I mentioned to on discord, the OmniSharp project has no control over this. You'll need to open a feature request at https://github.com/dotnet/roslyn.

**Comment by tilkinsc** [comment]
Reference: https://github.com/dotnet/roslyn/issues/66424
