### ISSUE TITLE
Add info about RenameOptions to wiki/Configuration-Options

### ISSUE THREAD

**Issue by askazakov** [OmniSharp/omnisharp-roslyn#2496]
Should https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options contain info about RenameOptions, added via https://github.com/OmniSharp/omnisharp-roslyn/pull/1495 ?

**Comment by filipw** [comment]
Yes! The wiki is editable by anyone, so feel free to just do it 😀

**Comment by askazakov** [comment]
I've add – https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options/6d6d900aff249c04651d83f656099559d38fe109

How is to do better – just add link to pr 1495 that contains nice gifs or copy gifs to wiki? Or it is good enough right now?

**Comment by filipw** [comment]
I think linking to the PR is fine for now. Thanks again for your help!
