### ISSUE TITLE
Where to get MSBuild?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [OmniSharp/omnisharp-roslyn#2526]
This is Windows 7 and I'm unable to install Visual Studio to get MSBuild. OmniSharp requires MSBuild to work. I have no idea where to get MSBuild without installing Visual Stdio. Please help. Thank you.

**Comment by JoeRobich** [comment]
The VS 2019 MSBuild Tools supports Win7. You can install the latest by clicking the [Build Tools link](https://download.visualstudio.microsoft.com/download/pr/7c09e2e8-2b3e-4213-93ab-5646874f8a2b/73d0e76d9156e11d8d448e5da817d4d83d7a9edb12190aea4c0b6fb8af25cd2c/vs_BuildTools.exe) on [this page](https://learn.microsoft.com/en-us/visualstudio/releases/2019/history#release-dates-and-build-numbers).
