### ISSUE TITLE
How to have OmniSharp detect and use MSBuild?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [OmniSharp/omnisharp-roslyn#2527]
`dotnet 6.0` is the last version supports Windows 7. There is no `MSBuild.exe` but there is `MSBuild.dll` on `sdk\6.0.408` directory. The problem is, OmniSharp is unable to detect and use it.

**Comment by JoeRobich** [comment]
The .NET Core build of OmniSharp should detect and use a dotnet 6 SDK. Look for the `-net6` build of OmniSharp that is right for your platform. https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.39.7
