### ISSUE TITLE
Explain how "global using"s are handled

### ISSUE THREAD

**Issue by gautaz** [OmniSharp/omnisharp-roslyn#2530]
Hello,

I did not find any relevant documentation on this matter but I am the kind of person looking for something in front of him in his own fridge so my apologies if I messed up again...

Since C# 10, one can use [global using](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive).
Having lately refactored a project to use dotnet6 starting from a fresh template, most `using`s are now handled globally so we started removing the local `using` directives.

We have also added our own `global using`'s file named `Usings.cs` at the root of our project.

The project builds without any error but the language server reports errors like this one (declared in template's `global using`s):
![image](https://github.com/OmniSharp/omnisharp-roslyn/assets/11046232/56cf7e72-2c39-424d-967c-9cf91d48c225)

Or this one (declared in `Usings.cs`):
![image](https://github.com/OmniSharp/omnisharp-roslyn/assets/11046232/3d39ec49-6377-4c9f-9444-ff41868aa577)

My own configuration is NixOS/neovim based but the same kind of errors are reported on Windows/VSCode (colleague's environment).

Would some knowledgeable people mind giving us some advice on this matter or redirect us to the right documentation describing how `omnisharp-roslyn` might be configured to handle correctly `global using`?

**Comment by JoeRobich** [comment]
@gautaz Sorry if O# is having trouble with global usings. I was unable to reproduce locally with a recent SDK. Are you using O# running with Mono or dotnet? Which version of the SDK are you running against? If this is still a problem, could you provide a repo project that I could use for testing?

**Comment by gautaz** [comment]
Hello @JoeRobich, sorry for lagging behind.

I have tried to reproduce the issue lately and was unable to do so.

My guess is that it was related to mixing up two different versions of dotnet as I am using a dockerized development environment and neovim starts the language server as an host process.

I am closing the issue for now, I will reopen it if occurs again, provided I have a clear way to reproduce it.

Thanks for the input.
