### ISSUE TITLE
E5248: Invalid character in group name(AstroNvim, Nvim)

### ISSUE THREAD

**Issue by Izanagi-96** [OmniSharp/omnisharp-roslyn#2540]
OmniSharp wasn't working at all in AstroNvim, Vanilla Nvim, VSCode, VS but now everything is working except that in AstroNvim which is my main ide and Vanilla Nvim whenever you try to edit a cs file you get this error "E5248 Invalid character in gruop name" so basically you are not able to make any changes as this error will pop up every single second

**Comment by Izanagi-96** [comment]
Now everything is working fine in both vscode and vs except that AstroNvim is still giving me this error after typing anything: "E5248: Invalid character in group name"

**Comment by BeratHundurel** [comment]
How do you fix the issue
