### ISSUE TITLE
`run` script is not executable in Linux tar.gz of 1.39.7 release

### ISSUE THREAD

**Issue by mthalman** [OmniSharp/omnisharp-roslyn#2547]
When extracting https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.7/omnisharp-linux-x64.tar.gz and attempting to execute the `run` script, I get a permission denied error. This is because the mode of the `run` file is `-rw-r--r--` (i.e. not executable). This is different than previous releases where the mode was set to `-rwxr-xr-x`. I consider this to be a breaking change for the release.

**Comment by mthalman** [comment]
This same issue applies to the 1.39.8 release.

**Comment by nickspoons** [comment]
Yes this has caused issues in omnisharp-vim too, we now `chmod +x` it ourselves but it was indeed a breaking change for us.

**Comment by nickspoons** [comment]
Merci, @JoeRobich!
