### ISSUE TITLE
.NET SDK MSBuild

### ISSUE THREAD

**Issue by iahung2** [OmniSharp/omnisharp-roslyn#2559]
.NET SDK has MSBuild included but it's a DLL (MSBuild.dll) and OmniSharp is unable to detect and use it. Do I need to build it from source (https://github.com/dotnet/msbuild) to get MSBuild.exe? It's better if OmniSharp could use the MSBuild.dll included with .NET SDK.

**Comment by JoeRobich** [comment]
The net6.0 builds of O# support .NET SDK.

**Comment by iahung2** [comment]
> The net6.0 builds of O# support .NET SDK.

I mean the MSBuild version included with .NET SDK. It's a dll (MSBuild.dll) and OmniSharp seems to need the exe (MSBuild.exe).

**Comment by iahung2** [comment]
I surrender. It's too difficult to setup OmniSharp manually. I ended up using Sublime Text to install OmniSharp and it's working now.
