### ISSUE TITLE
What is the so-called "code_actions.dll" ?

### ISSUE THREAD

**Issue by saint-yellow** [OmniSharp/omnisharp-roslyn#2562]
Hi, there.

The wiki shows an example of [Roslyn extensions options](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options) like below:
```json
{
  "RoslynExtensionsOptions": {
    "locationPaths": [
       "//path_to/code_actions.dll"
    ]
  }
}
```

I'm confused as to what file the code_actions.dll means. Can someone tell me?

**Comment by JoeRobich** [comment]
In this case the code_actions.dll would be a library that exports Roslyn analyzers and code fixes. See https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix for more details on how to build your own.

Typically, Analyzers are shipped as NuGet packages and added as PackageReferences in your project file or GlobalPackageReferences in your Directory.Packages.props. O# additionally supports loading these from a path on disk and applying them to all projects in the open workspace.
