### ISSUE TITLE
Errors with new version of Omnisharp

### ISSUE THREAD

**Issue by TimothyPescatore** [OmniSharp/omnisharp-roslyn#2571]
I updated my omnisharp-server this morning with the newest version via Mason (Neovim).

The server starts, but as soon as I try to use GoToDefinitio or any other method I get an error.

Error when executing textDocument/definition : Internal Error - System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.CodeAnalysis.NodeStateEntry`1<System.ValueTuple`2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable`1.GetEnumerator()'.
09:58:07 AM msg_show    at Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)

**Comment by davidwengier** [comment]
@allisonchou knows all about this error and the pain it has caused. I was on holiday. 😛

**Comment by 333fred** [comment]
We need to have O# include and prefer a matched version of the RazorCompiler external access dll (matched meaning the same version as our roslyn version). Sorry I forgot about this, I thought that the razor support was an entirely separate process and didn't need to line up with O# versions at all. See https://github.com/dotnet/roslyn/pull/70176.
