### ISSUE TITLE
How to installed OmniSharp for Linux and Razor Language Server for OmniSharp without network

### ISSUE THREAD

**Issue by truongan012** [OmniSharp/omnisharp-roslyn#2579]
Hello All,

Our company has firewall when downloading and installing the packages as below,
`Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=20.04

Downloading package 'OmniSharp for Linux (.NET 6 / x64)' Failed at stage: downloadPackage
Error: connect ETIMEDOUT 52.239.160.170:443

Installing Razor OmniSharp Version = 7.0.0-preview.23363.1...
Platform: linux, x86_64, name=ubuntu, version=20.04

Downloading package 'Razor Language Server for OmniSharp (Linux / x64)' Failed at stage: downloadPackage
Error: connect ETIMEDOUT 192.229.232.200:443`

I tried to download "omnisharp-linux-x64-net6.0.zip" and extracted to .../.vscode-server/extensions/ms-dotnettools.csharp-2.8.23/.omnisharp/1.39.10-net6.0/
But can not find Razor Language Server for OmniSharp (Linux / x64)
Thanks!

**Comment by JoeRobich** [comment]
Sorry you are running into issues. The Razor server is maintained and added to the C# extension by Microsoft. It would be best to open an issue at https://github.com/dotnet/vscode-csharp/issues with your question.

Taking a quick look at their package.json it includes the following url. https://github.com/dotnet/vscode-csharp/blob/2f591c271ace0f4d9401ef1b0b4b41db0908fe65/package.json#L774
