### ISSUE TITLE
Find implementations API not finding subclass

### ISSUE THREAD

**Issue by sp3ctum** [OmniSharp/omnisharp-roslyn#258]
So I started porting omnisharp-emacs over to omnisharp-roslyn. The first thing I'm taking on is porting the integration tests. Most of them seem to run just fine, but here's one that's oddly failing:

``` json
{
"Buffer": "using System;

namespace minimal
{
    public class BaseClass {}
    public class SomeClass : BaseClass {}
}",
"Column": "22",
"Line": "5",
"FileName": "/home/mika/git/omnisharp-emacs/test/MinimalSolution/minimal/MyClassContainer.cs"
}

************  Response ************ 
{"QuickFixes":[]}
/findimplementations: 200 366ms
```

The cursor is on the first instance of the word `BaseClass`. In `omnisharp-roslyn/tests/OmniSharp.Tests/BufferManagerFacts.cs` [one test](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/tests/OmniSharp.Tests/FindImplementationFacts.cs#L59) checks that `/findimplementations` should be able to find subclasses, but this does not seem to be the case for me.

What could be wrong?

**Comment by sp3ctum** [comment]
However, I also found that if I change the buffer contents to not have the using statement and the namespace block, the subclass can indeed be found. Could this be a bug, perhaps?

**Comment by nosami** [comment]
Yeah..... looks like a bug to me.

**Comment by DustinCampbell** [comment]
It *should* work. If not, there's a bug somewhere, because this code is present at https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindImplementationsService.cs#L46-L50

```C#
if (symbol is INamedTypeSymbol namedTypeSymbol)
{
    var derivedTypes = await SymbolFinder.FindDerivedClassesAsync(namedTypeSymbol, _workspace.CurrentSolution);
    quickFixes.AddRange(derivedTypes, _workspace);
}
```

**Comment by akshita31** [comment]
Yes this doesn't reprouduce anymore. I have also added an integration test to vscode C# extension just to be sure. https://github.com/OmniSharp/omnisharp-vscode/pull/2410.
