### ISSUE TITLE
Invalid LSP CodeAction response

### ISSUE THREAD

**Issue by bstaletic** [OmniSharp/omnisharp-roslyn#2616]
I have just tried the latest release of omnisharp-roslyn (1.39.11) in LSP mode and the code action response was wrong.

```json
{
  "jsonrpc": "2.0",
  "id": 24,
  "result": [
    {
      "title": "Use implicit type",
      "kind": "refactor",
      "diagnostics": [],
      "data": {
        "Uri": "file:///home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/ycmd/tests/cs/testdata/testy/FixItTestCase.cs",
        "Identifier": "Use implicit type",
        "Name": "Use implicit type",
        "Range": {
          "Start": {
            "Line": 3,
            "Character": 12
          },
          "End": {
            "Line": 3,
            "Character": 13
          }
        },
        "$$__handler_id__$$": "db8ae591-20c6-46a3-89a6-e8c50093aac3"
      }
    }
  ]
}
```

Code actions responses are supposed to be arrays of [`Command`s](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#command) and [`CodeAction`s](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction).

If the above is supposed to be a `Command`, it is missing the `command` property.
If the above is supposed to be a `CodeAction`, it is missing either `command` or `edit` as per

> A CodeAction must set either `edit` and/or a `command`

**Comment by rachartier** [comment]
I have the same issue with Neovim.

**Comment by bstaletic** [comment]
@rachartier Thank you. Though the server shouldn't be relying on `codeAction/resolve` if the client has not advertised that capability.
