### ISSUE TITLE
Multiple linux downloads contain windows .exes

### ISSUE THREAD

**Issue by Etiennepicard** [OmniSharp/omnisharp-roslyn#2632]
Multiple linux packages across both the latest and preview release contain an "OmniSharp.exe" file rather than a linux executable "OmniSharp" file as expected.
Here are a few of the packages I've found with the wrong file type:

omnisharp-linux-x64.tar.gz
omnisharp-linux-x64.zip
omnisharp-linux-x86.zip

The only package I've found with the correct executable type was:
omnisharp-linux-x64-net6.0.zip

**Comment by nickspoons** [comment]
@Etiennepicard those packages are expected to be run via `mono`. They contain a `run` script at the root level, which executes `mono OmniSharp.exe`.

The "net6.0" builds are the native builds, the one you most likely want is [omnisharp-linux-x64-net6.0.tar.gz](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.12/omnisharp-linux-x64-net6.0.tar.gz)

**Comment by Etiennepicard** [comment]
Ah, so they should be named something along the lines of omnisharp-mono-linux... rather than omnisharp-linux

**Comment by nickspoons** [comment]
There is also an [omnisharp-mono.tar.gz](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.12/omnisharp-mono.tar.gz) package already. I'm not exactly sure about what the differences are, I _think_ that they are the same except that the mono package doesn't contain the `run` script.

In any case the different packages are for different use-cases, they work, and as they are used as a primary installation source they can't be renamed or have their file structures changed, without it being a breaking change.

Keep in mind that for many years `mono` was the only way to run C# executables on linux/osx, so it wasn't necessary to explicitly name the package to mention `mono`. This project is older than .NET Core so the native builds are newer. But the package names have not been (and should not be) changed.

**Comment by JoeRobich** [comment]
Closing this as answered.
