### ISSUE TITLE
How to run the linux arm64 release?

### ISSUE THREAD

**Issue by ColeW-Picaro** [OmniSharp/omnisharp-roslyn#2639]
I am trying to download the linux arm64 release and install it so I can use it in my editor. The only executable file there is a .exe file, which I can't run. Is it intended for a linux release to have a .exe executable? If so, how do I run it?

**Comment by nickspoons** [comment]
You most likely want this package: https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.12/omnisharp-linux-arm64-net6.0.tar.gz

The ones that don't have "net6.0" in the name are meant to be run with mono, for older .NET Framework projects.
