### ISSUE TITLE
Plans to update to .NET 8 

### ISSUE THREAD

**Issue by sweetpeteza** [OmniSharp/omnisharp-roslyn#2644]
Any plans to update to .NET 8?
With all the improvements they've made to use Span<T> etc, I'm sure text editing could greatly benefit from these updates

Anyways, love the product and continue the good work

**Comment by JoeRobich** [comment]
Thanks for checking in. I have posted an announcement about planned future development at https://github.com/OmniSharp/omnisharp-roslyn/issues/2647
