### ISSUE TITLE
Lots of mscorlib issues with 3rd party packages

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#265]
Moved from https://github.com/OmniSharp/omnisharp-server/issues/204

Hi

I'm getting a lot of mscorlib issues with 3rd party nuget packages, any idea how to fix these?

![2015-07-10_1429](https://cloud.githubusercontent.com/assets/1169539/8618637/474380ea-2710-11e5-9ca3-7c93d73e1e00.png)

![2015-07-10_1430](https://cloud.githubusercontent.com/assets/1169539/8618636/4741cd86-2710-11e5-8619-d7b1e255c761.png)

Running on Windows 7.1, targeting .net 4.5.2, Atom 1.0.2, omnisharp-atom 0.19.1.

**Comment by jmkelly** [comment]
I'm seeing lots of these as well in existing msbuild projects.  No issue in Visual Studio, but same issue in both omnisharp and VS Code.  All errors seem centered around the mscorlib error above.

**Comment by RevenantX** [comment]
Confirm. Many projects (MSBuild) references System.dll (and similar System.Xml.Dll etc.) that has needed types (IDisposable and others). Strange issue...

**Comment by marshall007** [comment]
Anyone have a workaround yet?

**Comment by willl** [comment]
I've had a small poke around (Google) and found these that may potentially resolve this issue (Or at least the "Assuming assembly reference 'mscorlib, Version=2.0.0.0 ... matches identity 'mscorlib, Version4.0.0.0 ..." issue anyway):
 
* "Once, we had a similar problem with Roslyn (mscorlib 2.0.0.0 vs. 4.0.0.0 references). We solved this by using CSharpCompilationOptions.WithAssemblyIdentityComparer( DesktopAssemblyIdentityComparer.Default)": http://forum.linqpad.net/discussion/856/compile-errors-for-assemblies-which-reference-to-mscorlib-2-0-5-0-linqpad-5-00-08
* "you can get rid of the warnings by using the DesktopAssemblyIdentityComparer.Default": https://github.com/ctaggart/froto/issues/2#issuecomment-63953562. They also link to this [gist](https://gist.github.com/m0sa/d0f5eab1eed43952623f) that shows that option in use.

**Comment by RevenantX** [comment]
Thanks. This works. I will create pull request soon.

**Comment by nosami** [comment]
Fixed in v1.4.1. Thanks @RevenantX !

**Comment by nosami** [comment]
....and @willl for finding the fix :)

**Comment by willl** [comment]
:+1: awesome :)
