### ISSUE TITLE
Text changes inserting extra characters for a "Declare local variable" request

### ISSUE THREAD

**Issue by sp3ctum** [OmniSharp/omnisharp-roslyn#276]
Here's my request in emacs (humor me and just imagine it as JSON):

``` lisp
((Arguments
  (FileName . "/home/mika/git/omnisharp-emacs/test/MinimalSolution/minimal/MyClass.cs")
  (Line . "5")
  (Column . "12")
  (Buffer . "public class Class1
{
    public void Whatever()
    {
        int i = 1;
    }
}
")
  (Identifier . "Declare local variable")
  (WantsTextChanges . t))
 (Command . "v2/runcodeaction")
 (Seq . 83))
```

Here's the server response:

``` json
{
    "Type": "response",
    "Seq": 185,
    "Body": {
        "Changes": [
            {
                "Changes": [
                    {
                        "EndColumn": 12,
                        "EndLine": 5,
                        "StartColumn": 9,
                        "StartLine": 5,
                        "NewText": "var i = int;
        i"
                    }
                ],
                "Buffer": null,
                "FileName": "/home/mika/git/omnisharp-emacs/test/MinimalSolution/minimal/MyClass.cs"
            }
        ]
    },
    "Message": null,
    "Success": true,
    "Running": true,
    "Command": "v2/runcodeaction",
    "Request_seq": 83
}
```

After applying the text change, the buffer looks like this:

``` csharp
public class Class1
{
    public void Whatever()
    {
        var i = int;
        i i = 1;
    }
}
```

**Comment by sp3ctum** [comment]
Looking at the data, the correct thing would be to replace columns `9-12` with simply `var`.

**Comment by sp3ctum** [comment]
Oops, no. This is for the `Declare local variable` action, please disregard the last message.
`use 'var' keyword` works perfectly.

**Comment by nosami** [comment]
This is probably because we're currently using a very alpha version of NRefactory6. We want to switch it over to [Refactoring Essentials](http://vsrefactoringessentials.com/) soon. 

This is the refactorings portion of NRefactory extracted out into a new library and is a few months further on.

**Comment by sp3ctum** [comment]
Thanks for letting me know. I'll just not use this for now.

**Comment by nosami** [comment]
There's a blacklist here https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Api/v2/Refactoring/OmnisharpController.CodeActions.cs#L123

We also use most of the refactorings from VS. These all work fine.

**Comment by filipw** [comment]
This has been resolved
