### ISSUE TITLE
Should not scanning subdirectories for projects by default

### ISSUE THREAD

**Issue by kflu** [OmniSharp/omnisharp-roslyn#278]
My company has a huge directory that contains hundreds of projects. I have a sln file at the root. With 

    scripts\Omnisharp.cmd -p 2000 -s my.sln

It tries to scanning recursively for dnx projects which never finishes. This shouldn't be the default behavior.

**Comment by donovanlange** [comment]
FWIW, I'm also noticing that in the process of scanning, by default the Omnisharp included with Visual Studio Code will find the built Web projects in artifacts; which by default include an App/project.json file.  This causes no amount of confusion.

**Comment by davidfowl** [comment]
You can control this with `omnisharp.json`:

e.g https://github.com/OmniSharp/omnisharp-roslyn/blob/master/omnisharp.json

**Comment by david-driscoll** [comment]
@troydai this is old DTH behavior right? What does cli project system do today?

**Comment by troydai** [comment]
`project.json` searching should be based `global.json`. It only searches one level deeper into the path listed in `global.json` recursively find all `project.json` is wrong. I agree we should clear the logic of scanning projects including both `*.csproj` and `project.json`

I'll assign this to myself and clean up the scenarios.

**Comment by troydai** [comment]
This problem is fixed. Currently project system will relies on `global.json` to search for projects when there is no `project.json` at current folder. The logic is not recursive.
