### ISSUE TITLE
[DesignTimeHostManager] Failed to launch DesignTimeHost

### ISSUE THREAD

**Issue by per-samuelsson** [OmniSharp/omnisharp-roslyn#283]
Sorry if this is not the right place to post.

I'm experiencing something similar to #272, and I've spent like a day trying to get what goes wrong. My symptom is that Intellisense completely has stopped working in VS Code. And my best guess is that it's because of an OmniSharp failure I get every time I load any type of DNX project (see details below).

* Environment: Win7, 64-bit.
* Latest VS Code editor (0.5.0)
* DNVM/DNX installed [standalone](http://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-standalone). Currently on the latest beta7 (12302).

I've trimmed things down to the simplest possible project, based on [this getting started guide](http://docs.asp.net/en/latest/dnx/console.html), i.e a simple console app + a project.json.

Now, when I try opening said project in VS Code, the OmniSharp log goes like this:

```
Starting OmniSharp at 'c:\Users\Per\proj\dnx1'...
[INFORMATION:OmniSharp.Startup] Omnisharp server running on port '2000' at location 'c:\Users\Per\proj\dnx1' on host 8688.
[INFORMATION:OmniSharp.AspNet5.AspNet5Paths] Using runtime 'C:\Users\Per\.dnx\runtimes\dnx-clr-win-x64.1.0.0-beta7-12302'.
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] Scanning 'c:\Users\Per\proj\dnx1' for ASP.NET 5 projects
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] Found project 'c:\Users\Per\proj\dnx1\project.json'.
[ERROR:OmniSharp.AspNet5.DesignTimeHostManager] Failed to launch DesignTimeHost. Process exited with code 1.
``` 

Any kind of help or pointers would be appreciated!

**Comment by borgdylan** [comment]
Also happens on 0.6.0

**Comment by nosami** [comment]
This was fixed a few days ago in v1.1.1

**Comment by borgdylan** [comment]
is omnisharp-roslyn still on beta4?

**Comment by nosami** [comment]
Yes

**Comment by nosami** [comment]
Closing because this is a @code issue. /cc @jrieken

**Comment by nosami** [comment]
@per-samuelsson try this.

Download the latest omnisharp-roslyn release from [here](https://github.com/OmniSharp/omnisharp-roslyn/releases)

Set the OMNISHARP environment variable to c:\path-where-you-extracted-omnisharp\scripts\Omnisharp.cmd

**Comment by nosami** [comment]
Or try atom instead. The fix is bundled with Atom already.

**Comment by per-samuelsson** [comment]
> is omnisharp-roslyn still on beta4?

This was one of the things I wondered too, but couldn't seem to find information about. And related: since VS Code and OmniSharp seems quite bundled (i.e. OmniSharp comes as part of the installation), is there some way to see what OmniSharp bits are installed in a particular VS Code version?

Regardless of the above comment: thanks @nosami! I'll give your suggestions a try, and now I at least know what I suffer from, and on top of that, I also learned something about how OmniSharp operates. Cheers!

**Comment by per-samuelsson** [comment]
Downloaded latest bundle and set env variable as suggested in this https://github.com/OmniSharp/omnisharp-roslyn/issues/283#issuecomment-128486195, and still something funny going on with Intellisense, but it *did* make the OmniSharp server boot, so I'm definitely one step better. Thanks.

Notes to others if they try the same thing:

1)

> Set the OMNISHARP environment variable to c:\path-where-you-extracted-omnisharp\scripts\Omnisharp.cmd

The scripts folder is not there, OmniSharp.cmd in root (or I somehow messed up and got the wrong package).

2) I had to adapt OmniSharp.cmd to reference the Windows dnx.exe. It reference the mono-based one by default. Changing OmniSharp.cmd from `approot\packages\dnx-mono.1.0.0-beta4\bin\dnx.exe` to `approot\packages\dnx-clr-win-x86.1.0.0-beta4\bin\dnx.exe` did the trick for me.
