### ISSUE TITLE
Unsafe blocks shows error eventhough csproj has enabled them

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-roslyn#285]
I just wanted to try to add one feature for my C# project in omnisharp-atom and it shows errors in unsafe code eventhough my csproj has <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

To repro just download https://github.com/Bobris/BTDB and open root directory in atom to see it.

Sorry if this should be reported to omnisharp-server project.

see https://github.com/OmniSharp/omnisharp-atom/issues/403

**Comment by filipw** [comment]
Fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/309
