### ISSUE TITLE
build command results in 404 from server

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-roslyn#286]
I'm new to OmniSharp, so I don't know much yet about how to do a lot of troubleshooting.  After having failed to get a released version to work with DNX/project.json, I got the sources for the latest master (after the merge of the roslyn stuff) and tried that.  It kinda-sorta works, and I don't have all the red squigglies like before, but building doesn't work.  The following is produced in the OmniSharp output pane:

![image](https://cloud.githubusercontent.com/assets/1321/7109481/4c73fa50-e164-11e4-8cec-01ad85607ef5.png)

What did I do wrong?

Output of apm list:

```
C:\Users\Administrator\.atom\packages (7)
├── atom-html-preview@0.1.6
├── autocomplete-plus@2.9.0
├── language-csharp@0.5.0
├── language-cshtml@0.1.0
├── language-fsharp@0.8.4
├── merge-conflicts@1.3.0
└── omnisharp-atom@0.2.1
```

see https://github.com/OmniSharp/omnisharp-atom/issues/100

**Comment by willl** [comment]
Linking #451 to this issue.

**Comment by filipw** [comment]
The build command is not part of the server anymore.
