### ISSUE TITLE
Endpoint list

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#29]
## v1 endpoints

- [ ] /addreference
- [ ] /addtoproject
- [x] /autocomplete
- [ ] /buildcommand
- [ ] /buildtarget
- [x] /checkalivestatus
- [x] /checkreadystatus
- [x] /codecheck
- [x] /codeformat
- [x] /currentfilemembersasflat
- [x] /currentfilemembersastree
- [ ] /currentfiletopleveltypes
- [x] /findimplementations
- [x] /findsymbols

~~- [ ] /findtypes~~
- [x] /findusages
- [ ] /fixcodeissue
- [ ] /fixusings
- [ ] /getcodeactions

~~- [ ] /getcodeissues~~
- [ ] /getoverridetargets
- [x] /gotodefinition
- [x] /gotofile
- [x] /gotoregion
- [ ] /lookupalltypes
- [ ] /reloadsolution
- [ ] /removefromproject
- [x] /rename
- [x] /runcodeaction
- [ ] /runoverridetarget

~~- [ ] /semanticerrors~~
- [x] /stopserver

~~- [ ] /syntaxerrors~~
- [x] /typelookup
- [x] /updatebuffer

## new endpoints

- [x] /changebuffer
- [x] /formatRange
- [x] /formatAfterKeystroke
- [x] /signatureHelp

**Comment by CoreyKaylor** [comment]
Noticing when trying to use omnisharp-emacs with omnisharp-roslyn that there are errors for for /semanticerrors and saw it crossed out here. Is there a plan or workaround for this beyond not using flycheck w/roslyn?

**Comment by nosami** [comment]
`/semanticerrors', '/syntaxerrors' and '/codeissues' have been superseded by `/codecheck` which performs all 3 actions.

For now, you should probably manually patch it... see here
https://github.com/nosami/omnisharp-demo/blob/master/elpa/omnisharp-20141219.950/omnisharp.el#L980

and https://github.com/nosami/omnisharp-demo/blob/master/elpa/omnisharp-20141219.950/omnisharp.el#L128-L133

**Comment by CoreyKaylor** [comment]
Much better, thanks for the pointer.
