### ISSUE TITLE
Some themes don't contain @ui-lightness variable

### ISSUE THREAD

**Issue by mat-mcloughlin** [OmniSharp/omnisharp-roslyn#300]
There is a problem with two of the default Atom themes. They don't contain `@ui-lightness`. So omnisharp crashes out when it looks for it

**Comment by david-driscoll** [comment]
try v0.24.10

**Comment by nosami** [comment]
Also... wrong repo :)

**Comment by david-driscoll** [comment]
ahaha I didn't even notice, I just ripped out the css.

**Comment by mat-mcloughlin** [comment]
@nosami oops
