### ISSUE TITLE
Formatting options

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#31]
We need to serialize these http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.cs,dac739b7b8a53984

and http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Workspaces/Formatting/FormattingOptions.cs,2ce68197c6bbf674
into the config file, and load them on solution start into Workspace.Options

We also need a web UI for managing these.

**Comment by Mpdreamz** [comment]
Assigning this to me since I'm taking a stab at plugging editorconfig in. Finally making use of the rewrite to managed code :D https://www.nuget.org/packages/editorconfig

**Comment by jrieken** [comment]
:+1:
