### ISSUE TITLE
Flow diagnostics back from DTH to the editor

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-roslyn#313]
Today DTH has a rich set of diagnostics but they don't flow back the to the editor and we don't have a push based generalized way to push diagnostics. We might need to piggy back on codecheck though that's a v1 endpoint.

**Comment by david-driscoll** [comment]
Probably related to #229 to a degree.

**Comment by troydai** [comment]
We've moved to dotnet-cli base. DTH is retired.
