### ISSUE TITLE
What happened to UpdateBufferFilter (IActionFilter)?

### ISSUE THREAD

**Issue by ianbattersby** [OmniSharp/omnisharp-roslyn#328]
I'm just looking into why my incremental changes aren't working and I notice the `IActionFiler` that handled these on all requests (`UpdateBufferFilter`) - and not just `/updatebuffer - seems to have gone? Or has it been moved and I'm failing to find it? Any thoughts much appreciated.

**Comment by nosami** [comment]
See if this code is being hit https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn/BufferManager.cs#L59-L67

**Comment by willl** [comment]
It got shuffled/removed. https://github.com/OmniSharp/omnisharp-roslyn/commit/354bee47e488b55bb8aaf76714166be79d3ee407

**Comment by david-driscoll** [comment]
If buffer or changes is set on a request, they should pass through
automatically to /update buffer
On Thu, Nov 5, 2015 at 5:48 PM Jason Imison <notifications@github.com>
wrote:

> See if this code is being hit
> https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn/BufferManager.cs#L59-L67
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OmniSharp/omnisharp-roslyn/issues/328#issuecomment-154220611>
> .
>
-- 
Thanks,
David

**Comment by ianbattersby** [comment]
I'll have a look again tomorrow as when first moved to middleware it got invoked [here](https://github.com/OmniSharp/omnisharp-roslyn/commit/354bee47e488b55bb8aaf76714166be79d3ee407#diff-5cc7e564a536aefe4d44f812d0374bc3R126) but has obviously moved again.

**Comment by ianbattersby** [comment]
For the moment I've re-added the call in EndpointHandler as seen [here](https://github.com/OmniSharp/omnisharp-roslyn/commit/354bee47e488b55bb8aaf76714166be79d3ee407#diff-5cc7e564a536aefe4d44f812d0374bc3R126)

**Comment by david-driscoll** [comment]
It should be run by this code now https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Middleware/Endpoint/EndpointHandler.cs#L107-L115 .  Which will let buffer updates be handed off to other languages other than C#.

If it's not running, let me know the scenario and lets fix it.
