### ISSUE TITLE
Verbose logging contains &#65279;

### ISSUE THREAD

**Issue by ianbattersby** [OmniSharp/omnisharp-roslyn#331]
For some reason the verbose JSON being pushed out by the server contains an `&#65279;` character after the `Body:` tag but before the array. This upsets the json decoding in emacs ;(

``` json
{
    "Request_seq": 100,
    "Command": "autocomplete",
    "Running": true,
    "Success": true,
    "Message": null,
    "Body": ﻿[

    ],
    "Seq": 14,
    "Type": "response"
}
```

**Comment by ianbattersby** [comment]
Actually, and now seemingly obviously, this shouldn't be limited to verbose messages but anything with an array?!

**Comment by david-driscoll** [comment]
@ianbattersby any ideas what was/is going on?

**Comment by ianbattersby** [comment]
Not yet, it's still on my radar but thought I'd leave it here in case anyone else sees it. I'm going to check to see if it happens on Windows and take it from there.

**Comment by filipw** [comment]
This should be resolved now
