### ISSUE TITLE
DnxPaths does not load CoreCLR runtime

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-roslyn#336]
`DnxPaths.GetRuntimePathsFromVersionOrAlias` always looks for a mono version of the runtime, which will fail when users only have a coreclr version.

ASP.NET support for CoreCLR has improved enough lately that I often do not use dnx-mono at all for my dev projects. Is it possible to make omnisharp-roslyn work without mono?

**Comment by david-driscoll** [comment]
It is planned, I know @davidfowl is looking into it, as well as @troydai is making progress as well (see https://github.com/troydai/omnisharp-roslyn/tree/trdai/rc2)

Our current focus is trying to get off of beta4 (lol) and then also CoreClr support, while maintaining the code refactorings and other pieces that are currently only available on the desktop clr.

**Comment by natemcmaster** [comment]
@david-driscoll Ok. I couldn't find any issues already opened to track the work of adding more CoreCLR support. Feel free to close if this is issue is a duplicate.

**Comment by david-driscoll** [comment]
I leave it for now, because I don't think we have an issue tracking it either. :smile:

**Comment by NickolasAcosta** [comment]
Any updates on this?

**Comment by david-driscoll** [comment]
I merged the PR for the latest release, this should be available in the other editors shortly.
