### ISSUE TITLE
intelisense problem

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#346]
_From @MasoodRezazadeh on November 26, 2015 12:53_

there is no code suggestions for OVERRIDE ... last night it tooks till 6 AM for me to figure out that in DbContext i should  override OnConfiguring with DbContextOptionsBuilder parameter not DbContextOptions ... 

_Copied from original issue: Microsoft/vscode#709_

**Comment by jrieken** [comment]
Please provide details steps include a code sample so that we can understand and reproduce

**Comment by jrieken** [comment]
_From @MasoodRezazadeh on November 26, 2015 13:12_

```
public class AvaContext: DbContext
	{
		public DbSet<Place> Places { get; set; }
		public DbSet<Location> Locations { get; set; }
		
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
			
		}
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			var appEnv = CallContextServiceLocator.Locator.ServiceProvider
                            .GetRequiredService<IApplicationEnvironment>();
			optionsBuilder.UseSqlite($@"Data Source={appEnv.ApplicationBasePath}/../apiava/avaDB.db");
		}
    }
```

using EntityFramework 7 i created this context , for adding db connection query string ```OnConfiguring``` method should be overriden and in vscode intelisense not seggesting that or ```OnModelCreating```

**Comment by jrieken** [comment]
@MasoodRezazadeh Do I understand correctly that this is a feature request for IntelliSense helping you to implement a method?  Like so 

```
public class AvaContext: DbContext
    {
        public DbSet<Place> Places { get; set; }
        public DbSet<Location> Locations { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

        }
        OnCon<IntelliSense> -> Propose to override?
    }
```

**Comment by jrieken** [comment]
_From @MasoodRezazadeh on November 26, 2015 14:49_

@jrieken Yes i Thought this feature should be available for newbies like me

**Comment by jrieken** [comment]
ok. understood. moving to OmniSharp cos they drive the C# features

**Comment by david-driscoll** [comment]
It's possible it can be added, but we're waiting on the new service via #78, which would also solve the same problem.

**Comment by DustinCampbell** [comment]
This service probably wouldn't solve the problem precisely. "Override" completion has pretty specialized support since it has to do extra things like move the editor caret into the generated method. This is the same situation for XML doc comment completion (which moves the caret between the inserted start/end XML tags) and partial method completion after typing the "partial" keyword.

**Comment by 333fred** [comment]
@filipw I think this can be closed out, right?

**Comment by filipw** [comment]
yes we missed it somehow
