### ISSUE TITLE
NotSupportedException on Emacs: [Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /updatebuffer

### ISSUE THREAD

**Issue by dgalizzi** [OmniSharp/omnisharp-roslyn#356]
First: It's working on omnisharp-server but not with omnisharp-roslyn. I'm manually running the server. The function for checkalivestatus works but others don't (I tried autocomplete and /typelookup).

I tried debugging it, a few things I found:
* The exception thrown is at middleware.endpoint.endpointhandler.cs:170
* Same file on line 129 is returning null (model.FileName is fine):

> var language = _languagePredicateHandler.GetLanguageForFilePath(model.FileName ?? string.Empty); 

* Tried forcing language to LanguageNames.CSharp but then I got another exception: error : 

>[Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: C# does not support /updatebuffer System.NotSupportedException: C# does not support /updatebuffer  at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext() in [...]\omnisharp-roslyn\src\OmniSharp\Middleware\Endpoint\EndpointHandler.cs:line 163

I tried on both windows and linux, got the same. I'm using the latest code on master branch. I'm using emacs with the spacemacs configuration and the csharp layer which is using omnisharp 20150709.1045.

Thanks!

**Comment by david-driscoll** [comment]
cc @ianbattersby Have any idea about this issue?  I know you've been working on emacs a little bit lately.

**Comment by ianbattersby** [comment]
I suspect this might relate to the issue see before with the newer Roslyn branch that when emacs doesn't send the file name the server logic differs because it can't establish the language from the file extension.

I'll try and dig that out for reference. I'm likely not seeing this myself because my in-development version sends the file name with every request.

I'll try and get some time tomorrow to play with the current master branch and see if I can replicate however, rather than hypothising :)

**Comment by ianbattersby** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/issues/324#issuecomment-153787076

**Comment by david-driscoll** [comment]
What request is trying to make where it's not setting a filename?

To resolve this one, I'm not against defaulting the language to C#, instead of throwing an exception, I just want to make sure it'll work.

**Comment by dgalizzi** [comment]
It is setting the filename but not the language. I tried defaulting to C# but then I got another error (/updatebuffer not supported for C#), exports is empty at: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Middleware/Endpoint/EndpointHandler.cs#L156 so it can't get the handler for the language.

**Comment by david-driscoll** [comment]
I'm thinking something like #357, just assume C# if we can't determine it by default.

**Comment by david-driscoll** [comment]
Now I have no idea if #357 works, but feel free to test it out, and let me know if it helps with your issue.

**Comment by ianbattersby** [comment]
@dgalizzi Can you confirm the SHAs of your Roslyn and emacs branches and I'll have a play this end too. If defaulting language or pushing file and still isn't working then I'm a bit lost. My current wip version does incremental changes but it still uses /updatebuffer so haven't seen that error before.

**Comment by dgalizzi** [comment]
This issue got fixed by #358 even without sending the language or defaulting it.

**Comment by david-driscoll** [comment]
good to hear, sorry about causing the issue!

**Comment by ianbattersby** [comment]
Nice one guys, good spot :)

**Comment by filipw** [comment]
this is fixed already
