### ISSUE TITLE
OmniSharp failed to parse C# code with right syntax

### ISSUE THREAD

**Issue by GuidC0DE** [OmniSharp/omnisharp-roslyn#359]
Environment: OS X, Unity3D, VS Code

I found an issue that OmniSharp can't parse following code:
```
float mslt = minShurikenLifetime<.00001f?.00001f:minShurikenLifetime;
```
This code is in Particle Playground asset for Unity3D https://www.assetstore.unity3d.com/en/#!/content/13325
I use version 2.24
The problem is in file PlaygroundParticlesC.cs, method UpdateShuriken()

OmniSharp produces following errors:
```
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Unexpected symbol `1E-05', expecting `.' or `['
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Unexpected symbol `1E-05', expecting `.' or `['
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Unexpected symbol `1E-05', expecting `.' or `['
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Unexpected symbol `1E-05', expecting `.' or `['
```

When I changed this code to
```
float mslt = minShurikenLifetime<.00001f? .00001f:minShurikenLifetime;
```
OmniSharp parsed it well.

But I can't reproduce the issue just by creating the same construction in my own code. It seems the issue is reproducing only in context of whole PlaygroundParticlesC.cs

But this asset is not free, so I think I can't share its code. So, maybe if someone who has this asset and knows OmniSharp inside well will fix? Or maybe I'll try to play around this construction and find another way to reproduce.

**Comment by david-driscoll** [comment]
That's very odd... I wonder if it's a compiler bug?  @DustinCampbell do you have any idea if this might roslyn?

**Comment by DustinCampbell** [comment]
Well, it certainly looks like a compiler issue.

**Comment by david-driscoll** [comment]
Lets hold off on jumping on it until we settle on the dotnet cli, it's possible it's fixed at this point.

**Comment by DustinCampbell** [comment]
Sure thing

**Comment by GuidC0DE** [comment]
It seems the problem is not reproducible anymore with the latest VS Code

**Comment by DustinCampbell** [comment]
Interesting. I guess it got fixed, though I wish I knew where the bug had been. :smile:

**Comment by filipw** [comment]
This can be closed as not reproducible then?

**Comment by GuidC0DE** [comment]
I think, yes, so I'm closing it
