### ISSUE TITLE
Use MSBuild Solution-parsing API

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#36]
Currently, there are some files copied over from Roslyn to handle solution parsing. Eventually, the new MSBuild solution parsing API should be used, which is coming in MSBuild v12.

[SolutionFile](http://msdn.microsoft.com/en-us/library/microsoft.build.construction.solutionfile%28v=vs.121%29.aspx)
[SolutionConfigurationInSolution](http://msdn.microsoft.com/en-us/library/microsoft.build.construction.solutionconfigurationinsolution%28v=vs.121%29.aspx)

**Comment by nosami** [comment]
I created an issue requesting a nuget package https://github.com/Microsoft/msbuild/issues/45

**Comment by DustinCampbell** [comment]
This was fixed with #832.
