### ISSUE TITLE
Omnisharp times out when getting started

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#360]
_From @rhires on November 21, 2015 5:30_

I'm not sure how to view any kind of log besides the basic one that vscode already provides to see what's going on with it, but for whatever reason Omnisharp fails to start because it says that it took too long. I'm happy to provide more detail for this issue, if I can get some direction on where to get the info to provide. :-)

_Copied from original issue: Microsoft/vscode#395_

**Comment by jrieken** [comment]
@rhires Can you provide the omnisharp log (Cmd+L,L)

**Comment by jrieken** [comment]
_From @rhires on November 25, 2015 0:43_

[INFO] Starting OmniSharp at '/Users/localuser/Projects/TestProject'...
[INFO] Started OmniSharp from '/Applications/VSCode-darwin-signed/Visual Studio Code.app/Contents/Resources/app/extensions/csharp-o/bin/omnisharp' with process id 62537...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/localuser/Projects/TestProject' on host 62510.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/localuser/.dnx/runtimes/dnx-mono.1.0.0-rc1-final'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/localuser/Projects/TestProject' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/localuser/Projects/TestProject/project.json'.
Process ID 62558
Listening on port 64190
Listening on port 64190
[ERROR:OmniSharp.Dnx.DesignTimeHostManager] Failed to launch DesignTimeHost in a timely fashion.
[ERROR] Error: Failed to start OmniSharp

**Comment by jrieken** [comment]
_From @DiegoZoracKy on December 3, 2015 19:20_

@rhires 

I had the same problem but updating to 0.10.3 solved it.

**Comment by jrieken** [comment]
_From @rhires on December 4, 2015 1:53_

Cool. Just got the vscode 0.10.3 update. I thought you meant a separate update for omnisharp. We'll see if I continue having the time out issue. It isn't a consistent thing. Meanwhile: Interesting. I notice that the update date is 11-26-15...and vscode didn't tell me there was an update. Time for a new issue: "VScode "checking for updates" hangs and doesn't check for updates.

**Comment by jrieken** [comment]
_From @DiegoZoracKy on December 4, 2015 2:5_

@rhires I should have mentioned "vscode". And yes, i agree about the new issue. Like it was for you, vscode didn't tell me anything about the update.

**Comment by jrieken** [comment]
@rhires @DiegoZoracKy Do you guys have mono installed or is it just coreclr?

**Comment by jrieken** [comment]
_From @rhires on December 4, 2015 18:47_

Mono here...a fairly up-to-date version, too. I'll have to come back and say which version.

**Comment by jrieken** [comment]
_From @wolfspider on December 5, 2015 9:30_

I have an IMac at my office where everything works perfectly however I also have a Macbook Pro where this problem has been a continual issue. I have tried reinstalling VSCode (I'm on 0.10.3) and even getting OmniSharp from Github and running it purely from there as well which generates the same error. Right now I'm running Mono version 4.2.1 as well. I don't need to start VSCode to see the error just OmniSharp inside VSCode- if that narrows it down at all:

Jesses-MacBook-Pro:WebApplication jessebennett$ dnvm use 1.0.0-beta8 -p
Adding /Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8/bin to process PATH
Updating alias 'default' to 'dnx-mono.1.0.0-beta8'
Jesses-MacBook-Pro:WebApplication jessebennett$ "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/csharp-o/bin/omnisharp"
info    : [OmniSharp.Startup] Omnisharp server running on port '2000' at location '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' on host -1.
info    : [OmniSharp.Dnx.DnxPaths] Using runtime '/Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8'.
info    : [OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' for DNX projects
info    : [OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/project.json'.
Process ID 1523
Listening on port 49496
error   : [OmniSharp.Dnx.DesignTimeHostManager] Failed to launch DesignTimeHost in a timely fashion.

In the source code for OmniSharp I see the socket timeout ~30 seconds before generating this error mesage. I've tried reinstalling Mono from the Xamarin website as well as from homebrew. Both the MBP and IMac have the latest stable release of El Capitan. On this same MacBook DNX has always restored and built everything just fine. Kestrel runs, starts, and stops just fine as well. The DesignTimeHost process however seems to get orphaned every time this happens and multiple instances will just get "stuck".

**Comment by jrieken** [comment]
_From @rhires on December 5, 2015 13:1_

Hooray Open Source! So you were digging around in the code...roughly where were you looking? I'm curious if you saw anything about increased logging level or anything like that. Maybe we can turn up the logging level to see what else it might be doing. Or, we could custom build something for ourselves with lots of extra logging to see what's up...or maybe link this issue to the OmniSharp team? See if they can help?

**Comment by jrieken** [comment]
_From @wolfspider on December 5, 2015 19:49_

I was looking at the code in the Omnisharp-Roslyn project inside the file DesignTimeHostManager.cs inside the OmniSharp.Dnx folder. Beginning at line 100 we have this routine:

// Wait a little bit for it to conncet before firing the callback
                using (var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
                {
                    var t1 = DateTime.UtcNow;
                    var dthTimeout = TimeSpan.FromSeconds(30);
                    while (!socket.Connected && DateTime.UtcNow - t1 < dthTimeout)
                    {
                        Thread.Sleep(500);
                        try
                        {
                            socket.Connect(new IPEndPoint(IPAddress.Loopback, port));
                        }
                        catch (SocketException)
                        {
                            // this happens when the DTH isn't listening yet
                        }
                    }

                    if (!socket.Connected)
                    {
                        // reached timeout
                        _logger.LogError("Failed to launch DesignTimeHost in a timely fashion.");
                        return;
                    }
                }

Here is my console output for when I try to run OmniSharp directly from source:

Jesses-MacBook-Pro:omnisharp-roslyn jessebennett$ ./scripts/Omnisharp -s /Users/jessebennett/Documents/vnext/yeoman/WebApplication/ -p 48971
info    : [OmniSharp.Startup] Omnisharp server running on port '48971' at location '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/' on host -1.
info    : [OmniSharp.Dnx.DnxPaths] Using runtime '/Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta4'.
info    : [OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/' for DNX projects
info    : [OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/project.json'.
info    : [OmniSharp.Dnx.DesignTimeHostManager] Listening on port 49517
error   : [OmniSharp.Dnx.DesignTimeHostManager] Failed to launch DesignTimeHost in a timely fashion.

What you can see here is the issue is replicated on the OmniSharp side and even their script selects the Beta4 runtime correctly but yet we see the same error. The socket is created from a reference in System.Net.Sockets which is pretty low level in the stack compared to the other vnext features. This I suspect may be an issue with Mono creating sockets so it may be a good test to create some code that simply opens a socket in this manner using something like Xamarin studio. If that works (and there is a good possibility that it would) then absolutely it would be OmniSharp but on their issues list they have closed out multiple DesignTimeHost issues indicating that mitigating this involves building OmniSharp from source and getting VSCode to pick it up. Obviously, that didn't work for me and I'll just warn you the monolithic build script which goes into their Test suite has always had problems completing the tests. So what I'm saying is if your try and build it- it takes a little while but you will get a working OmniSharp out of it even if the CSharp tests don't complete 100% just give it a try to see if it did get built. I tried extending the timeout to 100 seconds and rebuilt it but still got the same problem.

**Comment by jrieken** [comment]
_From @wolfspider on December 5, 2015 23:30_

Ok, I managed to get this to work by killing the conditional statement for awaiting the socket connection and binding to 127.0.0.1 instead of using the loopback adapter. I would only suggest this if you don't mind getting your hands a little dirty and *desperate* to get this to work. Also, not really sure why this works so that in itself is problematic- I'll try to do some more testing later to see where this is going wrong. 

Here is a gist of my updated Design Time Host Manager file: https://gist.github.com/wolfspider/79512b40a9dd25035420 

Once you rebuild omnisharp edit your ~/.bash_profile script with an export statement like so to change where VSCode runs omnisharp from:

export OMNISHARP="/Users/jessebennett/Documents/omnisharp-roslyn/scripts/Omnisharp"

After you do that you should see VSCode come up with the modified path in the log for Omnisharp, just like in the attached screenshot I included. 

![dthsocket](https://cloud.githubusercontent.com/assets/4861700/11610832/c550870e-9b7c-11e5-9df3-86dddb5f4d25.png)

**Comment by jrieken** [comment]
_From @rhires on December 6, 2015 1:28_

Hmmm...you're a better coder than I...so basically, explicitly spelling out the loopback works, rather than what should be the constant (string). So maybe that's failing somehow. `socket.connected` thinks it's not connected. I wonder if the Mac OS is returning something in a way that is different than what Windows might return. Totally guessing here.

**Comment by jrieken** [comment]
_From @wolfspider on December 6, 2015 2:22_

@rhires That is definitely possible, nowadays the loop back adapter is a
reference to IPv6 local address. Specifying an IPv4 address like 127.0.0.1
keeps it from binding there. That change alone didn't do it so then I had
to remove the requirement to wait for a socket to be open. There is also
the possibility that the omnisharp build process generates unreliable
results on my MacBook and I just built it so many times that something
finally hooked up right- eventually I did get one passing build but most of
the time it would fail with the "too many files open" error during csharp
tests and I already have the mono filesystemwatcher fix in my bash profile.
The answer is between those two issues somewhere and when I can look at it
again I can help narrow this down.

**Comment by jrieken** [comment]
_From @wolfspider on December 6, 2015 17:23_

@rhires Alright mang, I wrote a simple socket tester with the internals of DTH you can find here:

https://github.com/wolfspider/ConsoleSocketTest

It *does* fail to bind so we can rule out the build weirdness. Here is my console output from this little experiment:

Jesses-MacBook-Pro:ConsoleApplication jessebennett$ cd '/Users/jessebennett/Documents/vnext/yeoman/ConsoleApplication' ; /Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8/bin/dnx ConsoleApplication
Port Created at: 49432
Now trying to bind...
Socket not Connected!

I think this may in fact be a Mono problem and not necessarily an OmniSharp issue but don't know enough to say why it works on some computers and not others.

**Comment by jrieken** [comment]
Thanks for the insights guys. First, I'll move this to omnisharp, then we tackle it there. @wolfspider I hear there is two changes (1) IPv4, IPv6 and (2) don't wait. Is that right. Do you want to do a PR against OmniSharp?

**Comment by wolfspider** [comment]
I would totally be down for a PR except after putting VSCode to much more use testing this fix I found that sometimes I need to restart omnisharp and then it all syncs up. Did some more research on this issue and found this is something that is even common in the .NET framework and has been for a while:
http://stackoverflow.com/questions/2661764/how-to-check-if-a-socket-is-connected-disconnected-in-c

On sunday I rewrote DTH to poll for the socket connection and it certainly did not like that (causes an exception) so I think we can do something better to ensure everything is warmed up and try to poll better. Going to have to channel some creative energies to find a fail-safe way to do this but we have quite a few options in .NET luckily. So..socket.connected is living up to its reputation in my case and when I have to restart it- it really is not working initially. Here is my log from when it fails to run and needs to be restarted after:

[INFO] Starting OmniSharp at '/Users/jessebennett/Documents/vnext/yeoman/WebApplication'...
[INFO] Started OmniSharp from '/Users/jessebennett/Documents/omnisharp-roslyn/scripts/Omnisharp' with process id 839...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' on host 827.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/project.json'.
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Process ID 851
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Listening on port 50314
[ERROR] Error: Failed to start OmniSharp
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Running teh DesignTimeHost on port 50314, with PID 851
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Connected
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:50314
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/Users/jessebennett/Documents/vnext/yeoman/WebApplication'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/jessebennett/Documents/vnext/yeoman/WebApplication'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
[INFO] Starting OmniSharp at '/Users/jessebennett/Documents/vnext/yeoman/WebApplication'...
[INFO] Started OmniSharp from '/Users/jessebennett/Documents/omnisharp-roslyn/scripts/Omnisharp' with process id 860...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' on host 827.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/jessebennett/Documents/vnext/yeoman/WebApplication' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/jessebennett/Documents/vnext/yeoman/WebApplication/project.json'.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/jessebennett/.dnx/runtimes/dnx-mono.1.0.0-beta8'.
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Listening on port 50321
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Process ID 868
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Running teh DesignTimeHost on port 50321, with PID 868
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Connected
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:50321
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/Users/jessebennett/Documents/vnext/yeoman/WebApplication'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/jessebennett/Documents/vnext/yeoman/WebApplication'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading

**Comment by willl** [comment]
Keep in mind is that the DesignTimeHost is going away when we move to [.NET CLI](https://github.com/dotnet/cli). 

@troydai has been working on that move here: https://github.com/troydai/omnisharp-roslyn/tree/trdai/cli 

That's not to say that a PR should not be submitted to fix the issue right now prior to the .NET CLI work being merged in.

**Comment by wolfspider** [comment]
@will Thanks for the heads up- this sounds promising and looking forward to a standard CLI!

I put some more duct tape on the sockets, as per the code on SO we're checking the socket, priming it, and seeing if its available. Figure we could do the same with the project system as well so put the same code in there too. Decided to implement the Nagle algorithm by setting NoDelay and also turned on KeepAlive as it seems to be turned off by default according to Xamarin docs. 

DesignTimeHostManager:
https://gist.github.com/wolfspider/de8b01eda0a57bfaa4ec

DnxProjectSystem:
https://gist.github.com/wolfspider/498d10146838f70a1a77

Also, what is necessary is the timeout in VSCode was set to 1 minute apparently so I increased to 5- that's where it was terminating most often on my stressed out MBP:

(VSCODE)
omnisharpServer.js in the csharp-o extensions:
https://gist.github.com/wolfspider/a4d7f340ee4f4d4d44e9

To save you some time there all I did was update this code on line 384 to this:
StdioOmnisharpServer.StartupTimeout = 1000 * 60 * 5;

@jrieken I feel more confident with this and its performing much better, if it's alright then we can do a PR if you'd like. I don't like putting the same code in two files like this so I'm sure it can be written better but don't know where to put the isSocketConnected since its just a one liner and mainly there for testing. Let me know what you think. Thanks.

**Comment by wolfspider** [comment]
updated the project system gist with the correct file this time.

**Comment by wolfspider** [comment]
@jrieken After having done a lot more testing I found that you can only query the socket correctly after binding the socket in this case. Have decided to go with an asynchronous connection polling method I've written into a SocketConnection utility class. It connects fast enough now to run without modifying the 1 min timeout in VSCode so no need to change that at all. There is no need to declare the 127.0.0.1 ip address any more either. The timeout on the initial DTH connection was always being exceeded so I've been able to fix that but still check for connection errors within that window of time.

DesignTimeHostManager:
https://gist.github.com/wolfspider/de8b01eda0a57bfaa4ec

DnxProjectSystem:
https://gist.github.com/wolfspider/498d10146838f70a1a77 

Socket Connection Class which would go into Utilities folder:
https://gist.github.com/wolfspider/d983a27d239fc5fa10e3

**Comment by wolfspider** [comment]
@jrieken I've gotten a chance to run this on another Mac and think I am ready to do a PR now this makes VSCode start up much faster

**Comment by troydai** [comment]
We've moved to `dotnet-cli` base. `DTH` is retired.
