### ISSUE TITLE
Support for IronPython

### ISSUE THREAD

**Issue by mostaphaRoudsari** [OmniSharp/omnisharp-roslyn#372]
I first posted this wish [here](https://github.com/OmniSharp/omnisharp-atom/issues/593) but it seems here is the right place to send this.

Any chance that omnisharp can be used for IronPython development?

In case it helps, [Visual Studio has a plugin](http://microsoft.github.io/PTVS/) which is available for free and is open source.

**Comment by DustinCampbell** [comment]
I think it's unlikely that we'll do this. If someone want to create an OmniSharp plug-in for IronPython, that'd be awesome. However, there are currently no plans.
