### ISSUE TITLE
WantImportableTypes on AutoCompleteRequest is not being used

### ISSUE THREAD

**Issue by alistair** [OmniSharp/omnisharp-roslyn#373]
I am currently in the process of trying to update YouCompleteMe to omnisharp-roslyn and have noticed that the completions functionality seems to have regressed on respecting the WantImportableTypes functionality.

I think its actually pretty important and useful.

see the original code here
https://github.com/OmniSharp/omnisharp-server/blob/e1902915c6790bcec00b8d551199c8a3537d33c9/OmniSharp/AutoComplete/AutoCompleteHandler.cs#L62

As a use case given you have a file like

```
using System;
namespace testy
{
    public class ImportTest
    {
        public static void Main (string[] args)
        {
            new Date
        }
    }
}
```

The original omnisharp when called via a POST to /autocomplete with a body of

```
{'column': 12, 'WantImportableTypes': True, 'buffer': 'using System;\n\nnamespace testy\n{\n\tpublic class ImportTest\n\t{\n\t\tpublic static void Main (string[] args)\n\t\t{\n\t\t\tnew Date\n\t\t}\n\t}\n}\n', 'WantDocumentationForEveryCompletionResult': True, 'ForceSemanticCompletion': True, 'line': 9, 'filename': '/home/alistair/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/cs/testdata/testy/ImportTest.cs'}
```

Would return a response containing DateTimeStyles even tho this exists within the System.Globalization namespace which isn't imported in the code sample.

**Comment by filipw** [comment]
renamed the issue to something more descriptive

Unfortunately, turns out at the moment the code is not even checking what the client sends in `WantImportableTypes`

**Comment by rokadias** [comment]
+1

Expected this to work in omnisharp-emacs as a work around for importing namespaces.

**Comment by filipw** [comment]
This is implemented in https://github.com/OmniSharp/omnisharp-roslyn/pull/1896 for the new completion service.
We will not support it for the old endpoint.
