### ISSUE TITLE
Question:  What other editors are using the github release output?

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-roslyn#378]
Omnisharp-node-client (used by atom) uses releases to pull it's artifacts over from this repo.  Are any other editors using releases as well?
https://github.com/OmniSharp/omnisharp-roslyn/releases

I ask, because as part of RC2 work, I added coreclr packages. Those coreclr packages, currently only come from the travis linux vm.  The problem with this, is that some `darwin` bits will be missing, making these packages fail to run on the coreclr on a mac machine.

I'd like to have the following binary released versions available, this will make the overall file size smaller for distribution (assuming distribution is by operating system)
- `Windows CLR x86`
- `Windows CoreCLR x86`
- `Windows CLR x64`
- `Windows CoreCLR x64`
- `Linux CoreCLR x64`
- `Darwin CoreCLR x64` (mac)
- `Mono`
- `None`

This would give us a distribution of something like, this would be breaking for any consumers that currently consume `omnisharp.tar.gz` today.
- `omnisharp-clr-win-x86.zip`
- `omnisharp-coreclr-win-x86.zip`
- `omnisharp-clr-win-x64.zip`
- `omnisharp-coreclr-win-x64.zip`
- `omnisharp-coreclr-linux-x64.tar.gz`
- `omnisharp-coreclr-darwin-x64.tar.gz`
- `omnisharp-mono.tar.gz`
- `omnisharp.zip` (would contain no runtime)
- `omnisharp.tar.gz` (would contain no runtime)

Then on the editor plugin side or omnisharp-node-client, we can install the correct runtime for the given environment the user is running on.

**Comment by robbert229** [comment]
Omnisharp-sublime currently just ships with the omnisharp-server inside of it, I would like to use releases in the future migrate to using releases though.

**Comment by mispencer** [comment]
I'm currently just cloning omnisharpserver and building it as part of the larger building process. Is there a benefit to using the release packages?

**Comment by david-driscoll** [comment]
@mispencer it just depends on your release process and cadence, with the release package you know that specific version is available, and when you clone with some code break that it won't break the editor intentionally.

For local testing atom/vscode support he `OMNISHARP` environment variable to locate a custom executable OmniSharp

**Comment by filipw** [comment]
closing this as expired
