### ISSUE TITLE
ubuntu 14.04 c# intellisense

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#380]
_From @iwnow on January 16, 2016 23:21_

not working intellisense .cs files, when i start type using namespace, it's not appears my namespaces from project.json file after dnu restore. Ver: 0.10.6

_Copied from original issue: Microsoft/vscode#2063_

**Comment by iwnow** [comment]
I've solved the problem to installed the last mono runtime, may closed.

**Comment by jrieken** [comment]
ok. thanks for getting back to us
