### ISSUE TITLE
RC2 release and OS X

### ISSUE THREAD

**Issue by wolfspider** [OmniSharp/omnisharp-roslyn#391]
I tested this on OS X and the build fails during CoreCLR tests which I can understand but OmniSharp seems broken as well although it builds just fine with RC2-16430. Is OS X support something we are waiting on/working on for RC2 still where OmniSharp is concerned? Here is the output from the Tests:

xUnit.net DNX Runner (64-bit DNX 4.5.1)
  Discovering: OmniSharp.Stdio.Tests
  Discovered:  OmniSharp.Stdio.Tests
  Starting:    OmniSharp.Stdio.Tests
  Finished:    OmniSharp.Stdio.Tests
=== TEST EXECUTION SUMMARY ===
   OmniSharp.Stdio.Tests  Total: 6, Errors: 0, Failed: 0, Skipped: 0, Time: 0.350s
~/Documents/omnisharp-roslyn
Adding /Users/jbennett/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc2-16430/bin to process PATH
~/Documents/omnisharp-roslyn/tests/OmniSharp.Tests ~/Documents/omnisharp-roslyn
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Runner.Dnx.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.Dnx.Program.Run(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
Tests failed for tests/OmniSharp.Tests with runtime coreclr

And here is what I see with OmniSharp:
is-jessie-mac:omnisharp-roslyn jbennett$ ./scripts/Omnisharp -s /Users/jessebennett/Documents/vnext/yeoman/WebApplication/ -p 48971
Error: Unable to resolve project from /Users/jbennett/Documents/omnisharp-roslyn

**Comment by wolfspider** [comment]
I think I am going to wait until the dust settles again looks like a lot of things are being moved around in addition to your team making some pretty big changes with the project management.

**Comment by troydai** [comment]
@wolfspider indeed it is in the process of a huge changes. The recent PR (https://github.com/OmniSharp/omnisharp-roslyn/pull/392) should be able to unblock you. But it may be broke any minute in the future.

**Comment by wolfspider** [comment]
@troydai Thanks for the info I'll take a look when I get a chance soon and will keep what you said in mind

**Comment by troydai** [comment]
@wolfspider `master` branch is reversed to last stable status which is `beta8`. In the meantime, `dev` branch is updated to use [dotnet-cli](https://github.com/dotnet/cli) to build and all packages versions are pinned. So both branches are stable. 

Is it ok if I close this issue?

**Comment by wolfspider** [comment]
Yeah should be fine to close it. admittedly ive been neck deep in work
related demos and haven't had the time to review Roslyn much at all
unfortunately. This issue was mainly just to ask if it was done and that
seems to be the case now.

**Comment by troydai** [comment]
Thanks @wolfspider . I’ll close this issue for now. Feel free to open new ones if you find anything wrongs with the `dev` branch.
