### ISSUE TITLE
QuickFix generate method should not add using directive

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#393]
_From @nixbb on February 1, 2016 9:36_

`editor.action.quickFix` currently adds a `using System` directive to the containing file when generating methods.

This is not always convenient and often means that the using has to be removed once the method has been fully implemented.

A lighter approach would be to change the generated method's body to `throw new System.NotImplementedException();` instead.

_Copied from original issue: Microsoft/vscode#2603_

**Comment by filipw** [comment]
Is this really something that should be done or is it more of an individual preference thing?
Sounds more like the latter to me

**Comment by nixbb** [comment]
Since it's a temporary reminder to implement the body of the method I don't think it's correct to assume that a new directive should be added to the file. Changes should be limited to the method block only.

**Comment by DustinCampbell** [comment]
FWIW, OmniSharp doesn't really control this. It's coming from Roslyn. The problem isn't really that GFU adds usings -- that can be kind of nice in many cases. It's really a problem with adding the using for "NotImplementedException". We should stop doing that. :smile:

The bug tracking this in Roslyn is https://github.com/dotnet/roslyn/issues/8257.
