### ISSUE TITLE
Suggestion: Cross-platform build script

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#396]
I’m updating the build tool chain from DNX to dotnet-cli now. To enable the build on different platforms, I have to write both bash script and ps1/batch script for cross-platform build. This is a long-term maintenance cost. I’m wondering if we can exploring the possibility of using a unified cross-plaform script language or tool to drive the build.

**Comment by david-driscoll** [comment]
One of my friends was looking to get involved and wanted to build a Cake script, then we would just bootstrap the cake build for windows and osx.

I know he has made some progress, but there might be some issues with the exports in `build.sh` today.

Personally I like the idea of a Cake script, as long as it can fill our needs.  It does offer some more abstractions over what say ScriptCS has today, specifically with building and running tasks, etc.  It also keeps us in the ".NET" world so to speak.  The only gotcha I see is that in order for the build to complete the travis environment will still need to have mono installed.

cc @RLittlesII

**Comment by troydai** [comment]
I'm interested in the progress of the project. Do we already have a running prototype/version or it is still in development? The major concerns about using a newly developed tool is it will be lack of tooling support and takes time to mature.

**Comment by RLittlesII** [comment]
I have started development of the cake script.  I have been active in the cake gitter channel around some of the environment variable concerns.  I haven't pushed any changes to my fork yet.  Sounds like the need is sooner than later.  I know there is DNU support in Cake, there is currently a PR in for dotnetcli.  I would be glad to talk through the requirements of the new script.

**Comment by devlead** [comment]
:+1: @RLittlesII just ping me @patriksvensson or @gep13 or raise an issue if you encounter any obstacles/concerns with @cake-build

**Comment by hal-ler** [comment]
I have made a pull request to make it possible to set the install path for dotnetcli as a command line argument instead of being forced to use the environment. This functionality already existed in the linux script, but not the powershell one. Using this change I was able to quickly create a Cake script which builds the dnxcore50 variant on Windows (and should work for Linux as-well, but still need to test).

The only other environment variables which I can see right now, are the ones related to the reference assemblies, which can also be set in the bootstrapping linux shell script.

https://github.com/dotnet/cli/pull/1701

**Comment by troydai** [comment]
@hal-ler I just pinged a few guys on the cli team to review and sign off the change.

**Comment by RLittlesII** [comment]
@troydai I haven't made much progress on this.  I have been struggling to get omnisharp to build on my mac.  I haven't moved much further on the script, I just resolved some dotnet pathing issues last week.  I'll take a look at this and see if I can get dotnet to build the project and run the unit tests with the cake script.

**Comment by niemyjski** [comment]
I have a solution... Bring powershell to the other platforms... We can bring linux to windows there is no reason powershell can't work on linux and osx!

**Comment by troydai** [comment]
Thanks @niemyjski. I'm not aware of Powershell's plan. Sounds nice through. 

@hal-ler has merged the cake scripts week ago. It is issue is indeed fixed. 

Thanks all.
