### ISSUE TITLE
[dev] Automatically configure the DOTNET_REFERENCE_ASSEMBILES_PATH variable if it not set.

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#412]
The variable is required by dotnet to compile projects which target desktop CLR. It’s usually missing on most environment. Once it is missing Roslyn will fail to resolve any BCL types and there is no intuitive error or warning for user to correct their environment.

**Comment by troydai** [comment]
Alternative solution: Fail and send warning early if mono is missing.

**Comment by anurse** [comment]
I'd suggest closing this without fixing in favor of fixing https://github.com/dotnet/cli/issues/531

**Comment by troydai** [comment]
Issue is fixed on __dotnet-cli__. Now __OmniSharp__ needs to update its dependencies to leverage the fix.

**Comment by troydai** [comment]
Fixed in 952c3fde16bf1abc6f3075a5e0dc25828516ce61
