### ISSUE TITLE
[dev] Intellisense in project.json is broken / missing

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#413]
### Scenario
1. Open asp.net project
2. Open project.json
3. Type half package name

### Expectation
Intellisense prompt potential package candidates.

**Comment by troydai** [comment]
Fixed in 7c55ca1

**Comment by GuardRex** [comment]
We're seeing this today (4/5) discussing OmniSharp (v1.0.993) in VS Code: Some look-ups in `project.json` are good, but others (Mvc here for example) are not shown ...

![capture](https://cloud.githubusercontent.com/assets/1622880/14293908/388d0a14-fb34-11e5-9b5c-867f482a00a3.PNG)

Our situation today is covered by this known issue, correct? ... so we just need to give it some time?

**Comment by Ciantic** [comment]
For me it only gives one suggestion:

![image](https://cloud.githubusercontent.com/assets/64731/14294172/6676d5d8-fb78-11e5-826b-ae7a074cdd54.png)

Basically all RC2 stuff "Microsoft.AspNetCore." is not autocompleting at all, but stuff like "Microsoft.AspNet." works.

**Comment by david-driscoll** [comment]
the default provider (as far as I'm aware) for vscode intellisense only supports the main nuget feed, and one of the ci feeds.

**Comment by GuardRex** [comment]
idk if @Ciantic has the same ones I do, but that might at least explain the difference between us on what is getting looked-up. Here's the set I'm using, which came from a very old David F. example app ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <!-- <add key="AspNetVolatile" value="https://www.myget.org/F/aspnetvolatiledev/api/v3/index.json" /> -->
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
    <add key="AspNetvNext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
  </packageSources>
</configuration>
```
Side Note: I only go volatile if things get really nasty and only as a temp workaround; I've only un-commented that line twice ever and only used it for a few days each time. It's just there to keep the link handy.

**Comment by troydai** [comment]
who provides these reference? VS code itself or omnisharp?

**Comment by Ciantic** [comment]
@troydai looks like this has nothing to do with OmniSharp, if I start the vscode without omnisharp (checked from process explorer) it still autocompletes same entries. 

Maybe this is some VS Code feature, and instead it should be configured to use OmniSharp in projects.json.

**Comment by troydai** [comment]
Close this here, since it is tracked in VS Code.
