### ISSUE TITLE
[dev] Package published build correctly

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#421]
1. `zip` for Windows, `tar` for *nix
2. Correct file name

**Comment by david-driscoll** [comment]
Tday we drop artifacts from both the Linux travis machine, the Osx travis machine, and the appveyor machines.

Linux provides us with the linux packages, and they're uploaded via the [`.travis.yml`](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/.travis.yml#L35).

On Appveyor they're uploaded by [`appveyor.yml`](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/appveyor.yml#L7-L14)

In both cases, the drop target is `artifacts/`.

Windows assumes zip files, and builds for both x86 and x64 targets.
Linux assumes tarballs, and only builds for x64 targets
Osx assumes tarballs, and only builds for x64 targets.
Linux also builds and publishes the Mono based release.

With Troy's changes, that shifts around a little bit, we can build multiple runtimes per environment.

While it might make more sense to use one CI environment to build all 3, I do like the idea of the CI environment building and publish their own assets, for one reason and one reason only.  If that build fails, a failing asset for that platform _doesn't_ get pushed, which helps track down the error sooner.

**Comment by hal-ler** [comment]
Pushed: https://github.com/OmniSharp/omnisharp-roslyn/pull/425

Is there a way to push only specific tar.gz files on Travis depending on the OS?

**Comment by david-driscoll** [comment]
In the previous iteration, I simply only bundled the packages for the current environment.

**Comment by david-driscoll** [comment]
Fixed by #421
