### ISSUE TITLE
Intellisense parameter suggestion hover doesn't dismiss properly

### ISSUE THREAD

**Issue by billwert** [OmniSharp/omnisharp-roslyn#427]
![intellisensehover](https://cloud.githubusercontent.com/assets/4523120/13710882/8d8727ac-e770-11e5-88c2-42347636e5bc.png)

The hover appears as expected when I type ( on the end of an API, but doesn't dismiss with ). In this screenshot I've hit enter a couple times just to show how it moves around with the cursor.

It dismisses on a mouse click anywhere or the Escape key.

This is on Ubuntu 14.04, using dotnet CLI, and omnisharp in this zip: https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.9-alpha1/omnisharp-linux-x64-dnxcore50.tar.gz

VSCode version:

Version 0.10.10-insider
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-07T10:06:50.354Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by willl** [comment]
Sounds like a UI bug in the vscode extension, so it would be better to address it in the [omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode) repo and not omnisharp-roslyn.

**Comment by billwert** [comment]
@willl given that the intellisense stuff only works based on what's in this repo right now I thought this might be a more appropriate place?

**Comment by DustinCampbell** [comment]
This is a duplicate of this issue: https://github.com/OmniSharp/omnisharp-vscode/issues/64

**Comment by billwert** [comment]
thanks!

**Comment by willl** [comment]
@billwert It's an editor specific bug. omnisharp-roslyn just powers the intellisense (it is editor agnostic). It is up to individual editors to manage how they present it.

In this case, VS Code uses the omnisharp-vscode extension, which calls to omnisharp-roslyn (the intellisense engine). I hope that makes sense.
