### ISSUE TITLE
AspNet5ProjectSystem should fail gracefully when there is no default k

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#43]
When a user hasn't installed and defaulted a version of k, #getRuntimePath throws an exception which ripples through the init procedure so that it brings down Omnisharp. It should be a little more graceful...

**Comment by davidfowl** [comment]
Yar!

**Comment by jrieken** [comment]
@davidfowl for now I made it fail less catastrophic. since this is such a low level problem we should maybe think of adding a diagnostics field to the ```AspNet5Context``` so that the /projects route tells you about it.

**Comment by jrieken** [comment]
Closing since it doesn't fail so bad anymore with the change above.
