### ISSUE TITLE
Show only dev and master branch travis notifications in Slack #general channel 

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#439]

**Comment by troydai** [comment]
Not doable.

**Comment by sankethkatta** [comment]
Any reason this would not be possible to do?

We use a common pattern of locking down our master branches (which represent production). We develop on other branches which consistently have failures as they are being developed on. Having notifications repo-wide adds way too much noise for them to be useful. 

Something like the syntax of deploy would be nice:

```yaml
on:
  branch: master
```
