### ISSUE TITLE
The type or namespace name `Forms' does not exist in the namespace `System.Windows'. Are you missing `System.Windows.Forms' assembly reference?

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#443]
_From @dpMerchant on March 20, 2016 21:58_
- VSCode Version: - 0.1.0 
  OS Version: elementary OS 0.3.2 Freya (64-bit) (Built on Ubuntu 14.04)
  Steps to Reproduce: 
1. After installing VSCode and Mono 4.2.3 I tried the "helloworld" samples.
2.  When I tried the Winforms sample I got these two error messages.

WinHello.cs(2,22): error CS0234: The type or namespace name `Forms' does not exist in the namespace`System.Windows'. Are you missing `System.Windows.Forms' assembly reference?
WinHello.cs(4,27): error CS0246: The type or namespace name`Form' could not be found. Are you missing an assembly reference?
Compilation failed: 2 error(s), 0 warnings

Here is a link to the sample code that you provided on your website.
http://www.mono-project.com/docs/getting-started/mono-basics/

_Copied from original issue: Microsoft/vscode#4479_

**Comment by dpMerchant** [comment]
I see no solution to this, did u post one?

**Comment by kasdihacene** [comment]
XXXX$mcs /reference:System.Drawing.dll /refere
nce:System.Windows.Forms.dll $FILE.cs

**Comment by DustinCampbell** [comment]
Is this still an issue? C# for VS Code has changed dramatically over the past year.
