### ISSUE TITLE
keyFile not parsed in workspace

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-roslyn#445]
It breaks internals visible to when using omnisharp.

/cc @troydai

**Comment by filipw** [comment]
same as #279?

**Comment by troydai** [comment]
Could be

**Comment by troydai** [comment]
Fixed in https://github.com/OmniSharp/omnisharp-roslyn/commit/8f04b008c2e89f56cf264c13a8f99cc505825f36
