### ISSUE TITLE
CI build is too slow

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#465]
A few solutions:

Split a project build into following parallel tasks:
- Test
- Build
- Build packages

Skip packaging for other platforms. Travis run on Ubuntu and Mac, Appveyor run on Windows. This is duplicate work.

**Comment by hal-ler** [comment]
Timing information from the last Cake build (Travis Ubuntu).
    
Download and install tools: 00:00:28.9455788
Restore packages: 00:01:57.8307627
Build for test: 00:00:49.1377238
Test for .NET Core: 00:00:39.3851627
Test for other: 00:00:05.1342930
Publish and package: 00:01:20.1555300

Total build time reported time in Travis: 7 min 4 sec

Timing information from the last Cake build (AppVeyor).

Download and install tools: 00:00:14.6579962
Restore packages: 00:02:53.8145390
Build for test: 00:00:58.2975376
Test for .NET Core: 00:00:46.3471438
Test for other: 00:00:07.2167222
Publish and package: 00:02:06.7346350

Total build time reported time in AppVeyor: 8 min 16 sec

**Comment by filipw** [comment]
The slow tests have been split into a dedicated parallel task.
