### ISSUE TITLE
OmniSharp should search for a project if neither project.json or global.json exists in the given path

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#469]
The `DotNetProjectSystem` throws when non project is found. https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.DotNet/DotNetProjectSystem.cs#L109

1. The exception type is wrong;
2. Missing projects should not cause error.

**Comment by DustinCampbell** [comment]
Maybe. I'm kind of OK with there needing to be a global.json or project.json at the the given path. However, I'm *really* disliking how the whole project.json selection works in VS Code. I want to gut that completely. :smile:

**Comment by troydai** [comment]
Thanks @willl :)

**Comment by halter73** [comment]
Can we follow the restore logic for finding project.jsons recursively from the root/solution directory.

ASP.NET projects don't have samples in tests in global.json for example.

**Comment by troydai** [comment]
Fixed in https://github.com/OmniSharp/omnisharp-roslyn/commit/c36e8c4e55014bebc5295d70831371262b1ccb46
