### ISSUE TITLE
DesignTimeHostManager only waits 1 sec 

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#47]
the DTH manager gives the dth host 1 second to start and start listening. If you have a slow machine or a machine under load this won't be enough. we should either wait longer or try a few times in a short interval.

https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/AspNet5/DesignTimeHostManager.cs#L62

**Comment by nosami** [comment]
Think I'd prefer a smaller interval with retry. The 1 second pause is too long for me :)

**Comment by jrieken** [comment]
:+1: seems like you are spoiled with a monster machine ;-)
