### ISSUE TITLE
Make "Unnecessary using directive" an code action instead of warning

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-roslyn#470]
It generates too much warnings.

**Comment by DustinCampbell** [comment]
Remove Unnecessary Using isn't really a warning. There's a diagnostic from the compiler, and IIRC it's supposed to be "Info" with a hint to the editor to simply fade it out. Unfortunately, VS Code doesn't support fading today.

This should be user configurable. We're working on a better configuration story for diagnostics (likely using .editorconfig) and we'll need to ensure that gets threaded through OmniSharp.

**Comment by jlmakes** [comment]
+1

**Comment by DustinCampbell** [comment]
This happened in C# for VS Code 1.9.
