### ISSUE TITLE
Project initialization fails due to unrecognized keyword "platform"

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-roslyn#478]
dotnet-cli added` "type": "platform"` to project.json schema. When launching omnisharp on a project that has this in the project.json, omnisharp crashes.

eg.
```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": { "type": "platform", "version": "1.0.0-rc2-23911" }
  },
  "frameworks": {
    "netstandard1.5": { }
  }
}
```

```
The project system 'DotNetProjectSystem' threw exception during initialization.
unknown keyword platform
   at Microsoft.DotNet.ProjectModel.ProjectReader.TryGetProject(String path, Project& project, ICollection`1 diagnostics, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.WorkspaceContext.AddProjectEntry(String projectDirectory, FileModelEntry`1 currentEntry)
```

**Comment by hal-ler** [comment]
I assume the solution is to pin a newer version of dotnet-cli during build.
@david-driscoll This might be considered as you bring in the new build system (the option is in build.json).

**Comment by david-driscoll** [comment]
yeah, that's probably the fix... I should have time to look tonight.

**Comment by troydai** [comment]
Solution #1: take in new CLI packages to keep up with project model changes.
Solution #2: use the project model server model. in this case, another process, like the old DTH, runs side by side with O#. the process is updated with local SDK. 

Choice?

**Comment by david-driscoll** [comment]
I'm fine with #1 eventually we'll stabilize once we hit rc2/rtm.

We could investigate in a daily release build, that produces new github releases every day with the latest bits.  We might run into a case or two where we have a break, but we can solve those as we hit them.

**Comment by troydai** [comment]
/cc @davidfowl 
The question will be as dotnet begin to support side by side SDK. it is possible for one solution to require one version of SDK and the other to relies on another one. If a SDK is specified in global.json, then we have no choice but go to solution #2.

**Comment by DustinCampbell** [comment]
OK. What is the plan here? We need to get something happening since OmniSharp is broken with the latest .NET CLI bits.

**Comment by DustinCampbell** [comment]
FWIW, I'm interested in solution 2, but it's probably too ambitious of a change to get in quickly.

**Comment by troydai** [comment]
I'll work on #1 first then we have to eventually move the #2.

**Comment by hal-ler** [comment]
I got it to work and will create a PR soon as I polish it.

**Comment by hal-ler** [comment]
#485

**Comment by troydai** [comment]
Fixed in #486. Thanks, @hal-ler .

**Comment by DustinCampbell** [comment]
Awesome guys -- should we kick off a release with this change?

**Comment by hal-ler** [comment]
I was hoping that we can validate it a bit using an editor. I had some silent failures that did not show up in the tests while making this change.
