### ISSUE TITLE
Omnisharp should have a self termination feature

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#48]
Omnisharp is mostly kept as a child process of some editor process. On some platforms (like windows) a crash of the parent process doesn't mean termination of its children but they become parents. This will lead to unpleasant process leakage. To tackle this, Omnisharp should have an option to check for the status of its owning process and terminate itself when the parent is gone. This is analog to the KRuntime DTH (https://github.com/aspnet/XRE/blob/dev/src/Microsoft.Framework.DesignTimeHost/Program.cs#L41)

**Comment by nosami** [comment]
Doesn't work on mono :(

**Comment by jrieken** [comment]
but hopefully soon ;-)

**Comment by nosami** [comment]
So long as we have the same PlatformHelper.IsMono check, it's fine.
