### ISSUE TITLE
Project.json editing has warning that "Platform" is not a supported "type"

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-roslyn#498]
<img width="608" alt="screen shot 2016-04-04 at 10 48 23 am" src="https://cloud.githubusercontent.com/assets/9561583/14257511/ecd2b89e-fa52-11e5-8fb3-a7517c2f6509.png">

Now that sharedfx has "type": "platform" by default, we should adjust the project.json editor to accept this pattern.

**Comment by DustinCampbell** [comment]
This is already fixed and we're trying to get a build out. #478
