### ISSUE TITLE
Find Implementations

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#5]
Should jump if there is only one, otherwise return a list of 'QuickFix' (eurgh) objects.

**Comment by david-driscoll** [comment]
@nosami this looks like we have it now with https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Api/v1/Navigation/OmnisharpController.FindImplementations.cs ?

I'm off base, please reopen.
