### ISSUE TITLE
Adding parameter info to intellisense

### ISSUE THREAD

**Issue by mat-mcloughlin** [OmniSharp/omnisharp-roslyn#50]
Got the ability to add some basic parameter hinting in brackets so I was going to modify the intellisense request to include parameter info if asked for. 

@jrieken heard you might have some interest in this so I figured I'd flag it before I go ahead

**Comment by jrieken** [comment]
yes - can you shed some details about how you will approach this?  Will this be part of the completions route or a separate route like TypeScript does it (https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L5400)

**Comment by mat-mcloughlin** [comment]
I was gonna do it as part of the intellisense request as I didn't need much functionality but @davidfowl has told me to stop being rubbish and do it propertly :)

Looking at how typescript does it makes sense so I'll try and replicated something similar. I'll let you know how it goes

**Comment by jrieken** [comment]
I will tackle this next week, but not as IntelliSense but as a separate route ala ```GetParameterHelpAtPosition```
