### ISSUE TITLE
Latest beta release no intellisense

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-roslyn#509]
Log from VSCode 0.10.11:

[INFO] Starting OmniSharp at '/Users/fishg/data/JDK/hero/hero.sln'...
[INFO] Started OmniSharp from '/Users/fishg/tools/omnisharp-osx-x64-netcoreapp1.0/OmniSharp' with process id 59150...
OmniSharp: -s /Users/fishg/data/JDK/hero/hero.sln --hostPID 59144 dnx:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/Users/fishg/data/JDK/hero' on host 59144.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/fishg/data/JDK/hero
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[ERROR:OmniSharp.Startup] The project system 'DotNetProjectSystem' threw exception during initialization.
Failed to initialize Microsoft.DotNet.ProjectModel.WorkspaceContext at /Users/fishg/data/JDK/hero.
   at OmniSharp.DotNet.DotNetProjectSystem.Initalize(IConfiguration configuration)
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor)
[INFORMATION:OmniSharp.Startup] Configuration finished.

ps process info:
/Users/fishg/tools/omnisharp-osx-x64-netcoreapp1.0/OmniSharp -s /Users/fishg/data/JDK/hero/hero.sln --hostPID 59144 dnx:enablePackageRestore=false --stdio
![qq20160406-0](https://cloud.githubusercontent.com/assets/1423545/14310234/7123a90c-fc13-11e5-9645-34afde4ef79b.png)

But I can't goto definition and no code intellisense.

**Comment by hal-ler** [comment]
If I understood correctly, MSBuild support is only available in the .NET 4.5.1 version (linux-mono for non-Windows platforms). The error message could be more clear about this though (like "No .NET Core project found in path").

**Comment by aukaost** [comment]
This is a regression. I'm having the same issue after updating the extension to the latest beta release. This does not happen using ms-vscode.csharp-0.3.7.

**Comment by aukaost** [comment]
I notice you're using Unity. 
If you place a project.json next to the sln file containing

> {
    "dependencies": {        
    },
    "frameworks": {        
        "net452": { }
    },
    "runtimes": {
        "win": { }
    } 
}
You can get it to at least start and show you references. I've not gotten further than that yet.

**Comment by DustinCampbell** [comment]
Closing this given that it's a year old now. If you're still having problems, please file an issue at https;//github.com/OmniSharp/omnisharp-vscode/issues for C# for Visual Studio Code.
