### ISSUE TITLE
OmniSharp-roslyn releases needs releases for more Linux distros

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-roslyn#516]
There isn't a single CoreCLR which is compatible with all Linux distros. So there shouldn't be a 'omnisharp-linux-x64-netcoreapp1.0.tar.gz' but rather multiple .gz's (or a single .gz or nupkg with just the OmniSharp bits).

If you want to follow the CoreCLR model, there should currently be three gz's with many more to come --

* Ubuntu-14.04
* Red Hat Enterprise Linux 7.2 / Centos 7
* Debian 8.2

From what we can tell, the Ubuntu CoreCLR actually works fine on Debian, so you can omit that if you want.

**Comment by troydai** [comment]
We need to add two more runtime targets. The current linux build is actually Ubuntu-14.04.

/cc @david-driscoll

**Comment by DustinCampbell** [comment]
Marking this as done. It was actually done awhile ago, but it is now "more" done with https://github.com/OmniSharp/omnisharp-roslyn/pull/596.
