### ISSUE TITLE
[ERROR] Error: spawn EACCES

### ISSUE THREAD

**Issue by cevarief** [OmniSharp/omnisharp-roslyn#526]
OmniSharp can be compiled successfully with 11 warnings on OSX El Capitan.

Running **./OmniSharp** return
```bash
OmniSharp:
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location '~/OmniSharp/artifacts/publish/OmniSharp/default/netcoreapp1.0' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in ~/OmniSharp/artifacts/publish/OmniSharp/default/netcoreapp1.0
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
fail: OmniSharp.Startup[0]
      The project system 'DotNetProjectSystem' threw exception during initialization.
      Failed to initialize Microsoft.DotNet.ProjectModel.WorkspaceContext at ~/OmniSharp/artifacts/publish/OmniSharp/default/netcoreapp1.0.
         at OmniSharp.DotNet.DotNetProjectSystem.Initalize(IConfiguration configuration)
         at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor)
info: OmniSharp.Startup[0]
      Configuration finished.
```
**In visual studio code, OmniSharp log output shows :**
 
[INFO] Starting OmniSharp at '/Path/To/An/MVC/App'...
[ERROR] Error: spawn EACCES

I add permission -Rf a+x to OmniSharp folder that error keeps showing.

**Comment by cevarief** [comment]
Testing with ```dotnet new``` and open using visual studio code, omnisharp run well.
The spawn EACCES error happened when i try with the cli sample https://github.com/aspnet/cli-samples/tree/master/HelloMvc.

**Comment by cevarief** [comment]
I reclone the repo, restore and it works good now 👍 .

**Comment by cevarief** [comment]
I was too happy but after seeing the omnisharp log and the intellisense does not work.
```bash
[INFO] Starting OmniSharp at '~/aspnet/cli-samples/HelloMvc'...
[INFO] Started OmniSharp from '~/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 11762...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '~/aspnet/cli-samples/HelloMvc' on host 11743.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '~/.dnx/runtimes/dnx-mono.1.0.0-rc1-update2'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '~/aspnet/cli-samples/HelloMvc/project.json'.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Looking for sdk version in '~/aspnet/cli-samples/global.json'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '~/aspnet/cli-samples/HelloMvc' for DNX projects
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Process ID 11782
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Listening on port 59103
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Running DesignTimeHost on port 59103, with PID 11782
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:59103
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:59103
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Connected
[ERROR:OmniSharp.Dnx.DnxProjectSystem] unknown keyword platform
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '~/aspnet/cli-samples/HelloMvc'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '~/aspnet/cli-samples/HelloMvc'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
```

**Comment by troydai** [comment]
@cevarief base on the log it seems that you're using an old version of omnisharp to deal with the cli samples. the `DNX` system doesn't support cli samples. please use the latest alpha3 build (https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.9-alpha13)

**Comment by cevarief** [comment]
@troydai I used to use [Vscode](https://github.com/OmniSharp/omnisharp-vscode) and it worked fine for cli. What's the difference with roslyn ?

**Comment by troydai** [comment]
@cevarief can I know the version of the C# extension for VS code you're using? base on the log you posted it won't work with `dotnet-cli` projects.

**Comment by cevarief** [comment]
@troydai It's 1.0.3-rc2, the same i'm using now with roslyn.

**Comment by troydai** [comment]
Base on this line of code it seems to be running on an older version.
```
[INFO] Started OmniSharp from '~/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 11762...
```

Here's what I got after install the [1.0.4-rc2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.4-rc2) build:

```
[INFO] Started OmniSharp from 'C:\Users\troyd\.vscode-insiders\extensions\ms-vscode.csharp-1.0.4-rc2\.omnisharp\OmniSharp.exe' with process id 
```

You can install the 1.0.4-rc2 build by:
1. Download the extension from here: https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.0.4-rc2/csharp-1.0.4-rc2.vsix
2. Open the vsix file like a normal file in VS Code (Ctrl + O)

**Comment by troydai** [comment]
And also your log is inline with VS Code 1.0 + default C# extension (0.3.7). This what I got for this set up:
```
[INFO] Starting OmniSharp at 'c:\code\NewProject02'...
[ERROR] OmniSharp does not exist at location: /Users/troydai/Code/omnisharp-roslyn/artifacts/publish/OmniSharp/default/netcoreapp1.0/OmniSharp
[INFO] Starting OmniSharp at 'c:\code\NewProject02'...
[INFO] Started OmniSharp from 'C:\Users\troyd\.vscode\extensions\ms-vscode.csharp-0.3.7\bin\omnisharp.cmd' with process id 13380...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location 'c:\code\NewProject02' on host 14680.
```

**Comment by cevarief** [comment]
I did not pay attention what C# extension version i used when the error appeared. 
But with version 1.0.3-rc2 i use it works good both with vscode and roslyn.

**Comment by cevarief** [comment]
I just updated to csharp-1.0.4-rc2.vsix. It work perfect too.

My unanswered question is what's the difference between using omni vcscode vs roslyn. 
Any performance difference ? Thanks @troydai

**Comment by troydai** [comment]
They're different thing. OmniSharp-vscode is the source code of the C# extension. It pack a build of OmniSharp-Roslyn in it. When you install C# extension from VS code market, it installs a release build of omnisharp-vscode repo. 

I'll close this issue then.
