### ISSUE TITLE
Project paths are case sensitive in MSBuildContext

### ISSUE THREAD

**Issue by carl-tanner** [OmniSharp/omnisharp-roslyn#527]
The MsBuildContext.Project dictionary is case sensitive.  As a result if the path in the solution file and the path in the msbuild proj file (or maybe the casing of the path on disk) is different from the solution file the project will generate the error "Unable to resolve project reference <path>".  I tested out using StringComparer.OrdinalIgnoreCase as the comparer for the collection and it fixes the load problems.

**Comment by troydai** [comment]
@carl-tanner did your PR (https://github.com/OmniSharp/omnisharp-roslyn/commit/297acb8b725bde30b27f555180ea85a4b4676b88) solve this issue?

**Comment by carl-tanner** [comment]
It fixed it.  Closing this issue.
