### ISSUE TITLE
Roslyn build.sh failure

### ISSUE THREAD

**Issue by xjackk** [OmniSharp/omnisharp-roslyn#531]
Getting a build error on Ubuntu 14 LTS...

Cleared .NuGet cache and wasn't able to build. 

Ran the build script as instructed in the repo and got these results.

(Terminal capture uploaded to Imgur)

(http://imgur.com/a/lGiYj)

**Comment by hal-ler** [comment]
Seems like a mono version problem: https://github.com/NuGet/Home/issues/2312

What version are you running locally?

**Comment by xjackk** [comment]
http://i.imgur.com/L3HTcR8.png

http://i.imgur.com/VCTkZhi.png

**Comment by hal-ler** [comment]
I'm no NuGet expert, but try something >=4.2.1. That is the version running on the CI servers.

**Comment by xjackk** [comment]
Got it working. You are a good man.
