### ISSUE TITLE
Error running build.ps1. Cannot find package 'xunit.runner.console'.

### ISSUE THREAD

**Issue by netxph** [OmniSharp/omnisharp-roslyn#534]
running build.ps1, here's the error.

```
WARNING: An error occurred while loading packages from 'https://www.myget.org/F/aspnetcidev/api/v3/index.json': The remote server returned an error: (404) Not Found.
WARNING: An error occurred while loading packages from 'https://www.myget.org/F/aspnetcidev/api/v3/index.json': The remote server returned an error: (404) Not Found.
Unable to find package 'xunit.runner.console'.
An error occured when executing task 'BuildEnvironment'.
Error: NuGet: Process returned an error (exit code 1).
```

Did I missed anything?

**Comment by jtbm37** [comment]
I had this one before. What's your `dotnet --version` ? Which Windows are you on ? Running in a VM ?

**Comment by netxph** [comment]
I think I have the stable one available here... https://dotnet.github.io/getting-started/. `dotnet --version` does not work.

I'm also running on Windows 7 and not on VM.

**Comment by willl** [comment]
@netxph If `dotnet --version` doesn't work, then that indicates that `dotnet` tools are not in your path.

After running the .msi installer from the getting started page, did you go through steps 2 and beyond?

**Comment by netxph** [comment]
I reinstalled dotnet and able to get `dotnet --version'.

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64
```

But still no luck. Same error. :(

**Comment by willl** [comment]
@netxph I think you're still using an older version of dotnet. 

You should be seeing 2439 rather than 1598.

You might want to uninstall all versions of the dotnet CLI that you have installed and then grab the latest version from https://github.com/dotnet/cli#installers-and-binaries

**Comment by netxph** [comment]
Thanks for the help. I already found the issue. Apparently, I installed nuget.commandline in chocolatey and the build is pointing to that executable which is an older version of NuGet.
