### ISSUE TITLE
Visual Studio 2015 is unable to resolve dependencies

### ISSUE THREAD

**Issue by jtbm37** [OmniSharp/omnisharp-roslyn#537]
I can build fine from command line, but when loading in Visual Studio 2015 Update 2 I get these errors:

![selection002](https://cloud.githubusercontent.com/assets/536407/14797838/8d4b6d7c-0b2c-11e6-9505-167299e9e061.png)

I am using the `dev` branch.
`$ dotnet --info`
```
.NET Command Line Tools (1.0.0-rc2-002397)

Product Information:
 Version:     1.0.0-rc2-002397
 Commit Sha:  ef982d120e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

**Comment by troydai** [comment]
@jtbm37 We haven't shipped a ASP.NET Web Tools extension supports dotnet-cli yet.

**Comment by jtbm37** [comment]
@troydai so devs on this project exclusively work in VS Code I guess ? or other editor + omnisharp (stable).

**Comment by troydai** [comment]
@jtbm37 we'll release the final VS tooling support with final rc2 build together.

**Comment by troydai** [comment]
VS Code + C# Extension (1.0.3) can help you with development work.

**Comment by jtbm37** [comment]
@troydai Thank you.
