### ISSUE TITLE
Trying to apply changes to OmnisharpWorkspace results in exception

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#55]
When any of the endpoints tries to apply *any* solution changes (add file, rename content, refactor etc etc) to the workspace using

                // Attempt to update the workspace
                if (_workspace.TryApplyChanges(solution))
                {
                    response.Changes = changes;
                }

OmniSharp will not do it - instead it will throw an exception.

See screenshot:
![screenshot 2015-01-28 08 21 35](https://cloud.githubusercontent.com/assets/1710369/5933910/81841fa4-a6c7-11e4-92fc-a641e2679eaa.png)

**Comment by davidfowl** [comment]
Well obviously not *any* change, but changes that make sense. The Omnisharp workspace is a bit special since it backs both msbuild projects as well as project.json based projects. We'll need to think through this a bit.

**Comment by filipw** [comment]
`ApplyChangesKinds` enum defines the types of changes that can happen to a workspace. here is what `MSBuildWorkspace` does:

        public override bool CanApplyChange(ApplyChangesKind feature)
        {
            switch (feature)
            {
                case ApplyChangesKind.ChangeDocument:
                case ApplyChangesKind.AddDocument:
                case ApplyChangesKind.RemoveDocument:
                case ApplyChangesKind.AddMetadataReference:
                case ApplyChangesKind.RemoveMetadataReference:
                case ApplyChangesKind.AddProjectReference:
                case ApplyChangesKind.RemoveProjectReference:
                case ApplyChangesKind.AddAnalyzerReference:
                case ApplyChangesKind.RemoveAnalyzerReference:
                    return true;
                default:
                    return false;
            }
        }

The extra `ApplyChangesKinds` it disallows are:

        AddProject = 0,
        RemoveProject = 1,
        AddAdditionalDocument = 11,
        RemoveAdditionalDocument = 12,
        ChangeAdditionalDocument = 13,
        ChangeCompilationOptions = 14,
        ChangeParseOptions = 15

Anyway, the override proposed in #56 - in some shape or form - is necessary, as right now everything is disallowed.

**Comment by davidfowl** [comment]
I'm aware, I'm asking what this change will fix at this very moment. Without thinking about how the OmnisharpWorkspace affects the underlying project system, does this change make sense without the rest?

**Comment by jrieken** [comment]
hm - need to think more on this. persisting changes on disk (and even in memory) conflicts with incremental buffer updates. so, when you send the full contents of a file on every keystroke you won't have a problem but when you actually send the changes (https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Api/Buffer/OmnisharpController.Buffer.cs#L20) this will become a problem as you now apply changes on an unknown state.

**Comment by filipw** [comment]
what is the use case for `changebuffer` (because I don't think it existed in Omnisharp v1)?

anyway, once you trigger a refactoring endpoint like the rename one, you get the a list of `ModifiedFileResponse` back so on the client side you know exactly what has changed.

**Comment by jrieken** [comment]
```changebuffer``` serves two purposes: (1) minimize the data that is exchanged between an editor and omnisharp (think of a large file and rapid typing) and (2) leverage the incremental parser in Roslyn by changing a source text via a series of text edits. 

Because of that it's vital that the states of documents in Roslyn and editors are equal and advance simultaneously.
