### ISSUE TITLE
Unable to build on a new windows devbox

### ISSUE THREAD

**Issue by wangzq** [OmniSharp/omnisharp-roslyn#550]
I am able to build latest source (dev branch) on a windows that has previously cached some old versions of packages, but on a new devbox I am not able to build; I am also able to reproduce on the first devbox by renaming `%userprofile%\.nuget`

    Errors in E:\temp\omnisharp-roslyn\src\OmniSharp.Nuget\project.json                                      
        Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.     
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\src\OmniSharp.DotNet\project.json                                     
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETFramework,Version=v4.5.1'.      
        Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1199)' for '.NETFramework,Version=v4.5.1'.         
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETStandard,Version=v1.5'.         
        Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1199)' for '.NETStandard,Version=v1.5'.            
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\src\OmniSharp.Host\project.json                                       
        Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.     
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\tests\OmniSharp.Bootstrap.Tests\project.json                          
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.          
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\tests\OmniSharp.DotNet.Tests\project.json                             
        Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.             
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.          
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\src\OmniSharp\project.json                                            
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETFramework,Version=v4.5.1'.      
        Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1199)' for '.NETFramework,Version=v4.5.1'.         
        Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.     
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.          
        Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.             
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\tests\OmniSharp.MSBuild.Tests\project.json                            
        Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.     
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\tests\TestUtility\project.json                                        
        Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.     
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\tests\OmniSharp.Stdio.Tests\project.json                              
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.          
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\tests\OmniSharp.Roslyn.CSharp.Tests\project.json                      
        Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.             
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.          
        Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.     
                                                                                                             
    Errors in E:\temp\omnisharp-roslyn\tests\OmniSharp.Tests\project.json                                    
        Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.             
        Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-beta-1199)' for '.NETCoreApp,Version=v1.0'.          
        Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.

**Comment by OskarSigvardsson** [comment]
I get a very similar error on mac: 

```
Errors in /Users/oskarsigvardsson/.vim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Nuget/project.json
    Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging.Core (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.

Errors in /Users/oskarsigvardsson/.vim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Host/project.json
    Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging.Core (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.

Errors in /Users/oskarsigvardsson/.vim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.DotNet/project.json
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1233)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1233)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1233)' for '.NETStandard,Version=v1.5'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1233)' for '.NETStandard,Version=v1.5'.

Errors in /Users/oskarsigvardsson/.vim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp/project.json
    Unable to resolve 'NuGet.Configuration (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging.Core (>= 3.5.0-beta-1178)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1233)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1233)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1233)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1233)' for '.NETCoreApp,Version=v1.0'.
```

**Comment by tmadsen** [comment]
I had the same problem. I ended overwriting `NuGet.Config` with `Nuget.Config.Source` and then all the dependencies installed fine. (I have a new problem during the `TestCore` build task though: `Unhandled Exception: System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IRuntimeEnvironment Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Runtime()'.` but I guess that's another issue)

**Comment by tmadsen** [comment]
I can build without changing stuff now. Has been working since #553

**Comment by wangzq** [comment]
Verified working now.
