### ISSUE TITLE
Non-functional x86 binaries in release packages

### ISSUE THREAD

**Issue by hal-ler** [OmniSharp/omnisharp-roslyn#558]
dotnet-cli(x64) is not able to create functional binaries for x86 with `--runtime win7-x86". The resulting binary is still x64, linking against x86 libraries. This was first reported at https://github.com/dotnet/cli/issues/1485, currently tracked at https://github.com/dotnet/cli/issues/2343.

Options that I see:
1. Remove x86 release option temporarily, until support is added in the CLI to create them easily.
2. Hack build system to download second copy of the SDK (x86) on Windows and to use it for the x86 build.
3. Loop build system on AppVeyor to simulate running on two different machines with x64 and x86 Windows.

(Maybe old binaries are best removed to avoid people trying to use them.)

@david-driscoll @troydai @DustinCampbell

**Comment by willl** [comment]
I think it's for the best to remove the old x86 binaries as they do not currently work.

**Comment by DustinCampbell** [comment]
This should be fixed now.

**Comment by DustinCampbell** [comment]
Fixed with https://github.com/OmniSharp/omnisharp-roslyn/pull/653
