### ISSUE TITLE
[netcoreapp1.0] An error loading .csproj file that references ".NETFramework,Version=v4.5"

### ISSUE THREAD

**Issue by razzmatazz** [OmniSharp/omnisharp-roslyn#586]
This is on the latest 'dev' branch when loading a `.sln` file with MSBuild project system.

The impact of this is that `System.Linq` is not available when syntax–checking the files or when requesting autocompletion. This is probably because .NET framework v2 SDK is used as a default for .csproj files (?)

Running on OS X 11.4.

Not sure if the problem is an issue with MSBuild project system implementation in `omnisharp-emacs`, a `coreclr` issue or a problem with any of my solution and/or projects.

```
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp#MSBuild","Message":"Loading project from '/Users/bob/src/XXX/src/YYY/YYY.csproj'."},"Seq":7,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp#ProjectFileInfo","Message":"Using toolset 14.1 for /Users/bob/src/XXX/src/YYY/YYY.csproj"},"Seq":8,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"WARNING","Name":"OmniSharp#ProjectFileInfo","Message":"The reference assemblies for framework \".NETFramework,Version=v4.5\" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend."},"Seq":9,"Type":"event"}
```

**Comment by troydai** [comment]
@razzmatazz can you help me with two questions?
1. Is it a regression for you?
2. What's the mono version on your machine?

**Comment by razzmatazz** [comment]
@troydai 
1. my omnisharp-emacs setup was broken for half a year, and just recently omnisharp-roslyn started to support .sln files again.. so.. yes, it is a regression
2. mono is
Mono JIT compiler version 4.4.0 (mono-4.4.0-branch/81f38a9 Wed Apr 20 17:10:46 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/a173357)
	GC:            sgen

But I thought that omnisharp-roslyn uses the dotnet-core runtime, does it?

I have omnisharp-emacs pointed to netcoreapp1.0/OmniSharp which is a x64 binary. It is probably some kind of bootstrap binary to actually load the mono (or the dotnet-core) runtime (?)

bob@mbp ~ $ file ~/src/omnisharp-roslyn/artifacts/publish/OmniSharp/default/netcoreapp1.0/OmniSharp
/Users/bob/src/omnisharp-roslyn/artifacts/publish/OmniSharp/default/netcoreapp1.0/OmniSharp: Mach-O 64-bit executable x86_64

**Comment by troydai** [comment]
Thanks for the information. 

Some background knowledge:
1. Since the error is associated to a .NET Framework 4.5 project, it is unlikely `dotnet` plays a role in this scenario. `csproj` is managed by `MSBuildProjectSystem`.
2. It seems that you're using the `netcoreapp1.0` version of OmniSharp. This is good. We recently add support of `MSBuild` project to `netcoreapp1.0` version of OmniSharp. The `MSBuildProjectSystem` tracking assemblies in GAC using this logic: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Resolution/FrameworkReferenceResolver.cs#L93. So in your case `System.Linq` is being seeked in Mono's GAC.

Can you make sure it can be located correctly? It may be environment related.

If you can build a minimal sample project, I can take a look the issue.

**Comment by troydai** [comment]
Another thing, can you try bump up the version to 4.5.1?

**Comment by razzmatazz** [comment]
@troydai – setting `<TargetFrameworkVersion>v4.5.1</TargetFrameworkVersion>` in csproj didn't help, now it says 

```
WARNING: The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

**Comment by DustinCampbell** [comment]
@razzmatazz: does it work if you use the mono-flavor of OmniSharp

**Comment by DustinCampbell** [comment]
Note: the MSBuild support is a incomplete on netcoreapp1.0 versions.

**Comment by BeeWarloc** [comment]
I seem to have the same, or a similar problem 

Given a simple "Hello World" .NET 4.5.1 console app (created using monodevelop) I get the following error when trying to load it with the netcoreapp1.0 version:

```
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNetTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Nuget, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Stdio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location '/home/karsten/TestNet451/TestNet451' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in /home/karsten/TestNet451/TestNet451
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp#MSBuild[0]
      Detecting projects in '/home/karsten/TestNet451/TestNet451/TestNet451.sln'.
info: OmniSharp#MSBuild[0]
      Loading project from '/home/karsten/TestNet451/TestNet451/TestNet451/TestNet451.csproj'.
info: OmniSharp#ProjectFileInfo[0]
      Using toolset 15.0 for /home/karsten/TestNet451/TestNet451/TestNet451/TestNet451.csproj
fail: OmniSharp#ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp#MSBuild[0]
      Failed to process project file '/home/karsten/TestNet451/TestNet451/TestNet451/TestNet451.csproj'.
info: OmniSharp.Startup[0]
      Configuration finished.
```

The net451 omnisharp variant, running with mono gives the following output:

```
○ → mono ~/src/omnisharp-roslyn/artifacts/publish/OmniSharp/default/net451/OmniSharp.exe -v
OmniSharp: -v
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNetTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Nuget, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.ScriptCs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Stdio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location '/home/karsten/TestNet451/TestNet451' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in /home/karsten/TestNet451/TestNet451
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp#MSBuild[0]
      Detecting projects in '/home/karsten/TestNet451/TestNet451/TestNet451.sln'.
info: OmniSharp#MSBuild[0]
      Loading project from '/home/karsten/TestNet451/TestNet451/TestNet451/TestNet451.csproj'.
warn: OmniSharp#MSBuild[0]
      Failed to process project file '/home/karsten/TestNet451/TestNet451/TestNet451/TestNet451.csproj'.
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Detecting CSX files in '/home/karsten/TestNet451/TestNet451'.
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Configuration finished.
```
(still not working, but not the same error output)

**Comment by DustinCampbell** [comment]
Yes, the netcoreapp1.0 won't work well.

**Comment by razzmatazz** [comment]
@DustinCampbell how can I can build omnisharp-roslyn to run against the mono runtime? 

artifacts/netcoreapp1.0/OmniSharp appears to be a native binary, not a script (for bootstrap?)

**Comment by david-driscoll** [comment]
Try running the build with `-Target OnlyPublish` that should produce a full set of published items... otherwise I think it just defaults to building `netcoreapp1.0` but we also have build support for `net451` which is what will work with mono.

**Comment by DustinCampbell** [comment]
net451 will work over stdio.

**Comment by razzmatazz** [comment]
@DustinCampbell – oh, I was under totally wrong impression then. pardon me, I will check it this helps

**Comment by razzmatazz** [comment]
@david-driscoll so the issue for me is resolved by using net451 on top of mono runtime. Should I close the issue? I have renamed it somewhat for the actual context of the issue to be evident from the name.

**Comment by DustinCampbell** [comment]
@razzmatazz: Just noticed this had gone stale. It sounds like your problem's solved?

**Comment by razzmatazz** [comment]
@DustinCampbell – yeah, things work OK now on mono+omnisharp-roslyn(stdio)+emacs25+osx10.12

so, i am not running netcoreapp version anyway, you can close the issue

**Comment by DustinCampbell** [comment]
sounds good -- thanks!
