### ISSUE TITLE
Getting a log level of hidden in the quick fixes

### ISSUE THREAD

**Issue by mat-mcloughlin** [OmniSharp/omnisharp-roslyn#59]
Some of the messages that come back from the quick fixes have a log level of "hidden". For example

    { 
        LogLevel: 'Hidden',
        FileName: 'C:\\GitHub\\omnisharp-roslyn\\src\\OmniSharp\\Api\\Status\\OmnisharpController.Status.cs',
        Line: 1,
        Column: 1,
        EndLine: 1,
        EndColumn: 14,
        Text: 'Unnecessary using directive.' 
    }

**Comment by davidfowl** [comment]
And?

**Comment by mat-mcloughlin** [comment]
And I'm assuming it not right? :)
