### ISSUE TITLE
intellisense doesnt work on osx

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#591]
_From @yas666 on June 21, 2016 20:45_
- VSCode Version: latest
- OS Version: OSX El capitan

Steps to Reproduce:
1. download visual studio code on osx
2. download and install unity
3. use ext install to install legacy c# tools
4. try and access unity engine api.
5. type transform in void start or a similar function
6. use dot notation to access methods and find that you cannot get the list.

_Copied from original issue: Microsoft/vscode#7937_

**Comment by jrieken** [comment]
_From @dbaeumer on June 22, 2016 8:27_

@jrieken assigning to you since he installs the legacy tools.

**Comment by DustinCampbell** [comment]
@jrieken -- this should be filed on the omnisharp-vscode repo.

**Comment by DustinCampbell** [comment]
This should be fixed by removing the legacy C# tools and installing the latest C# extension.
