### ISSUE TITLE
Can't build on Fedora 24

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-roslyn#599]
I have mono installed and try to repeat the steps to build as explained on the README.
However, I get the following error

```
mistria@mistria-rh:~/git/omnisharp-roslyn$ ./build.sh 
Feeds used:
  /home/mistria/.local/share/NuGet/Cache
  https://www.myget.org/F/roslyn-nightly/api/v3/index.json
  https://www.myget.org/F/aspnetcidev/api/v3/index.json
  https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://www.myget.org/F/nugetbuild/api/v3/index.json
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.10.1.
WARNING: Unable to find version '0.10.1' of package 'Cake'.
Restoring NuGet package Newtonsoft.Json.8.0.3.
WARNING: Unable to find version '8.0.3' of package 'Newtonsoft.Json'.
Could not find Cake.exe at '/home/mistria/git/omnisharp-roslyn/scripts/../.tools/Cake/Cake.exe'.
```

I'm not at all a .NET developer, so any hint, even the most basic one, would be welcome.

**Comment by DustinCampbell** [comment]
@mickaelistria: Are you using the latest dev branch? The reason I ask is because the list of feeds was changed just yesterday.

**Comment by mickaelistria** [comment]
Yes, it was on the dev branch.
However, it's not high priority: I simply downloaded the OmniSharp from release and start it fixing its LD_LIBRARY_PATH to use the right ICU and it starts as expected. I can even close this ticket if you're OK with it.
I now have some "how to" questions. What's the best place for them? I tried Slack yesterday but without success ATM.

**Comment by willl** [comment]
@mickaelistria What are you trying to achieve?

**Comment by mickaelistria** [comment]
Pasting my question from Slack:

Hi, I'm trying to implement a Java client for OmniSharp-roslyn. I managed to get the server started, and directly ran a basic request such as the one on https://github.com/OmniSharp/omnisharp-server#problems-or-just-want-to-see-whats-going-on however at the moment I always get an HTTP error 500:
> An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /autocomplete
> System.NotSupportedException: Must be able aggregate the response to spread them out across all plugins for /autocomplete
>  at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext() in /home/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.Host/Middleware/Endpoint/EndpointHandler.cs:line 202

Then I have several questions:
* Is this issue caused by my client sending incorrect request, or is it a pure server-side issue (as error 500 suggests)?
* What is the very simplest way to test the server is working as expected? Is the a /test URL or similar to validate server state?
* Do you have a simple example of a sequence of request that gets a feature such as autocomplete from scratch?

**Comment by willl** [comment]
You might find it easier to have a look at how other clients connect to omnisharp-roslyn. Your link to the omnisharp-server is for an old deprecated/no longer supported version so ignore any documentation for that.

There are several different client implementations with the most complete ones being omnisharp-server and omnisharp-atom (which connects via a node client/wrapper that you can utilise).

**Comment by mickaelistria** [comment]
I'm having a look but since I'm not familiar with JS, it's a bit tricky for me. IMHO, some documentation about the Web API and some examples of requests showing the protocol in action would be very helpful.

**Comment by willl** [comment]
Yeah, that's true enough. We do lack a fair bit of documentation. 

Hopefully these two links help:
* https://github.com/OmniSharp/omnisharp-node-client/blob/7b0618c9fe9f469337505e6d600f93940914beaf/languageserver/server.ts#L176
* https://github.com/OmniSharp/omnisharp-vscode/blob/8f4265882083072c3371e5e677e46a2b776b1949/src/features/completionItemProvider.ts#L25

Contributions of documentation are always welcome :)

**Comment by david-driscoll** [comment]
I'll attempt to write some documentation in the next weekend or two.

**Comment by mickaelistria** [comment]
Is there some kind of handshake requested to initiate conversation with the server? I tried to adapt my request according to the links shown about but still get
```
      An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /autocomplete
System.NotSupportedException: Must be able aggregate the response to spread them out across all plugins for /autocomplete
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext() in /home/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.Host/Middleware/Endpoint/EndpointHandler.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in /home/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.Host/Middleware/Endpoint/EndpointHandler.cs:line 130
```
or maybe something is wrong with my request?
```java
		HttpClient client = HttpClientBuilder.create().build();
		HttpPost post = new HttpPost("http://localhost:2000/autocomplete");
		String file = "/home/mistria/git/omnisharp-roslyn/src/OmniSharp.DotNetTest/Helpers/TestFeaturesDiscover.cs";
		String buffer = "public class TestFeaturesDiscover\n" +
"{\n" +
"   public static void Main()\n" +
"   {\n" +
"      System.Console.W\n" +
"   }\n" +
"}";
		post.setEntity(new StringEntity("Column=21" +
				"&Line=5" +
				"&Filename=" + file +
				"&Buffer=" + buffer +
				"&WantDocumentationForEveryCompletionResult=False" +
				"&WordToComplete=W")); // depends on Buffer, line, column
		HttpResponse res = client.execute(post);
```

**Comment by mcepl** [comment]
Just to say that I have the same issue with (unsupported, nightly) .NET Core 1.0.0 packages for RHEL-7 and f4d1dbf:
```
matej@mitmanek: omnisharp-roslyn (dev)$ ./build.sh 
Feeds used:
  /home/matej/.local/share/NuGet/Cache
  /home/matej/.nuget/packages/
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.10.1.
WARNING: Unable to find version '0.10.1' of package 'Cake'.
Restoring NuGet package Newtonsoft.Json.8.0.3.
```

**Comment by mickaelistria** [comment]
@david-driscoll I've created issue #606 to track the request for documentation, examples, whethever to help in writing some HTTP client. So this issue can remained focused on the build issue with Fedora 24.

**Comment by vanthome** [comment]
Same problem on Gentoo Linux. Any way to work around this?

**Comment by nfantone** [comment]
Same over here on Mac OSX. Just,

1. Clone the repo.
2. Run `$ ./build.sh`


```sh
Could not find Cake.exe at '/path/to/omnisharp-roslyn/scripts/../.tools/Cake/Cake.exe'.
```

**Comment by nfantone** [comment]
@willl Ok, figured it out. There's an unquoted `$PACKAGES_CONFIG` variable reference in `scripts/cake-bootstrap.sh`

```sh
mono "$NUGET_EXE" install $PACKAGES_CONFIG -ExcludeVersion -OutputDirectory "$TOOLS_DIR"
```

If your `pwd` contains spaces, the NuGet install breaks.

Sending a PR soon.
