### ISSUE TITLE
Code Actions / Issues

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#6]
Probably want to go with NRefactory 6 for this.... but should also look at https://github.com/code-cracker/code-cracker

**Comment by Yantrio** [comment]
this was kicked off with #63, however it could be good to keep this open for discussion. 
We are going to want to pull in codeactions from different providers and cherry pick them, apart from vanilla roslyn + NR6, what else is there out there?

**Comment by nosami** [comment]
Code crackers

**Comment by david-driscoll** [comment]
We have some both code actions v1 and v2 api's at this point, so I'm going to close this for now.  Unless someone feels like we need to reopen it.
