### ISSUE TITLE
Will there be x86 builds?

### ISSUE THREAD

**Issue by hismichael** [OmniSharp/omnisharp-roslyn#603]
that would be greatly appreciated by x86 users like me.

**Comment by willl** [comment]
@hismichael There used to be x86 builds, but apparently they never worked due to issues with dotnet CLI (see #558).

**Comment by DustinCampbell** [comment]
32-bit windows builds are now available in the latest release: https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.9-beta19.
