### ISSUE TITLE
[net451/stdio] on mono+emacs+OS X – some stdout lines are cut short

### ISSUE THREAD

**Issue by razzmatazz** [OmniSharp/omnisharp-roslyn#610]
There is this weird bug in --stdio mode on my 'dev' build.

Sometimes output lines from OmniSharp server is cut short and the problem appears to be intermittent. I got a dtruss trace excerpt from my OS X machine:
```
47866/0x279dc6:    131458      12      6 write(0x1, "{\"Event\":\"log\",\"Body\":{\"LogLevel\":\"INFORMATION\",\"Name\":\"OmniSharp.Middleware.LoggingMiddleware\",\"Message\":\"/codecheck: 200 0ms\"},\"Seq\":219,\"Type\":\"event\"}\n\0", 0x9B)		 = 155 0
47866/0x27ae4e:     49042      20     15 write(0x1, "tem.Web.Mvc;\\nusing NHibernate.Criterion;\\nusing NHibernate.Linq;\\nusing <...>", 0x3FD)		 = 1021 0
```

You can see the second `write()` syscall to stdout starts with `tem.Web.Mvc..` and is missing the whole header and json start tags.

I remember reading somewhere on omnisharp-emacs github site that @sp3ctum had this happening for him before, too. But I maybe be wrong about this.

Can anyone can give me hints how to trace this back?

**Comment by sp3ctum** [comment]
Yeah this happened to @nosami about a year ago and never was fixed as far as I can remember. Does not happen to me on Linux mint. Also does not happen to @andschwa on OSX.

I hope others can be more helpful than I can.

-----Original Message-----

**Comment by razzmatazz** [comment]
@sp3ctum there was a bug in omnisharp-emacs where it was not using pipe for communication with omnisharp-roslyn process but was using a 'tty' which has a 1024 char limit for a line discipline on OS X. See https://github.com/OmniSharp/omnisharp-emacs/pull/232
