### ISSUE TITLE
VS Code doesn't recognize project files

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#611]
_From @halcwb on July 7, 2016 23:6_

- VSCode Version: 1.3.0
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. clone http://github.com/halcwb/GenUnitApp.git 
2. cd GenUnitApp 
3. code .

Expect in the statusbar detection of 2 projects. 
No projects are detected. 

_Copied from original issue: Microsoft/vscode#8861_

**Comment by DustinCampbell** [comment]
Looking at GenUnitApp, these appear to be F# project files, not C#. Unfortunately, OmniSharp doesn't support F#. @halcwb: have you tried the [Ionide extension for VS Code](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp) to add F# project support?
