### ISSUE TITLE
build on windows requires powershell >= 3.0

### ISSUE THREAD

**Issue by comicfans** [OmniSharp/omnisharp-roslyn#612]
cake-bootstrap.ps1 use $PSScriptRoot , needs   powershell >=3.0

**Comment by willl** [comment]
@comicfans So what version of Powershell are you using and what is preventing you from moving to PowerShell 3.0+?

It's been available for awhile and works on Windows 7/Server 2008 and higher: https://blogs.technet.microsoft.com/heyscriptingguy/2012/09/05/powershell-3-0-is-now-available-for-download/

**Comment by comicfans** [comment]
I'm already upgraded to 4.0 and compiled successfully, but it's better to mention this in documents.
