### ISSUE TITLE
Cannot Compile on Gentoo

### ISSUE THREAD

**Issue by vanthome** [OmniSharp/omnisharp-roslyn#613]
```
thoppe@client11 /temp2/omnisharp-roslyn $ ./build.sh 
Feeds used:
  /home/thoppe/.local/share/NuGet/Cache
  /home/thoppe/.nuget/packages/
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

Alle in "/temp2/omnisharp-roslyn/scripts/packages.config" aufgeführten Pakete sind bereits installiert.
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...

========================================
Cleanup
========================================
Executing task: Cleanup
Finished executing task: Cleanup

========================================
BuildEnvironment
========================================
Executing task: BuildEnvironment
dotnet_install: Error: OS name could not be detected
ldconfig is not in PATH, trying /sbin/ldconfig.
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003121/dotnet-dev--x64.1.0.0-preview2-003121.tar.gz
dotnet_install: Error: Download failed
An error occured when executing task 'BuildEnvironment'.
Error: .NET CLI binary cannot be found.

```

what can I do?

**Comment by willl** [comment]
Hi @vanthome,

I think your issue is probably to do with dotnet CLI not being able to detect your OS rather than anything specific to omnisharp-roslyn.

See: https://github.com/dotnet/cli/blob/44bf7b499e2967bc1ebfcb377e70b3cb237f218c/scripts/obtain/dotnet-install.sh#L67

And: https://github.com/dotnet/cli/issues/1835, which has been closed in favour of https://github.com/dotnet/cli/issues/1532

**Comment by DustinCampbell** [comment]
Correct. Currently, compilation will not work on Gentoo because the .NET CLI does not support it today. The .NET CLI is dependent upon the CoreCLR to run, and there are specific versions of CoreCLR needed for each Linux distro.

**Comment by vanthome** [comment]
ok, then we can close this. For all Gentooers, you can have .net core working via this overlay:

https://github.com/gentoo/dotnet
