### ISSUE TITLE
Fix attribute name

### ISSUE THREAD

**Issue by eByte23** [OmniSharp/omnisharp-roslyn#614]
When adding an attribute to a Class,Method etc..

TestAttribute is valid as [Test] or [TestAttribute]

You are always forced to use [TestAttribute] in intellisense but when manually changed to [Test] it is still valid syntax.

As soon as you use visual studio it gives info message to say can be shortened.

**Comment by willl** [comment]
Thanks for raising this, it's a long-standing known issue.

See: https://github.com/OmniSharp/omnisharp-roslyn/issues/7#issuecomment-67890516

**Comment by eByte23** [comment]
Ahh cool. Sorry searched attributes before opening but that didn't show up.
As long as it's known.

**Comment by willl** [comment]
All good.

Also noticed it reported elsewhere (by editors that use omnisharp-roslyn).
Eg: https://github.com/OmniSharp/omnisharp-vscode/issues/393

**Comment by filipw** [comment]
Should be addressed in https://github.com/OmniSharp/omnisharp-roslyn/pull/840

**Comment by filipw** [comment]
this has been fixed in #840 and subsequent PRs
