### ISSUE TITLE
Types in shared source projects generate ambiguous references everywhere

### ISSUE THREAD

**Issue by GoldenCrystal** [OmniSharp/omnisharp-roslyn#615]
Hi,

In a project started with vscode a few month ago, I made use of shared source peojects to allow the same basic code to be included in multiple assemblies.
Once migrated to the latest version of the tools, I noticed that everywhere where a type from a shared source project was referenced, I could see an error message similar to "The call is ambiguous between the following methods or properties: Item.Item(int) and "Item.Item(int)".

I've tried many tweaks to the project files, with no success, ans since it used to work a few months ago, I think this may be a bug with omnisharp.

You should be able to reproduce the problem with the following configuration:

global.json:

``` json
{
  "projects": [ "src" ],
  "sdk": {
    "version": "1.0.0"
  }
}
```

src\Main\project.json:

``` json
{
    "description": "Main project referencing the shared source.",
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Shared": {
            "version": "1.0.0-*",
            "type": "build"
        }
    },
    "frameworks": {
        "net451": { }
    }
}
```

src\Main\Program.cs:

``` csharp
namespace Test
{
    internal static class Program
    {
        private static void Main()
        {
            var item = new Item(10);
        }
    }
}
```

src\Shared\project.json:

``` json
{
    "description": "Shared source project.",
    "version": "1.0.0-*",
    "frameworks": {
        "net451": { }
    },
    "shared": "**\\*.cs"
}
```

src\Shared\Item.cs:

``` csharp
namespace Test
{
    internal class Item
    {
        public int Id { get; }

        public Item(int id)
        {
            Id = id;
        }
    }
}
```

Could you look into that?

**Comment by david-driscoll** [comment]
In this case I think it's because the dependency is set as `"type": "build"`.  Is this strictly required for your use cases.

From what I recall (it's been a while since I looked at it), build type dependencies roll in the files at build time as part of the assembly, instead of using a reference.

**Comment by GoldenCrystal** [comment]
The ASP.NET team still uses this way of sharing code across assemblies, and I am not aware of any other way to achieve this:
https://github.com/aspnet/Common/blob/dev/src/Microsoft.Extensions.Primitives/project.json
https://github.com/aspnet/Common/blob/dev/src/Microsoft.Extensions.HashCodeCombiner.Sources/project.json
I've used the same setup for months and it worked like a charm, but not anymore. The code still compiles with dotnet-cli, but I see a lot of red squiggles in vscode.
Also, removing the "type": "build" on the project reference, does not seem to help in any way.

**Comment by filipw** [comment]
Since project.json is not supported anymore I will close this issue.
