### ISSUE TITLE
Reference location issue

### ISSUE THREAD

**Issue by wjk** [OmniSharp/omnisharp-roslyn#625]
I am trying to use OmniSharp in Visual Studio Code to provide IntelliSense for a fairly complicated MSBuild-based .NET Core project. I am using a fork of [dotnet/buildtools](https://github.com/dotnet/buildtools) (private repo, unfortunately). When I load the solution file, OmniSharp loads and parses the `*.csproj` files, but it provides no IntelliSense and emits 20,000+ predefined-type-not-found errors. Apparently, OmniSharp's MSBuild plugin is not looking for the `Microsoft.Portable.CSharp.targets` file in the right place, and as such the references are not correctly resolved. [Here's the full log.](https://gist.github.com/wjk/c72da9d11c12c71add1b8c2839ee0388) Any pointers? Thanks!

**Comment by willl** [comment]
I'm just guessing here, but perhaps it needs to be added [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/bd2183f294282c8fdbf86b22ef26b26b73309c15/src/OmniSharp/project.json#L11): https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp/project.json#L11

Looking at the [project.json documentation](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json), which says:
```
publishOptions
Type: Object

An object containing properties for compilation configuration.
```

So perhaps fork omnisharp-rolsyn and make the change to see if it works for you? If so, then send in a PR etc.

**Comment by wjk** [comment]
@willl That's true, but this file is deployed as part of Visual Studio. Is it OK license-wise for me to add this file, or more similar ones, to the OmniSharp repo? In addition, OmniSharp’s VSCode plugin is looking for this file in a very specific directory; in my case reproduced as (1) below. I don’t know if the `project.json` file has enough smarts to put this file in the appropriate place. Is there a way for me to add the file’s actual location, in my case (2) below, to the path that OmniSharp uses to resolve MSBuild `<Import/>` tags?

```
(1) C:\Users\William\.vscode\extensions\ms-vscode.csharp-1.3.0\out\.omnisharp-coreclr\Extensions\Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets
(2) C:\Program Files (x86)\MSBuild
```

**Comment by wjk** [comment]
@willl I figured it out, at least for my specific use-case; I need to override the `$(TargetFrameworkIdentifier)` and `$(TargetFrameworkVersion)` to be `.NETCoreApp` and `v1.0`, respectively. Then the project loads with no missing-predefined-type errors.

**Comment by wjk** [comment]
…except that now it tells me that the reference assemblies for `.NETCoreApp`/`.NETStandard`/whatever are not found, and that the assemblies in the GAC will be used instead. This gives me hundreds of version-mismatch warnings and no working IntelliSense.

**Comment by DustinCampbell** [comment]
@wjk: Note that the CoreCLR MSBuild will not locate targets that are intended for the Desktop version of MSBuild. The reason is that it can't actually load and run tasks that the Desktop targets point to -- i.e. the assemblies containing the targets will generally not run on Desktop. See https://github.com/Microsoft/msbuild/issues/711 for more details.

**Comment by DustinCampbell** [comment]
I think this is working better for you now with the latest VS Code extension for C#, correct?
