### ISSUE TITLE
autocomplete always returns null for Kind and other fields

### ISSUE THREAD

**Issue by danwalmsley** [OmniSharp/omnisharp-roslyn#630]
The data returned for autocomplete is always null for the Kind and Documentation and other fields.

Is this because its not implemented yet? Or because of a technical difficulty?

 If someone can point me where the implementation is missing I can probably submit a PR to resolve this.

**Comment by DustinCampbell** [comment]
@danwalmsley: Did you specify [WantKind](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Abstractions/Models/v1/AutoCompleteRequest.cs#L53) and [WantDocumentationForEveryCompletionResult](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Abstractions/Models/v1/AutoCompleteRequest.cs#L26) in your autocomplete request?

**Comment by DustinCampbell** [comment]
@danwalmsley: do you have any update?

**Comment by danwalmsley** [comment]
Hi, sorry been away. WantKind worked, and wantdocumentation also worked, however I believe it looks like the documentation was only partially parsed, it came back as xml and I had to parse manually. Will have a look at my code and find repro steps.

**Comment by DustinCampbell** [comment]
It does come back as XML. That is how the end point is designed.

**Comment by DustinCampbell** [comment]
Closing this issue as it is working as designed.
