### ISSUE TITLE
Latest release breaks scriptcs in Vs Code and Visual Studio 2015

### ISSUE THREAD

**Issue by seesharper** [OmniSharp/omnisharp-roslyn#631]
We used to get OmniSharp running for .csx files in Visual Studio Code by providing an empty project.json file. Thus has been working for a LONG time now. 

With the latest release it throws the following error.

[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree

Another option is to debug scripts in VS using a project that scriptcs sets up for us

```
:openvs "somescript.csx"
```

This also stopped working although I am not sure about the relation between VS 2015 and OmniSharp in this case.

Nevertheless, downgrading to beta13 solved the issue, at least for VS Code. 

I had to specify the path to OmniSharp in the workspace settings

```
{
    "omnisharp.path": "C:/omnisharp-win-x64-net451"
}
```

**Comment by filipw** [comment]
The problem (or rather not problem, just the cause of this situation) is that VS Code will use .NET Core version of omnisharp which has no scripting support at the moment.

If you manually point to Desktop CLR / Mono build of omnisharp using `omnisharp.path`, it's gonna work again (no need to downgrade to beta13, latest works too).

**Comment by seesharper** [comment]
Okay, how would such a configuration look like? 
The strange thing is that intellisense for .csx files stopped working for me yesterday in Visual Studio 2015.
I did update the .Net Core tooling stuff. Is that related somehow?

**Comment by filipw** [comment]
just download latest desktop build from [here](https://github.com/OmniSharp/omnisharp-roslyn/releases) and unzip somewhere

Then go to `File > Preferences > User Settings` and point to your newly unzipped omnisharp executable:

```
// Place your settings in this file to overwrite the default settings
{
    "omnisharp.path": "c:\\code\\omnisharp\\OmniSharp.exe"
}
```

**Comment by seesharper** [comment]
Nice. Any suggestion on why is is broken in Visual Studio 2015 too?. Might be off-topic here though :)

**Comment by filipw** [comment]
sorry, no idea at the moment - but please open an issue scriptcs repo
