### ISSUE TITLE
build error  on windows 10 x64

### ISSUE THREAD

**Issue by sunriseyuen** [OmniSharp/omnisharp-roslyn#633]
# 
# BuildEnvironment

Executing task: BuildEnvironment
dotnet-install: .NET SDK version 1.0.0-preview2-003121 is already installed.
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
Feeds used:
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

已安装程序包“xunit.runner.console.2.2.0-beta2-build3300”。
Finished executing task: BuildEnvironment
# 
# PopulateRuntimes

Executing task: PopulateRuntimes
Finished executing task: PopulateRuntimes
# 
# Setup

Executing task: Setup
Finished executing task: Setup
# 
# Restore

Executing task: Restore
Restoring packages....
Package restore successful!
Restoring packages....
Package restore successful!
Finished executing task: Restore
# 
# BuildTest

Executing task: BuildTest
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(19,15): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.5.1 in
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(21,28): error NU1001: The dependency System.Runtime could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(22,30): error NU1001: The dependency System.Threading could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(23,36): error NU1001: The dependency System.Threading.Tasks could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(24,32): error NU1001: The dependency System.Collections could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(25,25): error NU1001: The dependency System.Linq could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(26,34): error NU1001: The dependency System.Text.Encoding could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(27,31): error NU1001: The dependency System.Reflection could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(28,29): error NU1001: The dependency System.Security could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(29,34): error NU1001: The dependency System.Globalization could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(30,24): error NU1001: The dependency System.Xml could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(31,29): error NU1001: The dependency System.Xml.Linq could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(12,56): error NU1001: The dependency mscorlib could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(12,56): error NU1001: The dependency mscorlib could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(8,37): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(10,50): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(11,49): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(12,56): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(14,51): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(8,37): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(10,50): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(11,49): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(12,56): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(14,51): error NU1001: The dependency System could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(10,50): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(11,49): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(12,56): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(14,51): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(10,50): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(11,49): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(12,56): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(14,51): error NU1001: The dependency System.Core could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(10,50): error NU1001: The dependency System.ComponentModel.Composition could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(11,49): error NU1001: The dependency System.ComponentModel.Composition could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(12,56): error NU1001: The dependency System.ComponentModel.Composition could not be resolved.
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.Abstractions\project.json(14,51): error NU1001: The dependency System.ComponentModel.Composition could not be resolved.
An error occured when executing task 'BuildTest'.
Error: Building test OmniSharp.Stdio.Tests failed for net451.

**Comment by david-driscoll** [comment]
It kind of sounds like the dotnet assemblies are not registered properly.

This is based on the line:
D:\System\build-Vim\omnisharp-roslyn\src\OmniSharp.
Abstractions\project.json(19,15): error DOTNET1011: Framework not
installed: .NETFramework,Version=v4.5.1 in

I've not personally seen that before.

**Comment by DustinCampbell** [comment]
I've updated OmniSharp to .NET 4.6. Do you still see this failure? If so, you might try installing the [Microsoft .NET 4.5.1 Developer Pack](https://www.microsoft.com/en-us/download/details.aspx?id=40772).

Note that this failure can occur on machines where no Visual Studio has been installed (or a Visual Studio version earlier than 2013).

**Comment by bsermons** [comment]
I got this same error with .NET 4.6 and the solution was to download the corresponding .NET targeting pack [here](https://www.microsoft.com/en-us/download/details.aspx?id=48136)

**Comment by DustinCampbell** [comment]
This issue has grown pretty stale. Let me know if you're still experiencing the issue, and we'll take a look.
