### ISSUE TITLE
Can't build on macOS Sierra

### ISSUE THREAD

**Issue by d12frosted** [OmniSharp/omnisharp-roslyn#643]
Hey,

Just tried to build `omnisharp` on macOS Sierra 10.12 and run into multiple errors. I saw similar issue on other projects and if I understand the problem correctly, this must be fixed on project level.

# Problem

```
$ git rev-parse HEAD
3d943b4f5b21ce97667a0be06b8110e63c6456ec

$ ./build.sh
Feeds used:
  /Users/d12frosted/.local/share/NuGet/Cache
  /Users/d12frosted/.nuget/packages/
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

All packages listed in /Users/d12frosted/Developer/Other/omnisharp-roslyn/scripts/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...

========================================
Cleanup
========================================
Executing task: Cleanup
Finished executing task: Cleanup

========================================
BuildEnvironment
========================================
Executing task: BuildEnvironment
dotnet-install: .NET SDK version 1.0.0-preview2-003121 is already installed.
dotnet-install: Adding to current process PATH: /Users/d12frosted/Developer/Other/omnisharp-roslyn/.dotnet. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
Feeds used:
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

Package "xunit.runner.console.2.2.0-beta2-build3300" is already installed.
Finished executing task: BuildEnvironment

========================================
PopulateRuntimes
========================================
Executing task: PopulateRuntimes
Finished executing task: PopulateRuntimes

========================================
Setup
========================================
Executing task: Setup
Finished executing task: Setup

========================================
Restore
========================================
Executing task: Restore
Restoring packages....
Package restore successful!
Restoring packages....
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample06/src/Project2/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample06/tests/Test1/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestUtility/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/tests/Test1/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/src/Project1/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/src/Project2/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/src/Project2/Embed/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample06/src/Project2/Embed/project.json...
error: System.Diagnostics.Process 4.1.0 provides a compile-time reference assembly for System.Diagnostics.Process on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with osx.10.12-x64.

...
```

Full log can be found [here](https://github.com/OmniSharp/omnisharp-roslyn/files/487614/roslyn.txt).

Oh, and just to make this report more interesting, here is screenshot that made my day. I wasn't ready for this 💃 😸 

<img width="958" alt="screenshot 2016-09-22 18 04 53" src="https://cloud.githubusercontent.com/assets/6507913/18753797/1202c578-80ef-11e6-9295-a4c8c5e16472.png">

P. S. Sorry if it's actually not related to Omnisharp.

**Comment by willl** [comment]
You'll probably need to change [this line](https://github.com/OmniSharp/omnisharp-roslyn/blob/c651f0418d0ba130e2c05a84743e74469717724e/src/OmniSharp/project.json#L40) to `osx.10.12-x64`.

**Comment by d12frosted** [comment]
@willl 

Thanks for suggestion. But still doesn't work. I also tried to build on clean repository (so it downloaded some required tools / libs) with that change in `project.json` file. [Here](https://dl.dropboxusercontent.com/u/14438695/omnisharp/build.log) is new output (52.3 Mb and buffer has 202401 lines, 8321969 words, and 54891506 characters 😸).

**Comment by DustinCampbell** [comment]
@d12frosted, @wjk: Could you try PR #642? Does that address the problem. I'm a bit nervous about updating to Sierra myself to see if it fixes it.

**Comment by DustinCampbell** [comment]
Ah -- I see why it's failing. We didn't specify a RID in build.cake on OSX: https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/build.cake#L118

**Comment by DustinCampbell** [comment]
I *think* I've got a fix for this here: https://github.com/OmniSharp/omnisharp-roslyn/pull/644. It'd be great if somebody could pull that change and try it out.

**Comment by DustinCampbell** [comment]
It looks like we also do a "dotnet restore --infer-runtimes" for tests in https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/build.cake#L172-L183, which will *certainly* break on macSierra.

**Comment by wjk** [comment]
@DustinCampbell Replacing `dotnet restore --infer-runtimes` with just plain `dotnet restore` causes the restore to succeed, but then the `BuildTest` target fails with the following message:

```
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'osx.10.12-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.12-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
```

**Comment by DustinCampbell** [comment]
Yeah, "default" keeps getting threaded through various steps in the build process. I've updated to macSierra and am working through the issues.

**Comment by DustinCampbell** [comment]
OK. #644 should fix this now.

**Comment by d12frosted** [comment]
@DustinCampbell thank you for suggestions. I will try those PRs today in the evening. And I'll let you know about results.

> I'm a bit nervous about updating to Sierra myself to see if it fixes it.

Now I am a bit nervous about doing update as well 😸 💃

**Comment by DustinCampbell** [comment]
@d12frosted: No worries. #644 does fix the build.

**Comment by d12frosted** [comment]
@DustinCampbell indeed. Thanks for a quick solution! 💃 ❤️
