### ISSUE TITLE
Files in csproj

### ISSUE THREAD

**Issue by eByte23** [OmniSharp/omnisharp-roslyn#645]
Hi, 
This is a combination vscode and roslyn issue.

I use vscode to work on a .net project that contains asp classic files also. We have others using visual studio. 
When creating new c# and asp files it does not get added to csproj causing build issues for .net part and also non visible asp files in visual studio.

Could we show the files like visual studio which files are in the project and which are not. and for new files add them to the csproj

Sorry if this is dup, couldn't find an exact match.

**Comment by filipw** [comment]
OmniSharp will not support managing files using the legacy csproj project format - this is by design.
For new ("modern") project SDK, the files no longer need to be managed in the csproj file one by one explicitly.
