### ISSUE TITLE
net451 version crashes in Emacs

### ISSUE THREAD

**Issue by kimgronqvist** [OmniSharp/omnisharp-roslyn#647]
If I try to run the net451 version in Emacs on Windows 10, Emacs just crashes. The netcoreapp version however works fine. It's not related to `omnisharp-emacs` since just running `(start-process "foo" "*foo*" "OmniSharp")` causes a crash.

There are also several reports on different Windows configurations here: https://github.com/OmniSharp/omnisharp-emacs/issues/178

I've also tried this on the latest Emacs version (25.1) as well as an older one (24.4), with the same result.

**Comment by willl** [comment]
Hi @kimgronqvist, omnisharp-Roslyn was recently migrated to .NET 4.6, could you please re-test and see if that works better?

**Comment by kimgronqvist** [comment]
Sadly, no. This bug still persists with the latest version.

**Comment by JosephFerano** [comment]
Confirming this bug as well. Using emacs 25.2 with net451 v1.15.0
I'm trying to use omnisharp with Unity. From what I understand, I need to use net451; can't really use dotnetcore, so hopefully this can get fixed soon cause if not I can't use emacs with omnisharp for Unity.

**Comment by JosephFerano** [comment]
I just tested on emacs 25.2 with the 64bit version of O# net46 v.1.16.0, and it's still crashing. However, 32bit seems to be working fine!

However, I got these errors;
```OmniSharp server error: The project system ’OmniSharp.MSBuild.MSBuildProjectSystem’ threw exception during initialization.``` When I try to call go-to-definition, I get this warning; `Cannot go to definition as none was returned by the API.` Which I figure has to do with the exception.

Going to investigate further.

**Comment by JosephFerano** [comment]
I tested with a newly created Unity3D project. The trick is that you have to add a C# file to a normal directory and to an "Editor" directory, this will generate two csproj files. This is standard behavior in Unity, it will add up to 4 csprojs, here's a typical production Unity3D project in 5.6

```

Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "trolls-main", "Assembly-CSharp.csproj", "{950AC16F-807D-663D-1894-C53D473CC4B0}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "trolls-main", "Assembly-CSharp-Editor-firstpass.csproj", "{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "trolls-main", "Assembly-CSharp-Editor.csproj", "{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Release|Any CPU.Build.0 = Release|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Release|Any CPU.Build.0 = Release|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(MonoDevelopProperties) = preSolution
		StartupItem = Assembly-CSharp.csproj
	EndGlobalSection
EndGlobal
```

**Comment by razzmatazz** [comment]
Emacs bug has been reported in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27527 and should be fixed in the next emacs version.

In the meantime -x86- (NOT -x64-) omnisharp-roslyn bundle should be used instead, 32bit server exe doesn't crash for me.

**Comment by razzmatazz** [comment]
omnisharp-emacs now has the `M-x omnisharp-install-server` command that will properly setup the server for you automatically (see https://github.com/OmniSharp/omnisharp-emacs/issues/275).

It will also avoid 64bit binary on windows and will use 32bit one for now (until emacs-26 is released and detected). I think this issue can be closed then

**Comment by filipw** [comment]
I will close this as this is tracked in https://github.com/OmniSharp/omnisharp-emacs/issues/275, for any other Emacs issue, please open them in https://github.com/OmniSharp/omnisharp-emacs repo.
