### ISSUE TITLE
"Error: OS name could not be detected" on Fedora 24

### ISSUE THREAD

**Issue by dukebw** [OmniSharp/omnisharp-roslyn#655]
Hi,

I am trying to build omnisharp-roslyn on Fedora 24. When I run build.sh, I get the following error,
# 
# BuildEnvironment

Executing task: BuildEnvironment
dotnet_install: Error: OS name could not be detected
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003131/dotnet-dev--x64.1.0.0-preview2-003131.tar.gz
dotnet_install: Error: Download failed
An error occured when executing task 'BuildEnvironment'.
Error: .NET CLI binary cannot be found.

It appears to be an issue with getting the dotnet cli source code, since Fedora 24 is not supported. However, I am able to build dotnet cli from source using the dotnet/cli rel/1.0.0-preview2.1 branch, which does support Fedora 24.

I was wondering if there is any direction I can take to force the omnisharp-roslyn build to use this rel/1.0.0-preview2.1 branch to get dotnet cli?

**Comment by DustinCampbell** [comment]
This should have been fixed with #835
