### ISSUE TITLE
Unable to Build on Ubuntu

### ISSUE THREAD

**Issue by dalealleshouse** [OmniSharp/omnisharp-roslyn#658]
I am unable to build. The output is below. I'm running Ubuntu 16.10 and Mono 4.6.1.

Can someone help me out?

```bash
$ ./build.sh
Downloading NuGet...
Feeds used:
  /home/dalealleshouse/.local/share/NuGet/Cache
  /home/dalealleshouse/.nuget/packages/
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.10.1.
WARNING: Unable to find version '0.10.1' of package 'Cake'.
Restoring NuGet package Newtonsoft.Json.8.0.3.
WARNING: Unable to find version '8.0.3' of package 'Newtonsoft.Json'.
Could not find Cake.exe at '/home/dalealleshouse/.vim/bundle/omnisharp-vim/omnisharp-roslyn/scripts/../.tools/Cake/Cake.exe'.
```

**Comment by willl** [comment]
Seems like it's possibly similar to issues #650 and possibly #651,

**Comment by dalealleshouse** [comment]
Thanks @nmschulte , as the other issue suggested, I updated the nuget.exe. This got me a little bit further, but I had to also add some certs as outlined [here](http://stackoverflow.com/questions/15181888/nuget-on-linux-error-getting-response-stream)

Now, I have a new error:
```bash
========================================
Restore
========================================
Executing task: Restore
Restoring packages in /home/dalealleshouse/.vimpkg/bundle/omnisharp-vim/omnisharp-roslyn....
Failed to initialize CoreCLR, HRESULT: 0x80131500

An error occured when executing task 'Restore'.
Error: Failed to restore projects under working directory.
```

**Comment by dalealleshouse** [comment]
I was able to get a bit further by reinstall dotnet core

```bash
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'ubuntu.16.10-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'ubuntu.16.10-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
An error occured when executing task 'OnlyPublish'.
Error: Failed to publish OmniSharp / netcoreapp1.0
```

**Comment by nmschulte** [comment]
> 2. The project does not list one of 'ubuntu.16.10-x64' in the 'runtimes'
section.

The `/src/OmniSharp/project.json` doesn't include Ubuntu 16.10, only
16.04.  I'm not sure the implications, but maybe just add `16.10`?

**Comment by dalealleshouse** [comment]
Now I'm getting a bunch of new errors. There are several different assemblies listed with the same error.

```bash
error: System.IO.FileSystem.Watcher 4.0.0 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with ubuntu.16.10-x64.
```

**Comment by willl** [comment]
@dalealleshouse Could you paste the output of `dotnet --version`?

You might need to update dotnet to [1.1 Preview 1](https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-net-core-1-1-preview-1/) to support Ubuntu 16.10 from what I can see [here](https://github.com/dotnet/corefx/commit/cb217c066c93e331059f0273f816074faf3f456c).

**Comment by dalealleshouse** [comment]
@willl I did the install as outlined on your link, and below is the output. It looks like the build.sh script downloads a version of dotnet for some reason.

```bash
1.0.0-preview2-1-003155
```

**Comment by dalealleshouse** [comment]
I updated the OmniSharp project ofto use 1.1 preview

- Update the netcoreapp1.0 target framework to netcoreapp1.1.
- Update the Microsoft.NETCore.App package version from 1.0.x (for example, 1.0.0 or 1.0.1) to 1.1.0-preview1-001100-00.

Now I'm getting this error:

```bash
'/home/dalealleshouse/.vimpkg/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp' cannot be published for 'netcoreapp1.0' '<no runtime provided>'
An error occured when executing task 'OnlyPublish'.
Error: Failed to publish OmniSharp / netcoreapp1.0
```

**Comment by dalealleshouse** [comment]
I got this working by also editing the version in the build.json file. I submitted a pull request.

**Comment by Sujay-shetty** [comment]
@dalealleshouse 
I'm also facing the same issue while installing in Ubuntu 14.04.
Could you share what did you edited in build.json

**Comment by rajivpopat** [comment]
Any updates on this? This is the exact same issue I'm also facing and modifying the project.json file doesn't seem to help.
