### ISSUE TITLE
Code actions that show UI in visual studio -- missing?

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-roslyn#66]
When you have a interface and you get code actions on the name of your interface v1 server showed "implement inteface", eg/ https://github.com/OmniSharp/omnisharp-server/pull/151/files

**Comment by Yantrio** [comment]
I can't find anything in NR6 about abstract classes :cry: Also, stuff like this ( [NR6/.../ImplementInterfaceAction.cs](https://github.com/icsharpcode/NRefactory/blob/roslyn/ICSharpCode.NRefactory.CSharp.Refactoring/CodeActions/ImplementInterfaceAction.cs ) ) makes me think that NR6 isn't 100% ready for us to use, and we may have to cherrypick codeactions from all over :)

**Comment by jchannon** [comment]
Another one missing - "create field from ctor arg"

**Comment by rchande** [comment]
@akshita31 This issue is referring to 2 code actions that show UI in Visual Studio: implement interface and generate constructor. In both cases, the UI lets you control what members are used. I would propose that we implement this in O# in a way that doesn't show any UI and just generates as many members as possible.

**Comment by DustinCampbell** [comment]
Implement Interface doesn't show UI. I think you mean, "Extract Interface". There's also... "Generate Type", "Generate Equals/Hashcode", "Reorder Parameters", etc.

**Comment by rchande** [comment]
@DustinCampbell D'oh. You're right. Actually, "implement interface" and "generate field from ctor arg" already show up as code actions. Since this bug apparently no longer reproduces, I'm going to close and file a new feature request for the UI-based code actions.

**Comment by rchande** [comment]
Filed https://github.com/OmniSharp/omnisharp-roslyn/issues/1220
