### ISSUE TITLE
Excessive "runtime policy" warnings

### ISSUE THREAD

**Issue by wjk** [OmniSharp/omnisharp-roslyn#662]
I have a moderately-sized .NET Core project (private repo), which I am editing in Visual Studio Code using OmniSharp. For some time now, every time I reference an API from CoreFX, OmniSharp emits the following error text:

> Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Runtime.Extensions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy

The names of the assemblies vary depending on which API is being used, but the basic gist of the error is the same every time. I’ve grepped through the omnisharp-roslyn source code, but cannot find this error text anywhere. This indicates it probably is being emitted by an assembly built by dotnet/roslyn. However, as this seems to be an OmniSharp-specific behavior (it does not occur when I build a project exhibiting this behavior, for example), I am raising the issue here first.

**Comment by DustinCampbell** [comment]
This is actually [CS1701](https://msdn.microsoft.com/en-us/library/2h4x8b08.aspx) -- a warning from the C# compiler. I noticed the [project file you provided me with](https://gist.github.com/wjk/c6060c955bb894c4133d11be80572980) in #661 actually has a `NoWarn` for this particular warning.

Note that the DotNetProjectSystem specifically suppresses this warning [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.DotNet/DotNetProjectSystem.cs#L336).

**Comment by DustinCampbell** [comment]
This got fixed recently.
