### ISSUE TITLE
Add NUnit support in VS Code

### ISSUE THREAD

**Issue by HexWrench** [OmniSharp/omnisharp-roslyn#671]
Omnisharp has great support for XUnit in VS Code with the addition to CodeLens (run/debug tests).
Unfortunately, NUnit support is missing. It would be great if NUnit tests could be ran/debugged in VS Code the same way as XUnit tests.

**Comment by willl** [comment]
Looking at the old [PR](https://github.com/OmniSharp/omnisharp-roslyn/pull/562) that introduced xUnit, looks like a lot of it will work if you just switch to using the [nunit 3 test runner for .NET Core](https://github.com/nunit/dotnet-test-nunit), and add functionality similar to [TestFeaturesDiscoverer](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.DotNetTest/Helpers/TestFeaturesDiscover.cs), but for NUnit to discover their unit test methods.

I think (untested), that much of the current xUnit (minus the test features discover) can be reused as it looks like it just calls `dotnet test` under the hood, which will work if you use the nunit 3 runner for .net core I linked to earlier.

**Comment by HexWrench** [comment]
I added discovery for NUnit tests in TestFeaturesDiscoverer which would bring up the run/debug test in code lens:
```
private bool IsNUnitTest(ITypeSymbol symbol)
{
    string fullName;
    do
    {
        fullName = $"{symbol.ContainingNamespace}.{symbol.Name}";

        if (fullName == "NUnit.Framework.TestAttribute"
            || fullName == "NUnit.Framework.TestCaseAttribute"
            || fullName == "NUnit.Framework.TestCaseSourceAttribute")
        {
            return true;
        }

        symbol = symbol.BaseType;
    } while (symbol.Name != "Object");

    return false;
}
```
But the dotnet test runner for NUnit does not support the `--method MyTestMethod` argument to `dotnet test`. Using `--test MyTestMethod` works for NUnit, and for XUnit too.

I'll do further testing and (hopefully) create a PR (which would be my first one ever).

**Comment by HexWrench** [comment]
I commited a first version in my [repo](https://github.com/HexWrench/omnisharp-roslyn).
It only adds the run/debug tests to code lens yet.

**Comment by david-driscoll** [comment]
If you need any help feel free to ask.  We're also on slack if you need... though I seem to have lost the invite link and can't get to it at the moment.

**Comment by HexWrench** [comment]
Yeah thanks, the invite link was in the Readme.

This is my first VS Code extension, so I don't know if this is the correct way to implement.
My idea how to do this:
- Use different feature names for Xunit and NUnit (currently it's `XunitTestMethod`). Changing this will result in changes in the VS Code extension since it displays "run/debug test" for feature `XunitTestMethod`.
- When executing the command, send additional information about the test runner (use the feature name to check if it's NUnit or Xunit), so the correct argument can be used (`-method` or `--test`) 

Maybe someone from the team can have a quick look and tell me if I'm on the right way with this approach.

**Comment by DustinCampbell** [comment]
FWIW, this repo is for the OmniSharp server itself. Issues for the C# extension in VS Code (powered by OmniSharp) should be filed over in https://github.com/OmniSharp/omnisharp-vscode. Thanks!
