### ISSUE TITLE
Goto definition not working for symbols from external module

### ISSUE THREAD

**Issue by Jayatubi** [OmniSharp/omnisharp-roslyn#678]
Environment:

    Omnisharp: 1.5.3
    VScode: 1.7.2
    OS: macOS Sierra 10.12
    Unity: 5.4.1p1

Description:

    The `Goto definition` works only for the symbols within the same project, in other words from source code.
    For the symbols from external modules, such as UnityEngine.dll, Omnisharp only display the doc string while the mouse hover the symbol. There is no underline appear when hover with `cmd` key pressed and the F12 doesn't work neither.

Suppose to be:

    In the previous version the `Goto definition` would open a new tab and show the meta, reflection, information about the symbols.

**Comment by DustinCampbell** [comment]
This repo is for the OmniSharp server. Please file issues for the C# extension at https://github.com/OmniSharp/omnisharp-vscode. Thanks!

**Comment by Jayatubi** [comment]
Sorry for the mistake.

**Comment by DustinCampbell** [comment]
No problem. Just wanted to give you a chance to own the issue before I ported it. :smile:
