### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-roslyn#68]
Something is causing 70% CPU on one core on mono. Not sure whether its the DTH or the server.

I think we're all aware of this but just thought I'd raise an issue

**Comment by nosami** [comment]
Haven't noticed it myself yet.

**Comment by jchannon** [comment]
I know I have & @davidfowl @mat-mcloughlin have

**Comment by nosami** [comment]
OK. Can one of you tell me whether it is DTH or the server?

**Comment by jchannon** [comment]
Ok just looked and its the server

**Comment by nosami** [comment]
Can you post the results of ```ps ax | grep klr`` in here?

**Comment by jchannon** [comment]
![screen shot 2015-02-09 at 15 41 28](https://cloud.githubusercontent.com/assets/105126/6109371/42b424e0-b072-11e4-8b21-f2d44ca3a52a.png)


[15:42:40] jonathan:~ $ ps ax | grep klr
14578   ??  S      0:00.00 /bin/bash /Users/jonathan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/PrebuiltOmniSharpServer/approot/packages/KRE-Mono.1.0.0-beta2/bin/klr Microsoft.Framework.ApplicationHost omnisharp -s /Users/jonathan/Projects/omnisharp-roslyn -p 62565 -config /Users/jonathan/config.json --hostPID 14571
14582   ??  R      2:33.26 mono /Users/jonathan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/PrebuiltOmniSharpServer/approot/packages/KRE-Mono.1.0.0-beta2/bin/klr.mono.managed.dll Microsoft.Framework.ApplicationHost omnisharp -s /Users/jonathan/Projects/omnisharp-roslyn -p 62565 -config /Users/jonathan/config.json --hostPID 14571
14583   ??  S      0:00.00 /bin/bash /Users/jonathan/.kre/packages/KRE-Mono.1.0.0-beta2/bin/klr /Users/jonathan/.kre/packages/KRE-Mono.1.0.0-beta2/bin/lib/Microsoft.Framework.DesignTimeHost/Microsoft.Framework.DesignTimeHost.dll 62567 14582 298e3e41-2928-4741-aef3-58b08a9fefdf
14587   ??  S      0:04.70 mono /Users/jonathan/.kre/packages/KRE-Mono.1.0.0-beta2/bin/klr.mono.managed.dll /Users/jonathan/.kre/packages/KRE-Mono.1.0.0-beta2/bin/lib/Microsoft.Framework.DesignTimeHost/Microsoft.Framework.DesignTimeHost.dll 62567 14582 298e3e41-2928-4741-aef3-58b08a9fefdf
14954 s000  S+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn klr

**Comment by nosami** [comment]
I suspect that it's being caused by ManualEventResetSlim

https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Program.cs#L122 or in AspNet5ProjectSystem or the FileSystemWatcher.

CPU usage should be almost 0% when it's not being used.

**Comment by nosami** [comment]
Can't reproduce. CPU doesn't go above the 4% mark for me when idle. Profile here https://gist.githubusercontent.com/nosami/08267fedb62edbeb4a27/raw/gistfile1.txt

**Comment by jchannon** [comment]
High CPU usage is only when I open the omnisharp project in Sublime. If I open another in another window its 0.3%

![screen shot 2015-02-11 at 19 03 56](https://cloud.githubusercontent.com/assets/105126/6154063/d069c3c6-b220-11e4-9e1a-60f6731a557e.png)

**Comment by davidfowl** [comment]
Yea, sublime is destroying my machine on osx

**Comment by nosami** [comment]
I managed to reproduce this with the profiler attached. Server started, didn't use it at all. 100% CPU usage.

Almost definitely the file system watcher.

https://gist.githubusercontent.com/nosami/7cd49757d00b97dec040/raw/gistfile1.txt

**Comment by jchannon** [comment]
Fixed with #81
