### ISSUE TITLE
Unable to use multiple #load in CSX file

### ISSUE THREAD

**Issue by TzeWey** [OmniSharp/omnisharp-roslyn#689]
Using the latest `dev` build, create a folder, 3 CSX files and an empty project.json (to get OmniSharp to load).

File 1 - `A.CSX`
```
class ClassA{}
```

File 2 - `B.CSX`
```
class ClassB{}
```

File 3 - `C.CSX`
```
#load "A.CSX"
#load "B.CSX"
ClassA A = new ClassA();
ClassB B = new ClassB();
```

Intellisense shows that ClassA could not be found.
![image](https://cloud.githubusercontent.com/assets/3044158/20759569/36e027ec-b758-11e6-8af0-0ad157ce6901.png)

After swapping the `#load` around so that `C.CSX` looks like this (and restarting OmniSharp):
```
#load "B.CSX"
#load "A.CSX"
ClassA A = new ClassA();
ClassB B = new ClassB();
```

Intellisense would show that ClassB could not be found instead.
![image](https://cloud.githubusercontent.com/assets/3044158/20759524/1ad00fae-b758-11e6-823a-dfe9aa5c6998.png)

I am not able to figure out why this is happening. Is this behavior expected? Or am I doing something wrong?

Thanks!

**Comment by filipw** [comment]
thanks - will look into what's happening

**Comment by filipw** [comment]
when this is implemented https://github.com/OmniSharp/omnisharp-roslyn/pull/659#issuecomment-259746769, it should be fixed

**Comment by filipw** [comment]
fixed by github.com/OmniSharp/omnisharp-roslyn/pull/760
