### ISSUE TITLE
explore use of stdin/stdout

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#69]
The goal of this exploration is to use stdin/stdout for the communication between omnisharp-roslyn (server) and editors (client). Potential benefits will be

* better performance due to less message overhead (no http headers)
* clean relationship between editor and omnisharp and request ordering - http is multi client, allows for parallel requests etc
* simplified integration into editors as stdin/stdout is easier to support than http
* two-way communication between server and client, e.g. after a file change the server can push validation messages to the client (no need for polling)

Apart from the obvious adoption cost of editors a concern is that stdout is a shared resource that is also used for logging etc. We should not loose the logging features we have today.

**Comment by nosami** [comment]
@filipw changed the code yesterday to add a Global Filter to do the _workspace.EnsureBufferUpdated

You'll need to do it another way.

**Comment by nosami** [comment]
All logging is done through stderr currently.

**Comment by davidfowl** [comment]
I do have a crazy idea that would make mvc work over stdin/out.

**Comment by nosami** [comment]
![image](https://cloud.githubusercontent.com/assets/667194/6110808/41aa7b44-b07c-11e4-8e87-48ac53f81341.png)

**Comment by filipw** [comment]
clean relationship between editor and omnisharp and request ordering - http is multi client, allows for parallel requests etc

I wonder - has anyone considered building and running a cloud based editor using OmniSharp? as long as workspace is per user, not a singleton, that could work. Someone should change it into a business and challenge https://c9.io :smile: 

or, just from the top of my head, how about a scenario where I have a solution on my desktop, but can also edit it from my mobile device? that would work even today, as long as both devices are on the same network

    simplified integration into editors as stdin/stdout is easier to support than http

isn't HTTP the easiest thing to support? cause it works everywhere and with everything? the barrier of entry for any editor/client is probably the lowest when everything is HTTP based

**Comment by nosami** [comment]
The idea isn't to replace HTTP, but to supplement it for scenarios where
performance is a concern.

On 9 Feb 2015 19:15, "Filip W" <notifications@github.com> wrote:
>
>  clean relationship between editor and omnisharp and request ordering -
http is multi client, allows for parallel requests etc
>
> I wonder - has anyone considered building and running a cloud based
editor using OmniSharp? as long as workspace is per user, not a singleton,
that could work. Someone should change it into a business and challenge
https://c9.io
>
> or, just from the top of my head, how about a scenario where I have a
solution on my desktop, but can also edit it from my mobile device? that
would work even today, as long as both devices are on the same network
>
> simplified integration into editors as stdin/stdout is easier to support
than http
>
> isn't HTTP the easiest thing to support? cause it works everywhere and
with everything? the barrier of entry for any editor/client is probably the
lowest when everything is HTTP based

**Comment by nosami** [comment]
Another thing to consider is that it might be beneficial to have parallel requests even for a single user. 

For example, I might want to get diagnostics and code actions when the cursor stops moving.

**Comment by jrieken** [comment]
status

- [x] expose controllers via stdio
- [x] use v8 debugger protocol as message envelope
- [ ] update buffers on each request
- [ ] logging, eventing

All of this is pretty prototypical but I can see how we have a future with ```Omnisharp```, ```Omnisharp.Http``` and ```Omnisharp.Stdio```

**Comment by nosami** [comment]
Am I correct in thinking that if we used the V8 protocol, then even if there wasn't a native v8 debugger for the editor, we could use something like [node-inspector](https://github.com/node-inspector/node-inspector) for debugging c# code?

**Comment by nosami** [comment]
I also remember talk about using the gdb protocol. What's happening with that?

**Comment by jrieken** [comment]
for the scope of stdio its more about having some sort of message envelope so that you can correlate a request with a response (https://code.google.com/p/v8-wiki/wiki/DebuggerProtocol defines basic message types, like a request, response, and event and all have a sea-identifier etc). Their ```body```/```arguments``` field correspond semantically to HttpRequest/Response bodies

**Comment by davidfowl** [comment]
To me, the biggest benefits to something like stdio are:

- 2 way communication
- less dependencies

Downside is the shared resource thing.
