### ISSUE TITLE
Move off of project.json and back to .csproj

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#695]
It's going to have to happen sometime. :smile:

One consideration is whether we stick with .NET CLI. Once the embedded Mono work is done (#666), OmniSharp won't need to run on .NET Core. Additionally, if OmniSharp moves off of .NET Core during the move to .csproj, support won't implicitly be dropped for versions of Visual Studio earlier than 2017.

**Comment by filipw** [comment]
yes, I vote for dropping .NET Core as it will not add any value anymore after #666 / #709 and less complexity is always better

**Comment by david-driscoll** [comment]
most definitely, we only jumped on board because mono was a painful dependency.

**Comment by DustinCampbell** [comment]
I'll try to get us moved over to csproj next week in that case.

**Comment by DustinCampbell** [comment]
Looks like I actually got this done. :smile:
