### ISSUE TITLE
CSX - Intellisense not showing constructor parameters

### ISSUE THREAD

**Issue by Zuriel-C** [OmniSharp/omnisharp-roslyn#697]
VSCode - In a CSX script enter the following:
new System.IO.MemoryStream(

Expected results:
Intellisense displays the list of parameters of the constructor for any of the overloads

Actual results: 
Intellisense does not display the list of parameters of the constructor for any of the overloads.

Note that intellisense shows the correct information when hovering over the constructor.

version: omnisharp-roslyn-dev from Dec 5 US EST

**Comment by DustinCampbell** [comment]
This is a known issue and is the same for other C# files. We're tracking it with the C# extension for VS Code here: https://github.com/OmniSharp/omnisharp-vscode/issues/36.
