### ISSUE TITLE
Better code completions

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#7]
Currently /autocomplete returns a list of symbols ... but only after a '.' 

Also we don't get any parameter information or 'snippets'

**Comment by nosami** [comment]
Need to order completions like this :-

	* Completions are ranked in the following order
		* Exact start match (case sensitive)
		* Exact start match (case insensitive)
		* CamelCase completions
		* Subsequence match completions

**Comment by anfomin** [comment]
Is there any updates with attributes autocomplete?

> @nosami wrote on Dec 23, 2014:
> Attributes should complete without the word attribute, e.g. `[Fact]` vs `[FactAttribute]`

**Comment by david-driscoll** [comment]
Resolved by #840
