### ISSUE TITLE
Is it possible to add intellisense to dynamic object with something like JSDoc?

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-roslyn#713]
I want to feel like working with javascript object when using dynamic type in C#. And jsdoc approach like salsa from typescript is very neat in my opinion. So I wish C# could be able to do something the same

Is it possible for roslyn to support this feature?

**Comment by DustinCampbell** [comment]
I think you might want to ask this question on the Roslyn repo: https://github.com/dotnet/roslyn.

**Comment by Thaina** [comment]
Thanks @DustinCampbell

**Comment by DustinCampbell** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/15974.
