### ISSUE TITLE
omnisharp.json formatting options fail for exception filters

### ISSUE THREAD

**Issue by zeroskyx** [OmniSharp/omnisharp-roslyn#716]
**Expected behavior:**
With the following omnisharp.json

```json
{
	"FormattingOptions":
	{
		"NewLine": "\n",
		"UseTabs": true,
		"TabSize": 4,
		"IndentationSize": 4,

		"SpaceWithinMethodDeclarationParenthesis": true,
		"SpaceWithinMethodCallParentheses": true,
		"SpaceAfterControlFlowStatementKeyword": false,
		"SpaceWithinExpressionParentheses": true,
		"SpaceWithinCastParentheses": true,
		"SpaceWithinOtherParentheses": true,
		"SpaceWithinSquareBrackets": true
	}	
}
```

the following code should not be formatted in VSCode with "format document":
```csharp
try
{
}
catch( Exception Error ) when ( !( Error is OperationCanceledException ) )
{
}
```

**Actual behavior:**
The space after **when** is removed:
```csharp
try
{
}
catch( Exception Error ) when( !( Error is OperationCanceledException ) )
{
}
```

**Comment by DustinCampbell** [comment]
Since OmniSharp uses Roslyn for formatting and this easily repros in Visual Studio 2017 RC, you should probably file this in https://github.com/dotnet/roslyn/issues. Once it's fixed in Roslyn, OmniSharp will eventually pick it up. cc @Pilchie

**Comment by Pilchie** [comment]
Interesting.  I wonder if it's responding to the `"SpaceAfterControlFlowStatementKeyword": false,`

**Comment by DustinCampbell** [comment]
That's my expectation.

**Comment by filipw** [comment]
Closing this as obsolete. Please open a new issue if this still happens with the latest build.
