### ISSUE TITLE
Global omnisharp.json

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#717]
_From @zeroskyx on December 30, 2016 17:12_

Is there any way to use omnisharp.json globally instead of having to copy it to every project manually?
Placing one in C:\Users\<User>\AppData\Roaming\Code\User does not seem to work.

Help is greatly appreciated. Thanks in advance
-Simon

_Copied from original issue: OmniSharp/omnisharp-vscode#1101_

**Comment by willl** [comment]
@zeroskyx From what I can see in the [wiki](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration%20Options), if you don't include an omnisharp.json file in the code folder, it will use what is specified in the `config.json` or environment variables (in that order). Those two are essentially your global version of omnisharp.json.

**Comment by zeroskyx** [comment]
Thanks for the info!
However, unfortunately this does not work for vscode since there is no default config.json.

**Comment by filipw** [comment]
> However, unfortunately this does not work for vscode since there is no default config.json.

you could create a `config.json` with your global settings in the place where VS Code extension is installed. For example, on a mac that's `~/.vscode/extensions/ms-vscode.csharp-1.6.0/bin/omnisharp`.

The downside is, that would be overwritten on updates.

It wouldn't be too big of a deal to add omnisharp support for global config loaded from `%appdata%`
