### ISSUE TITLE
Omnisharp process using 10 GB of memory when there are 150 assemblies in the VSCode project folder

### ISSUE THREAD

**Issue by Zuriel-C** [OmniSharp/omnisharp-roslyn#723]
The Omnisharp process is using 10 GB of memory when there are 150 assemblies in the VSCode project folder. Removing the assemblies from the VSCode folder makes it use only 1 GB, which is high but not bad.

**Comment by filipw** [comment]
This was fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/794
