### ISSUE TITLE
Incorrect Xml docs when hovering over attributes

### ISSUE THREAD

**Issue by Zuriel-C** [OmniSharp/omnisharp-roslyn#724]
Steps:
1) Create a csx file in VSCode
2) Add a property/variable as follows:

[ThreadStatic]
string Foo;

3) Hover the mouse over the ThreadStatic attribute

Expected result:
The documentation of the type "ThreadStaticAttribute" is displayed

Actual result:
The documentation of the constructor of the type "ThreadStaticAttribute" is displayed.

Minor issue

**Comment by filipw** [comment]
This is a duplicate of "Scenario 1 for desktop .NET" from issue https://github.com/OmniSharp/omnisharp-roslyn/issues/685
