### ISSUE TITLE
Add tests to verify correct file encoding behavior against project systems 

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#728]
This is a tech debt follow up to https://github.com/OmniSharp/omnisharp-roslyn/pull/727
We should add tests to verify files with different BOM.

**Comment by akshita31** [comment]
The current state of the branch doesn't have these calling sites. The files are now being opened through 
Microsoft.CodeAnalysis.Workspaces.dll. The other places where we are opening the source files are also not opening these files directly.
@DustinCampbell @filipw @TheRealPiotrP  I'll close the issue tomorrow if there are no objections.

**Comment by TheRealPiotrP** [comment]
Looks reasonable to me.

**Comment by DustinCampbell** [comment]
Fine by me.

**Comment by TheRealPiotrP** [comment]
@DustinCampbell as an owner in this repo, can you close the issue?

**Comment by DustinCampbell** [comment]
Sure. We've made a lot of changes around this area to just rely on Roslyn better, which should handle this for us.
