### ISSUE TITLE
errors in all directive

### ISSUE THREAD

**Issue by darkgem666** [OmniSharp/omnisharp-roslyn#740]
Hi, after a couple of days trying to set up omnisharp-vim to work on my Mac (Sierra 10.12.2) I'm the following issue. 

1.- Create new project with yo (.net core).
2.- Start omnisharp-roslyn manually using parameter -s to new project path. (starts OK )
3.- open any .cs file.

Opening any .cs file gives me errors in all lines of the file, even the Program.cs file that is generated. 

I get error message like this:

* Unnecessary using directive.
* The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
*Predefined type 'System.Object' is not defined or imported

and many more errors.

omnisharp server looks like OK because a keep seeing responses like the following:

info: OmniSharp.Middleware.LoggingMiddleware[0]
      /typelookup: 200 0ms

info: OmniSharp.Middleware.LoggingMiddleware[0]
      /codecheck: 200 2ms

**Comment by tanordheim** [comment]
I see you closed the issue, but did you figure this out? I'm having the same issue here myself, and while I haven't really gotten far in my debugging yet it would be helpful if you had the solution to this handy for others having the same issue. :)
