### ISSUE TITLE
/formatOnType doesn't always work

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#75]
`/formatOnType` returns no changes when removing the ; from the following snippet and adding it back.

```cs
sourceText = sourceText.WithChanges(new[] {
                    new TextChange(    new TextSpan(startOffset,      endOffset - startOffset),     request.NewText)
                        });
```

**Comment by jrieken** [comment]
I will take a look - most likely a case in which we don't expand the position to a proper range. I have seen similar issues where ```}``` on a catch block doesn't include the try-part.

**Comment by jrieken** [comment]
interesting... the code in Omnisharp expands the ```;``` to the whole statement so that it basically becomes a format range of all code you pasted. However, the Roslyn formatter decides not to format it.

**Comment by nosami** [comment]
Just tried the same thing in VS2015. Doesn't work there either.

**Comment by jrieken** [comment]
I filed this against Roslyn and I am closing this one :arrow_backward:  https://github.com/dotnet/roslyn/issues/779
