### ISSUE TITLE
Please add dynamic intellisense from documentation commenting

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-roslyn#768]
At present we has no consensus to support dynamic member hinting syntax in C# language nor core compiler

Taken from js salsa idea, I think language server like omnisharp should support intellisense on dynamic object with commenting for the time being

Would be something like

```C#
public interface IUser
{
    string _id;
    string Name;
}

class A
{
    /// <dynamic type="IUser" />
    dynamic userField;

    /// <dynamic name="userArg" type="IUser" />
    public void DoSomething(dynamic userArg)
    {
        /// <dynamic type="IUser" />
        dynamic userVar;

        userVar.N // intellisense show Name here
    }
}
```

**Comment by Thaina** [comment]
This was moved from https://github.com/dotnet/roslyn/issues/15974 because it really have no movement on roslyn to add syntax into the language for intellisense

If we doing it by documentation commenting. I think omnisharp would be better place to add this functionality into

Any idea or better approach?

**Comment by filipw** [comment]
I think this should be closed as out of scope for OmniSharp at the moment. The Roslyn issue will track how this evolves in the context of C#. Thanks.
