### ISSUE TITLE
Problems list dominated by unused usings

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-roslyn#769]
Makes it hard to see real problems. Can we downgrade this thing so it doesn't show up by default in the list of problems?

![image](https://cloud.githubusercontent.com/assets/95136/22864750/c453da50-f10b-11e6-8289-9312e135b828.png)

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1231
