### ISSUE TITLE
Running Build script fails the Test target

### ISSUE THREAD

**Issue by couven92** [OmniSharp/omnisharp-roslyn#771]
Following the instructions in README.md I executed 
``` batch
git checkout origin/dev
powershell .\build.ps1
```

The build script fails with the following output from the `Test` task:
```
========================================
Test
========================================
Executing task: Test
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: OmniSharp.MSBuild.Tests
  Discovered:  OmniSharp.MSBuild.Tests
  Starting:    OmniSharp.MSBuild.Tests
    OmniSharp.MSBuild.Tests.ProjectFileInfoTests.HelloWorldSlim_has_correct_property_values [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   0
      Stack Trace:
        .\tests\OmniSharp.MSBuild.Tests\ProjectFileInfoTests.cs(56,0): at OmniSharp.MSBuild.Tests.ProjectFileInfoTests.HelloWorldSlim_has_correct_property_values()
      Output:
        [info]: OmniSharp.MSBuild.Tests.ProjectFileInfoTests
                Searching for solution OmniSharp.sln to locate MSBuild tools...
        [info]: OmniSharp.MSBuild.Tests.ProjectFileInfoTests
                MSBUILD_EXE_PATH environment variable set to .\.msbuild-net46\MSBuild.exe
        [info]: OmniSharp.MSBuild.Tests.ProjectFileInfoTests
                MSBuildExtensionsPath environment variable set to .\.msbuild-net46
        [info]: OmniSharp.MSBuild.Tests.ProjectFileInfoTests
                MSBuildSDKsPath environment variable set to .\.msbuild-net46\Sdks
  Finished:    OmniSharp.MSBuild.Tests
=== TEST EXECUTION SUMMARY ===
   OmniSharp.MSBuild.Tests  Total: 10, Errors: 0, Failed: 1, Skipped: 0, Time: 2,561s
An error occured when executing task 'Test'.
Error: Test OmniSharp.MSBuild.Tests failed for net46
```
The error also appears when checking out the latest tag `v1.10.0`

**Comment by DustinCampbell** [comment]
What OS are you running? Is this Windows? These paths look a little bizarre: MSBUILD_EXE_PATH environment variable set to .\.msbuild-net46\MSBuild.exe.

**Comment by couven92** [comment]
Yes, this is Windows 10 Release 15014.

All paths you see here are relative to the local root directory of the omnisharp-roslyn repository.

**Comment by DustinCampbell** [comment]
Based on the code, I would've expect those to be full paths. Did you modify them for your report?

**Comment by couven92** [comment]
OMG! Sorry, yes, I stripped my full path containing my username, etc... But that shouldn't really be an issue here, should it? Since everything is happening local to the repository directory anyways...
(But yes, sorry I forgot to mention it, I usually do...)

**Comment by DustinCampbell** [comment]
No worries! I just spotted that and it looked odd to me.

**Comment by DustinCampbell** [comment]
FWIW, I just tried this on a recently rebuilt machine and the same tests passed for me. Also, this is passing on our CI machines (AppVeyor for Windows, and Travis for OSX/Linux).

**Comment by couven92** [comment]
That's... weird... Any Env info I can post that would help in telling me what is wrong with my machine?

**Comment by DustinCampbell** [comment]
I don't have any good ideas. 😦 I just wanted to make note that this did not fail for me as I tried it.

**Comment by couven92** [comment]
Im running build.ps1 again right now, I'll link to a Gist with the complete output once it's done...

**Comment by couven92** [comment]
Ok, now I am REALLY pissed off at my computer! Because now of course everything works perfectly... Sorry to bother you, I'm closing this one as my computer appearently decided to automagically auto-correct the error on its own...

**Comment by DustinCampbell** [comment]
lol. I'm glad it worked at least. Sorry for the heisen-bug.
