### ISSUE TITLE
Problems due to MSBuild 15.0 syntax

### ISSUE THREAD

**Issue by aggieben** [OmniSharp/omnisharp-roslyn#778]
I mentioned this offhand in #301, but in the interest of not hijacking that issue, I've opened a new one.

My original comment:

> In my case, OmniSharp is still a little behind with respect to the new RC4 tooling, so I see issues listed in the Problems tab; they are intellisense issues in csproj files relating to missing syntax that would be expected in MSBuild 12.0, but not in the lastest build tools.

A response from @DustinCampbell:

> The latest version of omnisharp-roslyn is up-to-date with VS 2017 RC4 tooling. It even includes a build of MSBuild 15.0 inside of it.

By "latest version", do you mean latest release, or something nightly?  Here's what I see:

![image](https://cloud.githubusercontent.com/assets/1321/23046176/accb7d92-f46d-11e6-8381-afc19cd18101.png)

![image](https://cloud.githubusercontent.com/assets/1321/23046188/c6e2fae8-f46d-11e6-81e5-178d0cb15a8b.png)

![image](https://cloud.githubusercontent.com/assets/1321/23046192/cb6e3636-f46d-11e6-895b-641f183a305d.png)

**Comment by willl** [comment]
@aggieben What @DustinCampbell meant was the version of the [omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode), and not VS Code itself.

Current version if installed from the marketplace is 1.7. If you look at the [releases page](https://github.com/OmniSharp/omnisharp-vscode/releases) there is a v1.8.0-beta1.

**Comment by aggieben** [comment]
Sorry - I goofed on reporting my versions.  I have the 1.7.0 version of the extension through the marketplace.  

Are you implying that 1.7 doesn't have support for MSBuild 15.0 and 1.8.0-beta-1 does?

**Comment by DustinCampbell** [comment]
When I said "the latest version", I meant the latest version of C# for VS Code that shipped on the extension marketplace last week. That's version 1.7, which should be able to handle a project file like the one you screencapped above just fine (I just checked). I suspect something is set up wrong on your machine. Could you check the following points about your set up?

1. Check to ensure that you don't have multiple versions of C# for VS Code installed. To do this, check the following folder:
    * On Windows, `%USERPROFILE%\.vscode\extensions`
    * On OSX/Linux, `~/.vscode/extensions`

    In that folder, there should be *one* `ms-vscode.csharp-*`. If there's more than one, close VS Code, and delete all of `ms-vscode.csharp.*` folders.. That, install 1.7 of C# for VS Code from inside VS Code.

2. In VS Code, select Preferences->Settings from the main menu. This will open the "settings.json" file. If you have set "omnisharp.path" and/or "omnisharp.usesMono", please remove those settings.

**Comment by DustinCampbell** [comment]
Additionally, if neither of those ideas yields any fruit, could you provide your OmniSharp log when loading that project? Just select View->Output from the VS Code menu and select "OmniSharp Log" from the top-right of the Output pane.

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1248

**Comment by DustinCampbell** [comment]
I've moved this to the C# for VS Code repo.
