### ISSUE TITLE
Use new Roslyn Completion List API for IntelliSense

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#78]
Internal, but much better. Handles keywords, snippets, named parameters, object initializer etc.

https://github.com/dotnet/roslyn/blob/47ff630cc838b56248022c1d494299f35daec474/src/Features/CSharp/Completion/CSharpCompletionService.cs

``` cs
var completionService = new CSharpCompletionService();
var t = await completionService.GetGroupsAsync(document, position, new mca.Completion.CompletionTriggerInfo(), completionService.GetDefaultCompletionProviders(), new CancellationToken());
```

**Comment by davidfowl** [comment]
epic

**Comment by jrieken** [comment]
:+1: reflection ftw

**Comment by stirno** [comment]
I have a working impl of this in our codebase but it throws under Mono presently with a not-very-helpful error. Haven't had a chance to dig through that yet.

Also theres an internal extension method on document to help create the service, might be better to use that in case it gets more MEFy:

```
var completionService = document.GetLanguageService<ICompletionService>();
```

**Comment by Pilchie** [comment]
Nice!  I would like to make something like that public at some point after I make something like ICompletionProvider public (my current side project).

**Comment by nosami** [comment]
Seems that the features assembly doesn't yet have a nuget package - https://github.com/dotnet/roslyn/issues/572

**Comment by aelij** [comment]
@Pilchie, while you're doing that, how about moving `ISignatureHelpProvider` to the Features assembly and making it public as well? :)
It has no dependency on the VS SDK, so it should be easy (I know because I've [done it](https://github.com/aelij/roslynpad/)).

**Comment by Pilchie** [comment]
Tagging @dustincampbell on this too.

**Comment by DustinCampbell** [comment]
I'm going to tracking this over at https://github.com/dotnet/roslyn/issues/3538

**Comment by DustinCampbell** [comment]
And here: dotnet/roslyn#3540

**Comment by khellang** [comment]
:+1:

**Comment by DustinCampbell** [comment]
And if anyone's interested, the branch I'm working out of is at https://github.com/DustinCampbell/roslyn/tree/completion-api.

**Comment by tpetrina** [comment]
Hi @DustinCampbell, can you please give an example on how to use the completion API in your branch?

**Comment by DustinCampbell** [comment]
Patience. :smile: I'm actively integrating it back into Roslyn proper as an internal API. Once that happens, I'll run it through a formal API design process and we'll make it public.

**Comment by tpetrina** [comment]
OK, thanks. I was under the impression that you are nearly done :P

**Comment by DustinCampbell** [comment]
Getting pretty close (for example: https://github.com/dotnet/roslyn/pull/3955). I've been on vacation the past several weeks so work halted for a bit. I'm moving much faster now.

**Comment by Vidhyakp** [comment]
I need  a script editor that provides intellisense and squiggling. 

With Recommender I am not able to get the "keywords" which was possible ICompletionService which was public in earlier versions of Roslyn. 

Can you please whether we have any thing similar to ICompletionService that is public in the latest version or any update on making "ICompletionService" public?

**Comment by DustinCampbell** [comment]
This was implemented in Roslyn with #8170. A public completion API is now available. I'll own integrating it in OmniSharp.

**Comment by ivanz** [comment]
What is the status of this? I see that a pull requests #583 was merged in June which seems to implement the new completion API, but when I compile the dev branch and point my VSCode workspace to it - I see no change in auto-completion of object initializers and constructors? (https://github.com/OmniSharp/omnisharp-vscode/issues/260 ) 

```json
    "csharp.omnisharp" : "C:/code/omnisharp-roslyn/artifacts/publish/OmniSharp/default/netcoreapp1.0/OmniSharp.exe"

```

**Comment by DustinCampbell** [comment]
#583 uses the new completion API with the same OmniSharp end point. Currently, it only uses the completion API to retrieve the available keywords (which allowed me to remove a *ton* of code from OmniSharp). I've been looking at this and believe that a new v2 end point will be needed to properly target the completion API.

**Comment by Novack-** [comment]
Following.

**Comment by Novack-** [comment]
Any progress or changes?

**Comment by DustinCampbell** [comment]
@kzu -- what, specifically, would you like to see? The work tracked here isn't related to LSP.

**Comment by kzu** [comment]
Would like to see the full completion, and ideally even with some way to configure additional completion providers exported somehow to OmniSharp :)
