### ISSUE TITLE
An error occurred when executing task 'BuildMain'.

### ISSUE THREAD

**Issue by sandao** [OmniSharp/omnisharp-roslyn#801]
========================================
Setup
========================================
Executing task: Setup
Finished executing task: Setup

========================================
Restore
========================================
Executing task: Restore
Restoring packages in /Users/Sandao/Program/omnisharp-roslyn....
Package restore successful!
Restoring packages in /Users/Sandao/Program/omnisharp-roslyn/test-assets/test-projects/BasicTestProjectSample01....
Package restore successful!
Restoring packages in /Users/Sandao/Program/omnisharp-roslyn/test-assets/test-projects/BasicTestProjectSample02....
Package restore successful!
Finished executing task: Restore

========================================
BuildMain
========================================
Executing task: BuildMain
Building OmniSharp.csproj
An error occurred when executing task 'BuildMain'.
Error: Building OmniSharp.csproj failed.

**Comment by DustinCampbell** [comment]
I'm *guessing* you're on macOS. Let me know if I'm incorrect about that.

Have installed the requirements for building OmniSharp on macOS detailed [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/BUILD.md)?

**Comment by sandao** [comment]
@DustinCampbell yes,on my mac os and I have installed the requirements！I can run mono cmd in terminal.

**Comment by DustinCampbell** [comment]
Can you run 'msbuild' in terminal?

**Comment by DustinCampbell** [comment]
Also, could you check `artifacts/logs/Omnisharp.csproj-build.log` and see what the failure was?

**Comment by sandao** [comment]
@DustinCampbell Thank you for your help
1.No log file in artifacts/logs/ 

2.The following error occurred when I run msbuild

"/Users/Sandao/Program/omnisharp-roslyn/OmniSharp.sln" (default target) (1) ->
"/Users/Sandao/Program/omnisharp-roslyn/tests/OmniSharp.DotNet.Tests/OmniSharp.DotNet.Tests.csproj" (default target) (20) ->
  /Users/Sandao/Program/omnisharp-roslyn/tests/OmniSharp.DotNet.Tests/OmniSharp.DotNet.Tests.csproj : error MSB4019: The imported project "/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by DustinCampbell** [comment]
You might try grabbing the latest from 'dev'. We just merged some changes yesterday that should fix the logging.

Running MSBuild by itself won't work because there are several environment variables that need to be set first. Try running `./msbuild.sh OmniSharp.sln`

**Comment by sandao** [comment]
use the latest dev branch,I got the error log

[OmniSharp.csproj-build copy.txt](https://github.com/OmniSharp/omnisharp-roslyn/files/865279/OmniSharp.csproj-build.copy.txt)

**Comment by DustinCampbell** [comment]
OK. This is the same failure that we worked around [here](https://github.com/OmniSharp/omnisharp-roslyn/pull/802/commits/b9b482031322bde7cce869ba60307dd18a25a1aa) in our CI build.

Apparently, the latest release of Mono has a bug in MSBuild. The bug has been fixed already, but the fix isn't in the latest release yet. You should be able to fix the problem like so:

```
sudo cp /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/Roslyn/System.Reflection.Metadata.dll /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/System.Reflection.Metadata.dll
```

**Comment by sandao** [comment]
@DustinCampbell Thank you very much,I successfully build it！

**Comment by DustinCampbell** [comment]
That's great to hear! Note that this is only an issue with the latest service release of Mono 4.8.0. Since it's already fixed for the next Mono release, you'll hopefully only need to do this once.
