### ISSUE TITLE
build in mac osx error 

### ISSUE THREAD

**Issue by indie21** [OmniSharp/omnisharp-roslyn#819]
Executing task: Restore
Restoring packages in OmniSharp.sln...
  Restoring packages for /Users/zhuoyikang/source/omnisharp-roslyn/src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj...
  Restoring packages for /Users/zhuoyikang/source/omnisharp-roslyn/src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj...
  Restoring packages for /Users/zhuoyikang/source/omnisharp-roslyn/src/OmniSharp.DotNet/OmniSharp.DotNet.csproj...
  Restoring packages for /Users/zhuoyikang/source/omnisharp-roslyn/src/OmniSharp.Host/OmniSharp.Host.csproj...
/Users/zhuoyikang/source/omnisharp-roslyn/.dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Users/zhuoyikang/source/omnisharp-roslyn/OmniSharp.sln]
/Users/zhuoyikang/source/omnisharp-roslyn/.dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'System.Net.Http.CurlHandler' threw an exception. [/Users/zhuoyikang/source/omnisharp-roslyn/OmniSharp.sln]
/Users/zhuoyikang/source/omnisharp-roslyn/.dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'Http' threw an exception. [/Users/zhuoyikang/source/omnisharp-roslyn/OmniSharp.sln]
/Users/zhuoyikang/source/omnisharp-roslyn/.dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'HttpInitializer' threw an exception. [/Users/zhuoyikang/source/omnisharp-roslyn/OmniSharp.sln]
/Users/zhuoyikang/source/omnisharp-roslyn/.dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'CryptoInitializer' threw an exception. [/Users/zhuoyikang/source/omnisharp-roslyn/OmniSharp.sln]
/Users/zhuoyikang/source/omnisharp-roslyn/.dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found. [/Users/zhuoyikang/source/omnisharp-roslyn/OmniSharp.sln]
/Users/zhuoyikang/source/omnisharp-roslyn/.dotnet/sdk/1.0.1/NuGet.targets(97,5): error :    (Exception from HRESULT: 0x8007007E) [/Users/zhuoyikang/source/omnisharp-roslyn/OmniSharp.sln]
An error occurred when executing task 'Restore'.

**Comment by DustinCampbell** [comment]
building OmniSharp requires access to NuGet to restore the packages it needs. It looks like the machine you built on could not access NuGet?

**Comment by DustinCampbell** [comment]
@indie21: Are you still running into this issue?

**Comment by bodhy** [comment]
I have the same exact error. Does someone know how to resolve this? @DustinCampbell

**Comment by DustinCampbell** [comment]
It looks to me like an issue with NuGet. Maybe it was down temporarily or the .NET CLI isn't able to connect to it over the Internet?
