### ISSUE TITLE
Publish to NuGet/MyGet

### ISSUE THREAD

**Issue by mholo65** [OmniSharp/omnisharp-roslyn#822]
As discussed with @david-driscoll on Slack. To get plugin development started, libraries should be published to NuGet/MyGet.

For a Cake plugin, we would at least need following:
* OmniSharp.Abstractions
* OmniSharp.Roslyn
* OmniSharp.Roslyn.CSharp

**Comment by david-driscoll** [comment]
After my talk is ready for this Saturday, I'll be picking up the work to get the packages deployed.

@DustinCampbell do you think this would integrate directly into the C# plugin (through some sort of plugin provider) or would it make more sense to have a separate plugin that supported cake files?

My thinking here is if we break an interface between versions the cake plugin wouldn't work until it was updated.  However if we have a separate plugin, the user would be downloading OmniSharp twice... hmm.

@mholo65 thoughts on what kind of integration you guys are looking for?

**Comment by DustinCampbell** [comment]
I think this is a great way to get the plugin functionality going. Shall we create a `#cake` channel on the OmniSharp slack for discussion of this effort?

**Comment by DustinCampbell** [comment]
One thing to consider is what the actually public API for OmniSharp is. At the moment, things a real hodge-podge of public vs. internal.

**Comment by david-driscoll** [comment]
Totally agreed.  I'm with releasing something soon but calling it "beta" in that we may break you, but we didn't do it on purpose. 😄

**Comment by mholo65** [comment]
@david-driscoll as we need to translate linenumbers on both requests and responses and do CodeGen on Buffer updates/changes, I thought creating our own Cake RequestHandlers would be best option.

I managed to work out a solution which doesn't directly depend on OmniSharp.Roslyn.CSharp. Instead MEF will inject all handlers and we will find the corresponding C# handler ( see https://github.com/mholo65/omnisharp-roslyn/blob/wip/new-cake-plugin/src/Cake.OmniSharp/RequestHandlers/CakeRequestHandler.cs#L43)

So, as long as you wont break Abstractions and Roslyn we'll be fine :smile:

**Comment by mholo65** [comment]
@DustinCampbell +1 for ```#cake``` channel

**Comment by david-driscoll** [comment]
That is actually not to bad!

I know we will eventually move away from them toward LSP types as a breaking change in the future but we'll know far in advance when that is happening.  I'm also thinking we may keep the interfaces for some time, and instead have a mapping between the existing requests, and the new interfaces, so that we don't break all our consumers right away. (no promises however)

PS: Invited you into `#cake` on slack. 👍

**Comment by filipw** [comment]
the old CSX support, when it was built around ScriptCs, had almost everything that is needed for Cake https://github.com/OmniSharp/omnisharp-roslyn/blob/103978957bc541609489ddac4d37dd0a41d06d8c/src/OmniSharp.ScriptCs/ScriptCsProjectSystem.cs

Using same approach, adding Cake support would be very easy and it could be loaded as a new project system that reacts to `.cake` files

**Comment by filipw** [comment]
it also would make sense to have something like `PluginPath(s?)` in `omnisharp.json`, so that you can manually configure where the plugins should be searched for. This would make it easy to have per-folder plugins too

**Comment by filipw** [comment]
The nugets are already being published.
