### ISSUE TITLE
Cake

### ISSUE THREAD

**Issue by daveremy** [OmniSharp/omnisharp-roslyn#823]

**Comment by willl** [comment]
@daveremy What's the actual issue? 

Are you looking for Cake support in omnisharp-roslyn?

I believe the cake team is looking into that, as per this tweet by @mholo65: https://twitter.com/mholo65/status/847569520055025665

**Comment by mholo65** [comment]
Yes, we are working on a Cake plugin for OmniSharp-Roslyn. Code will eventually end up [here](https://github.com/cake-build/cake-omnisharp) once #822 is resolved.

**Comment by daveremy** [comment]
My specific issue was that I was trying to follow the instructions to install omnisharp-vim on Ubuntu 14.04 (using windows linux service though).  In there, it says if you want to use omnisharp-roslyn, to cd to omnisharp-roslyn and do a ./build.sh.  I am extremely newb at all this.  I get this error (which looks more like a nuget problem than a cake problem):
dremy@DREMY2-LT:~/.vim/bundle/omnisharp-vim/omnisharp-roslyn$ ./build.shFeeds used:  /home/dremy/.local/share/NuGet/Cache  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json  https://api.nuget.org/v3/index.json
Restoring NuGet package Cake.0.10.1.WARNING: Unable to find version '0.10.1' of package 'Cake'.Restoring NuGet package Newtonsoft.Json.8.0.3.WARNING: Unable to find version '8.0.3' of package 'Newtonsoft.Json'.Could not find Cake.exe at '/home/dremy/.vim/bundle/omnisharp-vim/omnisharp-roslyn/scripts/../.tools/Cake/Cake.exe'.
Thanks. _______________________________________________
Dave Remy (email@daveremy.com)

**Comment by david-driscoll** [comment]
That's fairly strange, however the `omnisharp-vim` package loads `omnisharp-roslyn` through a submodule.  If you tried updating that would be good as well.

**Comment by DustinCampbell** [comment]
Was this issue ever solved?

**Comment by DustinCampbell** [comment]
It seems this issue is dead.
