### ISSUE TITLE
Remove self references from find usages

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#85]
See screenshots

![screenshot 2015-02-15 19 07 49](https://cloud.githubusercontent.com/assets/1710369/6212497/4cb4707a-b5e6-11e4-939f-5e0f33aaca26.png)

![screenshot 2015-02-16 14 15 58](https://cloud.githubusercontent.com/assets/1710369/6212506/5aa20440-b5e6-11e4-8f6f-7242925a4f6b.png)

**Comment by jrieken** [comment]
Let's have a flag ```IncludeDeclaration``` in the request - that makes v1 happy and also full fills this request.

**Comment by Yantrio** [comment]
I also need to de-dupe the results, and/or look into the aspnet vs aspnet core and how that is all returned.

**Comment by nosami** [comment]
IncludeDeclaration is a bad name I think.

I would think of the definition of the symbol, whereas what we really need
is to remove the symbol under the cursor from the usages?

Is there ever a good reason to show the symbol under the cursor when making
a Find Usages request? I can't think of one, but that's what VS does :S

**Comment by jrieken** [comment]
Now that I use findUsages for mark occurrences I actually want the symbol under the cursor.

**Comment by nosami** [comment]
OK. Let's just pick another name for the flag then.
IncludeOriginalLocation??

**Comment by nosami** [comment]
Or just subtract 1 :)

**Comment by jrieken** [comment]
```ExcludeThisLocation``` is my word - it's sort of aligned with https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Models/FindUsagesRequest.cs#L9. Tho not saying that was a good choise ;-)

**Comment by nosami** [comment]
Sounds better to me

**Comment by filipw** [comment]
forgot to mention the dupes but I think everyone knows that :) 
this can happen not only between aspnet5/aspnetcore5 but also when the same file is linked under multiple projects

![screenshot 2015-02-16 19 16 35](https://cloud.githubusercontent.com/assets/1710369/6217078/7969ccda-b610-11e4-9d18-134d9091c8a1.png)

**Comment by Yantrio** [comment]
I'll take a look at all that, does anyone mind if (whilst we are on the subject of extending this) , I add a property that returns the Indentifier name also?

**Comment by jrieken** [comment]
@Yantrio - I think we should include the list of project they are in, for file member elements I have done something similar (https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Workers/StructureComputer.cs#L38). In addition tho we should also dedupe them, like we do for IntelliSense or FileMemeberElements (https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Workers/StructureComputer.cs#L56)

**Comment by Yantrio** [comment]
@jrieken I agree :) id like to use this for my codelens-alike feature in brackets, and it would be nice to get as much,if not more, information than VS displayed,

**Comment by nosami** [comment]
Yeah... me and Fowler already discussed putting the project name on usages. And +1 to adding the identifier name.

**Comment by nosami** [comment]
fixed by #115
