### ISSUE TITLE
build dev  errors in mac osx

### ISSUE THREAD

**Issue by gatspy** [OmniSharp/omnisharp-roslyn#855]
```
Restoring packages in OmniSharp.csproj for osx.10.11-x64...
Publishing OmniSharp.csproj for net46/osx.10.11-x64...
msbuild.sh: line 11: msbuild: command not found
/Volumes/Home/App/vim/k-vim/bundle/omnisharp-vim/omnisharp-roslyn/.dotnet/sdk/1.0.1
An error occurred when executing task 'OnlyPublish'.
Error: Failed to publish OmniSharp for net46/osx.10.11-x64
```

**Comment by GreyGhostIX** [comment]
I'm getting a similar problem on osx.10.10.5


========================================
BuildMain
========================================
Executing task: BuildMain
Building OmniSharp.csproj...
msbuild.sh: line 11: msbuild: command not found
~/desktop/omnisharp-roslyn/.dotnet/sdk/1.0.1
An error occurred when executing task 'BuildMain'.
Error: Building OmniSharp.csproj failed.

**Comment by DustinCampbell** [comment]
Have you installed the pre-requisites per https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/BUILD.md#macos?

**Comment by GreyGhostIX** [comment]
When I got my first error I had mono version > 4.8, but after installing the cask as per instructions for version 5.0.0.100 it made it past the BuildMain step. 

Unfortunately now I'm failing on PrepareTestAssets.
```
PrepareTestAssets

Executing task: PrepareTestAssets
Restoring packages in ~/Desktop/omnisharp-roslyn/test-assets/test-projects/NUnitTestProject...
Building ~/Desktop/omnisharp-roslyn/test-assets/test-projects/NUnitTestProject...
Restoring packages in ~/Desktop/omnisharp-roslyn/test-assets/test-projects/XunitTestProject...
Building ~/Desktop/omnisharp-roslyn/test-assets/test-projects/XunitTestProject...
Restoring project.json packages in ~/Desktop/omnisharp-roslyn/test-assets/test-projects/BasicTestProjectSample01...
Building ~/Desktop/omnisharp-roslyn/test-assets/test-projects/BasicTestProjectSample01...
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'osx.10.10-x64'. Possible causes:

1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.10-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.

An error occurred when executing task 'PrepareTestAssets'.
Error: Failed to restore '/Users/Patrick/Desktop/omnisharp-roslyn/test-assets/test-projects/BasicTestProjectSample01'.
```

**Comment by DustinCampbell** [comment]
Hmmm... `osx.10.10-x64` sticks out to me. Are you running a pre-El Capitan of OSX?

**Comment by gatspy** [comment]
mono --version:  `4.8.1`
dotnet --version: `1.0.4`
osx : `10.11.5`

**Comment by zcolonel** [comment]
Having the same issue. I've both mono as well as the cask for the dev kit.

```
Executing task: BuildMain
Building OmniSharp.csproj...
msbuild.sh: line 11: msbuild: command not found
/Users/coneil/dev/omnisharp-roslyn/.dotnet/sdk/1.0.1
An error occurred when executing task 'BuildMain'.
Error: Building OmniSharp.csproj failed.
```

mono is `5.0.1.1` on El Capitan `10.11.6`

**Comment by DustinCampbell** [comment]
After some investigation yesterday, I might have some ideas for this thread.

Essentially, how you install Mono may cause problems with building. We use the msbuild that installs with Mono to build on OSX/Linux. If you've installed Mono via Homebrew with `brew install mono`, that only installs a subset of what's needed to build OmniSharp. Notably, it doesn't include msbuild.

To build OmniSharp, you should install the full Mono Development Kit. You can download and install the .pkg at http://www.mono-project.com/download/, or install with Homebrew using cask: `brew cask install mono-mdk`. Note that we required 5.2.0 of Mono for building the latest master, which is in the Mono beta channel at the moment. Until that's released, you'll need to install the .pkg manually instead of using Homebrew.

**Comment by filipw** [comment]
Closing this as out of date, the build has changed much since then. If you still experience issues with the current build, please open a new issue. Thanks!
