### ISSUE TITLE
Red squiggles persist when doing restore and build outside of VS Code

### ISSUE THREAD

**Issue by danroth27** [OmniSharp/omnisharp-roslyn#869]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gc-excelviewer|GrapeCity|1.1.13|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1. Using .NET Core SDK 1.0.4, run `dotnet new console`
2. Open the project in VS Code with the C# extension 1.9.0
1. `dotnet add package Microsoft.AspNetCore`
1. `dotnet restore`
1. `dotnet build`
1. In VS Code add the following using statements in Program.cs
   ``` c#
   using Microsoft.AspNetCore.Builder;
   using Microsoft.AspNetCore.Http;
   using Microsoft.AspNetCore.Hosting;
   ```
1. Red squiggles, even though the build just succeeded:

![image](https://cloud.githubusercontent.com/assets/1874516/26277637/4bd28730-3d40-11e7-948c-4a2d87ccab10.png)

**Comment by danroth27** [comment]
Doing the restore from within VS Code seems to address the issue.

**Comment by danroth27** [comment]
@DustinCampbell

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1501
