### ISSUE TITLE
VSCode intellisense not working for c# dotnet core project

### ISSUE THREAD

**Issue by manishkp** [OmniSharp/omnisharp-roslyn#874]
Hi Team,
I am not sure what am I missing.
I have windows 10 machine with VS code vscode veriosn: 1.12.1 installed.
I have the 'ms-vscode.csharp' extension installed on  and the intellisense didnt work.

Then I have the dev branch built locally and I am pointing to 
	"omnisharp.path": "C:\\Users\\manis\\Source\\Repos\\omnisharp-roslyn\\artifacts\\publish\\OmniSharp\\default\\netcoreapp1.1\\Omnisharp.exe"
or 
"omnisharp.path": "C:\\Users\\manis\\Source\\Repos\\omnisharp-roslyn\\artifacts\\publish\\OmniSharp\\default\\netcoreapp1.1"

in my user settings json file.

Its still not working, I tried looking at the dev toolbar for any errors but couldnt find anything relevent.
Can you guys help?

thanks
Manish

**Comment by DustinCampbell** [comment]
@manishkp: Sorry that I didn't spot this issue immediately. This repo is for the OmniSharp server itself rather than C# for VS Code (which is https://github.com/OmniSharp/omnisharp-vscode).

Could you provide your OmniSharp Log to help us see what's happening? After opening your project and a C# file in VS Code, select View->Output from the menu and select "OmniSharp Log" from the combobox at the top-right of the Output pane.

**Comment by manishkp** [comment]
Thanks @DustinCampbell for replying.
I dont see "Omnisharp Log" option in outputs.
Also I dont see any projects detected option as mentioned  in https://code.visualstudio.com/docs/languages/csharp 

I am assuming Omnisharp is not getting loaded.

To make sure nothing else was messing up, I uninstalled the vscode and my user settings and extension by deleting 
C:\Users\manis\AppData\Roaming\Code
C:\Users\manis\.vscode\extensions

Then reinstalled vscode, just added 2 extensions (these are the folders in C:\Users\manis\.vscode\extensions)
ms-vscode.csharp-1.10.0
msjsdiag.debugger-for-chrome-3.1.2

Shall I clone the issue into the new repo ?

Thanks
Manish

**Comment by DustinCampbell** [comment]
If the OmniSharp Log isn't there, the C# for VS Code extension isn't actually launching.

Is there a particular reason that you're setting the "omnisharp.path"? C# for VS Code should download a build of OmniSharp itself upon launching (it'll launch if you open a C# file).

**Comment by manishkp** [comment]
With the re-install of vscode and user settings cleanup, I am not setting any overrides now.
so now I see the default  omnisharp.path = null in C:\Users\manis\AppData\Roaming\Code\User\settings.json and I dont have any user settings or workspace settings

**Comment by DustinCampbell** [comment]
Hmmm... try the following:

1. Open VS Code and select Help->Toggle Developer Tools.
2. In the Developer Tools, select the "Console" tab.
3. Open your project in VS Code and open a C# file.

Do you see any errors or other information in the Developer Tools?

**Comment by manishkp** [comment]
Thanks Dustin,
The console output seems to suggest that its related to  https://github.com/Microsoft/vscode/issues/20168
--- log---
Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
(anonymous) @ shell.ts:199
extensionHost.ts:172 ERROR starting extension host
(anonymous) @ extensionHost.ts:172
extensionHost.ts:173 timeout
(anonymous) @ extensionHost.ts:173

I have replied to that issue.

Thanks
Manish

**Comment by DustinCampbell** [comment]
Yes, that does look a VS Code-specific issue. It doesn't seem like C# for VS Code is getting loaded at all. I'll go ahead and close this issue. I've also subscribed to the VS Code issue above. If you don't get any traction, you might consider filing a new issue at https://github.com/Microsoft/vscode/issues as that one appears to be closed.
