### ISSUE TITLE
Allow Go To Definition to work inside metadata files

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#876]
At the moment we only support "go to definition" from:
 -  a source file into another source file 
 - a source file into metadata

However, we don't support "go to definition" from metadata to metadata. 
This is something that works fine in Visual Studio and it's not unreasonable to expect similar feature from OmniSharp.

I made a prototype of this yesterday and will PR soon.

**Comment by filipw** [comment]
Note that supporting it at the editor level would be a separate issue, but we obviously first need the feature to work in OmniSharp

**Comment by DustinCampbell** [comment]
Note that we also support Find All References from Metadata as Source in Visual Studio as well, which searches your currently opened solution.
