### ISSUE TITLE
Omnisharp fails to start when dependency version contains "*"

### ISSUE THREAD

**Issue by livioribeiro** [OmniSharp/omnisharp-roslyn#878]
If you declare a dependency in your .csproj file like this:

```xml
<PackageReference Include="Microsoft.AspNetCore" Version="1.1.*" />
```

After restoring the dependencies, omnisharp will fail to start with the message:

```
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The "ResolvePackageDependencies" task failed unexpectedly.
This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
System.FormatException: Input string was not in a correct format.
  at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x00306] in <12e050e5b3d34326a1b4e2e7624e75da>:0 
  at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x00026] in <12e050e5b3d34326a1b4e2e7624e75da>:0 
  at System.String.Format (System.IFormatProvider provider, System.String format, System.Object arg0, System.Object arg1, System.Object arg2) [0x0000b] in <12e050e5b3d34326a1b4e2e7624e75da>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.GetDependencyDiagnostics () [0x0017a] in <44c250c7557f45749e194fbbdb4b9145>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ExecuteCore () [0x00012] in <44c250c7557f45749e194fbbdb4b9145>:0 
  at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <44c250c7557f45749e194fbbdb4b9145>:0 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x0002a] in <bdf083ca20c84af487947992fd9a4a29>:0 
  at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x002bf] in <bdf083ca20c84af487947992fd9a4a29>:0
```

The problem only occurs after restoring the dependencies, just changing the .csproj file does not generate any problem.

**Comment by DustinCampbell** [comment]
@livioribeiro: This looks like it's failing in one of the MSBuild tasks the .NET Core SDK. Could you provide the information below to help me investigate?

1. What operating system (and version) are you using?
2. At a command prompt, run `dotnet --info` and provide the output
3. What editor (and version) are you using OmniSharp (e.g. VIM, VS Code, Emacs, etc.)?

Thanks!

**Comment by DustinCampbell** [comment]
Note: My _suspicion_ is that you are trying to use a nightly 2.0-preview2 .NET Core SDK build. Those nightly builds have known issues that are broken with OmniSharp (https://github.com/OmniSharp/omnisharp-roslyn/issues/865). However, if that's not the case let me know.

**Comment by livioribeiro** [comment]
I tested in two computers, home and work, both running Ubuntu 16.04 x64, and using VS Code 1.12.2.

First I tested at work, running sdk 1.0.4, and noticed the problem.
And now tested at home, tested with sdk 2.0-preview, all worked, then installed sdk 1.04, and it worked as well!

I will test again at my work computer to try to give more info on this.

**Comment by livioribeiro** [comment]
Just tested again at my work computer, problem still happening.
```
$ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
```

**Comment by DustinCampbell** [comment]
Does it still happen with the 2.0-preview that you also tried on your home computer?

**Comment by livioribeiro** [comment]
Yes, happens for both versions.

**Comment by DustinCampbell** [comment]
Hmmm... that is very strange. Both machines are running the same OS, one fails and the other works. I'll get Ubuntu 16.04 set up and see if I can repro.

**Comment by DustinCampbell** [comment]
I set up Ubuntu 16.04 and still could not repro. On the VM I have the following installed to try and replicate your machine.

1. Visual Studio Code 1.12.2.
2. .NET Core SDK 1.0.4
    ```Bash
    sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
    sudo apt-get update
    sudo apt-get install dotnet-dev-1.0.4
    ```
3. C# for Visual Studio Code 1.10.0 (using the Extensions pane in VS Code).

Then, I did the following in a Terminal window to create a new project and open it in VS Code.

```Bash
mkdir test
cd test
dotnet new console
code .
```

In VS Code, I opened Program.cs and and waited until I received two prompts:

1. `There are unresolved dependencies from 'Test.csproj'. Please execute the restore command to continue.` **_(I clicked 'Restore')_**
2. `Required assets to build and debug are missing from 'test'. Add them?` **_(I clicked 'Yes')_**

At this point, I have no squiggles in Program.cs.

Next, I opened test.csproj and added the following:

```XML
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore" Version="1.1.*" />
</ItemGroup>
```

Then, I saved the project and received another prompt to restore. **_(Again, I clicked 'Restore')_**

After the restore completed, I opened Program.cs and verified that I could get IntelliSense when typing `Microsoft.AspNetCore.Builder.IApplicationBuilder builder;` inside `Main(..)`.

**Comment by DustinCampbell** [comment]
Does that look similar to what you did?

**Comment by DustinCampbell** [comment]
_Sorry! Closed accidentally._

**Comment by livioribeiro** [comment]
Yes, that is what I did.

It seems that the problem is on my machine. I'll close this issue until I can figure out what was causing the problem.

Thanks a lot.

**Comment by DustinCampbell** [comment]
OK. Let me know if you learn anything. I'm very curious!
