### ISSUE TITLE
How can close the functionality in C# files ?

### ISSUE THREAD

**Issue by DFVSQY** [OmniSharp/omnisharp-roslyn#889]
For C# files, the intellisense is very good, but sometimes i think it should not show tips, as below:
![qq 20170607232940](https://user-images.githubusercontent.com/8075421/26886927-49ec8b08-4bd9-11e7-865a-3a95bd71cdf5.png)
When i press down '<' char, the intellisense appears and i think it's not right.  The '<' char here only mean less than, how can i close intellisense when i press down '<' char ?

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1553
