### ISSUE TITLE
Question About Xamarin.iOS.dll Support

### ISSUE THREAD

**Issue by pantaaron** [OmniSharp/omnisharp-roslyn#892]
I am hoping it is something I am looking over that is extremely obvious, but I can run just about any project with OmniSharp on Mac OS Sierra 10.12.5 with the exception of one with the Xamarin.iOS.dll in it. When I run it I get the error: 

`The reference assemblies for framework "Xamarin.iOS,Version=v1.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.`

I have the SDK installed and actually have access to the DLL in question- is there a way for me to include external DLLs like this in solutions run on OmniSharp? I tried just adding it to the GAC with `gacutil -i Xamarin.iOS.dll` which was given from [mono-project](http://www.mono-project.com/docs/advanced/assemblies-and-the-gac/) but that did not work either. Anything to nudge me in the right direction would be appreciated. Thanks!

**Comment by willl** [comment]
Hi @pantaaron, which version of omnisharp-roslyn have you got installed?

The netcore app version or the mono version? 

While I have no experience with Xamarin.iOS.dll, my guess is that you need to have the mono version of omnisharp-roslyn installed to work with it.

**Comment by pantaaron** [comment]
> Hi @pantaaron, which version of omnisharp-roslyn have you got installed?

The latest as of yesterday in the omnisharp-roslyn-dev stream. I am not sure how to determine the version as when I check the info on the project it just says 0.1 but I updated it yesterday and reran build.sh, which the output is the omnisharp I am using now.

> The netcore app version or the mono version?

Mono version, which is the latest 5.0.1.1 and is currently the one I am using in Visual Studio for Mac (which is an editor I am not fond of).

**Comment by DustinCampbell** [comment]
I've got a fix for this in PR here: https://github.com/OmniSharp/omnisharp-roslyn/pull/923.
