### ISSUE TITLE
Can not build for Debian 9 "Stretch"

### ISSUE THREAD

**Issue by igorkovalchuk** [OmniSharp/omnisharp-roslyn#895]
**Environment:**
Debian 9
mono-xbuild-5.2.0.179 (alpha-jessie, mono-project)
msbuild-15.2 (alpha-jessie, mono-project)

Creating directory /wrk/all/one/projects/omni/omnisharp-roslyn/.dotnet
dotnet_install: Error: OS name could not be detected: debian.9
An error occurred when executing task 'BuildEnvironment'.
Error: Failed to Install .NET Core SDK 1.0.1

 **If I manually edit the dotnet-install.sh**

                "debian.9")
                    echo "debian"
                    return 0
                    ;;

**and edit the build.cake**

    {
        //client.DownloadFile(url, scriptFilePath);
    }

**then I get (a "no such file" error in my language)**

Creating directory /wrk/all/one/projects/omni/omnisharp-roslyn/.dotnet-legacy
/bin/chmod: не вдалося отримати доступ до '/wrk/all/one/projects/omni/omnisharp-roslyn/.dotnet-legacy/dotnet-install.sh': Немає такого файла або каталогу
/bin/bash: /wrk/all/one/projects/omni/omnisharp-roslyn/.dotnet-legacy/dotnet-install.sh: Немає такого файла або каталогу
An error occurred when executing task 'BuildEnvironment'.
Error: Failed to Install .NET Core SDK 1.0.0-preview2-1-003177

**after that I copy dotnet-install.sh to .dotnet-legacy and continue then I have this: An error occurred when executing task 'Restore'.**

Restore

Executing task: Restore
Restoring packages in OmniSharp.sln...

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 5051 ms
Expanding 100% 27595 ms
  Restoring packages for /wrk/all/one/projects/omni/omnisharp-roslyn/src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj...
  Restoring packages for /wrk/all/one/projects/omni/omnisharp-roslyn/src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj...
  Restoring packages for /wrk/all/one/projects/omni/omnisharp-roslyn/src/OmniSharp.DotNet/OmniSharp.DotNet.csproj...
  Restoring packages for /wrk/all/one/projects/omni/omnisharp-roslyn/src/OmniSharp.Host/OmniSharp.Host.csproj...
An error occurred when executing task 'Restore'.
Error: Failed to restore projects in OmniSharp.sln.

**Comment by igorkovalchuk** [comment]
FYI: I am using the alpha-jessie repository of mono-project:
deb http://download.mono-project.com/repo/debian alpha-jessie  main

**Comment by johnhidey** [comment]
Any update available for this issue from anyone

**Comment by igorkovalchuk** [comment]
========================================
Restore
========================================
Executing task: Restore
Restoring packages in OmniSharp.sln...
  Restoring packages for /home/workerlamp/OmniBuild/omnisharp-roslyn-master/src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj...
  Restoring packages for /home/workerlamp/OmniBuild/omnisharp-roslyn-master/src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj...
  Restoring packages for /home/workerlamp/OmniBuild/omnisharp-roslyn-master/src/OmniSharp.DotNet/OmniSharp.DotNet.csproj...
  Restoring packages for /home/workerlamp/OmniBuild/omnisharp-roslyn-master/src/OmniSharp.Host/OmniSharp.Host.csproj...
An error occurred when executing task 'Restore'.
Error: Failed to restore projects in OmniSharp.sln.

**Comment by DustinCampbell** [comment]
This may be helped by #976.

**Comment by filipw** [comment]
Closing this as obsolete.
