### ISSUE TITLE
Add kre beta3 support

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-roslyn#91]
OmniSharp fails to launch when using the latest beta3 kre.

This is the error message:
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] Using configured version default
[ERROR:OmniSharp.AspNet5.AspNet5ProjectSystem] The specified runtime path 'default'. Does not exist. Try installing it with kvm install 'default'.

Notice that there is configure version 'default', that refers to beta3. Here is the output from kvm list:
Active Version              Runtime Location             Alias
       1.0.0-beta2          mono    ~/.k/runtimes        
  *   1.0.0-beta3-11030    mono    ~/.k/runtimes        default

**Comment by nosami** [comment]
@Yantrio is looking into this.

**Comment by Yantrio** [comment]
This should hopefully be fixed with #92 when it's pulled in :D

**Comment by nosami** [comment]
fixed in #92
