### ISSUE TITLE
No coherence in /findusages response

### ISSUE THREAD

**Issue by adelecourt** [OmniSharp/omnisharp-roslyn#921]
Hello,
I've noticed that in /findusages response, you have this strange situation:
- Text:  "MyClass test = new MyClass();"
- Column:  13
- EndColumn: 20

 I was expecting Column and EndColumn to match the first occurence of MyClass in the line. But it is not the case. It matches the first occurence of MyClass in the file with the real line: 

 ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `MyClass test = new MyClass();

As you can notice, there is some whitespaces at the beginning which explains the shift in the number for Column and EndColumn.
But I don't think we care about the location of the token in the file, but we want to have the place in the response's field Text.
Or if we really want to have this locationin the file, we should receive the line with all the whitespaces at beginning of the line.

**Comment by filipw** [comment]
Thank you. this is by design - find usages returns position based on the linespan in the document, and sets the `Text` property to the entire line.

The motivation is to allow the editors to show the entire line quickly and use the linespan to provide easy navigation to the target document.
