### ISSUE TITLE
Starting with a sln file doesn't load NuGet packages for .NET Core

### ISSUE THREAD

**Issue by DDoSolitary** [OmniSharp/omnisharp-roslyn#925]
```
.
├ foo.sln
└ fooproj
  └ fooproj.csproj
```
When I use `-s fooproj`(the directory that contains the csproj file) it works fine. I can see a lot of NuGet packages loaded if I use `-l Debug`, as .NET Core use NuGet for framework libraries too.
However if I use `-s foo.sln`(the solution file), `fooproj.csproj` is loaded but _not_ the NuGet packages.

_Environment_
Arch Linux
.NET Core SDK 2.0 preview2
omnisharp-roslyn 1.22.0 (the mono build)
mono 5.2

**Comment by DustinCampbell** [comment]
Could you share the output when loading with a solution?

**Comment by DDoSolitary** [comment]
Oh, I reinstalled all the softwares related(.net core, mono, omnisharp, etc) and it works.
Sorry, the problem must be on my side. 😢
