### ISSUE TITLE
Unable to install BuildEnvironment.

### ISSUE THREAD

**Issue by bayantt** [OmniSharp/omnisharp-roslyn#927]
![omnisharp_roslyn_install_error](https://user-images.githubusercontent.com/6358276/28756898-3a98d96e-7595-11e7-854c-3c446a7c6269.PNG)

This is what I am facing while running `build.ps1`. Please help me resolve this.

**Comment by DustinCampbell** [comment]
From the screenshot above, it looks like this is due to https://github.com/OmniSharp/omnisharp-roslyn/issues/691.
