### ISSUE TITLE
Ship a Fedora 26 zip

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-roslyn#928]
Fedora 26 was released a few weeks ago and has good adoption. It also enables a newer version of mono and should soon provide some dotnet-core 2.0 package to make developing .NET apps on and for Linux more and more natural.
It would be great if Omnisharp-Roslyn server could ship a fedora.26 zip, that would be easy to consume either directly or by the omnisharp-node-client.

**Comment by DustinCampbell** [comment]
We've just updated OmniSharp to remove to exclusively target Mono >= 5.2.0.209. These releases are available at https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.23.0.

There are two releases available that should work on Fedora 26.

1. omnisharp-mono.tar.gz - Can be run on mono >= 5.2.0. Fedora 26 doesn't ship with
2. omnisharp-linux-x64.tar.gz - Standalone (includes bundled Mono runtime and framework)

I tried both of these and found that they worked on Fedora 26. Note that I had to install the latest mono-devel beta to get the "omnisharp-mono" version working.

**Comment by DustinCampbell** [comment]
cc @david-driscoll about updating omnisharp-node-client

**Comment by david-driscoll** [comment]
Will work on this tonight... I have to update the code that downloads the binaries I'm sure.

**Comment by david-driscoll** [comment]
Work will be at https://github.com/OmniSharp/omnisharp-node-client/pull/441

**Comment by DustinCampbell** [comment]
I think this issue can be resolved now that there are two builds that work for Fedora x64.
