### ISSUE TITLE
Support logical selections

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#93]
The TypeScript playground supports a feature called _logical selection_ - which allows to grow and shrink your selection along the syntax tree. I would love to have something similar in C#.

![logicalselection](https://cloud.githubusercontent.com/assets/1794099/6351538/9f501d46-bc3c-11e4-9c3e-2b1d903914db.gif)

**Comment by nosami** [comment]
use emacs? :)

**Comment by Yantrio** [comment]
I would say that this is an editor feature more than anything, similar to multi-cursor selection.

**Comment by jrieken** [comment]
It is an editor feature but it needs a smart guys that tells it what the current syntax tree looks like. So for omnisharp this will be a call like ```getStructureUntilPosition``` returning ranges of syntax nodes. Then it's up to the editor to combine this with other information (like line, block, etc)

**Comment by nosami** [comment]
![expand](https://cloud.githubusercontent.com/assets/667194/6351829/a4365e52-bc36-11e4-9192-f5bd4df3b948.gif)

Please do ignore me... this is purely a troll.

**Comment by jrieken** [comment]
:open_mouth:

**Comment by jrieken** [comment]
I don't want this anymore ;-)
