### ISSUE TITLE
Run single Test in VSCode is slower with .Net CLI 2.0 because of restore

### ISSUE THREAD

**Issue by tverboon** [OmniSharp/omnisharp-roslyn#942]
dotnet cli 2.0 automatically restores before building when executing `dotnet build` or `dotnet test`. I can understand why, but still I have been adding `--no-restore` to all our build scripts and VSCode tasks. 

Going through the code Omnisharp-Roslyn code, I noticed that the CLI is also called with `build`: https://github.com/OmniSharp/omnisharp-roslyn/blob/e18913e887144119c41d60f1842e49f8e9bfcf72/src/OmniSharp.DotNetTest/VSTestManager.cs#L51

Calling with --no-restore is possible here, but not sure what you think is best from a functionality standpoint? In my opinion, during development, these tasks should be as fast as possible.

**Comment by DustinCampbell** [comment]
Thanks @tverboon. You're right, that's probably the right thing to do here. However, the "restore" on build is *supposed* to be very quick (milliseconds).

**Comment by tverboon** [comment]
Yes, in our case it's typically between 30 and 50 milliseconds per project. We have around 10 projects in the dependency graph, in that case it takes between 300 and 500 ms.

It's not possible to just add --no-restore in this line, because there needs to be a check for the dotnet version. Not sure if it's cached somewhere, otherwise starting the dotnet process to get the version, makes it potentially even slower for projects with less project dependencies.

**Comment by DustinCampbell** [comment]
Yup, I was already thinking about needing a version check. We do check the version earlier, so we should be able to pass that along.
