### ISSUE TITLE
Unable to build with ArchLinux

### ISSUE THREAD

**Issue by aignas** [OmniSharp/omnisharp-roslyn#943]
I am trying to use <https://github.com/omnisharp/omnisharp-vim> and have installed mono 5.2 via the `mono-beta` package from [AUR](https://aur.archlinux.org/packages/mono-beta/). However, it fails to build with the following output:
```
❯ ./build.sh
Feeds used:
  /home/ia/.nuget/packages/
  https://api.nuget.org/v3/index.json
  https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
  https://dotnet.myget.org/F/cli-deps/api/v3/index.json
  https://www.myget.org/F/xunit/api/v3/index.json

All packages listed in /home/ia/src/vim/omnisharp-vim/omnisharp-roslyn/tools/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...
Current platform: Linux (x64)

========================================
Cleanup
========================================
Executing task: Cleanup
Finished executing task: Cleanup

========================================
ValidateMono
========================================
Executing task: ValidateMono
Detected Mono version 5.2.0.215
Finished executing task: ValidateMono

========================================
InstallDotNetCoreSdk
========================================
Executing task: InstallDotNetCoreSdk
/home/ia/src/vim/omnisharp-vim/omnisharp-roslyn/.dotnet/dotnet-install.sh: line 70: VERSION_ID: unbound variable
An error occurred when executing task 'InstallDotNetCoreSdk'.
Error: Failed to Install .NET Core SDK 1.0.4
```

The HEAD is at `* (HEAD detached at 4c00f3a0)`

**EDIT**: I have also found [omnisharp-roslyn on AUR](https://aur.archlinux.org/packages/omnisharp-roslyn), so will try to use it, but it would be greate if it was possible to use the official instructions to build the package on my OS.

**Comment by SirJls** [comment]
@aignas,  you could take a look at this [issue](https://github.com/OmniSharp/omnisharp-vim/issues/306) I opened on [omnisharp-vim ](https://github.com/OmniSharp/omnisharp-vim) a while back. It still uses an older version of dotnet, but the instructions should still be able to guide you to a working solution.

Concerning your current issue, it is closely related to the [issue](https://github.com/OmniSharp/omnisharp-roslyn/issues/963) by @lwiechec

**Comment by filipw** [comment]
OmniSharp VIM has moved to consume binaries instead of using the submodule approach so I will close this as not applicable anymore.
