### ISSUE TITLE
How to use OmniSharpWorkspace to load existing .csproj and/or .sln files

### ISSUE THREAD

**Issue by abhijitparkhi1983** [OmniSharp/omnisharp-roslyn#946]
Hello @DustinCampbell ,

I am trying to use Roslyn on Mono framework for running analyzer on Ubuntu/Linux.
We use the **MSBuildWorkspace.OpenProjectAsync** and/or **MSBuildWorkspace.OpenSolutionAsync** for loading the existing .csproj and/or .sln files.

But for some reason not known to me yet, we get following exception on mono for the two api's above : **Msbuild failed when processing the file '.csproj' with message: Operation is not supported on this platform.** . 
Searching for a possible solution and a work around, I landed up on the **OmniSharpWorkspace** class which derives out of **Microsoft.CodeAnalysis.Workspace**. 

As much I have seen the usage of **OmniSharpWorkspace**, I have not seen any example where we can use this class or its variant to load an existing .csproj and/or .sln file based on the file path for either of the two. 

**Question** : Is there any way in which we can **use OmniSharpWorkspace** or any of its variant to **load existing  .csproj and/or .sln file based on the file path** for either of the two. ? 

If not, can you provide some lead on the way to Achieve this with some other mechanism or some pointer for using **MSBuildWorkspace** api's on Mono.

Your inputs will be extremely helpful for me. Looking forward to hear from you and the OmniSharp team.

**Comment by DustinCampbell** [comment]
@abhijitparkhi1983: I think you're going to have a lot of problems using MSBuildWorkspace on Mono. I actually compile MSBuild specially to target Mono to use it within OmniSharp. However, OmniSharpWorkspace is not a drop-in replacement for MSBuildWorkspace and not something I would recommend trying to use outside of OmniSharp.

I'm currently tasked with getting MSBuildWorkspace working and am starting that effort now. However, it'll be some weeks before I have a good answer for you.

**Comment by abhijitparkhi1983** [comment]
@DustinCampbell  thanks a lot for a quick reply. 

I am kind of stuck with a road blocker. My task is to run Roslyn analyzer for existing .csproj and/or .sln projects on Ubuntu/Linux.    

So what else can be used instead ? Do you have any other recommendation for me? 
I was even trying to check if MSBuildWorkspace works with .NET Core. But I guess it is not supported on .NET core as well. Am I right ?

Looking forward to your valuable input. Some lead would be very very helpful.

**Comment by DustinCampbell** [comment]
MSBuildWorkspace is not supported on .NET Core (yet!). In general, MSBuildWorkspace has not really been updated to be used with MSBuild 15, which is the first MSBuild to support cross-plat.

**Comment by abhijitparkhi1983** [comment]
Thanks again for a quick reply. 
So can i assume that Roslyn Analyzer does not have a cross-platform support for now and will have it in the near future?

**Comment by DustinCampbell** [comment]
I'm not sure what you mean by "Roslyn Analyzer".

**Comment by abhijitparkhi1983** [comment]
I am using the MSBuildWorkspace.OpenProjectAsync to navigate to the Document's of a particular .csproj and then using the **CSharpSyntaxWalker** and **SemanticModel** of the document (**Microsoft.CodeAnalysis** libraries ), I am trying to walk through various **Visitors** for the elements of the Document to analyse their corresponding **SyntaxTree**.

I can do all this analysis on a windows box easily using Roslyn 2.3.1. 
I had assumed that the same binaries would even work on a Ubuntu machine using Mono.
But it does not work on Mono. Infact it fails right at  MSBuildWorkspace.OpenProjectAsync. 

So essentially for Ubuntu/Linux, I want to use the **Visitor** mechanism along with **SymeticModel** for a **Document** provided by **Microsoft.CodeAnalysis**. Thats what I mean by Roslyn Analyzer.

Is there any way in which I can achieve this  ?

**Comment by DustinCampbell** [comment]
I see. I thought you meant a Roslyn "DiagnosticAnalyzer". In your case, your referring to performing analysis.

Well, MSBuildWorkspace.OpenProjectAsync(...) does quite a bit of work because that's where MSBuild gets run.

I believe that one of the primary problems you'll have trying to run MSBuildWorkspace on Mono is that it references the 'net46' versions of the MSBuild packages. Unfortunately, the binaries in those packages assume that they're running on Windows and contain P/Invokes into Win32 APIs.

**Comment by abhijitparkhi1983** [comment]
@DustinCampbell  thanks for your inputs. 

I would like to use MSBuildWorkspace or some thing similar; which for now looks difficult with Mono which is not a good news for me certainly.

If possible, is it possible to give a tentative time frame when we can expect a MSBuildWorkspace support on Mono. It will be very very helpful.

**Comment by DustinCampbell** [comment]
Unfortunately, per Microsoft policy, I can't provide meaningful ship dates. To be honest, work on MSBuildWorkspace is just beginning, so I don't have a feel for how long it will take and it's too soon to know what release the update will appear in.

I'm going to close this issue here. Discussion can continue over on the Roslyn repo on one of the many issues tracking this work there.

**Comment by abhijitparkhi1983** [comment]
Sure thanks
