### ISSUE TITLE
Can't point OmniSharp at an alternate .NET CLI installation

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#948]
_From @wjk on August 22, 2017 15:49_

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\Applications\dotnet-sdk\sdk\2.0.0\


Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.15.1
C# Extension version: 1.12.1

## Steps to reproduce

I am running VSCode on a system that I do not have admin rights to. Therefore, I cannot run the .NET CLI installer, as that requires that I elevate. (I have installed VSCode using [VSCodePortable](https://github.com/garethflowers/vscode-portable), if you're wondering.) I have downloaded a zipped copy of .NET CLI and extracted it into a local folder, but OmniSharp insists on searching the system PATH, and only the system PATH, for `dotnet.exe`. As it can't find a copy there, OmniSharp simply fails to start. There is no configuration setting I can find to override this and have OmniSharp use an arbitrary copy of .NET CLI.

## Expected behavior

I should be able to do this.

## Actual behavior

I can't.

_Copied from original issue: OmniSharp/omnisharp-vscode#1729_

**Comment by DustinCampbell** [comment]
It seems like we need a configuration option to set the location of `dotnet.exe`. We already have most of the [logic in place](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Abstractions/Services/DotNetCliService.cs#L44-L60). Anyone should be able to pick this up.

**Comment by mhosman** [comment]
Any news??

**Comment by citycide** [comment]
@wjk et al. I use this setup already - I use VS Code Portable with the dotnet SDK binaries in a non-standard location. I added the dotnet binary location to my `Path` environment variable and then created the `DOTNET_ROOT` env var with that same directory. Has worked for me since some of the earlier previews and through the GA release of .NET Core.

Ref:

https://github.com/dotnet/docs/blob/801fe29c48a5bce082edcaf5b9ac53a1fe7b6447/docs/core/tools/troubleshoot-usage-issues.md#runtime-not-found

**Comment by filipw** [comment]
This was implemented in https://github.com/OmniSharp/omnisharp-roslyn/pull/2227
