### ISSUE TITLE
Installation fails on InstallDotNetCoreSdk step

### ISSUE THREAD

**Issue by kolombet** [OmniSharp/omnisharp-roslyn#966]
Trying to install OmniSharp-roslin, as a submodule of OmniSharp-vim to get autocompletion in vim. 
When i try to build OmniSharp-roslin with ./build.sh, i get ConnectFailure error (log attached).
How to bypass InstallDotNetCoreSdk? I am already have DotNetCore 2.0 installed. 
My configuration is clean installation of Ubuntu 16.04.3 LTS 

> poweruser@PC123:~/.vim/bundle/omnisharp-vim/omnisharp-roslyn$ sudo ./build.sh
> Feeds used:
>   /home/poweruser/.nuget/packages/
>   https://api.nuget.org/v3/index.json
>   https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
>   https://dotnet.myget.org/F/cli-deps/api/v3/index.json
>   https://www.myget.org/F/xunit/api/v3/index.json
> 
> All packages listed in /home/poweruser/.vim/bundle/omnisharp-vim/omnisharp-roslyn/tools/packages.config are already installed.
> Analyzing build script...
> Processing build script...
> Installing addins...
> Compiling build script...
> Current platform: Linux (x64)
> 
> ========================================
> Cleanup
> ========================================
> Executing task: Cleanup
> Finished executing task: Cleanup
> 
> ========================================
> ValidateMono
> ========================================
> Executing task: ValidateMono
> Detected Mono version 5.2.0.224
> Finished executing task: ValidateMono
> 
> ========================================
> InstallDotNetCoreSdk
> ========================================
> Executing task: InstallDotNetCoreSdk
> Got a bad hardware address length for an AF_PACKET 16 8
> Got a bad hardware address length for an AF_PACKET 16 8
> An error occurred when executing task 'InstallDotNetCoreSdk'.
> Error: Error: ConnectFailure (Value does not fall within the expected range.)

**Comment by DustinCampbell** [comment]
This is the point at with the .NET Core SDK is downloaded and installed, which should work fine on ubuntu 16.04. Is your machine connected to the Internet when building? If so, I wonder if there's a network blip somewhere.

**Comment by kolombet** [comment]
My machine is connected to the internet. I was trying to run install script many times, same result. I suppose main problem is: my ubuntu runs as windows 10 linux subsystem. 

I have dotnet core installed already, on the ubuntu, from official microsoft site (2.0 version)
Can i skip InstallDotNetCoreSkd somehow?

**Comment by kolombet** [comment]
Maybe i can help to resolve this with some logs. I am bad at sh scripts, and can't locate problem myself.

**Comment by filipw** [comment]
Closing this as out of date, the build has changed much since then. If you still experience issues with the current build, please open a new issue. Thanks!
