### ISSUE TITLE
Add navigate up/down by method

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-roslyn#97]
Utility method to make navigating up and down by method faster. The response should be the same format as the go to definition response.

If there is no further method up or down, then the response should contain the location of the first or last method. If there are no methods at all, return the current location to make client side integration as simple as possible.

**Comment by sriramgd** [comment]
If no one else if working on it, can I take this?

**Comment by nosami** [comment]
sure! thanks

**Comment by sriramgd** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/pull/110

**Comment by nosami** [comment]
fixed by #110
