### ISSUE TITLE
Unable to build omnisharp-roslyn for vim, could not load file or assembly

### ISSUE THREAD

**Issue by atsuzaki** [OmniSharp/omnisharp-roslyn#970]
After running ./build.sh, this came up:
(Note that I'm using the Windows Linux Subsystem bash, which is rather wonky by itself)

> Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77
> a5c561934e089' or one of its dependencies.
> System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Cu
> lture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
> File name: 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
>   at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) <0x7ffc1b70 + 0x00487> in
>  <filename unknown>:0
> Could not restore NuGet packages.

I do have Mono installed from the previous step in setting up omnisharp-vim

**Comment by rchande** [comment]
@atsuzaki Have you tried building it outside of Windows Linux Subsystem?

**Comment by DustinCampbell** [comment]
Yeah, I'm definitely smelling some wonkiness here. After all, that's `nuget.exe` itself failing to load MEF.

Do you have Mono installed within WSL?

**Comment by filipw** [comment]
I will close this as obsolete at this point

**Comment by synthead** [comment]
I am experiencing the same issue on Ubuntu Linux.  Did you ever find a solution?
