### ISSUE TITLE
SDK version missing messages during build

### ISSUE THREAD

**Issue by omajid** [OmniSharp/omnisharp-roslyn#984]
I was trying to build omnisharp-roslyn on CentOS 7 and while the build completed, I got lots of strange messages during build:

> The specified SDK version [2.0.0] from global.json [/home/omajid/omnisharp-roslyn/global.json] n    ot found; install specified SDK version

Are these safe to ignore?

Here is the full build log: [omnisharp-build.log](https://github.com/OmniSharp/omnisharp-roslyn/files/1395422/omnisharp-build.log)

Possibly related, I notice that while we download a .NET Core SDK to `.dotnet/`, that path is never added to the environment variable PATH. When we call out to msbuild, how does msbuild find it? Could it be that it is not finding the SDK at all?

**Comment by DustinCampbell** [comment]
Yeah, I've seen those messages as well. I'm pretty sure they're printed by the SdkResolver in MSBuild. You're intuition about `.dotnet/` not being added to the path sounds right to me.

**Comment by DustinCampbell** [comment]
FWIW, I thought the [`dotnet-install.sh`](https://raw.githubusercontent.com/dotnet/cli/release/2.0.0/scripts/obtain/dotnet-install.sh) added the location to the PATH.

**Comment by omajid** [comment]
> FWIW, I thought the dotnet-install.sh added the location to the PATH.

It only does that if you source it (and that leads to other problems like https://github.com/dotnet/cli/issues/7588) into a shell. If you only run it, it can not manipulate the parent process's environment variables.

**Comment by DustinCampbell** [comment]
Ah. Of course, that makes complete sense. This is definitely why we're seeing these messages.

**Comment by omajid** [comment]
I made that change and warnings disappeared! I will open a PR.

**Comment by omajid** [comment]
Closing since this is fixed by #985

**Comment by DustinCampbell** [comment]
Thanks again for your contributions @omajid

**Comment by omajid** [comment]
Glad to be able to help out :)
