### ISSUE TITLE
Can't build on macOS

### ISSUE THREAD

**Issue by akamud** [OmniSharp/omnisharp-roslyn#989]
I just cloned the project on macOS and I'm trying to build following the instructions.

First of all, I was getting this:

```bash
omnisharp-roslyn: ./build.sh
zsh: ./build.sh: bad interpreter: /bin/bash^M: no such file or directory
```

I searched what this error meant and tried a bunch of things with no success. So I decided to take a look at what the script does. I saw that it just calls another script, so I did it manually:

```bash
omnisharp-roslyn: bash ./scripts/cake-bootstrap.sh
: command not foundstrap.sh: line 2: 
: command not foundstrap.sh: line 8: 
: command not foundstrap.sh: line 16: 
'/scripts/cake-bootstrap.sh: line 35: syntax error near unexpected token `do
'/scripts/cake-bootstrap.sh: line 35: `for i in "$@"; do
```

I don't know how I can provide you more information to help diagnose or at least understand if this is a problem with: omnisharp-roslyn, cake, or my machine.
I tried other cake scripts from other projects and they work fine, even having the same "for" loop, which is very strange.
I saw that it may be related to the script being created on Windows and having CR/LF characters issues. From my understanding, omnisharp-roslyn is built on OSX during CI, so this is very weird.

I guess that what I'm trying to understand is: what issues the script may have for people trying to build (and possibly contribute to) the project?

I'm using:
macOS 10.13
zsh 5.3

Any ideas?

**Comment by DustinCampbell** [comment]
FWIW, I could not reproduce this. I'm on 10.13 (High Sierra) and just switched to zsh 5.3. Executing `./build.sh` works fine for me:

```
Last login: Wed Oct 25 12:04:05 on ttys001
dustins-mbp% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A405
dustins-mbp% zsh --version
zsh 5.3 (x86_64-apple-darwin17.0)
dustins-mbp% 
```

**Comment by akamud** [comment]
I just confirmed, this is an issue with CR characters.

I had to use `dos2unix` to fix the issue on my Mac. Now everything works. Diff shows that only CR characters were changed.

```
warning: LF will be replaced by CRLF in build.sh.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in scripts/cake-bootstrap.sh.
The file will have its original line endings in your working directory.
```

I'm not sure why you can't reproduce and this happens on my Mac.

**Comment by DustinCampbell** [comment]
It's likely due to settings for how git works with line endings. Have you changed this on your machine?

**Comment by akamud** [comment]
Yes. Does it make sense to open a PR "fixing" this?

**Comment by DustinCampbell** [comment]
Sure

**Comment by akamud** [comment]
Will do that. Thanks.

**Comment by akamud** [comment]
All the docs say we should contribute to `dev`, but there is no `dev` branch atm. Which one should I use to open the PR?

**Comment by DustinCampbell** [comment]
Yeah, that's old. Make a PR to master.

**Comment by akamud** [comment]
Ok, I talked to some more people and found out why this is happening: I had a `autocrlf = true` in my `.gitconfig`. If anyone else has it when cloning, they will have the same problem.

Anyway, I still think the `.sh` should always use `LF` instead of `CRLF` since this is the default in systems where it will run.

I'll open a PR fixing this in all `.sh` scripts.

**Comment by DustinCampbell** [comment]
Thanks!

**Comment by akamud** [comment]
Due to #991 being merged, this shouldn't happen anymore.

**Comment by DustinCampbell** [comment]
Thanks for your contribution!
