### ISSUE TITLE
stdio server no longer recognizes commands without the / prefix

### ISSUE THREAD

**Issue by grendello** [OmniSharp/omnisharp-roslyn#994]
The issue is [explained here](https://github.com/OmniSharp/omnisharp-emacs/pull/389), however after Slack conversation it turns out it's most likely a bug in omnisharp-roslyn rather than omnisharp-emacs. In short: omnisharp-emacs seds `typelookup` and `omnisharp-roslyn` says `nope, sorry, nothing like that here` because there's no leading `/`

**Comment by razzmatazz** [comment]
the related code has been fixed in omnisharp-emacs tree and this issue can be closed
