### ISSUE TITLE
In csharp script using .netstandard library: The type 'List<>' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by gabomgp** [OmniSharp/omnisharp-roslyn#996]
I'm using a script referencing a assembly compiled with .net standard 2. When i use a property of type List'1, I'm getting the error in vscode:

    The type 'List<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [testValidation.csx]

Is possible to reference a assembly compiled with .net standard 2 from a csx file, and that the intellisense works properly in vscode?

**Comment by rchande** [comment]
@gabomgp Can you share your omnisharp log?

**Comment by filipw** [comment]
@gabomgp by default OmniSharp assumes `net46` mode for resolving dependencies. You can add `#! "netcoreapp2.0"` directive at the top of your script to force the assembly resolution to assume .NET Core 2.0 mode.

**Comment by gabomgp** [comment]
@filipw  Thanks you very much. You resolved my question.
