### ISSUE TITLE
cygwin-paths (omnisharp-vim) supported?

### ISSUE THREAD

**Issue by mgatgithub** [OmniSharp/omnisharp-roslyn#999]
In the previous omnisharp-server, in config.json, there was a PathReplacements setting. In omnisharp-roslyn i can't find anything like that and vim doesn't show me feedback (warnings or errors) even tough omnisharp-roslyn is running and responding it seems not to send any findings back to vim. So i am wondering if omnisharp-vim with omnisharp-roslyn in cygwin vim is actually supported or not.

**Comment by mgatgithub** [comment]
It seems to work without configuring path replacements, i just missed the -stdio command line option.
...sorry

**Comment by DustinCampbell** [comment]
No problem. Are you OK if I close this?

**Comment by WooterTheTroubleshooter** [comment]
@mgatgithub I'm running into similar problems using Cygwin and omnisharp-vim, returning empty results, and it looks like the filenames are passed incorrectly. How did you resolve this issue?

**Comment by mgatgithub** [comment]
@WooterTheTroubleshooter: i havent solved it, i just thought i had and later became aware i accidentally started the 'not roslyn' server or messed up something else. The pre-roslyn-server works fine in my setup but does not recognize c#6 syntax. I thought i will investigate further to that and probably ask later again if necessary. Sorry for the false positive.
